USE [UniTrac]
GO 
----REPLACE XXXXXXX WITH THE THE WI ID
SELECT  CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar(10)') AS LENDER_CODE ,
        *

INTO    #TMPWI
FROM    WORK_ITEM
WHERE   id in(  XXXXXXXX)

--SELECT * FROM #TMPWI

---- DROP TABLE #TMP_ESCROW
SELECT ISNULL(Content_xml.value('(/Content/Lender/Code)[1]','varchar(20)') , '') as LENDER_CODE ,
 #TMPWI.CREATE_DT , #TMPWI.UPDATE_DT , #TMPWI.STATUS_CD AS WI_STATUS_CD , #TMPWI.RELATE_ID AS PROCESS_LOG_ID , 
  #TMPWI.ID AS WORK_ITEM_ID , 
  ISNULL(PLI.INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]','varchar(20)') , '') as 'USER_ACTION' ,
  LOAN.LENDER_ID , LOAN.NUMBER_TX , 
COLL.LOAN_ID , ESC.ID AS ESC_ID , ESC.BIC_ID , RQCOV.*  , ESC.STATUS_CD AS ESC_STATUS_CD , ESC.SUB_STATUS_CD AS ESC_SUB_STATUS_CD , 
RQCOV.STATUS_CD AS RE_STATUS_CD , RQCOV.SUB_STATUS_CD AS RE_SUB_STATUS_CD , ESC.REPORTED_DT ,
'Closed' AS STATUS_MEANING , 'Reported' AS SUB_STATUS_MEANING , CONVERT(VARCHAR(10) , GETDATE() , 101) AS STATUS_DT , 
0 as EXCLUDE
INTO #TMP_ESCROW
--- SELECT COUNT(*)
FROM WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIPLIR 			 
 JOIN PROCESS_LOG_ITEM PLI ON PLI.ID = WIPLIR.PROCESS_LOG_ITEM_ID	
 AND PLI.PURGE_DT IS NULL AND WIPLIR.PURGE_DT IS NULL
 JOIN ESCROW ESC  ON ESC.ID = PLI.RELATE_ID AND PLI.RELATE_TYPE_CD = 'Allied.UniTrac.Escrow'	
 CROSS APPLY (
     SELECT TOP 1  RC1.TYPE_CD , RC1.ID AS RC_ID ,RC1.PROPERTY_ID ,RE1.STATUS_CD , RE1.SUB_STATUS_CD FROM REQUIRED_COVERAGE RC1 
     JOIN ESCROW_REQUIRED_COVERAGE_RELATE ER1 ON ER1.REQUIRED_COVERAGE_ID = RC1.ID
     JOIN REQUIRED_ESCROW RE1 ON RE1.REQUIRED_COVERAGE_ID = RC1.ID
     AND RE1.ACTIVE_IN = 'Y' 
     WHERE RE1.TYPE_CD = ESC.TYPE_CD AND RE1.SUB_TYPE_CD = ESC.SUB_TYPE_CD AND RE1.EXCESS_IN = ESC.EXCESS_IN AND ER1.ESCROW_ID = ESC.ID AND (RC1.TYPE_CD = 'HAZARD' OR RC1.TYPE_CD = RC1.TYPE_CD)
     ORDER BY 
     Case when RC1.TYPE_CD = 'HAZARD' Then 0 else 1 end 
     asc
    )  RQCOV  
  JOIN COLLATERAL COLL ON COLL.PROPERTY_ID = RQCOV.PROPERTY_ID AND COLL.PRIMARY_LOAN_IN = 'Y'
  AND COLL.PURGE_DT IS NULL
  JOIN LOAN ON LOAN.ID = COLL.LOAN_ID 	
  JOIN #TMPWI ON #TMPWI.id = WIPLIR.WORK_ITEM_ID
ORDER BY LENDER_CODE
---- 

SELECT T.ID [WI_ID],  WIPLI.ID [WIPLI_ID], WIPLI.PURGE_DT [WIPLI.PURGE_DT], PLI.ID [PLI_ID], PLI.PURGE_DT [PLI.PURGE_DT], 
wia.id [WIA ID], WIA.PURGE_DT [WIA.PURGE_DT]
INTO #TMP
 FROM #TMPWI T
INNER JOIN dbo.WORK_ITEM_ACTION WIA ON WIA.WORK_ITEM_ID = T.ID
INNER JOIN dbo.WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIPLI ON WIPLI.WORK_ITEM_ID = T.ID
INNER JOIN dbo.PROCESS_LOG_ITEM PLI ON PLI.ID = WIPLI. PROCESS_LOG_ITEM_ID


SELECT relate_id into #tmpEscrow2 
FROM dbo.PROCESS_LOG_ITEM
WHERE ID IN (SELECT PLI_ID FROM #TMP)
and relate_type_cd = 'Allied.UniTrac.Escrow'

---Make sure that this is zero IF IT IS NOT PLEASE REACH OUT TO USER and ask how these Escrows should be closed.
select RE1.ACTIVE_IN, L.NUMBER_TX, WIPLIR.WORK_ITEM_ID, esc.STATUS_CD,esc.* from #TMP
join WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIPLIR ON #TMP.[WI_ID] = WIPLIR.WORK_ITEM_ID
 JOIN PROCESS_LOG_ITEM PLI ON PLI.ID = WIPLIR.PROCESS_LOG_ITEM_ID AND PLI.PURGE_DT IS NULL AND WIPLIR.PURGE_DT IS NULL
 JOIN ESCROW ESC  ON ESC.ID = PLI.RELATE_ID AND PLI.RELATE_TYPE_CD = 'Allied.UniTrac.Escrow' 
 JOIN ESCROW_REQUIRED_COVERAGE_RELATE ER1 ON ER1.escrow_id = ESC.ID
 join REQUIRED_COVERAGE RC1  ON ER1.REQUIRED_COVERAGE_ID = RC1.ID
 JOIN REQUIRED_ESCROW RE1 ON RE1.REQUIRED_COVERAGE_ID = RC1.ID
 join collateral C on C.PROPERTY_ID = RC1.PROPERTY_ID
 join Loan L on L.ID = C.LOAN_ID
 where esc.id in (select relate_id from #tmpEscrow2)
and esc.STATUS_CD != 'CLSE'


/*
--If there is a need to close Escrow manually (update script is generic and open for modifications until we have it 

select RE1.ACTIVE_IN, L.NUMBER_TX, WIPLIR.WORK_ITEM_ID, esc.STATUS_CD, esc.id
into #TMPCloseEscrow 
from #TMP
join WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIPLIR ON #TMP.[WI_ID] = WIPLIR.WORK_ITEM_ID
 JOIN PROCESS_LOG_ITEM PLI ON PLI.ID = WIPLIR.PROCESS_LOG_ITEM_ID AND PLI.PURGE_DT IS NULL AND WIPLIR.PURGE_DT IS NULL
 JOIN ESCROW ESC  ON ESC.ID = PLI.RELATE_ID AND PLI.RELATE_TYPE_CD = 'Allied.UniTrac.Escrow' 
 JOIN ESCROW_REQUIRED_COVERAGE_RELATE ER1 ON ER1.escrow_id = ESC.ID
 join REQUIRED_COVERAGE RC1  ON ER1.REQUIRED_COVERAGE_ID = RC1.ID
 JOIN REQUIRED_ESCROW RE1 ON RE1.REQUIRED_COVERAGE_ID = RC1.ID
 join collateral C on C.PROPERTY_ID = RC1.PROPERTY_ID
 join Loan L on L.ID = C.LOAN_ID
 where esc.id in (select relate_id from #tmpEscrow2)
and esc.STATUS_CD <> 'CLSE'



update ESC
set esc.STATUS_CD = 'CLSE', update_user_tx = 'INC0XXXXX', update_dt = GETDATE()
--select *
from ESCROW ESC
join #TMPCloseEscrow T on T.ID = ESC.ID

*/


select RE1.ACTIVE_IN, L.NUMBER_TX, WIPLIR.WORK_ITEM_ID, esc.STATUS_CD,esc.* from #TMP
join WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIPLIR ON #TMP.[WI_ID] = WIPLIR.WORK_ITEM_ID
 JOIN PROCESS_LOG_ITEM PLI ON PLI.ID = WIPLIR.PROCESS_LOG_ITEM_ID AND PLI.PURGE_DT IS NULL AND WIPLIR.PURGE_DT IS NULL
 JOIN ESCROW ESC  ON ESC.ID = PLI.RELATE_ID AND PLI.RELATE_TYPE_CD = 'Allied.UniTrac.Escrow' 
 JOIN ESCROW_REQUIRED_COVERAGE_RELATE ER1 ON ER1.escrow_id = ESC.ID
 join REQUIRED_COVERAGE RC1  ON ER1.REQUIRED_COVERAGE_ID = RC1.ID
 JOIN REQUIRED_ESCROW RE1 ON RE1.REQUIRED_COVERAGE_ID = RC1.ID
 join collateral C on C.PROPERTY_ID = RC1.PROPERTY_ID
 join Loan L on L.ID = C.LOAN_ID
 where esc.id in (select relate_id from #tmpEscrow2)
and esc.STATUS_CD != 'CLSE'

/*
DROP TABLE #TMPWI
DROP TABLE #TMP
DROP TABLE #TMP_ESCROW
DROP TABLE #tmpEscrow2
DROP TABLE #TMPCloseEscrow
*/


