SELECT  L.ID AS 'LoanID' ,
        L.NUMBER_TX AS 'Loan Number' ,
        L.LENDER_ID AS 'Lender ID' ,
        LL.CODE_TX AS 'Lender Code' ,
        L.STATUS_CD AS 'Loan Status Code' ,
        L.BALANCE_AMOUNT_NO AS 'Loan Balance' ,
        L.UPDATE_DT AS 'Loan Update Date'
FROM    UniTrac..LOAN L
        JOIN UniTrac..LENDER LL ON LL.ID = L.LENDER_ID
WHERE   L.ID IN ( 118030627, 118032633, 118006489, 118005631, 118004469 )


SELECT TOP 5 ID, LENDER_ID, NUMBER_TX, STATUS_CD FROM UniTrac..LOAN
WHERE   ID IN ( 43054539 )



SELECT * FROM dbo.USERS
WHERE ID IN (SELECT  CURRENT_OWNER_ID
FROM    WORK_ITEM wi
        JOIN WORKFLOW_DEFINITION wd ON wi.WORKFLOW_DEFINITION_ID = wd.id
WHERE   wi.STATUS_CD NOT IN ( 'Error', 'Complete', 'Withdrawn' )
--AND wi.LAST_EVALUATION_DT IS NULL
        AND wi.PURGE_DT IS NULL AND WORKFLOW_DEFINITION_ID = '8')
		ORDER BY GIVEN_NAME_TX DESC


		SELECT  *
FROM    WORK_ITEM wi
        JOIN WORKFLOW_DEFINITION wd ON wi.WORKFLOW_DEFINITION_ID = wd.id
WHERE   wi.STATUS_CD NOT IN ( 'Error', 'Complete', 'Withdrawn' )
--AND wi.LAST_EVALUATION_DT IS NULL
        AND wi.PURGE_DT IS NULL AND WORKFLOW_DEFINITION_ID = '8'
		AND CURRENT_OWNER_ID = '392'