SELECT COUNT(*) LenderExtract FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '1'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) UTLMatch FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '2'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) CPICancelPending FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '3'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) KeyImage FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '4'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)
 
SELECT COUNT(*) InboundCall FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '5'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) OutboundCall FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '6'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) ActionRequest FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '7'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) VerifyData FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '8'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) Cycle FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '9'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) BillingGroup FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '10'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) Escrow FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '11'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) EOMReporting FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '12'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) InsuranceBackfeed FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '13'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)

SELECT COUNT(*) AgentNotification FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '14'
AND CREATE_DT >= DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)