Remove-Item -recurse C:\Temp\UniTrac-PreProd\DirectoryWatcherIn -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\DirectoryWatcherOut -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\LDHService -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\LDHServiceUSD -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\LetterGen -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVRBSS -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVREDIIDR -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVREXTHUNT -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVREXTINFO -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVREXTUSD -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVREXTVUT -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\MSGSRVRDEF -exclude Osprey.*.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessService -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessServiceCycle -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessServiceMatchIn -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessServiceMatchOut -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessServicePRT -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracBusinessServiceRPT -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\UnitracSyncService -exclude *.Config
Remove-Item -recurse C:\Temp\UniTrac-PreProd\WorkflowService -exclude Osprey.*.Config
