USE ROLE OWNER_EDW_PROD;
USE WAREHOUSE EDW_PROD_INFA_WH;
USE DATABASE EDW_PROD;

USE SCHEMA STG;

DESCRIBE TABLE EDW_TEST.STG.ETL_VALIDATION_ROW;

CREATE TABLE STG.ETL_VALIDATION_ROW
(
 APP_CD       TEXT
,TBL_NM       TEXT
,PK_1_COLN_NM TEXT
,PK_2_COLN_NM TEXT
,PK_3_COLN_NM TEXT
,PK_VAL_1_TXT TEXT
,PK_VAL_2_TXT TEXT
,PK_VAL_3_TXT TEXT
,CREATE_DT    DATETIME
,UPDATE_DT    DATETIME
,PURGE_DT     DATETIME
);
