USE [DBA]
GO

/****** Object:  StoredProcedure [dbo].[DISABLE_IVOS_USER]    Script Date: 2/10/2022 3:07:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* 
PARAMETER INPUT ASSISTANCE:
@USER_LOGIN				= USERNAME USED TO LOGIN
@EDIT_USER				= PERSON WHO IS DISABLING THIS USER (Example: IAMAdmin)

/*
EXAMPLE OF HOW TO RUN THE STORED PROCEDURE: 
USE [IVOS]
GO

DECLARE
	  @USER_LOGIN				= 'TestUser2'				-- USERNAME USED TO LOGIN
	, @EDIT_USER				= 'IAMAdmin'				-- PERSON WHO IS ADDING THIS USER (Example: IAMAdmin)

EXECUTE [dbo].[DISABLE_IVOS_USER] 
	  @USER_LOGIN
	, @EDIT_USER
GO
*/

*/

CREATE PROC [dbo].[DISABLE_IVOS_USER] @USER_LOGIN VARCHAR(8000), @EDIT_USER VARCHAR(8000)
AS

SET NOCOUNT ON


DECLARE 
	  @EDIT_DATE				DATETIME		= GETDATE()		-- edit_date
	, @USER_STATUS				INT				= 0

UPDATE 
	[IVOS].[dbo].[pl_usr]
SET 
	usr_status = @USER_STATUS
	, edit_user = @EDIT_USER
	, edit_date = @EDIT_DATE
WHERE
	usr_login =  @USER_LOGIN

GO


