


use IVOS
DECLARE @P0 int,@P1 int

/* BEGIN ACTIVE SECTION (comment inserted by DPA) */  
SELECT RELATED_ITEM.MATTER_ID,  
   RELATED_ITEM.MATTER_ENTITY_ID,  
   RELATED_ITEM.NOTEPAD_ID,  
   RELATED_ITEM.STICKY_NOTE_ID,  
   RELATED_ITEM.CORRESPOND_ID,  
   RELATED_ITEM.DOCUMENT_IMAGE_ID,  
   RELATED_ITEM.DIARY_ID,  
   RELATED_ITEM.BUDGET_ID,  
   RELATED_ITEM.SETTLEMENT_INFO_ID,  
   RELATED_ITEM.MATTER_DISCOVERY_ID,  
   RELATED_ITEM.MATTER_EVENT_ID,  
   RELATED_ITEM.MATTER_ATTORNEY_ID,  
   RELATED_ITEM.INVOICE_ID,  
   RELATED_ITEM.CLAIM_ID,  
   RELATED_ITEM.CONTACT_ID,  
   RELATED_ITEM.ADD_USER,  
   RELATED_ITEM.ADD_DATE,  
   RELATED_ITEM.EDIT_USER,  
   RELATED_ITEM.EDIT_DATE  
FROM RELATED_ITEM  
WHERE 1=1  
AND RELATED_ITEM.notepad_id= @P0  
AND RELATED_ITEM.claim_id = @P1 


/*
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RELATED_ITEM') AND name = N'IX_RELATED_ITEM_CORRESPOND_ID')
BEGIN
CREATE INDEX [IX_RELATED_ITEM_CORRESPOND_ID] ON [IVOS].[dbo].[RELATED_ITEM] 

( [CLAIM_ID]) INCLUDE ([NOTEPAD_ID],[CORRESPOND_ID]) 

WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

END

GO


00:00:02.355 to install IVOS-SQLSTG-03

*/


