BACKUP DATABASE [KAFC_Admin] TO  DISK = N'\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Admin\KAFC_Admin.bak' 
WITH INIT , NOUNLOAD , NAME = 'KAFC_Admin', NOSKIP , STATS = 10, COMPRESSION, NOFORMAT


BACKUP LOG [KAFC_Admin] 
TO DISK = N'\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Admin\KAFC_Admin.log'  WITH NOFORMAT, NOINIT,  
NAME = N'KAFC_Admin Log', SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 10
GO


BACKUP DATABASE [KAFC_Meta] TO  DISK = N'\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Meta\KAFC_Meta.bak' 
WITH INIT , NOUNLOAD , NAME = 'KAFC_Meta', NOSKIP , STATS = 10, COMPRESSION, NOFORMAT



BACKUP LOG [KAFC_Meta] 
TO DISK = N'\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Meta\KAFC_Meta.log'  WITH NOFORMAT, NOINIT,  
NAME = N'KAFC_Meta Log', SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 10
GO




--Full
BACKUP DATABASE [KAFC_Data] TO
DISK = '\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data1.Bak',
DISK = '\\IGNITE-SQL14\I$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data2.Bak',
DISK = '\\IGNITE-SQL14\I$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data3.Bak',
DISK = '\\IGNITE-SQL14\I$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data4.Bak',
DISK = '\\IGNITE-SQL14\I$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data5.Bak'
WITH INIT , NOUNLOAD , NAME = 'KAFC_Data', NOSKIP , STATS = 10, COMPRESSION, NOFORMAT




BACKUP LOG [KAFC_Data] 
TO DISK = N'\\IGNITE-SQL14\i$\Restores\OCR-SQLTST-07\KAFC_Data\KAFC_Data.log'  WITH NOFORMAT, NOINIT,  
NAME = N'KAFC_Data Log', SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 10
GO
