USE [UniTrac_DW]
GO


select CONCAT ('REVOKE SELECT ON [', name, ']  TO [EccdbAppIntegrationDev];')
from sys.tables 
where name not in ('WEEKLY_DIM', 'OPEN_CERTIFICATE')


select CONCAT ('SELECT TOP 1 * FROM [Unitrac_DW].dbo.[', name, ']')
from sys.tables 
where name  in ('WEEKLY_DIM', 'OPEN_CERTIFICATE')

SELECT TOP 1 * FROM [Unitrac_DW].dbo.[OPEN_CERTIFICATE]

SELECT OBJECT_NAME(major_id), USER_NAME(grantee_principal_id),* 
FROM sys.database_permissions 
where state = 'G'
and USER_NAME(grantee_principal_id) <> 'public'

where USER_NAME(grantee_principal_id) ='Eldredge_A\Contractors - Pingahla'
order by state desc 


SELECT OBJECT_NAME(major_id), USER_NAME(grantee_principal_id),* 
FROM sys.database_permissions 
where USER_NAME(grantee_principal_id) ='EccdbAppIntegrationDev'
--='Eldredge_A\Contractors - Pingahla'
order by state desc 

select s.name as schema_name, 
    s.schema_id,
    u.name as schema_owner
from sys.schemas s
    inner join sys.sysusers u
        on u.uid = s.principal_id





GRANT SELECT ON WEEKLY_DIM TO [Eldredge_A\Contractors - Pingahla];
GRANT SELECT ON OPEN_CERTIFICATE TO [Eldredge_A\Contractors - Pingahla];

GRANT SELECT ON WEEKLY_DIM TO [Eldredge_A\UniTrac Allied Development Team];
GRANT SELECT ON OPEN_CERTIFICATE TO [Eldredge_A\UniTrac Allied Development Team];


CREATE USER [EccdbAppIntegrationDev] FOR LOGIN [EccdbAppIntegrationDev]


GRANT SELECT ON WEEKLY_DIM TO [EccdbAppIntegrationDev];
GRANT SELECT ON [Unitrac_DW].dbo.[OPEN_CERTIFICATE] TO [EccdbAppIntegrationDev];


DENY SELECT ON LINE_ITEM_DEF_CRITERIA TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REF_DOMAIN_ATTRIBUTE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_OUTBOUND_QUEUE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON OUTSTANDING_QUEUE_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REF_CODE_ATTRIBUTE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_DIM_09242015 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON SSIS_CONTROL_MAIN TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IVR_History TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IVRInterval TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON SSIS_CONTROL_DETAIL TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON INTERACTIONS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON INTERACTION_SUMMARY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_SUMMARY_FACT_backup7012019 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_2YR_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REGION_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_2YR_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Unitrac_Service_Statistics_History_3180 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_1YR_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CENTER_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_1YR_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_6MO_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_DIM_Backup TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_6MO_2019_Jun TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_CERTIFICATES_and_NOTICES TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DATE_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON ININ_CALL_DETAIL_old TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON COVERAGE_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON FAXDATA TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_VUT_CALL_SUMMARY_JUNE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON FTPFaxLog TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CONTRACT_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_DEF_CRITERIA_Backup_03142016 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_FACT_03172016 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_GREAT_PLAINS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_CENTER TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNTbck TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_WEB_USAGE_backup8102016 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_CertificateDataPoints TO [Eldredge_A\Contractors - Pingahla];
--DENY SELECT ON [ININ TOP 500] TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_CONTRACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_FACT_20160318 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON may2014_lsf TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_COVERAGE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON sysdiagrams TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_DocumentDataPoints TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_EDIDataPoints TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_LENDER TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_2YR_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_NoticeDataPoints TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_2YR_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_REGION TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_1YR_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON UniTracFees TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNT_BCKUP_Feb17 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON ININ_CALL_DETAIL TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_LoanCountInformation TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_1YR_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LOAN_HISTORY_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON NOTICE_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_6MO_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_6MO_2019_Jul TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON WEB_ACTION_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON EDI_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON WEB_ACTION_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNTold TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_SUMMARY_FACT_backupFeb17 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CERT_DESTINATION_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_SUMMARY_FACT_bckup8212019 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_FACT_Backup_08222019 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CERTIFICATE_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_DEF_CRITERIA_02202018 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON QUEUE_TYPE_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DASH_CACHE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNTolde TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON SERVICE_CENTER_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IAgentQueueStats TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IStatsGroup TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_INBOUND_CISCO_CALLS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IWrkgrpQueueStats TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_OUTBOUND_CISCO_CALLS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CISCO_OUTBOUND_CALLS_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_DEF_CRITERIA_Backup04012019 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CISCO_INBOUND_CALLS_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MONTH_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON PREMIUM_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON ININ_CALL_DETAIL_TEMP TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON IMAGE_TYPE_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_EXCEPTION_EXGRATIA_CANCELLATIONS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LOAN_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_VUT_PREMIUM_SUMMARY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_CLAIM_SUMMARY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_SUMMARY_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON EXGRATIA_EXCEPTION_CANCELLATION_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_VUT_LOAN_COUNT_SUMMARY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REQUIRED_COVERAGE_STATUS TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_ID_MAP TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_DIM_ATTRIBUTE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON ININ_CALLID_MONTHLY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON SALES_REGION_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_SALES_REGION TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_LENDER_IMAGE_MANAGEMENT_CONSOLE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON JOB_TITLE_DEF TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_STATE_SALES_REGION_MAP TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_IMAGE_MANAGEMENT_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON STATE_SALES_REGION_MAP TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON JOB_CODE_JOB_TITLE_DEF_MAP TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON PS_HEAD_COUNT_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_DATASTORE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON FAX_CALL_IMPORT_DATE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON FEE_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_HEAD_COUNT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_OMR_CLAIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_FUNCTION_DEF TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CLAIMS_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_DEF_CRITERIA_Backup_05092017 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_FAX_MANAGEMENT_CONSOLE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_GREAT_PLAINS_PLAN TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON FAX_MANAGEMENT_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON MOVE_PROC_COUNTBackup_June2016 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LINE_ITEM_FACT_BCK TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON PROCESS_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON ESR_HISTORY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON Temp_ProcessDataPoints TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON PROCESS_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_VUT_CALL_SUMMARY1 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_VUT_CALL_SUMMARY TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_WEB_USAGE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON AGENCY_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_SUMMARY_FACT_BackupJuly TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON sysssislog TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON TEMP_LENDER_EXTRACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_DIM TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON LENDER_EXTRACT_FACT TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON PROCESS_FACT_05202012 TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_2YR_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_2YR_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_1YR_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_1YR_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REF_DOMAIN TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REPORT_HISTORY_6MO_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON DOCUMENT_CONTAINER_RH_6MO_2019_May TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON REF_CODE TO [Eldredge_A\Contractors - Pingahla];
DENY SELECT ON CISCO_EXTENSION_MAP TO [Eldredge_A\Contractors - Pingahla];

DENY SELECT ON [LINE_ITEM_DEF_CRITERIA]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REF_DOMAIN_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_OUTBOUND_QUEUE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [OUTSTANDING_QUEUE_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REF_CODE_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_DIM_09242015]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [SSIS_CONTROL_MAIN]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IVR_History]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IVRInterval]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [SSIS_CONTROL_DETAIL]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [INTERACTIONS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [INTERACTION_SUMMARY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_SUMMARY_FACT_backup7012019]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_2YR_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REGION_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Unitrac_Service_Statistics_History_3180]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_1YR_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CENTER_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_6MO_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_DIM_Backup]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jun]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_CERTIFICATES_and_NOTICES]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DATE_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ININ_CALL_DETAIL_old]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [COVERAGE_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [FAXDATA]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_VUT_CALL_SUMMARY_JUNE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [FTPFaxLog]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CONTRACT_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_03142016]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_FACT_03172016]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_GREAT_PLAINS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_CENTER]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNTbck]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_WEB_USAGE_backup8102016]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_CertificateDataPoints]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ININ TOP 500]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_CONTRACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_FACT_20160318]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [may2014_lsf]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_COVERAGE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [sysdiagrams]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_DocumentDataPoints]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_EDIDataPoints]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_LENDER]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_2YR_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_NoticeDataPoints]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_REGION]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_1YR_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [UniTracFees]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNT_BCKUP_Feb17]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ININ_CALL_DETAIL]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_LoanCountInformation]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LOAN_HISTORY_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [NOTICE_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_6MO_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jul]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [WEB_ACTION_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [EDI_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [WEB_ACTION_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNTold]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_SUMMARY_FACT_backupFeb17]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CERT_DESTINATION_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_SUMMARY_FACT_bckup8212019]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_FACT_Backup_08222019]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CERTIFICATE_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_DEF_CRITERIA_02202018]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [QUEUE_TYPE_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DASH_CACHE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNTolde]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [SERVICE_CENTER_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IAgentQueueStats]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IStatsGroup]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_INBOUND_CISCO_CALLS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IWrkgrpQueueStats]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_OUTBOUND_CISCO_CALLS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CISCO_OUTBOUND_CALLS_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup04012019]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CISCO_INBOUND_CALLS_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MONTH_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [PREMIUM_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ININ_CALL_DETAIL_TEMP]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [IMAGE_TYPE_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_EXCEPTION_EXGRATIA_CANCELLATIONS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LOAN_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_VUT_PREMIUM_SUMMARY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_CLAIM_SUMMARY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_SUMMARY_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [EXGRATIA_EXCEPTION_CANCELLATION_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_VUT_LOAN_COUNT_SUMMARY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REQUIRED_COVERAGE_STATUS]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_ID_MAP]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_DIM_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ININ_CALLID_MONTHLY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [SALES_REGION_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_SALES_REGION]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_LENDER_IMAGE_MANAGEMENT_CONSOLE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [JOB_TITLE_DEF]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_STATE_SALES_REGION_MAP]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_IMAGE_MANAGEMENT_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [STATE_SALES_REGION_MAP]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [JOB_CODE_JOB_TITLE_DEF_MAP]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [PS_HEAD_COUNT_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_DATASTORE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [FAX_CALL_IMPORT_DATE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [FEE_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_HEAD_COUNT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_OMR_CLAIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_FUNCTION_DEF]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CLAIMS_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_05092017]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_FAX_MANAGEMENT_CONSOLE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_GREAT_PLAINS_PLAN]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [FAX_MANAGEMENT_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [MOVE_PROC_COUNTBackup_June2016]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LINE_ITEM_FACT_BCK]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [PROCESS_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [ESR_HISTORY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [Temp_ProcessDataPoints]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [PROCESS_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_VUT_CALL_SUMMARY1]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_VUT_CALL_SUMMARY]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_WEB_USAGE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [AGENCY_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_SUMMARY_FACT_BackupJuly]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [sysssislog]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [TEMP_LENDER_EXTRACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_DIM]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [LENDER_EXTRACT_FACT]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [PROCESS_FACT_05202012]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_2YR_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_1YR_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REF_DOMAIN]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REPORT_HISTORY_6MO_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_May]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [REF_CODE]  TO [EccdbAppIntegrationDev];
DENY SELECT ON [CISCO_EXTENSION_MAP]  TO [EccdbAppIntegrationDev];



CREATE USER [EccdbAppIntegrationDev] FOR LOGIN [EccdbAppIntegrationDev];

CREATE ROLE [DW_APP_ACCESS] AUTHORIZATION [dbo];


GRANT SELECT ON WEEKLY_DIM TO [DW_APP_ACCESS];
GRANT SELECT ON [Unitrac_DW].dbo.[OPEN_CERTIFICATE] TO [DW_APP_ACCESS];



ALTER ROLE [DW_APP_ACCESS] ADD MEMBER [EccdbAppIntegrationDev];

GRANT SELECT ON [LINE_ITEM_DEF_CRITERIA]  TO [public];
GRANT SELECT ON [REF_DOMAIN_ATTRIBUTE]  TO [public];
GRANT SELECT ON [TEMP_OUTBOUND_QUEUE]  TO [public];
GRANT SELECT ON [OUTSTANDING_QUEUE_FACT]  TO [public];
GRANT SELECT ON [REF_CODE_ATTRIBUTE]  TO [public];
GRANT SELECT ON [LENDER_DIM_09242015]  TO [public];
GRANT SELECT ON [SSIS_CONTROL_MAIN]  TO [public];
GRANT SELECT ON [IVR_History]  TO [public];
GRANT SELECT ON [IVRInterval]  TO [public];
GRANT SELECT ON [SSIS_CONTROL_DETAIL]  TO [public];
GRANT SELECT ON [INTERACTIONS]  TO [public];
GRANT SELECT ON [INTERACTION_SUMMARY]  TO [public];
GRANT SELECT ON [LENDER_SUMMARY_FACT_backup7012019]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_2YR_2019_Jun]  TO [public];
GRANT SELECT ON [REGION_DIM]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jun]  TO [public];
GRANT SELECT ON [Unitrac_Service_Statistics_History_3180]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_1YR_2019_Jun]  TO [public];
GRANT SELECT ON [CENTER_DIM]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jun]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_6MO_2019_Jun]  TO [public];
GRANT SELECT ON [LENDER_DIM_Backup]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jun]  TO [public];
GRANT SELECT ON [TEMP_CERTIFICATES_and_NOTICES]  TO [public];
GRANT SELECT ON [DATE_DIM]  TO [public];
GRANT SELECT ON [ININ_CALL_DETAIL_old]  TO [public];
GRANT SELECT ON [COVERAGE_DIM]  TO [public];
GRANT SELECT ON [FAXDATA]  TO [public];
GRANT SELECT ON [TEMP_VUT_CALL_SUMMARY_JUNE]  TO [public];
GRANT SELECT ON [FTPFaxLog]  TO [public];
GRANT SELECT ON [CONTRACT_DIM]  TO [public];
GRANT SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_03142016]  TO [public];
GRANT SELECT ON [LINE_ITEM_FACT_03172016]  TO [public];
GRANT SELECT ON [TEMP_GREAT_PLAINS]  TO [public];
GRANT SELECT ON [TEMP_CENTER]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNTbck]  TO [public];
GRANT SELECT ON [TEMP_WEB_USAGE_backup8102016]  TO [public];
GRANT SELECT ON [Temp_CertificateDataPoints]  TO [public];
GRANT SELECT ON [ININ TOP 500]  TO [public];
GRANT SELECT ON [TEMP_CONTRACT]  TO [public];
GRANT SELECT ON [LINE_ITEM_FACT_20160318]  TO [public];
GRANT SELECT ON [may2014_lsf]  TO [public];
GRANT SELECT ON [TEMP_COVERAGE]  TO [public];
GRANT SELECT ON [sysdiagrams]  TO [public];
GRANT SELECT ON [Temp_DocumentDataPoints]  TO [public];
GRANT SELECT ON [Temp_EDIDataPoints]  TO [public];
GRANT SELECT ON [LINE_ITEM_FACT]  TO [public];
GRANT SELECT ON [TEMP_LENDER]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_2YR_2019_Jul]  TO [public];
GRANT SELECT ON [Temp_NoticeDataPoints]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jul]  TO [public];
GRANT SELECT ON [TEMP_REGION]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_1YR_2019_Jul]  TO [public];
GRANT SELECT ON [UniTracFees]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNT_BCKUP_Feb17]  TO [public];
GRANT SELECT ON [ININ_CALL_DETAIL]  TO [public];
GRANT SELECT ON [Temp_LoanCountInformation]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jul]  TO [public];
GRANT SELECT ON [LOAN_HISTORY_FACT]  TO [public];
GRANT SELECT ON [NOTICE_FACT]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_6MO_2019_Jul]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jul]  TO [public];
GRANT SELECT ON [WEB_ACTION_DIM]  TO [public];
GRANT SELECT ON [EDI_FACT]  TO [public];
GRANT SELECT ON [WEB_ACTION_FACT]  TO [public];
GRANT SELECT ON [OPEN_CERTIFICATE]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNTold]  TO [public];
GRANT SELECT ON [DOCUMENT_FACT]  TO [public];
GRANT SELECT ON [LENDER_SUMMARY_FACT_backupFeb17]  TO [public];
GRANT SELECT ON [WEEKLY_DIM]  TO [public];
GRANT SELECT ON [CERT_DESTINATION_DIM]  TO [public];
GRANT SELECT ON [LENDER_SUMMARY_FACT_bckup8212019]  TO [public];
GRANT SELECT ON [LINE_ITEM_FACT_Backup_08222019]  TO [public];
GRANT SELECT ON [CERTIFICATE_FACT]  TO [public];
GRANT SELECT ON [LINE_ITEM_DEF_CRITERIA_02202018]  TO [public];
GRANT SELECT ON [QUEUE_TYPE_DIM]  TO [public];
GRANT SELECT ON [DASH_CACHE]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNTolde]  TO [public];
GRANT SELECT ON [SERVICE_CENTER_DIM]  TO [public];
GRANT SELECT ON [IAgentQueueStats]  TO [public];
GRANT SELECT ON [IStatsGroup]  TO [public];
GRANT SELECT ON [TEMP_INBOUND_CISCO_CALLS]  TO [public];
GRANT SELECT ON [IWrkgrpQueueStats]  TO [public];
GRANT SELECT ON [TEMP_OUTBOUND_CISCO_CALLS]  TO [public];
GRANT SELECT ON [CISCO_OUTBOUND_CALLS_FACT]  TO [public];
GRANT SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup04012019]  TO [public];
GRANT SELECT ON [CISCO_INBOUND_CALLS_FACT]  TO [public];
GRANT SELECT ON [MONTH_DIM]  TO [public];
GRANT SELECT ON [PREMIUM_FACT]  TO [public];
GRANT SELECT ON [ININ_CALL_DETAIL_TEMP]  TO [public];
GRANT SELECT ON [IMAGE_TYPE_DIM]  TO [public];
GRANT SELECT ON [TEMP_EXCEPTION_EXGRATIA_CANCELLATIONS]  TO [public];
GRANT SELECT ON [LOAN_FACT]  TO [public];
GRANT SELECT ON [TEMP_VUT_PREMIUM_SUMMARY]  TO [public];
GRANT SELECT ON [TEMP_CLAIM_SUMMARY]  TO [public];
GRANT SELECT ON [LENDER_SUMMARY_FACT]  TO [public];
GRANT SELECT ON [EXGRATIA_EXCEPTION_CANCELLATION_FACT]  TO [public];
GRANT SELECT ON [TEMP_VUT_LOAN_COUNT_SUMMARY]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNT]  TO [public];
GRANT SELECT ON [REQUIRED_COVERAGE_STATUS]  TO [public];
GRANT SELECT ON [LENDER_ID_MAP]  TO [public];
GRANT SELECT ON [LENDER_DIM_ATTRIBUTE]  TO [public];
GRANT SELECT ON [ININ_CALLID_MONTHLY]  TO [public];
GRANT SELECT ON [SALES_REGION_DIM]  TO [public];
GRANT SELECT ON [TEMP_SALES_REGION]  TO [public];
GRANT SELECT ON [TEMP_LENDER_IMAGE_MANAGEMENT_CONSOLE]  TO [public];
GRANT SELECT ON [JOB_TITLE_DEF]  TO [public];
GRANT SELECT ON [TEMP_STATE_SALES_REGION_MAP]  TO [public];
GRANT SELECT ON [LENDER_IMAGE_MANAGEMENT_FACT]  TO [public];
GRANT SELECT ON [STATE_SALES_REGION_MAP]  TO [public];
GRANT SELECT ON [JOB_CODE_JOB_TITLE_DEF_MAP]  TO [public];
GRANT SELECT ON [PS_HEAD_COUNT_FACT]  TO [public];
GRANT SELECT ON [TEMP_DATASTORE]  TO [public];
GRANT SELECT ON [FAX_CALL_IMPORT_DATE]  TO [public];
GRANT SELECT ON [FEE_FACT]  TO [public];
GRANT SELECT ON [TEMP_HEAD_COUNT]  TO [public];
GRANT SELECT ON [TEMP_OMR_CLAIM]  TO [public];
GRANT SELECT ON [REPORT_FUNCTION_DEF]  TO [public];
GRANT SELECT ON [CLAIMS_FACT]  TO [public];
GRANT SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_05092017]  TO [public];
GRANT SELECT ON [TEMP_FAX_MANAGEMENT_CONSOLE]  TO [public];
GRANT SELECT ON [TEMP_GREAT_PLAINS_PLAN]  TO [public];
GRANT SELECT ON [FAX_MANAGEMENT_FACT]  TO [public];
GRANT SELECT ON [MOVE_PROC_COUNTBackup_June2016]  TO [public];
GRANT SELECT ON [LINE_ITEM_FACT_BCK]  TO [public];
GRANT SELECT ON [PROCESS_DIM]  TO [public];
GRANT SELECT ON [ESR_HISTORY]  TO [public];
GRANT SELECT ON [Temp_ProcessDataPoints]  TO [public];
GRANT SELECT ON [PROCESS_FACT]  TO [public];
GRANT SELECT ON [TEMP_VUT_CALL_SUMMARY1]  TO [public];
GRANT SELECT ON [TEMP_VUT_CALL_SUMMARY]  TO [public];
GRANT SELECT ON [TEMP_WEB_USAGE]  TO [public];
GRANT SELECT ON [AGENCY_DIM]  TO [public];
GRANT SELECT ON [LENDER_SUMMARY_FACT_BackupJuly]  TO [public];
GRANT SELECT ON [sysssislog]  TO [public];
GRANT SELECT ON [TEMP_LENDER_EXTRACT]  TO [public];
GRANT SELECT ON [LENDER_DIM]  TO [public];
GRANT SELECT ON [LENDER_EXTRACT_FACT]  TO [public];
GRANT SELECT ON [PROCESS_FACT_05202012]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_2YR_2019_May]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_May]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_1YR_2019_May]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_May]  TO [public];
GRANT SELECT ON [REF_DOMAIN]  TO [public];
GRANT SELECT ON [REPORT_HISTORY_6MO_2019_May]  TO [public];
GRANT SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_May]  TO [public];
GRANT SELECT ON [REF_CODE]  TO [public];
GRANT SELECT ON [CISCO_EXTENSION_MAP]  TO [public];



REVOKE SELECT ON [LINE_ITEM_DEF_CRITERIA]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REF_DOMAIN_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_OUTBOUND_QUEUE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [OUTSTANDING_QUEUE_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REF_CODE_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_DIM_09242015]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [SSIS_CONTROL_MAIN]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IVR_History]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IVRInterval]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [SSIS_CONTROL_DETAIL]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [INTERACTIONS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [INTERACTION_SUMMARY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_SUMMARY_FACT_backup7012019]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_2YR_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REGION_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Unitrac_Service_Statistics_History_3180]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_1YR_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CENTER_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_6MO_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_DIM_Backup]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jun]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_CERTIFICATES_and_NOTICES]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DATE_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ININ_CALL_DETAIL_old]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [COVERAGE_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [FAXDATA]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_VUT_CALL_SUMMARY_JUNE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [FTPFaxLog]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CONTRACT_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_03142016]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_FACT_03172016]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_GREAT_PLAINS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_CENTER]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNTbck]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_WEB_USAGE_backup8102016]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_CertificateDataPoints]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ININ TOP 500]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_CONTRACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_FACT_20160318]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [may2014_lsf]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_COVERAGE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [sysdiagrams]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_DocumentDataPoints]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_EDIDataPoints]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_LENDER]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_2YR_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_NoticeDataPoints]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_REGION]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_1YR_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [UniTracFees]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNT_BCKUP_Feb17]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ININ_CALL_DETAIL]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_LoanCountInformation]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LOAN_HISTORY_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [NOTICE_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_6MO_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_Jul]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [WEB_ACTION_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [EDI_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [WEB_ACTION_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNTold]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_SUMMARY_FACT_backupFeb17]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CERT_DESTINATION_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_SUMMARY_FACT_bckup8212019]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_FACT_Backup_08222019]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CERTIFICATE_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_DEF_CRITERIA_02202018]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [QUEUE_TYPE_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DASH_CACHE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNTolde]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [SERVICE_CENTER_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IAgentQueueStats]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IStatsGroup]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_INBOUND_CISCO_CALLS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IWrkgrpQueueStats]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_OUTBOUND_CISCO_CALLS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CISCO_OUTBOUND_CALLS_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup04012019]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CISCO_INBOUND_CALLS_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MONTH_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [PREMIUM_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ININ_CALL_DETAIL_TEMP]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [IMAGE_TYPE_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_EXCEPTION_EXGRATIA_CANCELLATIONS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LOAN_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_VUT_PREMIUM_SUMMARY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_CLAIM_SUMMARY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_SUMMARY_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [EXGRATIA_EXCEPTION_CANCELLATION_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_VUT_LOAN_COUNT_SUMMARY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REQUIRED_COVERAGE_STATUS]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_ID_MAP]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_DIM_ATTRIBUTE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ININ_CALLID_MONTHLY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [SALES_REGION_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_SALES_REGION]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_LENDER_IMAGE_MANAGEMENT_CONSOLE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [JOB_TITLE_DEF]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_STATE_SALES_REGION_MAP]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_IMAGE_MANAGEMENT_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [STATE_SALES_REGION_MAP]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [JOB_CODE_JOB_TITLE_DEF_MAP]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [PS_HEAD_COUNT_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_DATASTORE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [FAX_CALL_IMPORT_DATE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [FEE_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_HEAD_COUNT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_OMR_CLAIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_FUNCTION_DEF]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CLAIMS_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_DEF_CRITERIA_Backup_05092017]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_FAX_MANAGEMENT_CONSOLE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_GREAT_PLAINS_PLAN]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [FAX_MANAGEMENT_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [MOVE_PROC_COUNTBackup_June2016]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LINE_ITEM_FACT_BCK]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [PROCESS_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [ESR_HISTORY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [Temp_ProcessDataPoints]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [PROCESS_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_VUT_CALL_SUMMARY1]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_VUT_CALL_SUMMARY]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_WEB_USAGE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [AGENCY_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_SUMMARY_FACT_BackupJuly]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [sysssislog]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [TEMP_LENDER_EXTRACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_DIM]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [LENDER_EXTRACT_FACT]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [PROCESS_FACT_05202012]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_2YR_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_2YR_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_1YR_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_1YR_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REF_DOMAIN]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REPORT_HISTORY_6MO_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [DOCUMENT_CONTAINER_RH_6MO_2019_May]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [REF_CODE]  TO [EccdbAppIntegrationDev];
REVOKE SELECT ON [CISCO_EXTENSION_MAP]  TO [EccdbAppIntegrationDev];