----Scripts ran on Friday 
USE [master]

GO

ALTER DATABASE [IQQ_LIVE] MODIFY FILE ( NAME = N'IQQ_log', MAXSIZE = 512000000KB, FILEGROWTH = 307200KB )

GO

USE iqq_live

CREATE NONCLUSTERED INDEX [IDX_QUOTE_PURGE_DT_INCLUDE]
  ON [dbo].[QUOTE] ([PURGE_DT])
  INCLUDE ([BRANCH_ID], [VENDOR_OFFERING_ID], [SOURCE_CD], [PRODUCT_ID], [QUOTE_DT])WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

/*
CREATE INDEX Harold_Brotherton_wants_and_asked_for_this_a_year_ago ON [iqq_live].[dbo].[QUOTE_TERM_DETAIL] ([QUOTE_TERM_ID]) 
    INCLUDE ([ID], [KEY_TX], [VALUE_TX], [LOCK_ID]);
CREATE INDEX Steve_Moran_Wants ON [iqq_live].[dbo].[QUOTE_TERM] ([QUOTE_PLAN_ID], [PURGE_DT]) 
    INCLUDE ([ID], [PRODUCT_TYPE_CD], [SELECTED_IN], [INCLUSIVE_IN], [COST_NO], [UNCAPPED_COST_NO], [FLAGS], [VARIABLE_COMPENSATION_NO], [LOCK_ID])
*/
---Script ran on Monday 
CREATE INDEX QUOTE_TERM_DETAIL_QUOTE_TERM_ID
  ON [iqq_live].[dbo].[QUOTE_TERM_DETAIL] ([QUOTE_TERM_ID])
  INCLUDE ([ID], [KEY_TX], [VALUE_TX], [LOCK_ID]) WITH (SORT_IN_TEMPDB = ON, ONLINE = ON)

CREATE INDEX QUOTE_TERM_QUOTE_PLAN_ID_PURGE_DT
  ON [iqq_live].[dbo].[QUOTE_TERM] ([QUOTE_PLAN_ID], [PURGE_DT])
  INCLUDE ([ID], [PRODUCT_TYPE_CD], [SELECTED_IN], [INCLUSIVE_IN], [COST_NO], [UNCAPPED_COST_NO], [FLAGS], [VARIABLE_COMPENSATION_NO], [LOCK_ID]) WITH (SORT_IN_TEMPDB = ON, ONLINE = ON) 
