USE ROLE ACCOUNTADMIN;

BEGIN
	CASE WHEN (select COUNT(*) FROM information_schema.ENABLED_ROLES where NAME = 'PHDATA_ADVISOR_ROLE') = 0
	THEN

CREATE ROLE PHDATA_ADVISOR_ROLE;


RETURN 'SUCCESS: Role created';

ELSE 

RETURN 'WARNING: Role exists';


	END;
    
END;


GRANT USAGE ON WAREHOUSE EDW_PROD_INFA_WH TO ROLE PHDATA_ADVISOR_ROLE;
GRANT OPERATE ON WAREHOUSE EDW_PROD_INFA_WH TO ROLE PHDATA_ADVISOR_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE PHDATA_ADVISOR_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE EDW_PROD TO ROLE PHDATA_ADVISOR_ROLE;

GRANT ROLE IDENTIFIER('"PHDATA_ADVISOR_ROLE"') TO ROLE IDENTIFIER('"SYSADMIN"');



USE ROLE ACCOUNTADMIN;

BEGIN
	CASE WHEN (select COUNT(*) FROM snowflake.account_usage.users where NAME = 'PHDATA_ADVISOR')  = 0
	THEN

create USER IDENTIFIER('"PHDATA_ADVISOR"') COMMENT = 'phData Advisor User' PASSWORD = 'Password_in_CyberArk' 
MUST_CHANGE_PASSWORD = false LOGIN_NAME = 'PHDATA_ADVISOR' FIRST_NAME = '' LAST_NAME = '' DISPLAY_NAME = 'phData Advisor User' EMAIL = '' DEFAULT_NAMESPACE = '' 
DEFAULT_ROLE = 'PHDATA_ADVISOR_ROLE';
GRANT ROLE IDENTIFIER('"PHDATA_ADVISOR_ROLE"') TO USER IDENTIFIER('"PHDATA_ADVISOR"');
RETURN 'SUCCESS: Account created';

ELSE 


RETURN 'WARNING: Account exists';
	END;
    
END;



