USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OCR-Capture-Temp] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [OCR]
GO
CREATE USER [ELDREDGE_A\OCR-Capture-Temp] FOR LOGIN [ELDREDGE_A\OCR-Capture-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OCR-Capture-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OCR-Capture-Temp]
GO




USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OCR-Search-Temp] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [OCR]
GO
CREATE USER [ELDREDGE_A\OCR-Search-Temp] FOR LOGIN [ELDREDGE_A\OCR-Search-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OCR-Search-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OCR-Search-Temp]
GO




USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OCR-Transform-Temp] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [OCR]
GO
CREATE USER [ELDREDGE_A\OCR-Transform-Temp] FOR LOGIN [ELDREDGE_A\OCR-Transform-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OCR-Transform-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OCR-Transform-Temp]
GO




USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OCR-Daemon-Temp] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [OCR]
GO
CREATE USER [ELDREDGE_A\OCR-Daemon-Temp] FOR LOGIN [ELDREDGE_A\OCR-Daemon-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OCR-Daemon-Temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OCR-Daemon-Temp]
GO







USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OCR-reports-temp] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [OCR]
GO
CREATE USER [ELDREDGE_A\OCR-reports-temp] FOR LOGIN [ELDREDGE_A\OCR-reports-temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OCR-reports-temp]
GO
USE [OCR]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OCR-reports-temp]
GO






