USE iqq_live 

   RETURN
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCT') AND name = N'IX_PRODUCT_TYPE_CD_PURGE_DT')
BEGIN
    BEGIN TRY   
		CREATE NONCLUSTERED INDEX [IX_PRODUCT_TYPE_CD_PURGE_DT] ON [dbo].[PRODUCT] (
	[TYPE_CD] ASC,
	[PURGE_DT] ASC
)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		  END TRY  
    BEGIN CATCH  
		PRINT 'WARNING: [IX_PRODUCT_TYPE_CD_PURGE_DT] ON [dbo].[PRODUCT] was not added either not in the correct database or index itself failed.'
   RETURN
    END CATCH  

PRINT 'SUCCESS:  [IX_PRODUCT_TYPE_CD_PURGE_DT] ON [dbo].[PRODUCT] successfully added'
END
	ELSE
BEGIN
		PRINT 'WARNING: [IX_PRODUCT_TYPE_CD_PURGE_DT] ON [dbo].[PRODUCT] was not added either table does not exist or index already exists'
END



