USE ROLE SYSADMIN;
USE WAREHOUSE BOND_PROD_INFA_WH;
USE DATABASE BOND_PROD;

BEGIN
	CASE WHEN (select count(*) from information_schema.schemata  where CATALOG_NAME = 'BOND_PROD'AND SCHEMA_NAME = 'BONDFLYWAY' ) = 1
	THEN
DROP SCHEMA BONDFLYWAY;
RETURN 'SUCCESS: Schema BONDFLYWAY DROPPED';

ELSE 

RETURN 'WARNING: Schema STILL exists';

	END;
    END;

use role OWNER_BOND_PROD;

BEGIN
	CASE WHEN (select count(*) from information_schema.schemata  where CATALOG_NAME = 'BOND_PROD'AND SCHEMA_NAME = 'BONDFLYWAY' ) = 0
	THEN

CREATE SCHEMA BONDFLYWAY;
RETURN 'SUCCESS: Schema BONDFLYWAY created';

ELSE 

RETURN 'WARNING: Schema exists';

	END;
    
END;
GRANT USAGE ON SCHEMA BONDFLYWAY TO ROLE OWNER_BOND_PROD;
GRANT USAGE ON SCHEMA BONDFLYWAY TO ROLE READWRITE_BOND_PROD;
GRANT USAGE ON SCHEMA BONDFLYWAY TO ROLE READ_BOND_PROD;