SELECT rh.ID
INTO #tmpRHID
FROM REPORT_HISTORY rh
    JOIN dbo.LENDER L
        ON L.ID = rh.LENDER_ID
    LEFT JOIN REPORT R
        ON R.ID = rh.REPORT_ID
WHERE rh.STATUS_CD = 'ERR'
      AND CAST(rh.UPDATE_DT AS DATE) >= CAST(GETDATE()-1 AS DATE)
ORDER BY rh.MSG_LOG_TX DESC;

---Update the Errors
UPDATE RH
SET STATUS_CD = 'PEND',
    RETRY_COUNT_NO = 0,
    MSG_LOG_TX = NULL,
    RECORD_COUNT_NO = 0,
    ELAPSED_RUNTIME_NO = 0,
    UPDATE_DT = GETDATE(),
    DOCUMENT_CONTAINER_ID = NULL, RH.UPDATE_USER_TX = 'AIH_7989'
--SELECT * 
FROM  [UniTrac].[dbo].[REPORT_HISTORY] RH
WHERE 
    ID IN (SELECT id FROM #tmpRHID )


UPDATE RH
SET STATUS_CD = 'IGN',
    RETRY_COUNT_NO = 0,
    MSG_LOG_TX = NULL,
    RECORD_COUNT_NO = 0,
    ELAPSED_RUNTIME_NO = 0,
    UPDATE_DT = GETDATE(),
    DOCUMENT_CONTAINER_ID = NULL, RH.UPDATE_USER_TX = 'AIH_7989'
--SELECT * 
FROM  [UniTrac].[dbo].[REPORT_HISTORY] RH
WHERE 
    ID IN (28399552, 28399544, 28401228, 28401229 )



