USE [Premacc3]
GO
/****** Object:  Table [dbo].[Big_Parameters]    Script Date: 9/12/2023 2:19:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Big_Parameters](
	[Big_Parameter_Name] [nvarchar](50) NOT NULL,
	[Big_Parameter_Value] [ntext] NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BSS_TranLog]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BSS_TranLog](
	[ID] [bigint] NOT NULL,
	[InputOutput_ID] [bigint] NOT NULL,
	[LoggedFrom] [nvarchar](50) NULL,
	[FrontEnd_Version] [nvarchar](30) NULL,
	[Middle_Version] [nvarchar](30) NULL,
	[BackEnd_Version] [nvarchar](30) NULL,
	[Server_Machine] [nvarchar](128) NULL,
	[ServerTime_DTO] [datetimeoffset](7) NULL,
	[ClientTime_DTO] [datetimeoffset](7) NULL,
	[ActionYear] [int] NULL,
	[ActionMonth] [int] NULL,
	[ActionAttempt] [tinyint] NULL,
	[ActionMethod] [nvarchar](50) NOT NULL,
	[HTTP_Method] [nvarchar](20) NULL,
	[Act_Lookup_InsDoc] [bit] NULL,
	[Act_Get_InsDoc] [bit] NULL,
	[Act_Submit_InsDoc] [bit] NULL,
	[Act_Submit_InsDoc_WithAttach] [bit] NULL,
	[Act_Upload_Attach] [bit] NULL,
	[Act_Survey] [bit] NULL,
	[ActionCodePrefix] [nvarchar](15) NULL,
	[ActionCodeSuffix_A_B] [nvarchar](5) NULL,
	[ActionCodeSuffix_M_V] [nvarchar](5) NULL,
	[ActionCodeSuffix_Other] [nvarchar](10) NULL,
	[Origin_User] [nvarchar](50) NOT NULL,
	[Origin_Phone] [nvarchar](20) NULL,
	[Origin_Email] [nvarchar](100) NULL,
	[Originator] [nvarchar](35) NULL,
	[Agent] [bit] NULL,
	[Borrower] [bit] NULL,
	[Other_A_B] [nvarchar](30) NULL,
	[ContractCode] [nvarchar](10) NULL,
	[Vehicle] [bit] NULL,
	[Mortgage] [bit] NULL,
	[Other_M_V] [nvarchar](100) NULL,
	[User_IP] [nvarchar](50) NULL,
	[Session] [nvarchar](50) NULL,
	[User_Browser] [nvarchar](160) NULL,
	[AbandonAttempt_DTO] [datetimeoffset](7) NULL,
	[Abandon_DTO] [datetimeoffset](7) NULL,
	[AbandonAttempt_Question] [nvarchar](100) NULL,
	[AbandonAttempt_Step] [nvarchar](10) NULL,
	[AbandonAttempt_Route] [nvarchar](50) NULL,
	[Abandon_Answer] [nvarchar](200) NULL,
	[Abandon_Step] [nvarchar](10) NULL,
	[Abandon_Route] [nvarchar](50) NULL,
	[URL_CameFrom] [nvarchar](250) NULL,
	[Host_Domain] [nvarchar](50) NULL,
	[URL_Route] [nvarchar](50) NULL,
	[URL_RefID] [nvarchar](22) NULL,
	[URL_Source] [nvarchar](15) NULL,
	[URL_LeaveTo] [nvarchar](250) NULL,
	[Source_SMS] [bit] NULL,
	[Source_Email] [bit] NULL,
	[Source_SmartVideo] [bit] NULL,
	[Step0_Message] [nvarchar](max) NULL,
	[NoRef] [bit] NULL,
	[NoRef_Other] [bit] NULL,
	[ReferenceID] [nvarchar](22) NULL,
	[COVERAGE_ID] [bigint] NULL,
	[COLLATERAL_ID] [bigint] NULL,
	[PROPERTY_ID] [bigint] NULL,
	[LenderCode] [nvarchar](10) NOT NULL,
	[LenderBrand_ID] [int] NULL,
	[LenderBrand_Color] [nvarchar](50) NULL,
	[LenderBrand_LogoFile] [nvarchar](250) NULL,
	[Branch] [nvarchar](20) NULL,
	[Department] [nvarchar](20) NULL,
	[Division] [nvarchar](20) NULL,
	[LOAN_ID] [bigint] NULL,
	[LoanNumber] [nvarchar](18) NULL,
	[PolicyNumber] [nvarchar](30) NULL,
	[FPC_ID] [bigint] NULL,
	[OWNER_POLICY_ID] [bigint] NULL,
	[POLICY_COVERAGE_ID] [bigint] NULL,
	[PrimaryOwner_ID] [bigint] NULL,
	[PrimaryOwner_Type] [nvarchar](4) NULL,
	[Lienholder_ID] [bigint] NULL,
	[Lienholder_Type] [nvarchar](4) NULL,
	[BIC_Carrier] [nvarchar](100) NULL,
	[CoverageType] [nvarchar](30) NULL,
	[HasLiabCov] [bit] NULL,
	[CovAmounts] [nvarchar](250) NULL,
	[WindCovIncluded] [bit] NULL,
	[FloodCovPrivate] [bit] NULL,
	[CovEffective_DT] [datetime] NULL,
	[ContinuousCov] [bit] NULL,
	[CovExpiration_DT] [datetime] NULL,
	[HadCovLapse] [bit] NULL,
	[CoverageLapses] [nvarchar](250) NULL,
	[LIMC] [bit] NULL,
	[Attach_PDF] [tinyint] NULL,
	[Attach_JPG] [tinyint] NULL,
	[Attach_TIF] [tinyint] NULL,
	[NumAttach_Final] [tinyint] NULL,
	[NumAttach_Std] [tinyint] NULL,
	[NumAttach_NonStd] [tinyint] NULL,
	[NumAttach_Other] [tinyint] NULL,
	[Attach_Other] [nvarchar](5) NULL,
	[Upload_ID] [nvarchar](10) NULL,
	[Uploaded] [nvarchar](300) NULL,
	[Attached] [nvarchar](300) NULL,
	[Status] [nvarchar](15) NULL,
	[OK] [bit] NULL,
	[NotFound] [bit] NULL,
	[Unauth] [bit] NULL,
	[Invalid] [bit] NULL,
	[Timeout] [bit] NULL,
	[Warning] [bit] NULL,
	[Warning_Message] [nvarchar](50) NULL,
	[Error] [bit] NULL,
	[AppError] [bit] NULL,
	[SoapException] [bit] NULL,
	[Exception_Type] [varchar](250) NULL,
	[Exception_Message] [varchar](500) NULL,
	[Exception_Stack] [varchar](4000) NULL,
	[Exception_Email] [nvarchar](max) NULL,
	[Exception_Email_SentTo] [nvarchar](250) NULL,
	[Exception_Email_Insert] [nvarchar](50) NULL,
	[TranDate] [datetime2](7) NULL,
	[TranFlag] [int] NULL,
	[TranNumber] [float] NULL,
	[OtherInfo] [nvarchar](500) NULL,
	[OtherInfo_Format] [nvarchar](250) NULL,
	[OtherInfo_Meaning] [nvarchar](50) NULL,
	[RELATE_ONE_NAME] [nvarchar](655) NULL,
	[RELATE_ONE_ID] [bigint] NULL,
	[MONTH_BATCH_ID] [uniqueidentifier] NULL,
	[RELATE_MANY_NAME] [nvarchar](655) NULL,
	[RELATE_MANY_ID] [bigint] NULL,
	[FromTestRun] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BSS_TranLog_IO]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BSS_TranLog_IO](
	[ID] [bigint] NOT NULL,
	[TranLog_ID] [bigint] NOT NULL,
	[SS_UID] [int] NULL,
	[Session] [nvarchar](50) NULL,
	[LenderCode] [nvarchar](10) NOT NULL,
	[LIMC] [bit] NULL,
	[Borrower] [bit] NULL,
	[Vehicle] [bit] NULL,
	[ActionYear] [int] NULL,
	[ActionMonth] [int] NULL,
	[ActionAttempt] [tinyint] NULL,
	[ActionMethod] [nvarchar](50) NOT NULL,
	[AppVer] [nvarchar](20) NULL,
	[Input_Request] [varchar](8000) NULL,
	[Output_Response] [varchar](8000) NULL,
	[URL_REST] [nvarchar](160) NULL,
	[Input_REST_JSON] [nvarchar](max) NULL,
	[Output_REST_JSON] [nvarchar](max) NULL,
	[URL_IVS] [nvarchar](160) NULL,
	[Input_IVS_Doc_XML] [nvarchar](max) NULL,
	[Output_IVS_Doc_XML] [nvarchar](max) NULL,
	[URL_LDH] [nvarchar](max) NULL,
	[Input_LDH_ExternalID] [nvarchar](10) NULL,
	[Input_LDH_Source] [nvarchar](10) NULL,
	[Input_LDH_Doc_XML] [nvarchar](max) NULL,
	[Input_LDH_Attach_IDs] [nvarchar](655) NULL,
	[LDH_Process] [nvarchar](1000) NULL,
	[Memo_Notes] [nvarchar](1000) NULL,
	[Output_LDH_Doc_XML] [nvarchar](max) NULL,
	[Status] [nvarchar](15) NULL,
	[Result_Reason] [nvarchar](100) NULL,
	[URL_MailService] [nvarchar](160) NULL,
	[Input_MailService] [nvarchar](max) NULL,
	[Output_MailService] [nvarchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Field_Tracking]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Field_Tracking](
	[ID] [int] NOT NULL,
	[Table_Name] [nvarchar](50) NULL,
	[Field_Name] [nvarchar](150) NULL,
	[Primary_Key] [nvarchar](50) NULL,
	[Old_Value] [nvarchar](512) NULL,
	[New_Value] [nvarchar](512) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](25) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Import_List]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Import_List](
	[ID] [int] NOT NULL,
	[Security_Level] [int] NOT NULL,
	[Import_Name] [nvarchar](75) NULL,
	[Import_Description] [ntext] NULL,
	[Import_Group] [nvarchar](50) NULL,
	[Date_Option] [int] NOT NULL,
	[Begin_Date] [nvarchar](50) NOT NULL,
	[End_Date] [nvarchar](50) NOT NULL,
	[Begin_Date_2] [nvarchar](50) NOT NULL,
	[End_Date_2] [nvarchar](50) NOT NULL,
	[Coverage_Type] [nvarchar](50) NOT NULL,
	[Relationship_ID_Number] [nvarchar](50) NOT NULL,
	[Client_ID_Number] [nvarchar](50) NOT NULL,
	[Parent_Client_ID_Number] [nvarchar](50) NOT NULL,
	[Underwriter_ID_Number] [nvarchar](50) NOT NULL,
	[Input_File_Name] [nvarchar](50) NOT NULL,
	[Worksheet_Name] [nvarchar](50) NOT NULL,
	[Output_File_Name] [nvarchar](50) NOT NULL,
	[File_Filter] [nvarchar](50) NULL,
	[Default_Underwriter_ID_Number] [int] NOT NULL,
	[Default_Relationship_ID_Number] [int] NOT NULL,
	[Default_Client_ID_Number] [int] NOT NULL,
	[Default_Parent_Client_ID_Number] [int] NOT NULL,
	[Default_Coverage_Type] [int] NOT NULL,
	[Default_Worksheet_Name] [nvarchar](50) NULL,
	[Begin_Date_Caption] [nvarchar](50) NOT NULL,
	[Begin_Date_2_Caption] [nvarchar](50) NOT NULL,
	[Program_Number] [int] NOT NULL,
	[Notify_Type] [int] NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](25) NULL,
	[Import_Table] [varchar](max) NULL,
	[Import_Instruction] [varchar](max) NULL,
	[Pre_Import_Instruction] [varchar](max) NULL,
	[Post_Import_Instruction] [varchar](max) NULL,
	[Rows_To_Skip] [int] NULL,
	[Skip_Instruction] [varchar](max) NULL,
	[Error_Detection_Instruction] [varchar](max) NULL,
	[HDR_IMEX_Instruction] [varchar](max) NULL,
	[Program_Name] [nvarchar](50) NULL,
	[Delimiter] [varchar](10) NULL,
	[Text_Qualifier] [varchar](2) NULL,
	[Delimiter_Qualifier] [varchar](2) NULL,
	[Is_Delimited] [bit] NULL,
	[Is_Fixed_Width] [bit] NULL,
	[Generic_Integer_1] [nvarchar](50) NOT NULL,
	[Generic_Integer_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_2] [nvarchar](50) NOT NULL,
	[Generic_Integer_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_3] [nvarchar](50) NOT NULL,
	[Generic_Integer_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_4] [nvarchar](50) NOT NULL,
	[Generic_Integer_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_1] [nvarchar](50) NOT NULL,
	[Generic_Money_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_2] [nvarchar](50) NOT NULL,
	[Generic_Money_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_3] [nvarchar](50) NOT NULL,
	[Generic_Money_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_4] [nvarchar](50) NOT NULL,
	[Generic_Money_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_1] [nvarchar](50) NULL,
	[Generic_String_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_2] [nvarchar](50) NULL,
	[Generic_String_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_3] [nvarchar](50) NULL,
	[Generic_String_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_4] [nvarchar](50) NULL,
	[Generic_String_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_Date_1] [nvarchar](50) NOT NULL,
	[Generic_Date_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Date_2] [nvarchar](50) NOT NULL,
	[Generic_Date_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_bit_1] [nvarchar](50) NOT NULL,
	[Generic_bit_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_bit_2] [nvarchar](50) NOT NULL,
	[Generic_bit_2_Caption] [nvarchar](max) NOT NULL,
	[Month_Only] [nvarchar](50) NOT NULL,
	[Month_Only_Caption] [nvarchar](max) NOT NULL,
	[Year_Only] [nvarchar](50) NOT NULL,
	[Year_Only_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_1] [nvarchar](50) NOT NULL,
	[Generic_ddl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_2] [nvarchar](50) NOT NULL,
	[Generic_ddl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_3] [nvarchar](50) NOT NULL,
	[Generic_ddl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_4] [nvarchar](50) NOT NULL,
	[Generic_ddl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_4_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_1] [nvarchar](50) NOT NULL,
	[Generic_lbx_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_1_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_2] [nvarchar](50) NOT NULL,
	[Generic_lbx_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_2_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_3] [nvarchar](50) NOT NULL,
	[Generic_lbx_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_3_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_4] [nvarchar](50) NOT NULL,
	[Generic_lbx_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_4_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_1] [nvarchar](50) NOT NULL,
	[Generic_cbl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_2] [nvarchar](50) NOT NULL,
	[Generic_cbl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_3] [nvarchar](50) NOT NULL,
	[Generic_cbl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_4] [nvarchar](50) NOT NULL,
	[Generic_cbl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_4_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_1] [nvarchar](50) NOT NULL,
	[Generic_rbl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_2] [nvarchar](50) NOT NULL,
	[Generic_rbl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_3] [nvarchar](50) NOT NULL,
	[Generic_rbl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_4] [nvarchar](50) NOT NULL,
	[Generic_rbl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_4_Query] [nvarchar](max) NOT NULL,
	[RequireSecureGateway] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImportParameters]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImportParameters](
	[ID] [int] NOT NULL,
	[Import_List_ID] [int] NOT NULL,
	[Import_Name] [nvarchar](75) NOT NULL,
	[Import_Title] [nvarchar](75) NULL,
	[Date_Option] [int] NULL,
	[Begin_Date] [datetime] NULL,
	[End_Date] [datetime] NULL,
	[Begin_Date_2] [datetime] NULL,
	[End_Date_2] [datetime] NULL,
	[Underwriter_ID_Number] [int] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[Parent_Client_ID_Number] [int] NOT NULL,
	[Coverage_Type] [nvarchar](50) NULL,
	[Relationship_ID_Number] [int] NOT NULL,
	[Input_File_Name] [nvarchar](512) NULL,
	[Worksheet_Name] [nvarchar](50) NULL,
	[Output_File_Name] [nvarchar](512) NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[Que_User_ID] [nvarchar](50) NULL,
	[E_Mail_To] [nvarchar](max) NULL,
	[E_Mail_CC] [nvarchar](max) NULL,
	[E_Mail_Sent] [datetime] NULL,
	[Notify] [nvarchar](75) NULL,
	[Notify_Sent] [datetime] NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](25) NULL,
	[Batch_Number] [int] NOT NULL,
	[Generic_Integer_1] [bigint] NULL,
	[Generic_Integer_2] [bigint] NULL,
	[Generic_Integer_3] [bigint] NULL,
	[Generic_Integer_4] [bigint] NULL,
	[Generic_Money_1] [money] NULL,
	[Generic_Money_2] [money] NULL,
	[Generic_Money_3] [money] NULL,
	[Generic_Money_4] [money] NULL,
	[Generic_String_1] [nvarchar](max) NULL,
	[Generic_String_2] [nvarchar](max) NULL,
	[Generic_String_3] [nvarchar](max) NULL,
	[Generic_String_4] [nvarchar](max) NULL,
	[Generic_Date_1] [datetime] NULL,
	[Generic_Date_2] [datetime] NULL,
	[Generic_bit_1] [bit] NULL,
	[Generic_bit_2] [bit] NULL,
	[Month_Only] [smallint] NULL,
	[Year_Only] [smallint] NULL,
	[Generic_ddl_1] [nvarchar](max) NULL,
	[Generic_ddl_2] [nvarchar](max) NULL,
	[Generic_ddl_3] [nvarchar](max) NULL,
	[Generic_ddl_4] [nvarchar](max) NULL,
	[Generic_lbx_1] [nvarchar](max) NULL,
	[Generic_lbx_2] [nvarchar](max) NULL,
	[Generic_lbx_3] [nvarchar](max) NULL,
	[Generic_lbx_4] [nvarchar](max) NULL,
	[Generic_cbl_1] [nvarchar](max) NULL,
	[Generic_cbl_2] [nvarchar](max) NULL,
	[Generic_cbl_3] [nvarchar](max) NULL,
	[Generic_cbl_4] [nvarchar](max) NULL,
	[Generic_rbl_1] [nvarchar](max) NULL,
	[Generic_rbl_2] [nvarchar](max) NULL,
	[Generic_rbl_3] [nvarchar](max) NULL,
	[Generic_rbl_4] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImportParametersHistory]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImportParametersHistory](
	[ID] [int] NOT NULL,
	[Import_List_ID] [int] NOT NULL,
	[Import_Name] [nvarchar](75) NOT NULL,
	[Import_Title] [nvarchar](75) NULL,
	[Date_Option] [int] NULL,
	[Begin_Date] [datetime] NULL,
	[End_Date] [datetime] NULL,
	[Begin_Date_2] [datetime] NULL,
	[End_Date_2] [datetime] NULL,
	[Underwriter_ID_Number] [int] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[Parent_Client_ID_Number] [int] NOT NULL,
	[Coverage_Type] [nvarchar](50) NULL,
	[Relationship_ID_Number] [int] NOT NULL,
	[Input_File_Name] [nvarchar](512) NULL,
	[Worksheet_Name] [nvarchar](50) NULL,
	[Output_File_Name] [nvarchar](512) NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[Que_User_ID] [nvarchar](50) NULL,
	[E_Mail_To] [nvarchar](max) NULL,
	[E_Mail_CC] [nvarchar](max) NULL,
	[E_Mail_Sent] [datetime] NULL,
	[Notify] [nvarchar](75) NULL,
	[Notify_Sent] [datetime] NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](25) NULL,
	[Batch_Number] [int] NOT NULL,
	[Generic_Integer_1] [bigint] NULL,
	[Generic_Integer_2] [bigint] NULL,
	[Generic_Integer_3] [bigint] NULL,
	[Generic_Integer_4] [bigint] NULL,
	[Generic_Money_1] [money] NULL,
	[Generic_Money_2] [money] NULL,
	[Generic_Money_3] [money] NULL,
	[Generic_Money_4] [money] NULL,
	[Generic_String_1] [nvarchar](max) NULL,
	[Generic_String_2] [nvarchar](max) NULL,
	[Generic_String_3] [nvarchar](max) NULL,
	[Generic_String_4] [nvarchar](max) NULL,
	[Generic_Date_1] [datetime] NULL,
	[Generic_Date_2] [datetime] NULL,
	[Generic_bit_1] [bit] NULL,
	[Generic_bit_2] [bit] NULL,
	[Month_Only] [smallint] NULL,
	[Year_Only] [smallint] NULL,
	[Generic_ddl_1] [nvarchar](max) NULL,
	[Generic_ddl_2] [nvarchar](max) NULL,
	[Generic_ddl_3] [nvarchar](max) NULL,
	[Generic_ddl_4] [nvarchar](max) NULL,
	[Generic_lbx_1] [nvarchar](max) NULL,
	[Generic_lbx_2] [nvarchar](max) NULL,
	[Generic_lbx_3] [nvarchar](max) NULL,
	[Generic_lbx_4] [nvarchar](max) NULL,
	[Generic_cbl_1] [nvarchar](max) NULL,
	[Generic_cbl_2] [nvarchar](max) NULL,
	[Generic_cbl_3] [nvarchar](max) NULL,
	[Generic_cbl_4] [nvarchar](max) NULL,
	[Generic_rbl_1] [nvarchar](max) NULL,
	[Generic_rbl_2] [nvarchar](max) NULL,
	[Generic_rbl_3] [nvarchar](max) NULL,
	[Generic_rbl_4] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Parameters]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Parameters](
	[Parameter_Name] [nvarchar](50) NOT NULL,
	[Parameter_Value] [nvarchar](512) NULL,
	[PIMS_Security] [bit] NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Report_List]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Report_List](
	[ID] [int] NOT NULL,
	[Security_Level] [int] NOT NULL,
	[Report_Name] [nvarchar](75) NULL,
	[Report_Description] [ntext] NULL,
	[Report_Group] [nvarchar](50) NULL,
	[Report_Sequence] [money] NOT NULL,
	[Date_Option] [int] NOT NULL,
	[Begin_Date] [nvarchar](50) NOT NULL,
	[End_Date] [nvarchar](50) NOT NULL,
	[Date_Closed_Begin] [nvarchar](50) NOT NULL,
	[Date_Closed_End] [nvarchar](50) NOT NULL,
	[Date_Sold_Begin] [nvarchar](50) NOT NULL,
	[Date_Sold_End] [nvarchar](50) NOT NULL,
	[Date_Received_Begin] [nvarchar](50) NOT NULL,
	[Date_Received_End] [nvarchar](50) NOT NULL,
	[Date_Entered_Begin] [nvarchar](50) NOT NULL,
	[Date_Entered_End] [nvarchar](50) NOT NULL,
	[Coverage_Type] [nvarchar](50) NOT NULL,
	[Product_Group] [nvarchar](50) NOT NULL,
	[Relationship_ID_Number] [nvarchar](50) NOT NULL,
	[Relationship_Status_Code] [nvarchar](50) NOT NULL,
	[Client_ID_Number] [nvarchar](50) NOT NULL,
	[Client_Status_Code] [nvarchar](50) NOT NULL,
	[Parent_Client_ID_Number] [nvarchar](50) NOT NULL,
	[Underwriter_ID_Number] [nvarchar](50) NOT NULL,
	[Underwriter_Group] [nvarchar](50) NOT NULL,
	[Representative_ID_Number] [nvarchar](50) NOT NULL,
	[Product_ID_Number] [nvarchar](50) NOT NULL,
	[Fiscal_Year] [nvarchar](50) NOT NULL,
	[Batch_Number] [nvarchar](50) NOT NULL,
	[Region] [nvarchar](50) NOT NULL,
	[State_Code] [nvarchar](50) NOT NULL,
	[Sort_Option] [nvarchar](50) NOT NULL,
	[File_Name] [nvarchar](50) NOT NULL,
	[Input_File_Name] [nvarchar](50) NOT NULL,
	[Printer_Name] [nvarchar](50) NOT NULL,
	[Representative_Type_ID_Number] [nvarchar](50) NOT NULL,
	[Client_Underwriter_ID] [nvarchar](50) NOT NULL,
	[Company_Code] [nvarchar](50) NOT NULL,
	[UDF_Options] [nvarchar](50) NOT NULL,
	[Client_UDF_Options] [nvarchar](50) NOT NULL,
	[Relationship_Division] [nvarchar](50) NOT NULL,
	[Relationship_Department] [nvarchar](50) NOT NULL,
	[Default_Coverage_Type] [int] NOT NULL,
	[Default_Relationship_Status_Code] [int] NOT NULL,
	[Default_Client_Status_Code] [int] NOT NULL,
	[Default_Underwriter_ID] [int] NOT NULL,
	[Begin_Date_Caption] [nvarchar](50) NOT NULL,
	[PIMS_Available] [bit] NOT NULL,
	[E_Mail_Prohibited] [bit] NOT NULL,
	[Notify_Prohibited] [bit] NOT NULL,
	[Product_Type] [nvarchar](20) NOT NULL,
	[Use_Product_Groups] [bit] NOT NULL,
	[Assets_Greater] [nvarchar](50) NOT NULL,
	[Assets_Less] [nvarchar](50) NOT NULL,
	[Data_Processor] [nvarchar](50) NOT NULL,
	[Restart_ID_Number] [nvarchar](50) NOT NULL,
	[Client_Type_ID] [nvarchar](50) NOT NULL,
	[Client_Group_ID] [nvarchar](50) NOT NULL,
	[VUT_Lender_ID] [nvarchar](50) NOT NULL,
	[CWS_Status] [nvarchar](50) NOT NULL,
	[CWS_Contract_Status] [nvarchar](50) NOT NULL,
	[New_Program] [bit] NOT NULL,
	[New_Program_Test] [bit] NOT NULL,
	[Program_Number] [int] NOT NULL,
	[Notify_Type] [int] NOT NULL,
	[Report_Query_1] [nvarchar](max) NULL,
	[Generic_Query_1] [bit] NOT NULL,
	[Report_Query_2] [nvarchar](max) NULL,
	[Generic_Query_2] [bit] NOT NULL,
	[Report_Query_3] [nvarchar](max) NULL,
	[Generic_Query_3] [bit] NOT NULL,
	[Report_Query_4] [nvarchar](max) NULL,
	[Generic_Query_4] [bit] NOT NULL,
	[Report_Query_5] [nvarchar](max) NULL,
	[Generic_Query_5] [bit] NOT NULL,
	[Multiple_Coverage_Type] [bit] NOT NULL,
	[CWS_Initiator] [nvarchar](50) NOT NULL,
	[CWS_Level_1] [nvarchar](50) NOT NULL,
	[CWS_Level_2] [nvarchar](50) NOT NULL,
	[CWS_Level_3] [nvarchar](50) NOT NULL,
	[CWS_Level_4] [nvarchar](50) NOT NULL,
	[CWS_Level_5] [nvarchar](50) NOT NULL,
	[CWS_Sales] [nvarchar](50) NOT NULL,
	[CWS_CDM] [nvarchar](50) NOT NULL,
	[Lock_Representative] [bit] NOT NULL,
	[Footer_Type] [smallint] NOT NULL,
	[CS_Month_End_UID] [nvarchar](50) NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL,
	[Uses_Calculation_Module] [bit] NULL,
	[File_Format] [nvarchar](50) NOT NULL,
	[Generic_Integer_1] [nvarchar](50) NOT NULL,
	[Generic_Integer_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_2] [nvarchar](50) NOT NULL,
	[Generic_Integer_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_3] [nvarchar](50) NOT NULL,
	[Generic_Integer_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_Integer_4] [nvarchar](50) NOT NULL,
	[Generic_Integer_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_1] [nvarchar](50) NOT NULL,
	[Generic_Money_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_2] [nvarchar](50) NOT NULL,
	[Generic_Money_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_3] [nvarchar](50) NOT NULL,
	[Generic_Money_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_Money_4] [nvarchar](50) NOT NULL,
	[Generic_Money_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_1] [nvarchar](50) NULL,
	[Generic_String_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_2] [nvarchar](50) NULL,
	[Generic_String_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_3] [nvarchar](50) NULL,
	[Generic_String_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_String_4] [nvarchar](50) NULL,
	[Generic_String_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_Date_1] [nvarchar](50) NOT NULL,
	[Generic_Date_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_Date_2] [nvarchar](50) NOT NULL,
	[Generic_Date_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_bit_1] [nvarchar](50) NOT NULL,
	[Generic_bit_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_bit_2] [nvarchar](50) NOT NULL,
	[Generic_bit_2_Caption] [nvarchar](max) NOT NULL,
	[Month_Only] [nvarchar](50) NOT NULL,
	[Month_Only_Caption] [nvarchar](max) NOT NULL,
	[Year_Only] [nvarchar](50) NOT NULL,
	[Year_Only_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_1] [nvarchar](max) NOT NULL,
	[Generic_ddl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_2] [nvarchar](max) NOT NULL,
	[Generic_ddl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_3] [nvarchar](max) NOT NULL,
	[Generic_ddl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_ddl_4] [nvarchar](max) NOT NULL,
	[Generic_ddl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_ddl_4_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_1] [nvarchar](max) NOT NULL,
	[Generic_lbx_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_1_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_2] [nvarchar](max) NOT NULL,
	[Generic_lbx_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_2_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_3] [nvarchar](max) NOT NULL,
	[Generic_lbx_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_3_Query] [nvarchar](max) NOT NULL,
	[Generic_lbx_4] [nvarchar](max) NOT NULL,
	[Generic_lbx_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_lbx_4_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_1] [nvarchar](max) NOT NULL,
	[Generic_cbl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_2] [nvarchar](max) NOT NULL,
	[Generic_cbl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_3] [nvarchar](max) NOT NULL,
	[Generic_cbl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_cbl_4] [nvarchar](max) NOT NULL,
	[Generic_cbl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_cbl_4_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_1] [nvarchar](max) NOT NULL,
	[Generic_rbl_1_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_1_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_2] [nvarchar](max) NOT NULL,
	[Generic_rbl_2_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_2_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_3] [nvarchar](max) NOT NULL,
	[Generic_rbl_3_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_3_Query] [nvarchar](max) NOT NULL,
	[Generic_rbl_4] [nvarchar](max) NOT NULL,
	[Generic_rbl_4_Caption] [nvarchar](max) NOT NULL,
	[Generic_rbl_4_Query] [nvarchar](max) NOT NULL,
	[Report_Worksheet_Name_1] [nvarchar](max) NULL,
	[Report_Worksheet_Name_2] [nvarchar](max) NULL,
	[Report_Worksheet_Name_3] [nvarchar](max) NULL,
	[Report_Worksheet_Name_4] [nvarchar](max) NULL,
	[Report_Worksheet_Name_5] [nvarchar](max) NULL,
	[Report_Worksheet_Format_1] [nvarchar](max) NULL,
	[Report_Worksheet_Format_2] [nvarchar](max) NULL,
	[Report_Worksheet_Format_3] [nvarchar](max) NULL,
	[Report_Worksheet_Format_4] [nvarchar](max) NULL,
	[Report_Worksheet_Format_5] [nvarchar](max) NULL,
	[Report_Worksheet_Total_1] [nvarchar](max) NULL,
	[Report_Worksheet_Total_2] [nvarchar](max) NULL,
	[Report_Worksheet_Total_3] [nvarchar](max) NULL,
	[Report_Worksheet_Total_4] [nvarchar](max) NULL,
	[Report_Worksheet_Total_5] [nvarchar](max) NULL,
	[Report_Worksheet_Orientation_1] [nvarchar](max) NULL,
	[Report_Worksheet_Orientation_2] [nvarchar](max) NULL,
	[Report_Worksheet_Orientation_3] [nvarchar](max) NULL,
	[Report_Worksheet_Orientation_4] [nvarchar](max) NULL,
	[Report_Worksheet_Orientation_5] [nvarchar](max) NULL,
	[CallsCalculationModule] [bit] NOT NULL,
	[ConvertVB6] [bit] NOT NULL,
	[VB6Converted] [bit] NOT NULL,
	[Report_Worksheet_Subtotal_1] [nvarchar](max) NULL,
	[Report_Worksheet_Subtotal_2] [nvarchar](max) NULL,
	[Report_Worksheet_Subtotal_3] [nvarchar](max) NULL,
	[Report_Worksheet_Subtotal_4] [nvarchar](max) NULL,
	[Report_Worksheet_Subtotal_5] [nvarchar](max) NULL,
	[Work_in_Progress] [varchar](max) NULL,
	[Report_Worksheet_Conditional_Format_1] [nvarchar](max) NULL,
	[Report_Worksheet_Conditional_Format_2] [nvarchar](max) NULL,
	[Report_Worksheet_Conditional_Format_3] [nvarchar](max) NULL,
	[Report_Worksheet_Conditional_Format_4] [nvarchar](max) NULL,
	[Report_Worksheet_Conditional_Format_5] [nvarchar](max) NULL,
	[Server_1] [nvarchar](max) NULL,
	[Server_2] [nvarchar](max) NULL,
	[Server_3] [nvarchar](max) NULL,
	[Server_4] [nvarchar](max) NULL,
	[Server_5] [nvarchar](max) NULL,
	[Report_Worksheet_Query] [nvarchar](max) NULL,
	[Delete_Empty_Worksheets] [bit] NOT NULL,
	[Text_File_Option] [nvarchar](50) NOT NULL,
	[File_Name_Date_Option] [nvarchar](50) NOT NULL,
	[Text_File_Query] [nvarchar](max) NULL,
	[Text_File_Server] [nvarchar](max) NULL,
	[RequireSecureGateway] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReportParameters]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReportParameters](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Report_List_ID] [int] NOT NULL,
	[Report_Name] [nvarchar](75) NOT NULL,
	[Report_Title] [nvarchar](75) NULL,
	[Date_Option] [int] NULL,
	[Begin_Date] [datetime] NULL,
	[End_Date] [datetime] NULL,
	[Date_Closed_Begin] [datetime] NULL,
	[Date_Closed_End] [datetime] NULL,
	[Date_Sold_Begin] [datetime] NULL,
	[Date_Sold_End] [datetime] NULL,
	[Date_Received_Begin] [datetime] NULL,
	[Date_Received_End] [datetime] NULL,
	[Date_Entered_Begin] [datetime] NULL,
	[Date_Entered_End] [datetime] NULL,
	[Coverage_Type] [nvarchar](max) NULL,
	[Product_Group] [nvarchar](50) NULL,
	[Relationship_ID_Number] [int] NOT NULL,
	[Relationship_Status_Code] [int] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[Client_Status_Code] [int] NOT NULL,
	[Parent_Client_ID_Number] [int] NOT NULL,
	[Underwriter_ID_Number] [int] NOT NULL,
	[Underwriter_Group] [nvarchar](50) NULL,
	[Representative_ID_Number] [int] NOT NULL,
	[Product_ID_Number] [int] NOT NULL,
	[Product_Type] [nvarchar](20) NULL,
	[Fiscal_Year] [int] NOT NULL,
	[Batch_Number] [int] NOT NULL,
	[Region] [nvarchar](50) NULL,
	[State_Code] [nvarchar](50) NULL,
	[Sort_Option] [nvarchar](50) NULL,
	[File_Name] [nvarchar](512) NULL,
	[Input_File_Name] [nvarchar](512) NULL,
	[Printer_Name] [nvarchar](255) NULL,
	[Representative_Type_ID_Number] [int] NULL,
	[Client_Underwriter_ID] [nvarchar](50) NULL,
	[Company_Code] [nvarchar](6) NULL,
	[UDF_Options] [nvarchar](255) NULL,
	[Client_UDF_Options] [nvarchar](255) NULL,
	[Relationship_Division] [nvarchar](5) NULL,
	[Relationship_Department] [nvarchar](5) NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[E_Mail_To] [nvarchar](max) NULL,
	[E_Mail_CC] [nvarchar](max) NULL,
	[E_Mail_Sent] [datetime] NULL,
	[Notify] [nvarchar](400) NULL,
	[Notify_Sent] [datetime] NULL,
	[Assets_Greater] [money] NOT NULL,
	[Assets_Less] [money] NOT NULL,
	[Data_Processor] [nvarchar](50) NULL,
	[Restart_ID_Number] [int] NULL,
	[Client_Type_ID] [int] NULL,
	[Client_Group_ID] [int] NULL,
	[VUT_Lender_ID] [nvarchar](10) NULL,
	[CWS_Status] [int] NOT NULL,
	[CWS_Contract_Status] [int] NOT NULL,
	[Que_User_ID] [nvarchar](50) NULL,
	[CWS_Initiator] [nvarchar](50) NULL,
	[CWS_Level_1] [nvarchar](50) NULL,
	[CWS_Level_2] [nvarchar](50) NULL,
	[CWS_Level_3] [nvarchar](50) NULL,
	[CWS_Level_4] [nvarchar](50) NULL,
	[CWS_Level_5] [nvarchar](50) NULL,
	[CWS_Sales] [int] NOT NULL,
	[CWS_CDM] [int] NOT NULL,
	[CS_Month_End_UID] [int] NOT NULL,
	[Underwriter_Import_Status] [varchar](max) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL,
	[File_Format] [nvarchar](50) NULL,
	[Generic_Integer_1] [bigint] NULL,
	[Generic_Integer_2] [bigint] NULL,
	[Generic_Integer_3] [bigint] NULL,
	[Generic_Integer_4] [bigint] NULL,
	[Generic_Money_1] [money] NULL,
	[Generic_Money_2] [money] NULL,
	[Generic_Money_3] [money] NULL,
	[Generic_Money_4] [money] NULL,
	[Generic_String_1] [nvarchar](max) NULL,
	[Generic_String_2] [nvarchar](max) NULL,
	[Generic_String_3] [nvarchar](max) NULL,
	[Generic_String_4] [nvarchar](max) NULL,
	[Generic_Date_1] [datetime] NULL,
	[Generic_Date_2] [datetime] NULL,
	[Generic_bit_1] [bit] NULL,
	[Generic_bit_2] [bit] NULL,
	[Month_Only] [smallint] NULL,
	[Year_Only] [smallint] NULL,
	[Generic_ddl_1] [nvarchar](max) NULL,
	[Generic_ddl_2] [nvarchar](max) NULL,
	[Generic_ddl_3] [nvarchar](max) NULL,
	[Generic_ddl_4] [nvarchar](max) NULL,
	[Generic_lbx_1] [nvarchar](max) NULL,
	[Generic_lbx_2] [nvarchar](max) NULL,
	[Generic_lbx_3] [nvarchar](max) NULL,
	[Generic_lbx_4] [nvarchar](max) NULL,
	[Generic_cbl_1] [nvarchar](max) NULL,
	[Generic_cbl_2] [nvarchar](max) NULL,
	[Generic_cbl_3] [nvarchar](max) NULL,
	[Generic_cbl_4] [nvarchar](max) NULL,
	[Generic_rbl_1] [nvarchar](max) NULL,
	[Generic_rbl_2] [nvarchar](max) NULL,
	[Generic_rbl_3] [nvarchar](max) NULL,
	[Generic_rbl_4] [nvarchar](max) NULL,
	[Text_File_Option] [bit] NOT NULL,
	[Report_Text_Enclosure_ID_Number] [int] NULL,
	[Text_File_Headers] [bit] NOT NULL,
	[Text_File_Delimiter] [nvarchar](max) NULL,
	[File_Name_Date_Option] [bit] NOT NULL,
	[File_Name_Date_ID_Number] [int] NULL,
	[File_Name_Date_Format] [nvarchar](max) NULL,
	[File_Name_Date_Root] [nvarchar](max) NULL,
	[Run_After] [datetime] NOT NULL,
	[ForceSecureGateway] [bit] NOT NULL,
 CONSTRAINT [PK_ReportParameters] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReportParametersHistory]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReportParametersHistory](
	[ID] [int] NOT NULL,
	[Report_List_ID] [int] NOT NULL,
	[Report_Name] [nvarchar](75) NOT NULL,
	[Report_Title] [nvarchar](75) NULL,
	[Date_Option] [int] NULL,
	[Begin_Date] [datetime] NULL,
	[End_Date] [datetime] NULL,
	[Date_Closed_Begin] [datetime] NULL,
	[Date_Closed_End] [datetime] NULL,
	[Date_Sold_Begin] [datetime] NULL,
	[Date_Sold_End] [datetime] NULL,
	[Date_Received_Begin] [datetime] NULL,
	[Date_Received_End] [datetime] NULL,
	[Date_Entered_Begin] [datetime] NULL,
	[Date_Entered_End] [datetime] NULL,
	[Coverage_Type] [nvarchar](max) NULL,
	[Product_Group] [nvarchar](50) NULL,
	[Relationship_ID_Number] [int] NOT NULL,
	[Relationship_Status_Code] [int] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[Client_Status_Code] [int] NOT NULL,
	[Parent_Client_ID_Number] [int] NOT NULL,
	[Underwriter_ID_Number] [int] NOT NULL,
	[Underwriter_Group] [nvarchar](50) NULL,
	[Representative_ID_Number] [int] NOT NULL,
	[Product_ID_Number] [int] NOT NULL,
	[Product_Type] [nvarchar](20) NULL,
	[Fiscal_Year] [int] NOT NULL,
	[Batch_Number] [int] NOT NULL,
	[Region] [nvarchar](50) NULL,
	[State_Code] [nvarchar](50) NULL,
	[Sort_Option] [nvarchar](50) NULL,
	[File_Name] [nvarchar](512) NULL,
	[Input_File_Name] [nvarchar](512) NULL,
	[Printer_Name] [nvarchar](255) NULL,
	[Representative_Type_ID_Number] [int] NULL,
	[Client_Underwriter_ID] [nvarchar](50) NULL,
	[Company_Code] [nvarchar](6) NULL,
	[UDF_Options] [nvarchar](255) NULL,
	[Client_UDF_Options] [nvarchar](255) NULL,
	[Relationship_Division] [nvarchar](5) NULL,
	[Relationship_Department] [nvarchar](5) NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[E_Mail_To] [nvarchar](max) NULL,
	[E_Mail_CC] [nvarchar](max) NULL,
	[E_Mail_Sent] [datetime] NULL,
	[Notify] [nvarchar](400) NULL,
	[Notify_Sent] [datetime] NULL,
	[Assets_Greater] [money] NOT NULL,
	[Assets_Less] [money] NOT NULL,
	[Data_Processor] [nvarchar](50) NULL,
	[Restart_ID_Number] [int] NULL,
	[Client_Type_ID] [int] NULL,
	[Client_Group_ID] [int] NULL,
	[VUT_Lender_ID] [nvarchar](10) NULL,
	[CWS_Status] [int] NOT NULL,
	[CWS_Contract_Status] [int] NOT NULL,
	[Que_User_ID] [nvarchar](50) NULL,
	[CWS_Initiator] [nvarchar](50) NULL,
	[CWS_Level_1] [nvarchar](50) NULL,
	[CWS_Level_2] [nvarchar](50) NULL,
	[CWS_Level_3] [nvarchar](50) NULL,
	[CWS_Level_4] [nvarchar](50) NULL,
	[CWS_Level_5] [nvarchar](50) NULL,
	[CWS_Sales] [int] NOT NULL,
	[CWS_CDM] [int] NOT NULL,
	[CS_Month_End_UID] [int] NOT NULL,
	[Underwriter_Import_Status] [varchar](max) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL,
	[File_Format] [nvarchar](50) NULL,
	[Generic_Integer_1] [bigint] NULL,
	[Generic_Integer_2] [bigint] NULL,
	[Generic_Integer_3] [bigint] NULL,
	[Generic_Integer_4] [bigint] NULL,
	[Generic_Money_1] [money] NULL,
	[Generic_Money_2] [money] NULL,
	[Generic_Money_3] [money] NULL,
	[Generic_Money_4] [money] NULL,
	[Generic_String_1] [nvarchar](max) NULL,
	[Generic_String_2] [nvarchar](max) NULL,
	[Generic_String_3] [nvarchar](max) NULL,
	[Generic_String_4] [nvarchar](max) NULL,
	[Generic_Date_1] [datetime] NULL,
	[Generic_Date_2] [datetime] NULL,
	[Generic_bit_1] [bit] NULL,
	[Generic_bit_2] [bit] NULL,
	[Month_Only] [smallint] NULL,
	[Year_Only] [smallint] NULL,
	[Generic_ddl_1] [nvarchar](max) NULL,
	[Generic_ddl_2] [nvarchar](max) NULL,
	[Generic_ddl_3] [nvarchar](max) NULL,
	[Generic_ddl_4] [nvarchar](max) NULL,
	[Generic_lbx_1] [nvarchar](max) NULL,
	[Generic_lbx_2] [nvarchar](max) NULL,
	[Generic_lbx_3] [nvarchar](max) NULL,
	[Generic_lbx_4] [nvarchar](max) NULL,
	[Generic_cbl_1] [nvarchar](max) NULL,
	[Generic_cbl_2] [nvarchar](max) NULL,
	[Generic_cbl_3] [nvarchar](max) NULL,
	[Generic_cbl_4] [nvarchar](max) NULL,
	[Generic_rbl_1] [nvarchar](max) NULL,
	[Generic_rbl_2] [nvarchar](max) NULL,
	[Generic_rbl_3] [nvarchar](max) NULL,
	[Generic_rbl_4] [nvarchar](max) NULL,
	[Text_File_Option] [bit] NOT NULL,
	[Report_Text_Enclosure_ID_Number] [int] NULL,
	[Text_File_Headers] [bit] NOT NULL,
	[Text_File_Delimiter] [nvarchar](max) NULL,
	[File_Name_Date_Option] [bit] NOT NULL,
	[File_Name_Date_ID_Number] [int] NULL,
	[File_Name_Date_Format] [nvarchar](max) NULL,
	[File_Name_Date_Root] [nvarchar](max) NULL,
	[Run_After] [datetime] NOT NULL,
	[ForceSecureGateway] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ScheduleParameters]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ScheduleParameters](
	[ID] [int] NOT NULL,
	[Report_List_ID] [int] NOT NULL,
	[Report_Name] [nvarchar](75) NOT NULL,
	[Report_Title] [nvarchar](75) NULL,
	[Date_Option] [int] NULL,
	[Begin_Date] [datetime] NULL,
	[End_Date] [datetime] NULL,
	[Date_Closed_Begin] [datetime] NULL,
	[Date_Closed_End] [datetime] NULL,
	[Date_Sold_Begin] [datetime] NULL,
	[Date_Sold_End] [datetime] NULL,
	[Date_Received_Begin] [datetime] NULL,
	[Date_Received_End] [datetime] NULL,
	[Date_Entered_Begin] [datetime] NULL,
	[Date_Entered_End] [datetime] NULL,
	[Coverage_Type] [nvarchar](max) NULL,
	[Product_Group] [nvarchar](50) NULL,
	[Relationship_ID_Number] [int] NOT NULL,
	[Relationship_Status_Code] [int] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[Client_Status_Code] [int] NOT NULL,
	[Parent_Client_ID_Number] [int] NOT NULL,
	[Underwriter_ID_Number] [int] NOT NULL,
	[Underwriter_Group] [nvarchar](50) NULL,
	[Representative_ID_Number] [int] NOT NULL,
	[Product_ID_Number] [int] NOT NULL,
	[Product_Type] [nvarchar](20) NULL,
	[Fiscal_Year] [int] NOT NULL,
	[Batch_Number] [int] NOT NULL,
	[Region] [nvarchar](50) NULL,
	[State_Code] [nvarchar](50) NULL,
	[Sort_Option] [nvarchar](50) NULL,
	[File_Name] [nvarchar](512) NULL,
	[Input_File_Name] [nvarchar](512) NULL,
	[Printer_Name] [nvarchar](255) NULL,
	[Representative_Type_ID_Number] [int] NULL,
	[Client_Underwriter_ID] [nvarchar](50) NULL,
	[Company_Code] [nvarchar](6) NULL,
	[UDF_Options] [nvarchar](255) NULL,
	[Client_UDF_Options] [nvarchar](255) NULL,
	[Relationship_Division] [nvarchar](5) NULL,
	[Relationship_Department] [nvarchar](5) NULL,
	[Started] [datetime] NULL,
	[Finished] [datetime] NULL,
	[E_Mail_To] [nvarchar](max) NULL,
	[E_Mail_CC] [nvarchar](max) NULL,
	[E_Mail_Sent] [datetime] NULL,
	[Notify] [nvarchar](400) NULL,
	[Notify_Sent] [datetime] NULL,
	[Assets_Greater] [money] NOT NULL,
	[Assets_Less] [money] NOT NULL,
	[Data_Processor] [nvarchar](50) NULL,
	[Restart_ID_Number] [int] NULL,
	[Client_Type_ID] [int] NULL,
	[Client_Group_ID] [int] NULL,
	[VUT_Lender_ID] [nvarchar](10) NULL,
	[CWS_Status] [int] NOT NULL,
	[CWS_Contract_Status] [int] NOT NULL,
	[Que_User_ID] [nvarchar](50) NULL,
	[Run_After] [datetime] NOT NULL,
	[Run_Interval] [int] NOT NULL,
	[Run_Number] [int] NOT NULL,
	[Run_Period] [int] NOT NULL,
	[CWS_Initiator] [nvarchar](50) NULL,
	[CWS_Level_1] [nvarchar](50) NULL,
	[CWS_Level_2] [nvarchar](50) NULL,
	[CWS_Level_3] [nvarchar](50) NULL,
	[CWS_Level_4] [nvarchar](50) NULL,
	[CWS_Level_5] [nvarchar](50) NULL,
	[CWS_Sales] [int] NOT NULL,
	[CWS_CDM] [int] NOT NULL,
	[CS_Month_End_UID] [int] NOT NULL,
	[Underwriter_Import_Status] [varchar](max) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL,
	[File_Format] [nvarchar](50) NULL,
	[Generic_Integer_1] [bigint] NULL,
	[Generic_Integer_2] [bigint] NULL,
	[Generic_Integer_3] [bigint] NULL,
	[Generic_Integer_4] [bigint] NULL,
	[Generic_Money_1] [money] NULL,
	[Generic_Money_2] [money] NULL,
	[Generic_Money_3] [money] NULL,
	[Generic_Money_4] [money] NULL,
	[Generic_String_1] [nvarchar](max) NULL,
	[Generic_String_2] [nvarchar](max) NULL,
	[Generic_String_3] [nvarchar](max) NULL,
	[Generic_String_4] [nvarchar](max) NULL,
	[Generic_Date_1] [datetime] NULL,
	[Generic_Date_2] [datetime] NULL,
	[Generic_bit_1] [bit] NULL,
	[Generic_bit_2] [bit] NULL,
	[Month_Only] [smallint] NULL,
	[Year_Only] [smallint] NULL,
	[Generic_ddl_1] [nvarchar](max) NULL,
	[Generic_ddl_2] [nvarchar](max) NULL,
	[Generic_ddl_3] [nvarchar](max) NULL,
	[Generic_ddl_4] [nvarchar](max) NULL,
	[Generic_lbx_1] [nvarchar](max) NULL,
	[Generic_lbx_2] [nvarchar](max) NULL,
	[Generic_lbx_3] [nvarchar](max) NULL,
	[Generic_lbx_4] [nvarchar](max) NULL,
	[Generic_cbl_1] [nvarchar](max) NULL,
	[Generic_cbl_2] [nvarchar](max) NULL,
	[Generic_cbl_3] [nvarchar](max) NULL,
	[Generic_cbl_4] [nvarchar](max) NULL,
	[Generic_rbl_1] [nvarchar](max) NULL,
	[Generic_rbl_2] [nvarchar](max) NULL,
	[Generic_rbl_3] [nvarchar](max) NULL,
	[Generic_rbl_4] [nvarchar](max) NULL,
	[Text_File_Option] [bit] NOT NULL,
	[Report_Text_Enclosure_ID_Number] [int] NULL,
	[Text_File_Headers] [bit] NOT NULL,
	[Text_File_Delimiter] [nvarchar](max) NULL,
	[File_Name_Date_Option] [bit] NOT NULL,
	[File_Name_Date_ID_Number] [int] NULL,
	[File_Name_Date_Format] [nvarchar](max) NULL,
	[File_Name_Date_Root] [nvarchar](max) NULL,
	[ForceSecureGateway] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Service_Statistics]    Script Date: 9/12/2023 2:19:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Service_Statistics](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[Service_Source_Code] [nvarchar](50) NOT NULL,
	[Service_Name] [nvarchar](50) NOT NULL,
	[Service_Method] [nvarchar](50) NOT NULL,
	[User_Name] [nvarchar](50) NULL,
	[Started] [datetime] NOT NULL,
	[Finished] [datetime] NOT NULL,
	[Client_ID_Number] [int] NOT NULL,
	[VUT_Lender_ID] [nvarchar](50) NULL,
	[Claim_Policy_Number] [nvarchar](50) NULL,
	[Comment_1] [nvarchar](max) NULL,
	[Comment_2] [nvarchar](max) NULL,
	[Comment_3] [ntext] NULL,
	[IP_Address] [nvarchar](50) NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NOT NULL,
	[User_ID] [nvarchar](50) NULL,
	[UniTracID] [int] NULL,
	[SLXID] [char](12) NULL,
	[Created_Mo]  AS (datepart(month,[Created])) PERSISTED,
	[Created_Yr]  AS (datepart(year,[Created])) PERSISTED,
 CONSTRAINT [PK_Service_Statistics] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Service_Statistics] SET (LOCK_ESCALATION = DISABLE)
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Report_List_ID]  DEFAULT ((0)) FOR [Report_List_ID]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Relationship_ID_Number]  DEFAULT ((0)) FOR [Relationship_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Relationship_ID_Number1]  DEFAULT ((0)) FOR [Relationship_Status_Code]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Client_ID_Number]  DEFAULT ((0)) FOR [Client_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Relationship_Status_Code1]  DEFAULT ((0)) FOR [Client_Status_Code]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Client_ID_Number1]  DEFAULT ((0)) FOR [Parent_Client_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Underwriter_ID_Number]  DEFAULT ((0)) FOR [Underwriter_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Representative_ID_Number]  DEFAULT ((0)) FOR [Representative_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Product_ID_Number]  DEFAULT ((0)) FOR [Product_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Fiscal_Year]  DEFAULT ((0)) FOR [Fiscal_Year]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Batch_Number]  DEFAULT ((0)) FOR [Batch_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Representative_Type_ID_Number]  DEFAULT ((0)) FOR [Representative_Type_ID_Number]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Assets_Greater]  DEFAULT ((0)) FOR [Assets_Greater]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Assets_Less]  DEFAULT ((0)) FOR [Assets_Less]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_CWS_Status]  DEFAULT ((0)) FOR [CWS_Status]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_CWS_Contract_Status]  DEFAULT ((0)) FOR [CWS_Contract_Status]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_CWS_Sales]  DEFAULT ((0)) FOR [CWS_Sales]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_CWS_CDM]  DEFAULT ((0)) FOR [CWS_CDM]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_CS_Month_End_UID_1]  DEFAULT ((0)) FOR [CS_Month_End_UID]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Created]  DEFAULT (getdate()) FOR [Created]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Modified]  DEFAULT (getdate()) FOR [Modified]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Text_File_Option]  DEFAULT ((0)) FOR [Text_File_Option]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Text_File_Headers]  DEFAULT ((0)) FOR [Text_File_Headers]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_File_Name_Date_Option]  DEFAULT ((0)) FOR [File_Name_Date_Option]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  CONSTRAINT [DF_ReportParameters_Run_After]  DEFAULT (getdate()) FOR [Run_After]
GO
ALTER TABLE [dbo].[ReportParameters] ADD  DEFAULT ((0)) FOR [ForceSecureGateway]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Table1_Service_Source_Allowed]  DEFAULT ((0)) FOR [Service_Method]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Service_Statistics_Started]  DEFAULT (getdate()) FOR [Started]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Service_Statistics_Finished]  DEFAULT (getdate()) FOR [Finished]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Service_Statistics_Client_ID_Number]  DEFAULT ((0)) FOR [Client_ID_Number]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Service_Statistics_Created]  DEFAULT (getdate()) FOR [Created]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  CONSTRAINT [DF_Service_Statistics_Modified]  DEFAULT (getdate()) FOR [Modified]
GO
ALTER TABLE [dbo].[Service_Statistics] ADD  DEFAULT ((0)) FOR [UniTracID]
GO
