USE [UniTrac]
GO

/****** Object:  Index [IDX_UPDATE_DT]    Script Date: 5/19/2022 5:25:33 PM ******/
CREATE NONCLUSTERED INDEX [IDX_UPDATE_DT] ON [dbo].[PROPERTY]
(
	[UPDATE_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO






USE [UniTrac]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IDX_PROPERTY_VIN]    Script Date: 5/19/2022 5:25:47 PM ******/
CREATE NONCLUSTERED INDEX [IDX_PROPERTY_VIN] ON [dbo].[PROPERTY]
(
	[VIN_TX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

