USE DPM_DOM

ALTER DATABASE DPM_DOM SET ALLOW_SNAPSHOT_ISOLATION ON 
ALTER DATABASE DPM_DOM SET READ_COMMITTED_SNAPSHOT ON

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DOM_APP_ACCESS]

USE DPM_DPR

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DPR_APP_ACCESS]


ALTER DATABASE DPM_DPR SET ALLOW_SNAPSHOT_ISOLATION ON 



USE DPM_MOR


ALTER DATABASE DPM_MOR SET ALLOW_SNAPSHOT_ISOLATION ON 
ALTER DATABASE DPM_MOR SET READ_COMMITTED_SNAPSHOT ON


USE DPM_DPR

ALTER DATABASE DPM_DPR SET ALLOW_SNAPSHOT_ISOLATION ON 
ALTER DATABASE DPM_DPR SET READ_COMMITTED_SNAPSHOT ON
ALTER DATABASE DPM_DPR SET AUTO_UPDATE_STATISTICS_ASYNC ON
ALTER DATABASE DPM_DPR SET AUTO_UPDATE_STATISTICS ON




USE DPM_MOR


ALTER DATABASE DPM_MOR SET ALLOW_SNAPSHOT_ISOLATION ON 
ALTER DATABASE DPM_MOR SET READ_COMMITTED_SNAPSHOT ON


USE DPM_DWH

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DWH_APP_ACCESS]


USE DPM_PWH

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_PWH_APP_ACCESS]


USE DPM_DPR

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DPR_APP_ACCESS]

USE DPM_DOM

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DOM_APP_ACCESS]


USE DPM_DOC

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_DOC_APP_ACCESS]


USE DPM_WFR

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_WFR_APP_ACCESS]


USE DPM_MOR

GRANT CONTROL ON SCHEMA::[dbo] TO [INFA_DPM_MOR_APP_ACCESS]





use master

SELECT * FROM sys.server_principals

SELECT name, CASE WHEN snapshot_isolation_state = 1 THEN 'ENABLED' ELSE 'DISABLED' END [snapshot_isolation_state] FROM sys.databases 
SELECT name, CASE WHEN is_read_committed_snapshot_on = 1 THEN 'ENABLED' ELSE 'DISABLED' END [is_read_committed_snapshot_on] FROM sys.databases 
SELECT name, CASE WHEN is_auto_update_statistics_on = 1 THEN 'ENABLED' ELSE 'DISABLED' END [is_auto_update_statistics_on] FROM sys.databases 
SELECT name, CASE WHEN is_auto_update_statistics_async_on = 1 THEN 'ENABLED' ELSE 'DISABLED' END [is_read_committed_snapshot_on] FROM sys.databases 



SELECT * from  sys.databases 
where (database_id >=5 AND  name not in ('Perfstats', 'DBA', 'HDTStorage')) 








USE DPM_DOM
USE DPM_DWH
USE DPM_DOC
USE DPM_WFR
USE DPM_PWH
USE DPM_DPR
USE DPM_MOR