
USE [SolarWindsFlowStorage]
GO
ALTER AUTHORIZATION ON DATABASE::[SolarWindsFlowStorage] TO [ELDREDGE_A\SW-SQL-PROD]
GO

USE [SolarWindsOrionLog]
GO
ALTER AUTHORIZATION ON DATABASE::[SolarWindsOrionLog] TO [ELDREDGE_A\SW-SQL-PROD]
GO

USE [SolarWindsOrion]
GO
ALTER AUTHORIZATION ON DATABASE::[SolarWindsOrion] TO [ELDREDGE_A\SW-SQL-PROD]
GO
