--IVOSdbIVOSAppTest
USE [IVOS]
GO
ALTER ROLE [SAIL_APP_ACCESS] DROP MEMBER [ELDREDGE_A\svc_idnw_ivos_prd01]
ALTER ROLE [db_datareader] DROP MEMBER [ELDREDGE_A\svc_idnw_ivos_prd01]
ALTER ROLE [db_datawriter] DROP MEMBER [ELDREDGE_A\svc_idnw_ivos_prd01]
GO


USE [IVOS]
GO

/****** Object:  User [ELDREDGE_A\svc_idnw_ivos_prd01]    Script Date: 2/22/2023 2:22:34 PM ******/
DROP USER [ELDREDGE_A\svc_idnw_ivos_prd01]
GO



CREATE USER [ELDREDGE_A\svc_SAIL_STG01] FOR LOGIN [ELDREDGE_A\svc_SAIL_STG01] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [SAIL_APP_ACCESS] ADD MEMBER [ELDREDGE_A\svc_SAIL_STG01]
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\svc_SAIL_STG01]
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\svc_SAIL_STG01]





USE [IVOS]
GO
CREATE USER [IVOSdbIVOSAppStg] FOR LOGIN [IVOSdbIVOSAppStg] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_datawriter] ADD MEMBER [IVOSdbIVOSAppStg]
ALTER ROLE [db_datareader] ADD MEMBER [IVOSdbIVOSAppStg]
ALTER ROLE [db_execute] DROP  MEMBER [IVOSdbIVOSAppStg]

GO


USE [IVOS]
GO
CREATE USER [IVOSdbLinkedDSSQLTEST14_IVOSTEST] FOR LOGIN [IVOSdbLinkedDSSQLTEST14_IVOSTEST] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_datareader] ADD MEMBER [IVOSdbLinkedDSSQLTEST14_IVOSTEST]
GO



USE [IVOS]
GO
CREATE USER [IVOSdbIVOSRptStg] FOR LOGIN [IVOSdbIVOSRptStg] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_owner] ADD MEMBER [IVOSdbIVOSRptStg] 
GO



USE [JasperNew]
GO
CREATE USER [IVOSdbIVOSRptStg] FOR LOGIN [IVOSdbIVOSRptStg] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_owner] ADD MEMBER [IVOSdbIVOSRptStg] 
GO


USE [JasperServer]
GO
CREATE USER [IVOSdbIVOSRptStg] FOR LOGIN [IVOSdbIVOSRptStg] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_owner] ADD MEMBER [IVOSdbIVOSRptStg] 
GO