USE [ThePlayPen]
GO

/****** Object:  Table [dbo].[PrevalidatedData]    Script Date: 4/6/2021 10:03:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PrevalidatedData](
	[ImportID] [bigint] NULL,
	[Status] [nvarchar](10) NULL,
	[BatchID] [nvarchar](50) NULL,
	[LenderID] [nvarchar](10) NULL,
	[LenderName] [nvarchar](100) NULL,
	[ContractType] [nvarchar](1) NULL,
	[AlliedDocID] [bigint] NULL,
	[DocumentPath] [nvarchar](500) NULL,
	[BatchDate] [datetime2](7) NULL,
	[ScanOperator] [nvarchar](30) NULL,
	[ValidationOperator] [nvarchar](30) NULL,
	[ImportTime] [datetime2](7) NULL,
	[ExportTime] [datetime2](7) NULL,
	[ManualValidation] [nvarchar](1) NULL,
	[TransactionType] [nvarchar](4) NULL,
	[TransactionType_Confc] [decimal](5, 2) NULL,
	[TransactionType_Conft] [nvarchar](1) NULL,
	[MailDate] [datetime2](7) NULL,
	[MailDate_Confc] [decimal](5, 2) NULL,
	[MailDate_Conft] [nvarchar](1) NULL,
	[Insured_LastName] [nvarchar](30) NULL,
	[Insured_LastName_Confc] [decimal](5, 2) NULL,
	[Insured_LastName_Conft] [nvarchar](1) NULL,
	[Insured_FirstName] [nvarchar](30) NULL,
	[Insured_FirstName_Confc] [decimal](5, 2) NULL,
	[Insured_FirstName_Conft] [nvarchar](1) NULL,
	[Insured_LastName2] [nvarchar](30) NULL,
	[Insured_LastName2_Confc] [decimal](5, 2) NULL,
	[Insured_LastName2_Conft] [nvarchar](1) NULL,
	[Insured_FirstName2] [nvarchar](30) NULL,
	[Insured_FirstName2_Confc] [decimal](5, 2) NULL,
	[Insured_FirstName2_Conft] [nvarchar](1) NULL,
	[Insured_DBAName] [nvarchar](30) NULL,
	[Insured_DBAName_Confc] [decimal](5, 2) NULL,
	[Insured_DBAName_Conft] [nvarchar](1) NULL,
	[Insured_Addr] [nvarchar](100) NULL,
	[Insured_Addr_Confc] [decimal](5, 2) NULL,
	[Insured_Addr_Conft] [nvarchar](1) NULL,
	[Insured_Zip] [nvarchar](30) NULL,
	[Insured_Zip_Confc] [decimal](5, 2) NULL,
	[Insured_Zip_Conft] [nvarchar](1) NULL,
	[InsCoName] [nvarchar](100) NULL,
	[InsCoName_Confc] [decimal](5, 2) NULL,
	[InsCoName_Conft] [nvarchar](1) NULL,
	[BIC_ID] [bigint] NULL,
	[BIC_ID_Confc] [decimal](5, 2) NULL,
	[BIC_ID_Conft] [nvarchar](1) NULL,
	[InsCoAddr1] [nvarchar](100) NULL,
	[InsCoAddr1_Confc] [decimal](5, 2) NULL,
	[InsCoAddr1_Conft] [nvarchar](1) NULL,
	[InsCoAddr2] [nvarchar](100) NULL,
	[InsCoAddr2_Confc] [decimal](5, 2) NULL,
	[InsCoAddr2_Conft] [nvarchar](1) NULL,
	[InsCoCity] [nvarchar](40) NULL,
	[InsCoCity_Confc] [decimal](5, 2) NULL,
	[InsCoCity_Conft] [nvarchar](1) NULL,
	[InsCoState] [nvarchar](30) NULL,
	[InsCoState_Confc] [decimal](5, 2) NULL,
	[InsCoState_Conft] [nvarchar](1) NULL,
	[InsCoZip] [nvarchar](30) NULL,
	[InsCoZip_Confc] [decimal](5, 2) NULL,
	[InsCoZip_Conft] [nvarchar](1) NULL,
	[AgencyCompanyName] [nvarchar](100) NULL,
	[AgencyCompanyName_Confc] [decimal](5, 2) NULL,
	[AgencyCompanyName_Conft] [nvarchar](1) NULL,
	[AgencyID] [bigint] NULL,
	[AgencyID_Confc] [decimal](5, 2) NULL,
	[AgencyID_Conft] [nvarchar](1) NULL,
	[AgencyPhone] [nvarchar](20) NULL,
	[AgencyPhone_Confc] [decimal](5, 2) NULL,
	[AgencyPhone_Conft] [nvarchar](1) NULL,
	[AgencyFax] [nvarchar](20) NULL,
	[AgencyFax_Confc] [decimal](5, 2) NULL,
	[AgencyFax_Conft] [nvarchar](1) NULL,
	[AgencyEmail] [nvarchar](100) NULL,
	[AgencyEmail_Confc] [decimal](5, 2) NULL,
	[AgencyEmail_Conft] [nvarchar](1) NULL,
	[PolicyNumber] [nvarchar](30) NULL,
	[PolicyNumber_Confc] [decimal](5, 2) NULL,
	[PolicyNumber_Conft] [nvarchar](1) NULL,
	[EffectiveDate] [datetime2](7) NULL,
	[EffectiveDate_Confc] [decimal](5, 2) NULL,
	[EffectiveDate_Conft] [nvarchar](1) NULL,
	[ExpirationDate] [datetime2](7) NULL,
	[ExpirationDate_Confc] [decimal](5, 2) NULL,
	[ExpirationDate_Conft] [nvarchar](1) NULL,
	[CancellationDate] [datetime2](7) NULL,
	[CancellationDate_Confc] [decimal](5, 2) NULL,
	[CancellationDate_Conft] [nvarchar](1) NULL,
	[CancellationReason] [nvarchar](4) NULL,
	[CancellationReason_Confc] [decimal](5, 2) NULL,
	[CancellationReason_Conft] [nvarchar](1) NULL,
	[flg_IsApplication] [nvarchar](1) NULL,
	[flg_IsApplication_Confc] [decimal](5, 2) NULL,
	[flg_IsApplication_Conft] [nvarchar](1) NULL,
	[flg_LienholderNameErr] [nvarchar](1) NULL,
	[flg_LienholderNameErr_Confc] [decimal](5, 2) NULL,
	[flg_LienholderNameErr_Conft] [nvarchar](1) NULL,
	[flg_LienholderAddrErr] [nvarchar](1) NULL,
	[flg_LienholderAddrErr_Confc] [decimal](5, 2) NULL,
	[flg_LienholderAddrErr_Conft] [nvarchar](1) NULL,
	[LoanNumber] [nvarchar](18) NULL,
	[LoanNumber_Confc] [decimal](5, 2) NULL,
	[LoanNumber_Conft] [nvarchar](1) NULL,
	[flg_LiabilityCard] [nvarchar](1) NULL,
	[flg_LiabilityCard_Confc] [decimal](5, 2) NULL,
	[flg_LiabilityCard_Conft] [nvarchar](1) NULL,
	[Veh_Year] [nvarchar](8) NULL,
	[Veh_Year_Confc] [decimal](5, 2) NULL,
	[Veh_Year_Conft] [nvarchar](1) NULL,
	[Veh_Make] [nvarchar](60) NULL,
	[Veh_Make_Confc] [decimal](5, 2) NULL,
	[Veh_Make_Conft] [nvarchar](1) NULL,
	[Veh_Model] [nvarchar](60) NULL,
	[Veh_Model_Confc] [decimal](5, 2) NULL,
	[Veh_Model_Conft] [nvarchar](1) NULL,
	[VIN] [nvarchar](36) NULL,
	[VIN_Confc] [decimal](5, 2) NULL,
	[VIN_Conft] [nvarchar](1) NULL,
	[veh_CompDeductibleAmt] [decimal](18, 2) NULL,
	[veh_CompDeductibleAmt_Confc] [decimal](5, 2) NULL,
	[veh_CompDeductibleAmt_Conft] [nvarchar](1) NULL,
	[flg_ComprehensiveCoverage] [nvarchar](1) NULL,
	[flg_ComprehensiveCoverage_Confc] [decimal](5, 2) NULL,
	[flg_ComprehensiveCoverage_Conft] [nvarchar](1) NULL,
	[veh_CollDeductibleAmt] [decimal](18, 2) NULL,
	[veh_CollDeductibleAmt_Confc] [decimal](5, 2) NULL,
	[veh_CollDeductibleAmt_Conft] [nvarchar](1) NULL,
	[flg_CollisionCoverage] [nvarchar](1) NULL,
	[flg_CollisionCoverage_Confc] [decimal](5, 2) NULL,
	[flg_CollisionCoverage_Conft] [nvarchar](1) NULL,
	[veh_CSL] [decimal](18, 2) NULL,
	[veh_CSL_Confc] [decimal](5, 2) NULL,
	[veh_CSL_Conft] [nvarchar](1) NULL,
	[veh_BIP] [decimal](18, 2) NULL,
	[veh_BIP_Confc] [decimal](5, 2) NULL,
	[veh_BIP_Conft] [nvarchar](1) NULL,
	[veh_BIO] [decimal](18, 2) NULL,
	[veh_BIO_Confc] [decimal](5, 2) NULL,
	[veh_BIO_Conft] [nvarchar](1) NULL,
	[veh_PDO] [decimal](18, 2) NULL,
	[veh_PDO_Confc] [decimal](5, 2) NULL,
	[veh_PDO_Conft] [nvarchar](1) NULL,
	[flg_ExcessLiability] [nvarchar](1) NULL,
	[flg_ExcessLiability_Confc] [decimal](5, 2) NULL,
	[flg_ExcessLiability_Conft] [nvarchar](1) NULL,
	[flg_LessorErr] [nvarchar](1) NULL,
	[flg_LessorErr_Confc] [decimal](5, 2) NULL,
	[flg_LessorErr_Conft] [nvarchar](1) NULL,
	[Prop_Addr] [nvarchar](100) NULL,
	[Prop_Addr_Confc] [decimal](5, 2) NULL,
	[Prop_Addr_Conft] [nvarchar](1) NULL,
	[Prop_Zip] [nvarchar](30) NULL,
	[Prop_Zip_Confc] [decimal](5, 2) NULL,
	[Prop_Zip_Conft] [nvarchar](1) NULL,
	[haz_ADwellCoverageAmt] [decimal](18, 2) NULL,
	[haz_ADwellCoverageAmt_Confc] [decimal](5, 2) NULL,
	[haz_ADwellCoverageAmt_Conft] [nvarchar](1) NULL,
	[haz_ADeductibleAmt] [decimal](18, 2) NULL,
	[haz_ADeductibleAmt_Confc] [decimal](5, 2) NULL,
	[haz_ADeductibleAmt_Conft] [nvarchar](1) NULL,
	[haz_ADeductiblePct] [decimal](18, 8) NULL,
	[haz_ADeductiblePct_Confc] [decimal](5, 2) NULL,
	[haz_ADeductiblePct_Conft] [nvarchar](1) NULL,
	[flg_HazardCoverage] [nvarchar](1) NULL,
	[flg_HazardCoverage_Confc] [decimal](5, 2) NULL,
	[flg_HazardCoverage_Conft] [nvarchar](1) NULL,
	[flood_ADwellCoverageAmt] [decimal](18, 2) NULL,
	[flood_ADwellCoverageAmt_Confc] [decimal](5, 2) NULL,
	[flood_ADwellCoverageAmt_Conft] [nvarchar](1) NULL,
	[flood_ADeductibleAmt] [decimal](18, 2) NULL,
	[flood_ADeductibleAmt_Confc] [decimal](5, 2) NULL,
	[flood_ADeductibleAmt_Conft] [nvarchar](1) NULL,
	[flood_ADeductiblePct] [decimal](18, 8) NULL,
	[flood_ADeductiblePct_Confc] [decimal](5, 2) NULL,
	[flood_ADeductiblePct_Conft] [nvarchar](1) NULL,
	[flg_FloodCoverage] [nvarchar](1) NULL,
	[flg_FloodCoverage_Confc] [decimal](5, 2) NULL,
	[flg_FloodCoverage_Conft] [nvarchar](1) NULL,
	[flood_zone] [nvarchar](10) NULL,
	[flood_zone_Confc] [decimal](5, 2) NULL,
	[flood_zone_Conft] [nvarchar](1) NULL,
	[flood_grandfathered] [nvarchar](1) NULL,
	[flood_grandfathered_Confc] [decimal](5, 2) NULL,
	[flood_grandfathered_Conft] [nvarchar](1) NULL,
	[haz_WindExcluded] [nvarchar](1) NULL,
	[haz_WindExcluded_Confc] [decimal](5, 2) NULL,
	[haz_WindExcluded_Conft] [nvarchar](1) NULL,
	[wind_ADwellCoverageAmt] [decimal](18, 2) NULL,
	[wind_ADwellCoverageAmt_Confc] [decimal](5, 2) NULL,
	[wind_ADwellCoverageAmt_Conft] [nvarchar](1) NULL,
	[wind_ADeductibleAmt] [decimal](18, 2) NULL,
	[wind_ADeductibleAmt_Confc] [decimal](5, 2) NULL,
	[wind_ADeductibleAmt_Conft] [nvarchar](1) NULL,
	[wind_ADeductiblePct] [decimal](18, 8) NULL,
	[wind_ADeductiblePct_Confc] [decimal](5, 2) NULL,
	[wind_ADeductiblePct_Conft] [nvarchar](1) NULL,
	[flg_WindCoverage] [nvarchar](1) NULL,
	[flg_WindCoverage_Confc] [decimal](5, 2) NULL,
	[flg_WindCoverage_Conft] [nvarchar](1) NULL,
	[quake_ADwellCoverageAmt] [decimal](18, 2) NULL,
	[quake_ADwellCoverageAmt_Confc] [decimal](5, 2) NULL,
	[quake_ADwellCoverageAmt_Conft] [nvarchar](1) NULL,
	[quake_ADeductibleAmt] [decimal](18, 2) NULL,
	[quake_ADeductibleAmt_Confc] [decimal](5, 2) NULL,
	[quake_ADeductibleAmt_Conft] [nvarchar](1) NULL,
	[quake_ADeductiblePct] [decimal](18, 8) NULL,
	[quake_ADeductiblePct_Confc] [decimal](5, 2) NULL,
	[quake_ADeductiblePct_Conft] [nvarchar](1) NULL,
	[flg_EarthquakeCoverage] [nvarchar](1) NULL,
	[flg_EarthquakeCoverage_Confc] [decimal](5, 2) NULL,
	[flg_EarthquakeCoverage_Conft] [nvarchar](1) NULL,
	[hurricane_ADwellCoverageAmt] [decimal](18, 2) NULL,
	[hurricane_ADwellCoverageAmt_Confc] [decimal](5, 2) NULL,
	[hurricane_ADwellCoverageAmt_Conft] [nvarchar](1) NULL,
	[hurricane_ADeductibleAmt] [decimal](18, 2) NULL,
	[hurricane_ADeductibleAmt_Confc] [decimal](5, 2) NULL,
	[hurricane_ADeductibleAmt_Conft] [nvarchar](1) NULL,
	[hurricane_ADeductiblePct] [decimal](18, 8) NULL,
	[hurricane_ADeductiblePct_Confc] [decimal](5, 2) NULL,
	[hurricane_ADeductiblePct_Conft] [nvarchar](1) NULL,
	[flg_HurricaneCoverage] [nvarchar](1) NULL,
	[flg_HurricaneCoverage_Confc] [decimal](5, 2) NULL,
	[flg_HurricaneCoverage_Conft] [nvarchar](1) NULL,
	[StatedInsValue] [decimal](18, 2) NULL,
	[StatedInsValue_Confc] [decimal](5, 2) NULL,
	[StatedInsValue_Conft] [nvarchar](1) NULL,
	[CoverageBasis] [nvarchar](4) NULL,
	[CoverageBasis_Confc] [decimal](5, 2) NULL,
	[CoverageBasis_Conft] [nvarchar](1) NULL,
	[ExtCvgAmtFixed] [decimal](18, 2) NULL,
	[ExtCvgAmtFixed_Confc] [decimal](5, 2) NULL,
	[ExtCvgAmtFixed_Conft] [nvarchar](1) NULL,
	[ExtCvgAmtPct] [decimal](18, 8) NULL,
	[ExtCvgAmtPct_Confc] [decimal](5, 2) NULL,
	[ExtCvgAmtPct_Conft] [nvarchar](1) NULL,
	[bill_RemittanceID] [bigint] NULL,
	[bill_RemittanceID_Confc] [decimal](5, 2) NULL,
	[bill_RemittanceID_Conft] [nvarchar](1) NULL,
	[bill_PremiumDue] [decimal](18, 2) NULL,
	[bill_PremiumDue_Confc] [decimal](5, 2) NULL,
	[bill_PremiumDue_Conft] [nvarchar](1) NULL,
	[bill_SupplementalBilled] [nvarchar](1) NULL,
	[bill_SupplementalBilled_Confc] [decimal](5, 2) NULL,
	[bill_SupplementalBilled_Conft] [nvarchar](1) NULL,
	[bill_TotalPremium] [decimal](18, 2) NULL,
	[bill_TotalPremium_Confc] [decimal](5, 2) NULL,
	[bill_TotalPremium_Conft] [nvarchar](1) NULL,
	[bill_DueDate] [datetime2](7) NULL,
	[bill_DueDate_Confc] [decimal](5, 2) NULL,
	[bill_DueDate_Conft] [nvarchar](1) NULL,
	[condo_flg_CondoAssocPolicy] [nvarchar](1) NULL,
	[condo_flg_CondoAssocPolicy_Confc] [decimal](5, 2) NULL,
	[condo_flg_CondoAssocPolicy_Conft] [nvarchar](1) NULL,
	[condo_AssocName] [nvarchar](100) NULL,
	[condo_AssocName_Confc] [decimal](5, 2) NULL,
	[condo_AssocName_Conft] [nvarchar](1) NULL,
	[condo_Units] [int] NULL,
	[condo_Units_Confc] [decimal](5, 2) NULL,
	[condo_Units_Conft] [nvarchar](1) NULL,
	[condo_WallsInCoverage] [nvarchar](1) NULL,
	[condo_WallsInCoverage_Confc] [decimal](5, 2) NULL,
	[condo_WallsInCoverage_Conft] [nvarchar](1) NULL,
	[condo_flg_OwnersPolicy] [nvarchar](1) NULL,
	[condo_flg_OwnersPolicy_Confc] [decimal](5, 2) NULL,
	[condo_flg_OwnersPolicy_Conft] [nvarchar](1) NULL,
	[flg_FloodNFIP] [nvarchar](1) NULL,
	[flg_FloodNFIP_Confc] [decimal](5, 2) NULL,
	[flg_FloodNFIP_Conft] [nvarchar](1) NULL,
	[flg_FloodCertPrivate] [nvarchar](1) NULL,
	[flg_FloodCertPrivate_Confc] [decimal](5, 2) NULL,
	[flg_FloodCertPrivate_Conft] [nvarchar](1) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[fpr_version] [nvarchar](200) NULL,
	[InsertTime] [datetime2](7) NULL,
	[veh_num] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

