USE [master]
GO
CREATE LOGIN [ELDREDGE_A\OctopusDeploy] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [UTL]
GO
CREATE USER [ELDREDGE_A\OctopusDeploy] FOR LOGIN [ELDREDGE_A\OctopusDeploy]
GO
USE [UTL]
GO
ALTER USER [ELDREDGE_A\OctopusDeploy] WITH DEFAULT_SCHEMA=[DBO]
GO
USE [UTL]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\OctopusDeploy]
GO
USE [UTL]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ELDREDGE_A\OctopusDeploy]
GO
USE [UTL]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [ELDREDGE_A\OctopusDeploy]
GO

use [UTL]
GO
GRANT EXECUTE TO [ELDREDGE_A\OctopusDeploy]
GO
use [UTL]
GO
GRANT VIEW DEFINITION TO [ELDREDGE_A\OctopusDeploy]
GO
