CREATE DATABASE [HDTStorage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HDTStorage', FILENAME = N'F:\SQLDATA\HDTStorage.mdf' , SIZE = 5120000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HDTStorage_log', FILENAME = N'G:\SQLLOGS\HDTStorage_log.ldf' , SIZE = 1048576KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HDTStorage] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [HDTStorage] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HDTStorage] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HDTStorage] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HDTStorage] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HDTStorage] SET ARITHABORT OFF 
GO
ALTER DATABASE [HDTStorage] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HDTStorage] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HDTStorage] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [HDTStorage] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HDTStorage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HDTStorage] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HDTStorage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HDTStorage] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HDTStorage] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HDTStorage] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HDTStorage] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HDTStorage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HDTStorage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HDTStorage] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HDTStorage] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HDTStorage] SET  READ_WRITE 
GO
ALTER DATABASE [HDTStorage] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HDTStorage] SET  MULTI_USER 
GO
ALTER DATABASE [HDTStorage] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HDTStorage] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [HDTStorage] SET DELAYED_DURABILITY = DISABLED 
GO
USE [HDTStorage]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [HDTStorage] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
