ALTER SERVER ROLE [sysadmin] DROP MEMBER [UTQAAdmin]
GO
USE [HDTStorage]
GO
CREATE USER [UTQAAdmin] FOR LOGIN [UTQAAdmin]
GO
USE [HDTStorage]
GO
ALTER ROLE [db_owner] ADD MEMBER [UTQAAdmin]
GO
USE [UnitracHDStorage]
GO
CREATE USER [UTQAAdmin] FOR LOGIN [UTQAAdmin]
GO
USE [UnitracHDStorage]
GO
ALTER ROLE [db_owner] ADD MEMBER [UTQAAdmin]
GO
USE [UTL]
GO
CREATE USER [UTQAAdmin] FOR LOGIN [UTQAAdmin]
GO
USE [UTL]
GO
ALTER ROLE [db_owner] ADD MEMBER [UTQAAdmin]
GO
USE [UTL_Backup]
GO
CREATE USER [UTQAAdmin] FOR LOGIN [UTQAAdmin]
GO
USE [UTL_Backup]
GO
ALTER ROLE [db_owner] ADD MEMBER [UTQAAdmin]
GO
USE [UTLDev]
GO
CREATE USER [UTQAAdmin] FOR LOGIN [UTQAAdmin]
GO
USE [UTLDev]
GO
ALTER ROLE [db_owner] ADD MEMBER [UTQAAdmin]
GO
use [master]
GO
REVOKE ADMINISTER BULK OPERATIONS TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY AVAILABILITY GROUP TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY CONNECTION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY CREDENTIAL TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY DATABASE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY ENDPOINT TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY EVENT NOTIFICATION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY EVENT SESSION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY LINKED SERVER TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY LOGIN TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY SERVER AUDIT TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER ANY SERVER ROLE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER RESOURCES TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER SERVER STATE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER SETTINGS TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE ALTER TRACE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE AUTHENTICATE SERVER TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CONTROL SERVER TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE ANY DATABASE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE AVAILABILITY GROUP TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE DDL EVENT NOTIFICATION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE ENDPOINT TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE SERVER ROLE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE CREATE TRACE EVENT NOTIFICATION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE EXTERNAL ACCESS ASSEMBLY TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE SHUTDOWN TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE UNSAFE ASSEMBLY TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE VIEW ANY DATABASE TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE VIEW ANY DEFINITION TO [UTQAAdmin] AS [sa]
GO
use [master]
GO
REVOKE VIEW SERVER STATE TO [UTQAAdmin] AS [sa]
GO
