USE IQQ_TRAINING;

DECLARE @PURGEDATE DATETIME = DATEADD(DAY,-90,GETDATE());
SELECT CAST(@PURGEDATE AS DATE) AS PURGEDATE;
--TOTALS
SELECT COUNT(ID) AS TOTAL_RESPONSE_LOG_COUNT FROM RESPONSE_LOG  WHERE CREATE_DT <= @PURGEDATE;
SELECT COUNT(RESPONSE_ID) AS TOTAL_RESPONSE_PROPERTY_LOG_COUNT FROM RESPONSE_PROPERTY  WHERE CREATE_DT <= @PURGEDATE;
SELECT COUNT(ID) TOTAL_RESPONSE_COUNT FROM RESPONSE WHERE CREATE_DT <= @PURGEDATE;

/*********
The details of each table by month
*********/
--RESPONSE_LOG
SELECT CONVERT(VARCHAR(7), CREATE_DT, 120) AS RESPONSE_LOG_DATES,
       COUNT(ID) AS TOTALS,
	MIN(CREATE_DT) FROM RESPONSE_LOG
WHERE CREATE_DT <= @PURGEDATE
    GROUP BY CONVERT(VARCHAR(7), CREATE_DT, 120)
    ORDER BY CONVERT(VARCHAR(7), CREATE_DT, 120) DESC;
--RESPONSE_PROPERTY
SELECT CONVERT(VARCHAR(7), CREATE_DT, 120) AS RESPONSE_PROPERTY_DATES,
       COUNT(RESPONSE_ID) AS TOTALS ,
	MIN(CREATE_DT)FROM RESPONSE_PROPERTY
WHERE CREATE_DT <= @PURGEDATE
    GROUP BY CONVERT(VARCHAR(7), CREATE_DT, 120) 
    ORDER BY CONVERT(VARCHAR(7), CREATE_DT, 120) DESC;

--RESPONSE
SELECT CONVERT(VARCHAR(7), CREATE_DT, 120) AS RESPONSE_DATES,
    COUNT(ID) AS TOTALS ,
	MIN(CREATE_DT) FROM RESPONSE 
WHERE CREATE_DT <= @PURGEDATE
    GROUP BY CONVERT(VARCHAR(7), CREATE_DT, 120)
    ORDER BY CONVERT(VARCHAR(7), CREATE_DT, 120) DESC;