USE UniTrac

/* 
SELECT * FROM dbo.DOCUMENT_MANAGEMENT
ORDER BY STORAGE_TYPE_CD ASC
*/




UPDATE DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = '\\unitrac\UT_TEST_IMAGE'
WHERE STORAGE_TYPE_CD = 'IMAGE'

UPDATE DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = '\\unitrac\UT_TEST_CERT'
WHERE STORAGE_TYPE_CD = 'CERT'

UPDATE DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = '\\unitrac\UT_TEST_NOTICE'
WHERE STORAGE_TYPE_CD = 'NTC'

UPDATE DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = '\\unitrac\UT_TEST_REPORT'
WHERE STORAGE_TYPE_CD = 'RPT'

UPDATE DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = '\\unitrac\UT_TEST_PDF'
WHERE STORAGE_TYPE_CD = 'EDITXN'




