/*
These warehouses can be removed
*/
USE ROLE SYSADMIN;

DROP WAREHOUSE IF EXISTS "CONCURRENCY_WH";
DROP WAREHOUSE IF EXISTS "COMPUTE_WH";


/*
These warehouses can be renamed to clarify which product they belong to
Naming convention <System>_<Environment>_<Product>_<Type>  

Example:  
EDW_PRODUCTION_WH (Enterprise data warehouse, production, warehouse)

*****Future thoughts*****
Break down compute by "environment"
This will give the ability to see how much work DEV/QA/PROD are doing

Examples:
EDW_PROD_PRODSUPPORT_WH
EDW_QA_INFORMATICA_WH
EDW_DEV_INFORMATICA_WH


*/
USE ROLE SYSADMIN;
ALTER WAREHOUSE IF EXISTS "PRODSUPPORT" RENAME TO "EDW_PRODSUPPORT_WH", COMMENT = 'EDW production support warehouse';
ALTER WAREHOUSE IF EXISTS "SANDBOX" RENAME TO "EDW_SANDBOX_WH", COMMENT = 'EDW sandbox warehouse';
ALTER WAREHOUSE IF EXISTS "DATASCIENCE" RENAME TO "EDW_DATASCIENCE_WH", COMMENT = 'EDW Data Science Warehouse';
ALTER WAREHOUSE IF EXISTS "INFORMATICA" RENAME TO "EDW_INFORMATICA_WH", COMMENT = 'EDW Informatica ETL warehouse';
ALTER WAREHOUSE IF EXISTS "WEBFOCUS" RENAME TO "EDW_WEBFOCUS_WH", COMMENT = 'EDW Webfocus BI warehouse';


USE ROLE SYSADMIN;
/***** INFORMATICA WAREHOUSES *****/
CREATE WAREHOUSE IF NOT EXISTS EDW_DEV_INFA_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Informatica Development Warehouse';

CREATE WAREHOUSE IF NOT EXISTS EDW_TEST_INFA_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Informatica Test Warehouse';

CREATE WAREHOUSE IF NOT EXISTS EDW_PROD_INFA_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Informatica Production Warehouse';

/***** BUSINESS INTELLIGENCE WAREHOUSES *****/
CREATE WAREHOUSE IF NOT EXISTS EDW_DEV_BI_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Business Intelligence Development Warehouse';

CREATE WAREHOUSE IF NOT EXISTS EDW_TEST_BI_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Business Intelligence Test Warehouse';

CREATE WAREHOUSE IF NOT EXISTS EDW_PROD_BI_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD' COMMENT = 'EDW Business Intelligence Production Warehouse';