USE UniTrac
GO

declare @wi as varchar(MAX)
DECLARE @pl AS VARCHAR(max)
DECLARE @TranType AS varchar(max)

set @wi = 34743333

SET @TranType ='UNITRAC'


SELECT
      @pl = RELATE_ID 
FROM
      dbo.WORK_ITEM WI
WHERE
      WI.id = @wi
 




 
SELECT OUTPUT_BATCH.EXTERNAL_ID,OUTPUT_BATCH_LOG.*
from OUTPUT_BATCH
INNER JOIN OUTPUT_BATCH_LOG ON OUTPUT_BATCH.ID = OUTPUT_BATCH_LOG.OUTPUT_BATCH_ID
WHERE OUTPUT_BATCH.PROCESS_LOG_ID IN (@pl) --AND LOG_TXN_TYPE_CD = 'SENT' 