USE ROLE ACCOUNTADMIN;

BEGIN
	CASE WHEN (select COUNT(*) FROM snowflake.account_usage.users where NAME = 'NEWUSER_NAME')  = 0
	THEN

create USER IDENTIFIER('"NEWUSER_NAME"') COMMENT = '' PASSWORD = '??????????????' MUST_CHANGE_PASSWORD = false LOGIN_NAME = '' 
FIRST_NAME = '' LAST_NAME = '' DISPLAY_NAME = '' EMAIL = '' 
DEFAULT_WAREHOUSE = 'WAREHOUSE' DEFAULT_NAMESPACE = '' DEFAULT_ROLE = 'ROLE';
GRANT ROLE IDENTIFIER('"ROLE"') TO USER IDENTIFIER('"NEWUSER_NAME"');
RETURN 'SUCCESS: Account created';

ELSE 


RETURN 'WARNING: Account exists';
	END;
    
END;