USE ROLE SYSADMIN;

BEGIN
	CASE WHEN (select count(*) FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES GU WHERE name = 'WAREHOUSE_NAME' and granted_on = 'WAREHOUSE'and deleted_on is null) ;
	THEN

CREATE WAREHOUSE WAREHOUSE_NAME WAREHOUSE_SIZE=LARGE INITIALLY_SUSPENDED=X-Small;
RETURN 'SUCCESS: Warehouse created';


ELSE 

RETURN 'WARNING: Warehouse exists';
	END;
    
END;

GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE READ_BOND_STAGE;

