USE ROLE --OWNER OF THE DB


BEGIN
	CASE WHEN  (select count(*) FROM information_schema.DATABASES where DATABASE_NAME = 'TEMP_ROLE')  = 0
	THEN

CREATE DATABASE JIRA_EXPORTS;
RETURN 'SUCCESS: Database created';
ELSE 

RETURN 'WARNING: Database exists';



	END;
    
END;

GRANT USAGE ON DATABASE BOND_STAGE TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON DATABASE BOND_STAGE TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON DATABASE BOND_STAGE TO ROLE READ_BOND_STAGE;
GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE READ_BOND_STAGE;
