Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherIn |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherOut |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHService |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceVUT |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceUSD |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LetterGen |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessService |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle2 |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchOut |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceRPT |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTDEF |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTUSD |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVRBSS |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow2 |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow3 |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow4 |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchIn |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessMatchIn2 |  select machinename, name, status
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UTLBusinessService |  select machinename, name, status