Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherIn |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherOut |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHService |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceVUT |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceUSD |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LetterGen |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessService |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle2 |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchOut |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceRPT |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTDEF |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTUSD |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVRBSS |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow2 |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow3 |Restart-Service
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow4 |Restart-Service
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchIn |Restart-Service
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessMatchIn2 |Restart-Service
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UTLBusinessService |Restart-Service
