Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherIn |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	DirectoryWatcherOut |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHService |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceVUT |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LDHServiceUSD |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	LetterGen |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessService |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceCycle2 |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchOut |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceRPT |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTDEF |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVREXTUSD |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	MSGSRVRBSS |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow2 |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow3 |Stop-Service  -Force
Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	Workflow4 |Stop-Service  -Force
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessServiceMatchIn |Stop-Service  -Force
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UnitracBusinessMatchIn2 |Stop-Service  -Force
#Get-Service	 -ComputerName	UTAUTO-APP1	  -Name	UTLBusinessService |Stop-Service  -Force
