--SELECT * FROM LENDER WHERE CODE_TX = '6155'

--SELECT * FROM UniTracHDStorage..INC0222294_RC_ONLYNew

---- DROP TABLE #TMPLOAN
SELECT LOAN.NUMBER_TX , LOAN.DIVISION_CODE_TX , LOAN.BRANCH_CODE_TX , 
COLL.LOAN_ID , COLL.ID AS COLL_ID , COLL.PROPERTY_ID , COLL.PRIMARY_LOAN_IN , 
RC.ID AS RC_ID , RC.TYPE_CD , RC.SUMMARY_STATUS_CD , RC.SUMMARY_SUB_STATUS_CD , 
RC.INSURANCE_STATUS_CD , RC.INSURANCE_SUB_STATUS_CD , 
RC.BEGAN_NEW_IN , RC.CPI_QUOTE_ID , RC.NOTICE_DT , 
RC.NOTICE_SEQ_NO , RC.NOTICE_TYPE_CD , 
RC.LAST_EVENT_DT , RC.LAST_EVENT_SEQ_ID , RC.LAST_SEQ_CONTAINER_ID , 
RC.EXPOSURE_DT
INTO #TMPLOAN
 FROM LOAN
JOIN COLLATERAL COLL ON COLL.LOAN_ID = LOAN.ID
AND COLL.PURGE_DT IS NULL AND LOAN.PURGE_DT IS NULL
JOIN PROPERTY PR ON PR.ID = COLL.PROPERTY_ID
AND PR.PURGE_DT IS NULL
JOIN REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = PR.ID
AND RC.PURGE_DT IS NULL
WHERE LOAN.LENDER_ID = 730
AND LOAN.RECORD_TYPE_CD = 'G'
AND PR.RECORD_TYPE_CD = 'G'
AND RC.RECORD_TYPE_CD = 'G'
AND RC.SUMMARY_STATUS_CD = 'N'
AND RC.EXPOSURE_DT < '01/01/2016'
AND RC.TYPE_CD = 'PHYS-DAMAGE'
----- 10701


----- GET THE LIST OF RC'S IN #TMPRC
---- DROP TABLE #TMPRC
SELECT  *
INTO #TMPRC
FROM #TMPLOAN
WHERE CPI_QUOTE_ID > 0
---- 268

---- DROP TABLE #tmpIH
SELECT DISTINCT IH.ID AS IH_ID
INTO #tmpIH
FROM #TMPRC tmp
		JOIN INTERACTION_HISTORY IH ON IH.RELATE_ID = tmp.CPI_QUOTE_ID
WHERE
		IH.TYPE_CD = 'CPI'
		AND IH.RELATE_CLASS_TX = 'ALLIED.UNITRAC.CPIQUOTE'
		AND tmp.RC_ID = ISNULL(IH.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]', 'BIGINT'),0 )
		and tmp.PROPERTY_ID = IH.property_id     
		AND ISNULL(IH.SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar(20)'),'') = 'Open'
		AND IH.PURGE_DT IS NULL
---- 195


SELECT * 
INTO UnitracHDStorage.dbo.tmpTask37067_Loan
FROM #TMPLOAN
---- 10701

SELECT * 
INTO UnitracHDStorage.dbo.tmpTask37067_IH
FROM #tmpIH
---- 195

	
INSERT INTO
	PROPERTY_CHANGE (
		ENTITY_NAME_TX,
		ENTITY_ID,
		USER_TX,
		ATTACHMENT_IN,
		CREATE_DT,
		AGENCY_ID,
		DESCRIPTION_TX,
		DETAILS_IN,
		FORMATTED_IN,
		LOCK_ID,
		PARENT_NAME_TX,
		PARENT_ID,
		TRANS_STATUS_CD,
		UTL_IN)
SELECT DISTINCT
	'Allied.UniTrac.RequiredCoverage',
	tf.RC_ID,
	'TASK37067',
	'N',
	GETDATE(),
	1,
	'Notice Cycle Cleared',
	'N',
	'Y',
	1,
	'Allied.UniTrac.RequiredCoverage',
	TF.RC_ID,
	'PEND',
	'N'
FROM
	 #TMPLOAN tf
WHERE
	NOTICE_SEQ_NO > 0
	----- 267
			
						
			
UPDATE QT
	SET	QT.CLOSE_REASON_CD = 'NCC',
		QT.CLOSE_DT = GETDATE(),
		QT.UPDATE_DT = GETDATE(),
		QT.UPDATE_USER_TX = 'TASK37067',
		QT.LOCK_ID = (QT.LOCK_ID % 255) + 1
	--SELECT COUNT(*)
	FROM CPI_QUOTE QT
	JOIN #TMPRC RC
		ON RC.CPI_QUOTE_ID = QT.ID
		---- 268
			
			
UPDATE IH
SET	SPECIAL_HANDLING_XML.modify('replace value of (/SH/Status/text())[1] with "Closed" '),
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'TASK37067',
	LOCK_ID = (LOCK_ID % 255) + 1
--SELECT COUNT(*)
FROM INTERACTION_HISTORY IH
JOIN #tmpIH
	ON #tmpIH.IH_ID = IH.ID
	---- 195


-- Update RequiredCoverage Status from Track to Active
UPDATE RC SET SUMMARY_STATUS_CD = 'A' ,
INSURANCE_STATUS_CD = 'A' , BEGAN_NEW_IN = 'N' , 
GOOD_THRU_DT = NULL , 
CPI_QUOTE_ID = NULL , NOTICE_DT = NULL , NOTICE_TYPE_CD = NULL , 
NOTICE_SEQ_NO = NULL , LAST_EVENT_SEQ_ID = NULL , LAST_EVENT_DT = NULL ,
LAST_SEQ_CONTAINER_ID = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'TASK37067' , 
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT RC.SUMMARY_STATUS_CD , RC.INSURANCE_STATUS_CD , RC.BEGAN_NEW_IN , RC.EXPOSURE_DT , RC.TYPE_CD ---,  *
FROM REQUIRED_COVERAGE RC JOIN #TMPLOAN TMP 
ON TMP.RC_ID = RC.ID 
---- 10701

--SELECT DISTINCT LOAN_ID FROM #TMPLOAN

-- Add Property change log
 INSERT INTO PROPERTY_CHANGE
 (
 ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN
 )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , TMP.RC_ID , 'TASK37067' , 'N' ,
 GETDATE(),  1 ,
 'Changed Summary Status from New to Audit' ,
 'N' , 'Y' , 1 ,  'Allied.UniTrac.RequiredCoverage' , TMP.RC_ID , 'PEND' , 'N'
 FROM #TMPLOAN TMP
 ---- 10682


UPDATE EE
SET STATUS_CD = 'CLR',
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'TASK37067',
	LOCK_ID = (EE.LOCK_ID % 255) + 1
--SELECT ee.*
FROM
	EVALUATION_EVENT EE
	JOIN #TMPLOAN te ON EE.REQUIRED_COVERAGE_ID = te.RC_ID
	WHERE ee.STATUS_CD = 'PEND'
	AND ee.EVENT_SEQUENCE_ID > 0
	---- 4
