USE UniTrac 

SELECT * FROM dbo.BUSINESS_OPTION BO
JOIN dbo.BUSINESS_OPTION_GROUP BG ON BO.BUSINESS_OPTION_GROUP_ID = BG.ID
LEFT JOIN dbo.BUSINESS_RULE_BASE BR ON BR.ID = BO.BUSINESS_RULE_ID
LEFT JOIN dbo.LENDER_PRODUCT LP ON LP.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
LEFT JOIN dbo.LENDER L ON L.ID =LP.LENDER_ID
WHERE  BO.NAME_TX= 'EventOptionReaudit' AND L.CODE_TX IN ()

SELECT   * 
FROM dbo.EVENT_SEQ_CONTAINER E
JOIN dbo.ESC_ERD_RELATE EE ON EE.ESC_ID = E.ID
JOIN dbo.EVENT_REACTION_DEFINITION ERD ON ERD.ID = EE.ERD_ID
JOIN dbo.EVENT_STATUS ES ON ES.EVENT_REACTION_DEFINITION_ID = ERD.ID
JOIN dbo.LENDER_PRODUCT lp ON lp.id = LENDER_PRODUCT_ID
JOIN dbo.IMPAIRMENT_DEFINITION ID ON ID.LENDER_PRODUCT_ID = lp.ID
JOIN dbo.LENDER L ON L.ID = E.LENDER_ID
WHERE l.CODE_TX = '4804' AND e.PURGE_DT IS NULL 
AND e.DESCRIPTION_TX LIKE '' 