SELECT SOURCE_CD as SOURCE, CONVERT(varchar, CREATEDDATE,101) as DATE, COUNT(ID) AS COUNT
FROM VUT.dbo.lkuvinlookup
WHERE CREATEDDATE >= '2016-01-01' AND CREATEDDATE <= '2016-06-09'
GROUP BY SOURCE_CD,CONVERT(varchar, CREATEDDATE,101)
ORDER BY CONVERT(varchar, CREATEDDATE,101), SOURCE