USE UniTrac



SELECT DISTINCT MESSAGE_ID INTO #tmpMess
FROM dbo.TRADING_PARTNER_LOG
WHERE UPDATE_USER_TX  ='MsgSrvrDEF'
AND CREATE_DT >= '2020-06-01'


SELECT ID INTO #tmpDoc
FROM dbo.DOCUMENT
WHERE MESSAGE_ID IN (SELECT MESSAGE_ID FROM #tmpMess)







SELECT COUNT(*), tp.EXTERNAL_ID_TX, tp.NAME_TX
FROM dbo.[TRANSACTION] T
JOIN dbo.DOCUMENT D ON D.ID = t.DOCUMENT_ID
JOIN dbo.MESSAGE m ON m.ID = D.MESSAGE_ID
JOIN dbo.TRADING_PARTNER tp ON tp.id = m.RECIPIENT_TRADING_PARTNER_ID
WHERE DOCUMENT_ID IN (SELECT id FROM #tmpDoc)
GROUP BY tp.EXTERNAL_ID_TX, tp.NAME_TX





SELECT * FROM dbo.PROCESS_DEFINITION
WHERE id IN (2739)



SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID = 2739
AND UPDATE_DT >= '2020-06-01'

SELECT * FROM dbo.TRADING_PARTNER_LOG
WHERE UPDATE_USER_TX  ='MsgSrvrDEF'
AND CREATE_DT >= '2020-06-01'
ORDER BY CREATE_DT DESC 

SELECT * FROM dbo.DOCUMENT
WHERE MESSAGE_ID IN (SELECT MESSAGE_ID FROM #tmpMess)

SELECT * FROM dbo.MESSAGE
WHERE id IN (SELECT MESSAGE_ID FROM #tmpMess)


SELECT * 
FROM dbo.[TRANSACTION]
WHERE DOCUMENT_ID IN (SELECT id FROM #tmpDoc)
ORDER BY CREATE_DT DESC 