
--Lender File Setup 
USE UniTrac

SELECT * FROM dbo.PREPROCESSING_DETAIL pd 
JOIN dbo.DELIVERY_INFO_GROUP dig ON dig.ID = pd.DELIVERY_INFO_GROUP_ID
JOIN dbo.DELIVERY_INFO di ON DIG.DELIVERY_INFO_ID = di.ID

SELECT RDD.NAME_TX, RD.* 
FROM dbo.RELATED_DATA rd
JOIN dbo.RELATED_DATA_DEF RDD ON RDD.id = rd.DEF_ID
JOIN dbo.DELIVERY_INFO DI ON DI.id = rd.RELATE_ID




