SELECT ERD.*
FROM   dbo.EVENT_SEQ_CONTAINER E
       JOIN dbo.ESC_ERD_RELATE EE ON EE.ESC_ID = E.ID
       JOIN dbo.EVENT_REACTION_DEFINITION ERD ON ERD.ID = EE.ERD_ID
       JOIN dbo.LENDER L ON L.ID = E.LENDER_ID
WHERE  E.PURGE_DT IS NULL
       AND EE.PURGE_DT IS NULL
       AND ERD.PURGE_DT IS NULL
       AND L.PURGE_DT IS NULL
       AND L.TEST_IN = 'N'
	   AND l.CODE_TX = '3000';