USE UniTrac

SELECT * from UniTrac..DOCUMENT_MANAGEMENT

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTIMAGE','\UTIMAGE','\UT_TEST_IMAGE') WHERE STORAGE_TYPE_CD = 'IMAGE'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTCERT','\UTCERT','\UT_TEST_CERT') WHERE STORAGE_TYPE_CD = 'CERT'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTNOTICE','\UTNOTICE','\UT_TEST_NOTICE') WHERE STORAGE_TYPE_CD = 'NTC'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTREPORT','\UTREPORT','\UT_TEST_REPORT') WHERE STORAGE_TYPE_CD = 'RPT'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\EDI_IMAGE','\EDI_IMAGE','\UT_TEST_PDF') WHERE STORAGE_TYPE_CD = 'EDITXN'


--*****PURGES EMAIL, TXT AND FAX OUTPUT CONFIGS****
UPDATE OUTPUT_CONFIGURATION
SET PURGE_DT = GETDATE(), UPDATE_USER_TX = 'StagingRefresh',LOCK_ID = LOCK_ID + 1
--SELECT * FROM dbo.OUTPUT_CONFIGURATION
WHERE OUTPUT_TYPE_CD IN ('Email','FAX','TXT') 


 UPDATE OUTPUT_CONFIGURATION
 SET XML_CONTAINER = '<OutputConfigurationSettings />', LOCK_ID = LOCK_ID + 1, PURGE_DT = NULL
WHERE OUTPUT_TYPE_CD IN ('Email') --AND RELATE_ID = 1

 UPDATE OUTPUT_CONFIGURATION
 SET OUTPUT_DEVICE_ID = 39, LOCK_ID = LOCK_ID + 1, PURGE_DT = NULL
WHERE OUTPUT_TYPE_CD IN ('FAX') --AND RELATE_ID = 1

 UPDATE OUTPUT_CONFIGURATION
 SET XML_CONTAINER = '<OutputConfigurationSettings />', OUTPUT_DEVICE_ID = 39, LOCK_ID = LOCK_ID + 1, PURGE_DT = NULL
WHERE OUTPUT_TYPE_CD IN ('TXT') AND RELATE_ID = 199 AND RELATE_CLASS_TX = 'Allied.UniTrac.Lender'




--------- STOP PROCESS DEFINITIONS!!!!!!!
--UPDATE UniTrac..PROCESS_DEFINITION
--SET ACTIVE_IN = 'N' WHERE ACTIVE_IN = 'Y'

--------- Don't Forget HOV Mapping!!!!!!
SELECT * FROM UniTrac..OUTPUT_DEVICE
WHERE NAME_TX LIKE 'hov%'

UPDATE OUTPUT_DEVICE
SET UNC_PATH_TX = 'C:\OutputBatchFiles\UniTracHOVQA'
WHERE NAME_TX LIKE 'HOV%' 

UPDATE OUTPUT_DEVICE
SET UNC_PATH_TX = 'C:\OutputBatchFiles\NapaBatches'
WHERE NAME_TX LIKE 'Napa%' 

--------- Whatever this does, update it!!!!!!! (LFP Stuff!)
SELECT * FROM UniTrac..PPDATTRIBUTE
WHERE CODE_CD IN ('DBServer','DBUserID','DBPassword','DBInstance','PPDHelperTypeCode')
AND PURGE_DT IS NULL

SELECT * FROM UniTrac..PPDATTRIBUTE
WHERE CODE_CD IN ('DBServer','DBUserID','DBPassword','DBInstance','PPDHelperTypeCode')
AND VALUE_TX NOT IN ('UTQA-SQL-14', 'UniTracAppUser','UniTracAppUser', 'onA8LfDMlZEDOTRnAebg','VUT')

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'ut-preprod-1'
--SELECT * FROM PPDATTRIBUTE
WHERE CODE_CD = 'DBServer'

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'qauser'
WHERE CODE_CD = 'DBUserId'

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'qauser'
WHERE CODE_CD = 'DBPassword'

SELECT * FROM UniTrac..PPDATTRIBUTE
--SELECT * FROM PPDATTRIBUTE
WHERE CODE_CD IN ('DBServer','DBUserID','DBPassword','DBUserID')

SELECT * FROM UniTrac..PREPROCESSING_DETAIL
WHERE TYPE_CD = 'TrackingCH'

UPDATE PREPROCESSING_DETAIL
SET TYPE_CD = 'TrackingCH' WHERE TYPE_CD = 'Tracking'
