

--Full
BACKUP DATABASE [WinAppLog] TO
DISK = '\\IGNITE-SQL14\Restores\CP-SQLDEV-02\WinAppLog.Bak'
WITH INIT , NOUNLOAD , NAME = 'WinAppLog_Backup', NOSKIP , STATS = 10, COMPRESSION, NOFORMAT



--Diff
BACKUP DATABASE [WinAppLog]
TO DISK =  '\\IGNITE-SQL14\i$\Restores\OCR-SQLPRD-07\WinAppLog3\WinAppLog1.DIF'
WITH DIFFERENTIAL, NOFORMAT, NOINIT,
SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 25




--Logs
BACKUP LOG [WinAppLog]
TO DISK = '\\IGNITE-SQL14\Restores\CP-SQLDEV-02\WinAppLog.LOG'


