USE UniTrac	


SELECT     
concat(SERVER_SHARE_TX,'\',RELATIVE_PATH_TX,'\')  as  [Document], dc.id
FROM dbo.DOCUMENT_CONTAINER DC 
JOIN dbo.DOCUMENT_MANAGEMENT DM ON DM.ID = DC.DOCUMENT_MANAGEMENT_ID
where  dc.ID = '149209645'

