SELECT TP.NAME_TX,DI.DOCUMENT_TYPE_CD,DD.*
FROM TRADING_PARTNER TP
INNER JOIN DELIVERY_INFO DI ON TP.ID = DI.TRADING_PARTNER_ID AND DI.PURGE_DT IS NULL
INNER JOIN DELIVERY_INFO_GROUP DIG ON DI.ID = DIG.DELIVERY_INFO_ID AND DIG.PURGE_DT IS NULL
INNER JOIN DELIVERY_DETAIL DD ON DD.DELIVERY_INFO_GROUP_ID = DIG.ID AND DD.PURGE_DT IS NULL
WHERE TYPE_CD = 'EDI_TP'
ORDER BY TP.NAME_TX