/* 
SELECT * FROM PROCESS_DEFINITION
*/



---------- START OFF SIDELINING -------
UPDATE PROCESS_DEFINITION
SET ACTIVE_IN = 'N', ONHOLD_IN = 'N'
--SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ACTIVE_IN = 'Y' AND ONHOLD_IN = 'Y'



----- TURN ON BY PROCESS TYPE CODE
UPDATE  PROCESS_DEFINITION
SET     ACTIVE_IN = 'Y'
--SELECT * FROM dbo.PROCESS_DEFINITION
WHERE   PROCESS_TYPE_CD IN ( 'RPTGEN', 'LETGEN', 'HISTFORM', 'LDAPSYNC',
                             'WFEVAL', 'PDUNLOCK', 'WFUNLCK', 'BSSPA',
                             'INSDOCPA', 'UTLMTCHOB', 'VUTPA', 'FULFILLPRC',
                             'DWINBOUND', 'DWINBOUND', 'DWOUTBOUND',
                             'KEYIMAGE','DASHCACHE' )

----- TURN ON JUST ONE GOODTHRU
UPDATE  PROCESS_DEFINITION
SET     ACTIVE_IN = 'Y'
WHERE   PROCESS_TYPE_CD IN ( 'GOODTHRUDT' )
AND ID = 52

------ PICK THE SPECIFIC MESSAGESERVERS
UPDATE  PROCESS_DEFINITION
SET     ACTIVE_IN = 'Y'
WHERE   PROCESS_TYPE_CD IN ( 'MSGSRVWF', 'MSGSRV' )
        AND UPDATE_USER_TX IN ( 'MsgSrvrDEF', 'MsgSrvrEDIIDR', 'MsgSrvrBSS',
                                'MsgSrvrEXTUSD', 'MsgSrvrEXTVUT',
                                'MsgSrvrEXTHUNT', 'MsgSrvrEXTSANT' )
