use unitrac




      SELECT *
	FROM dbo.OUTPUT_BATCH WHERE STATUS_CD IN ('PEND') 
   AND PURGE_DT IS NULL

update ob set PURGE_DT = GETDATE(), STATUS_CD = 'COMP', OUTSOURCER_STATUS_CD= '', update_user_tx = 'Bug49561'
--   SELECT *
	FROM dbo.OUTPUT_BATCH ob
	WHERE STATUS_CD IN ('PEND')  
	AND CAST(UPDATE_DT AS DATE) <= CAST(GETDATE()-2 AS DATE)
 --  AND EXTERNAL_ID not LIKE 'RPT%'
   AND PURGE_DT IS NULL
   
