SELECT IsNull(LOB.CODE_TX, 'All')as CODE_TX,LOB.NAME_TX,LOC.NAME_TX,*
FROM DELIVERY_INFO_EXTRACT_CONFIG_RELATE DIE
LEFT JOIN VUT.dbo.tbllenderextract LE on DIE.RELATE_ID = LE.LenderExtractKey AND DIE.RELATE_CLASS_NAME_TX = 'LenderExtract'
LEFT JOIN LENDER_ORGANIZATION LOC ON LE.ContractTypeKey = LOC.ID
LEFT JOIN LENDER_ORGANIZATION LOB ON LE.BranchKey = LOB.ID 
WHERE DELIVERY_INFO_ID = 2079 AND DIE.PURGE_DT IS NULL
order by LOB.CODE_TX,LOC.NAME_TX