SELECT *
FROM LENDER
WHERE CODE_TX = '3039'

SELECT *
FROM LOAN
WHERE LENDER_ID = 2271

SELECT *
FROM LENDER_PAYEE_CODE_FILE
WHERE LENDER_ID = 2273 AND PAYEE_CODE_TX = '15'


SELECT *
FROM LENDER_PAYEE_CODE_MATCH
INNER JOIN ADDRESS ON LENDER_PAYEE_CODE_MATCH.REMITTANCE_ADDR_ID = ADDRESS.ID
WHERE LENDER_PAYEE_CODE_FILE_ID = 30947 AND LENDER_PAYEE_CODE_MATCH.PURGE_DT IS NULL

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
WHERE LENDER_PAYEE_CODE_FILE_ID = 30947

UPDATE LENDER_PAYEE_CODE_MATCH
SET PURGE_DT = GETDATE(), UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'admin', LOCK_ID = LOCK_ID + 1
--SELECT * FROM LENDER_PAYEE_CODE_MATCH
WHERE LENDER_PAYEE_CODE_FILE_ID = 30947 AND ID IN (21098)

