Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UniTracBusinessServiceMatchIn7
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchInN 
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchIn9
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	UniTracBusinessServiceMatchIn10
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInL
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn1
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn17
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	UniTracBusinessServiceMatchIn8
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn5
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn4
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	UniTracBusinessServiceMatchIn6
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	UniTracBusinessServiceMatchIn12
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn13
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInG
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInH
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInI
Get-Service	 -ComputerName	 Unitrac-WH15	 -Name	UnitracBusinessServiceMatchIn15
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceMatchInF
Get-Service	 -ComputerName	 Unitrac-WH17	 -Name	UnitracBusinessServiceMatchInJ
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	UnitracBusinessServiceMatchIn14
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceMatchInK
