Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	DirectoryWatcherServerIn
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	DirectoryWatcherServerOut
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LDHServ
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LDHServiceVUT
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessService
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	ldhserviceUSD
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceCycle
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServicePRT
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceMatchIn
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceMatchOut
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceRPT
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService2
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService3
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREDIIDR
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVRBSS
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVRDEF
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTUSD
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTVUT
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTINFO	
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTHUNT
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LIMCExport
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceBackfeed
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	MSGSRVREXTSANT
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	LDHServiceSANT
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	LetterGen
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	UTLBusinessService
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	WorkflowService4
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	UnitracBusinessServiceMatchIn2
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	UnitracBusinessServiceCycle2
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCBatchEvaluationProcess
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCBatchSendProcess
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCImportProcess
Get-Service	 -ComputerName	UTSTAGE-ASR1	  -Name	UnitracBusinessServiceDist
Get-Service	 -ComputerName	UTSTAGE-ASR1	  -Name	UnitracBusinessServiceProc1
Get-Service	 -ComputerName	UTSTAGE-ASR2	  -Name	UnitracBusinessServiceProc2
Get-Service	 -ComputerName	UTSTAGE-ASR3	  -Name	UnitracBusinessServiceProc3
