Get-Service	 -ComputerName	Unitrac-APP01	 -Name	UnitracBusinessService
Get-Service	 -ComputerName	Unitrac-APP01	 -Name	FAXAssistService
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	ldhserviceUSD
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceCycle
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServicePRT
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceFax
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UniTracBusinessServiceMatchIn7
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	LDHServicePRCPA
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchInN 
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchIn9
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	UniTracBusinessServiceMatchIn10
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	ListenService
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	LDHSERV
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	WorkflowService
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	LDHServiceADHOC
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInL
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchOut
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceRPT
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn1
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	LDHServiceHUNT
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceBILL
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn17
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceFEE
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRBSS
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREDIIDR
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRDEF
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTUSD
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTPENF
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRADHOC
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTINFO
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTHUNT
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTGATE
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	UniTracBusinessServiceMatchIn8
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn5
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn4
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchDefault
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchWF
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	UniTracBusinessServiceMatchIn6
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	WorkflowService2
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	UniTracBusinessServiceMatchIn12
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	WorkflowService3
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn13
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn18
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCExport
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCOCR
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCExportSoftfile
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCBatchEvaluationProcess
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCBatchSendProcess
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCCleanupProcess
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCImportProcess
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	WorkflowService4
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInG
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInH
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInI
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceBackfeed
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	DirectoryWatcherServerIn
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	DirectoryWatcherServerOut
Get-Service  -ComputerName  Unitrac-WH14     -Name	UTLRematchMidSizeLenders
Get-Service	 -ComputerName	 Unitrac-WH15	 -Name	UnitracBusinessServiceMatchIn15
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceCycle3
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceMatchInF
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch2
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLRematchRepoPlus
Get-Service	 -ComputerName	 Unitrac-WH17	 -Name	UnitracBusinessServiceMatchInJ
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	UnitracBusinessServiceMatchIn14
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	LetterGen
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	MSGSRVREXTSANT
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	LDHServiceSANT
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	WorkflowService5
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT2
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceMatchInK
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	MSGSRVREXTWellsFargo
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	LDHWellsFargo
Get-Service	 -ComputerName	utprod-asr1.colo.as.local	 -Name	UnitracBusinessServiceDist
Get-Service	 -ComputerName	utprod-asr2.colo.as.local  -Name	UnitracBusinessServiceProc1
Get-Service	 -ComputerName	utprod-asr3.colo.as.local -Name	UnitracBusinessServiceProc2
Get-Service	 -ComputerName	utprod-asr4.colo.as.local	 -Name	UnitracBusinessServiceProc4
Get-Service	 -ComputerName	utprod-asr5.colo.as.local	 -Name	UnitracBusinessServiceProc5
Get-Service	 -ComputerName	utprod-asr6.colo.as.local -Name	UnitracBusinessServiceProc6
Get-Service	 -ComputerName	utprod-asr7.colo.as.local -Name	UnitracBusinessServiceProc7
Get-Service	 -ComputerName	UTPROD-UTLAPP-1.colo.as.local -Name	UTLBusinessService 