Get-Service	 -ComputerName	Unitrac-APP01	 -Name	UnitracBusinessService |  Restart-Service
Get-Service	 -ComputerName	Unitrac-APP01	 -Name	FAXAssistService |  Restart-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	ldhserviceUSD |  Restart-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceCycle |  Restart-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServicePRT |  Restart-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceFax |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	LDHServicePRCPA |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	LDHSERV |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	WorkflowService |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	LDHServiceADHOC |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchOut |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceRPT |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	LDHServiceHUNT |  Restart-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceFEE |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRBSS |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREDIIDR |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRDEF |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTUSD |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTPENF |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRADHOC |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTINFO |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTHUNT |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTGATE |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH22  -Name	UTLRematchDefault |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH22  -Name	UTLRematchRepoPlus |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH22     -Name	UTLRematchMidSizeLenders |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH22  -Name	UTLRematchAdhoc |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	WorkflowService2 |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	WorkflowService3 |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCExportSoftfile |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCOCR |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name LIMCExport |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCBatchEvaluationProcess |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCBatchSendProcess |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCCleanupProcess |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH12  -Name	QCImportProcess |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	WorkflowService4 |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceBackfeed |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	DirectoryWatcherServerIn |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	DirectoryWatcherServerOut |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH23  -Name	UTLRematchDefaultWellsFargo |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH23  -Name	UTLRematchDefaultSantander |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch |  Restart-Service
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch2 |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	LetterGen |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	MSGSRVREXTSANT |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	LDHServiceSANT |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	WorkflowService5 |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT2 |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	MSGSRVREXTWellsFargo |  Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	LDHWellsFargo |  Restart-Service
Get-Service	 -ComputerName	utprod-asr1.colo.as.local	 -Name	UnitracBusinessServiceDist |  Restart-Service
Get-Service	 -ComputerName	utprod-asr2.colo.as.local  -Name	UnitracBusinessServiceProc1 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr3.colo.as.local -Name	UnitracBusinessServiceProc2 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr4.colo.as.local	 -Name	UnitracBusinessServiceProc4 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr5.colo.as.local	 -Name	UnitracBusinessServiceProc5 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr6.colo.as.local -Name	UnitracBusinessServiceProc6 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr7.colo.as.local -Name	UnitracBusinessServiceProc7 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr8.colo.as.local -Name	UnitracBusinessServiceProc8 |  Restart-Service
Get-Service	 -ComputerName	utprod-asr9.colo.as.local -Name	UnitracBusinessServiceProc9|  Restart-Service
Get-Service	 -ComputerName	utprod-asr10.colo.as.local -Name	UnitracBusinessServiceProc10 |  Restart-Service
Get-Service	 -ComputerName	UTPROD-UTLAPP-1.colo.as.local -Name	UTLBusinessService  |  Restart-Service 



