Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	DirectoryWatcherServerIn	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	DirectoryWatcherServerOut	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LDHServ	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LDHServiceVUT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessService	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	ldhserviceUSD	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceCycle	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServicePRT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceMatchIn	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceMatchOut	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceRPT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService2	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	WorkflowService3	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREDIIDR	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVRBSS	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVRDEF	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTUSD	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTVUT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTINFO	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	MSGSRVREXTHUNT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	LIMCExport |Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP1	  -Name	UnitracBusinessServiceBackfeed	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	MSGSRVREXTSANT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	LDHServiceSANT	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	LetterGen	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP3	  -Name	UTLBusinessService |Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	WorkflowService4	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	UnitracBusinessServiceMatchIn2	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	UnitracBusinessServiceCycle2	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCBatchEvaluationProcess |Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCBatchSendProcess |Start-Service
Get-Service	 -ComputerName	UTSTAGE-APP4	  -Name	QCImportProcess |Start-Service
Get-Service	 -ComputerName	UTSTAGE-ASR1	  -Name	UnitracBusinessServiceDist	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-ASR1	  -Name	UnitracBusinessServiceProc1	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-ASR2	  -Name	UnitracBusinessServiceProc2	|Start-Service
Get-Service	 -ComputerName	UTSTAGE-ASR3	  -Name	UnitracBusinessServiceProc3	|Start-Service