Get-Service	 -ComputerName	Unitrac-APP01	 -Name	UnitracBusinessService	|Start-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	ldhserviceUSD	|Start-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceCycle	|Start-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServicePRT	|Start-Service
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UniTracBusinessServiceMatchIn7	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	UniTracBusinessServiceMatchIn11	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	LDHServicePRCPA	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchIn9	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	UniTracBusinessServiceMatchIn10	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	LDHSERV	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	LDHServiceADHOC	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInL	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInM	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInA	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInB	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInC	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInD	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInE	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchOut	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceMatchIn2	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceRPT	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn1	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	LDHServiceHUNT	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceBILL	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn17	|Start-Service
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceFEE	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRBSS	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREDIIDR	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	UniTracBusinessServiceMatchIn8	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRDEF	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTUSD	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTPENF	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRADHOC	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTINFO	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTHUNT	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTGATE	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn5	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn4	|Start-Service
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchDefault |Start-Service
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	UniTracBusinessServiceMatchIn6	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	UniTracBusinessServiceMatchIn12	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn13	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInG	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInH	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInI	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceBackfeed	|Start-Service
Get-Service  -ComputerName  Unitrac-WH14     -Name	UTLRematchMidSizeLenders |Start-Service
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	UnitracBusinessServiceMatchIn16	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH15	 -Name	UnitracBusinessServiceMatchIn15	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceCycle3	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceMatchInF	|Start-Service
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch |Start-Service
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLRematchRepoPlus |Start-Service
Get-Service	 -ComputerName	 Unitrac-WH17	 -Name	UnitracBusinessServiceMatchInJ	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	UnitracBusinessServiceMatchIn14	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	LetterGen	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	MSGSRVREXTSANT	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	LDHServiceSANT	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT2	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceMatchInK	|Start-Service
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	MSGSRVREXTWellsFargo |Start-Service
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	LDHWellsFargo |Start-Service
Get-Service	 -ComputerName	utprod-asr1.colo.as.local	 -Name	UnitracBusinessServiceDist |Start-Service
Get-Service	 -ComputerName	utprod-asr2.colo.as.local  -Name	UnitracBusinessServiceProc1 |Start-Service
Get-Service	 -ComputerName	utprod-asr3.colo.as.local -Name	UnitracBusinessServiceProc2 |Start-Service
Get-Service	 -ComputerName	utprod-asr4.colo.as.local	 -Name	UnitracBusinessServiceProc4 |Start-Service
Get-Service	 -ComputerName	utprod-asr5.colo.as.local	 -Name	UnitracBusinessServiceProc5 |Start-Service
Get-Service	 -ComputerName	utprod-asr6.colo.as.local -Name	UnitracBusinessServiceProc6 |Start-Service
Get-Service	 -ComputerName	utprod-asr7.colo.as.local -Name	UnitracBusinessServiceProc7 |Start-Service