Get-Service	 -ComputerName	Unitrac-APP01	 -Name	UnitracBusinessService	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	ldhserviceUSD	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceCycle	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServicePRT	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UniTracBusinessServiceMatchIn7	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	UniTracBusinessServiceMatchIn11	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	LDHServicePRCPA	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchIn9	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	UniTracBusinessServiceMatchIn10	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	LDHSERV	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	LDHServiceADHOC	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInL	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInM	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInA	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInB	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInC	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInD	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInE	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchOut	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceMatchIn2	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceRPT	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn1	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	LDHServiceHUNT	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceBILL	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn17	|Stop-Service -Force
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceFEE	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRBSS	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREDIIDR	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	UniTracBusinessServiceMatchIn8	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRDEF	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTUSD	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTPENF	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRADHOC	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTINFO	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTHUNT	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTGATE	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn5	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn4	|Stop-Service -Force
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchDefault |Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	UniTracBusinessServiceMatchIn6	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	UniTracBusinessServiceMatchIn12	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn13	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInG	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInH	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInI	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceBackfeed	|Stop-Service -Force
Get-Service  -ComputerName  Unitrac-WH14     -Name	UTLRematchMidSizeLenders |Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	UnitracBusinessServiceMatchIn16	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH15	 -Name	UnitracBusinessServiceMatchIn15	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceCycle3	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceMatchInF	|Stop-Service -Force
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch |Stop-Service -Force
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLRematchRepoPlus |Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH17	 -Name	UnitracBusinessServiceMatchInJ	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	UnitracBusinessServiceMatchIn14	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	LetterGen	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	MSGSRVREXTSANT	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH19	 -Name	LDHServiceSANT	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT2	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceMatchInK	|Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	MSGSRVREXTWellsFargo |Stop-Service -Force
Get-Service	 -ComputerName	 Unitrac-WH21	 -Name	LDHWellsFargo |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr1.colo.as.local	 -Name	UnitracBusinessServiceDist |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr2.colo.as.local  -Name	UnitracBusinessServiceProc1 |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr3.colo.as.local -Name	UnitracBusinessServiceProc2 |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr4.colo.as.local	 -Name	UnitracBusinessServiceProc4 |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr5.colo.as.local	 -Name	UnitracBusinessServiceProc5 |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr6.colo.as.local -Name	UnitracBusinessServiceProc6 |Stop-Service -Force
Get-Service	 -ComputerName	utprod-asr7.colo.as.local -Name	UnitracBusinessServiceProc7 |Stop-Service -Force