Get-Service	 -ComputerName	Unitrac-APP01	 -Name	UnitracBusinessService	
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServiceCycle	
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UnitracBusinessServicePRT	
Get-Service	 -ComputerName	Unitrac-APP02	 -Name	UniTracBusinessServiceMatchIn7	
Get-Service	 -ComputerName	Unitrac-WH01	 -Name	UniTracBusinessServiceMatchIn11	
Get-Service	 -ComputerName	Unitrac-WH02	 -Name	UniTracBusinessServiceMatchIn9	
Get-Service	 -ComputerName	Unitrac-WH03	 -Name	UniTracBusinessServiceMatchIn10	
Get-Service	 -ComputerName	Unitrac-WH04	 -Name	UnitracBusinessServiceMatchInL	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInA	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInB	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInC	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInD	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchInE	
Get-Service	 -ComputerName	Unitrac-WH05	 -Name	UnitracBusinessServiceMatchOut	
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceMatchIn2	
Get-Service	 -ComputerName	Unitrac-WH06	 -Name	UnitracBusinessServiceRPT	
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn1	
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceBILL	
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceMatchIn17	
Get-Service	 -ComputerName	Unitrac-WH07	 -Name	UnitracBusinessServiceFEE	
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	UniTracBusinessServiceMatchIn8	
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn5	
Get-Service	 -ComputerName	 Unitrac-WH09	 -Name	UniTracBusinessServiceMatchIn4	
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchDefault 
Get-Service  -ComputerName  Unitrac-WH09  -Name	UTLRematchWF 
Get-Service	 -ComputerName	 Unitrac-WH10	 -Name	UniTracBusinessServiceMatchIn6	
Get-Service	 -ComputerName	 Unitrac-WH11	 -Name	UniTracBusinessServiceMatchIn12	
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn13	
Get-Service	 -ComputerName	 Unitrac-WH12	 -Name	UniTracBusinessServiceMatchIn18	
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInG	
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInH	
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceMatchInI	
Get-Service	 -ComputerName	 Unitrac-WH13	 -Name	UnitracBusinessServiceBackfeed	
Get-Service  -ComputerName  Unitrac-WH14     -Name	UTLRematchMidSizeLenders 
Get-Service	 -ComputerName	 Unitrac-WH14	 -Name	UnitracBusinessServiceMatchIn16	
Get-Service	 -ComputerName	 Unitrac-WH15	 -Name	UnitracBusinessServiceMatchIn15	
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceCycle3	
Get-Service	 -ComputerName	 Unitrac-WH16	 -Name	UnitracBusinessServiceMatchInF	
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch 
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLMatch2 
Get-Service  -ComputerName  Unitrac-WH16  -Name	UTLRematchRepoPlus 
Get-Service	 -ComputerName	 Unitrac-WH17	 -Name	UnitracBusinessServiceMatchInJ	
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	UnitracBusinessServiceMatchIn14	
Get-Service	 -ComputerName	 Unitrac-WH18	 -Name	LetterGen	
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT	
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceCycleSANT2	
Get-Service	 -ComputerName	 Unitrac-WH20	 -Name	UnitracBusinessServiceMatchInK	
Get-Service	 -ComputerName	utprod-asr1.colo.as.local	 -Name	UnitracBusinessServiceDist 
Get-Service	 -ComputerName	utprod-asr2.colo.as.local  -Name	UnitracBusinessServiceProc1 
Get-Service	 -ComputerName	utprod-asr3.colo.as.local -Name	UnitracBusinessServiceProc2 
Get-Service	 -ComputerName	utprod-asr4.colo.as.local	 -Name	UnitracBusinessServiceProc4 
Get-Service	 -ComputerName	utprod-asr5.colo.as.local	 -Name	UnitracBusinessServiceProc5 
Get-Service	 -ComputerName	utprod-asr6.colo.as.local -Name	UnitracBusinessServiceProc6 
Get-Service	 -ComputerName	utprod-asr7.colo.as.local -Name	UnitracBusinessServiceProc7 