USE UniTrac


SELECT PLI.RELATE_ID AS VERIFICATION_EVENT_WI ,
     *
FROM   PROCESS_LOG_ITEM PLI
       JOIN WORK_ITEM_PROCESS_LOG_ITEM_RELATE WIP ON WIP.PROCESS_LOG_ITEM_ID = PLI.ID
                                                     AND WIP.PURGE_DT IS NULL
       JOIN WORK_ITEM WI ON WI.ID = WIP.WORK_ITEM_ID
                            AND WI.WORKFLOW_DEFINITION_ID = 9
	   JOIN NOTICE N on N.ID = PLI.RELATE_ID and PLI.RELATE_TYPE_CD = 'Allied.UniTrac.Notice' and N.TYPE_CD = 'PN'
WHERE  PLI.PURGE_DT IS NULL
       AND WI.ID = XXXXXXXX;     /* CYLE WORK ITEM */


	 