Get-Service -ComputerName	UTSTAGE-APP4	  -Name	DirectoryWatcherIn |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	DirectoryWatcherOut |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	LDHService	|Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	LDHServiceHUNT	|Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	LDHServicePRCPA	|Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	ldhserviceUSD |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	WorkflowService |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	WorkflowService2 |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	WorkflowService3 |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	WorkflowService4 |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	WorkflowService5 |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	LIMCExport |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	LIMCOCR |Start-Service
Get-Service -ComputerName	UT-STGAPP-02	  -Name	OCRLookup |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessService |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessServiceBackfeed |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessServiceCycle |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessServiceMatchOut |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessServicePRT |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3      -Name	UnitracBusinessServiceRPT |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	UTLBusinessService |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	UTLMatch |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	UTLRematch |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	LetterGen |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	QCBatchEvaluationProcess |Start-Service 
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	QCBatchSendProcess |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	QCImportProcess |Start-Service
Get-Service -ComputerName	UTSTAGE-APP3	  -Name	QCCleanupProcess |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVRBSS |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREDIIDR |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTDEF |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTHUNT |Start-Service 
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTINFO |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTPENF |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTSANT	 |Start-Service
Get-Service -ComputerName	UTSTAGE-APP4	  -Name	MSGSRVREXTUSD |Start-Service
Get-Service -ComputerName  UTSTAGE-ASR1  -Name	UnitracBusinessServiceDist |Start-Service 
Get-Service -ComputerName  UTSTAGE-ASR1  -Name	UnitracBusinessServiceProc1 |Start-Service 
Get-Service -ComputerName  UTSTAGE-ASR2  -Name	UnitracBusinessServiceProc2 |Start-Service 
Get-Service -ComputerName  UTSTAGE-ASR3  -Name	UnitracBusinessServiceProc3 |Start-Service 

