SELECT * 
INTO #TMPPLCY
FROM UnitracHDStorage.dbo.tmpTask36802_PLCY_01
---- 10

SELECT * 
INTO #TMPPLCY_01
FROM #TMPPLCY
WHERE EXCLUDE = 0 
---- 10


UPDATE RC SET GOOD_THRU_DT = NULL , 
EXPOSURE_DT = NULL ,
UPDATE_DT = GETDATE() , 
UPDATE_USER_TX = 'TASK36802' , 
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT RC.GOOD_THRU_DT , RC.EXPOSURE_DT ,   *
FROM REQUIRED_COVERAGE RC JOIN #TMPPLCY_01 T1 ON T1.RC_ID = RC.ID
WHERE EXCLUDE = 0 
----10