USE UniTrac

SELECT * FROM dbo.USERS
WHERE GIVEN_NAME_TX LIKE '%UnitracBusinessServiceProc%'


insert into users 
(USER_NAME_TX, PASSWORD_TX, FAMILY_NAME_TX, GIVEN_NAME_TX, ACTIVE_IN, EMAIL_TX, EXTERN_MAINT_IN, LOGIN_COUNT_NO, LAST_LOGIN_DT, CREATE_DT, UPDATE_DT, PURGE_DT, UPDATE_USER_TX, LOCK_ID, DEFAULT_AGENCY_ID, SYSTEM_IN)
select 'UBSProc10', PASSWORD_TX, 'Server', 'UnitracBusinessServiceProc10', ACTIVE_IN, EMAIL_TX, EXTERN_MAINT_IN, NULL, LAST_LOGIN_DT, GETDATE(), GETDATE(), PURGE_DT, UPDATE_USER_TX, LOCK_ID, DEFAULT_AGENCY_ID, SYSTEM_IN 
from Users
where id in (3870)



select * from process_log
where SERVICE_NAME_TX = 'UnitracBusinessServiceProc10'