
USE ROLE OWNER_EDW_PROD;
USE WAREHOUSE EDW_PROD_INFA_WH;
USE DATABASE EDW_PROD;
USE SCHEMA STG;

DESC TABLE EDW_TEST.STG.STG_UT_OWNER_POLICY_H;

ALTER TABLE EDW_PROD.STG.STG_UT_OWNER_POLICY_H ADD SPECIAL_HANDLING_XML VARIANT;

ALTER TABLE EDW_PROD.STG.STG_UT_OWNER_POLICY_H ADD SRC_UPDATE_USER_TX VARCHAR(30);