
--Full
BACKUP DATABASE [IQQ_TRAINING] TO
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING1.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING2.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING3.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING4.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING5.Bak'
WITH INIT , NOUNLOAD , NAME = 'IQQ_Backup', NOSKIP , STATS = 10, COMPRESSION, NOFORMAT



------Differentials 
BACKUP DATABASE [IQQ_TRAINING]
TO DISK =  '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING1.DIF'
WITH DIFFERENTIAL, NOFORMAT, NOINIT,
SKIP, NOREWIND, NOUNLOAD, COMPRESSION, STATS = 25


--Logs
BACKUP LOG [IQQ_TRAINING]
TO DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING.LOG'