

---Fulls
  RESTORE DATABASE [IQQ_TRAINING]
  FROM  DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING1.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING2.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING3.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING4.Bak',
DISK = '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING5.Bak' --WITH  FILE = 1,  NOUNLOAD,  STATS = 5
WITH  FILE = 1, NORECOVERY,  NOUNLOAD,  STATS = 5
  GO

  ESTORE DATABASE @dbname FROM DISK = @backupfile WITH FILE = 1, NORECOVERY, NOUNLOAD;
RESTORE LOG @dbname FROM DISK = @backupfile WITH FILE = 2, NORECOVERY, NOUNLOAD;


-----Differentials 
RESTORE DATABASE IQQ_TRAINING 
FROM DISK =  '\\IGNITE-SQL14\i$\Restores\CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING1.DIF'
WITH  FILE = 2, NORECOVERY,  NOUNLOAD,  STATS = 5
GO


---LOGS

RESTORE LOG [IQQ_TRAINING] FROM DISK =  '\\IGNITE-SQL14\i$\Restores \CP-SQLQA-02\IQQ_TRAINING\IQQ_TRAINING.LOG' WITH FILE = 2, NORECOVERY,NOUNLOAD;