USE OspreyDashboard





--4) Insert Lender Information into DATASOURCE_CACHE_LOOKUP on UTPROD-SUB-01 (OspreyDashboard Database)
INSERT INTO DATASOURCE_CACHE_LOOKUP (LOOKUP_KEY_CD,LOOKUP_VALUE,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID)
VALUES ('LENDER_CODE','XXX',GETDATE(),GETDATE(),'Script',1)




