--SELECT DISTINCT STATUS_CD 
--FROM UniTrac..OUTPUT_BATCH 


SELECT COUNT(*) [Complete]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'Comp'

SELECT COUNT(*) [Empty]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'Empty'

SELECT COUNT(*) [Error]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'ERR'

SELECT COUNT(*) [FC]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'FC'


SELECT COUNT(*) [Null]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'Null'

SELECT COUNT(*) [Pending]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'Pend'

SELECT COUNT(*) [Test]
FROM UniTrac..OUTPUT_BATCH 
WHERE STATUS_CD = 'Test'



--SELECT DISTINCT STATUS_CD  last day
--FROM UniTrac..OUTPUT_BATCH 
SELECT COUNT(*) [Complete]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'COMP'

SELECT COUNT(*) [Empty]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'Empty'

SELECT COUNT(*) [Error]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'ERR'

SELECT COUNT(*) [FC]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'FC'


SELECT COUNT(*) [Null]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'NULL'

SELECT COUNT(*) [Pending]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'PEND'

SELECT COUNT(*) [Test]
FROM UniTrac..OUTPUT_BATCH 
WHERE UPDATE_DT >= '2015-07-24' AND STATUS_CD = 'Test'



 