SELECT *
FROM LENDER
WHERE ID = 904

SELECT *
FROM ADDRESS
WHERE ID IN (12070,12071)

SELECT *
FROM LENDER 
WHERE CODE_tX = '5600'


SELECT *
FROM LENDER
WHERE NAME_TX = 'Lampco Federal Credit Union' 

select TOP 10 *
from LOAN
WHERE LENDER_ID = 1000 AND RECORD_TYPE_CD = 'G' AND CREATE_DT >= '2015-04-01' AND STATUS_CD = 'A'
ORDER BY BALANCE_AMOUNT_NO DESC

SELECT TOP 10 *
FROM SEARCH_FULLTEXT

SELECT *
FROM OUTPUT_DEVICE
WHERE LOCATION_TX NOT LIKE 'Carmel %' AND DEVICE_DRIVER_TX IS NOT NULL AND DEVICE_DRIVER_TX NOT LIKE 'Sharp %'
ORDER BY LOCATION_TX ASC

SELECT *
FROM OUTPUT_DEVICE
WHERE DEVICE_DRIVER_TX LIKE 'Sharp %' AND LOCATION_TX LIKE 'Carmel %' AND LOCATION_TX NOT LIKE 'Carmel % Test'



SELECT * 
FROM WORK_ITEM 
WHERE RELATE_ID = 23400728


SELECT DC.*
FROM LOAN L 
inner join NOTICE N on L.ID = n.LOAN_ID
left outer join document_container dc on dc.relate_id = n.id and dc.relate_class_name_tx = 'allied.unitrac.notice' AND DC.PURGE_DT IS NULL	
WHERE L.NUMBER_TX = '7410813' 

SELECT *
FROM LOAN L 
inner join FORCE_PLACED_CERTIFICATE FPC on L.ID = FPC.LOAN_ID
left outer join document_container dc on dc.relate_id = FPC.id and dc.relate_class_name_tx = 'allied.unitrac.forceplacedcertificate' AND DC.PURGE_DT IS NULL
WHERE L.NUMBER_TX = '039-007806' AND L.LENDER_ID = 2216


SELECT *
FROM dbo.LOAN
WHERE NUMBER_TX = '7410813'





select *
from LOAN
INNER JOIN COLLATERAL ON LOAN.ID = COLLATERAL.LOAN_ID
INNER JOIN PROPERTY ON COLLATERAL.PROPERTY_ID = PROPERTY.ID
INNER JOIN REQUIRED_COVERAGE ON PROPERTY.ID = REQUIRED_COVERAGE.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE ON LOAN.ID = OWNER_LOAN_RELATE.LOAN_ID
INNER JOIN OWNER ON OWNER_LOAN_RELATE.OWNER_ID = OWNER.ID
INNER JOIN OWNER_ADDRESS ON OWNER.ADDRESS_ID = OWNER_ADDRESS.ID
WHERE LOAN.NUMBER_TX = '7410813' AND LOAN.LENDER_ID = 1000

SELECT TOP 10 *
FROM INTERACTION_HISTORY
WHERE PROPERTY_ID = 85507662 

--Get Versions
SELECT @@VERSION AS 'SQL Server Version'

SELECT @@VERSION AS 'SQL Server Version'

--Product Information
SELECT
SERVERPROPERTY('ProductVersion') AS ProductVersion,
SERVERPROPERTY('ProductLevel') AS ProductLevel,
SERVERPROPERTY('Edition') AS Edition,
SERVERPROPERTY('EngineEdition') AS EngineEdition;
GO
--ServerName
SELECT @@SERVERNAME [DB installed on]


select TOP 5 *
from LOAN
WHERE LENDER_ID = 1000 AND RECORD_TYPE_CD = 'G' AND CREATE_DT >= '2015-05-01'
ORDER BY BALANCE_AMOUNT_NO ASC



SELECT TOP 10 *
FROM dbo.LENDER

WHERE STATUS_CD = 'Active'


SELECT COUNT(*) FROM dbo.ESCROW

SELECT *
FROM dbo.LENDER
WHERE TAX_ID_TX = '450226664'

SELECT *
FROM ADDRESS
WHERE ID IN (10238,10239)

--Find out what SQL Logins
SELECT * FROM sys.server_principals
WHERE type LIKE 'S'
ORDER BY name ASC

--Find out logins 
SELECT * FROM sys.server_principals
ORDER BY name ASC

select *
from LOAN
INNER JOIN COLLATERAL ON LOAN.ID = COLLATERAL.LOAN_ID
INNER JOIN PROPERTY ON COLLATERAL.PROPERTY_ID = PROPERTY.ID
INNER JOIN REQUIRED_COVERAGE ON PROPERTY.ID = REQUIRED_COVERAGE.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE ON LOAN.ID = OWNER_LOAN_RELATE.LOAN_ID
INNER JOIN OWNER ON OWNER_LOAN_RELATE.OWNER_ID = OWNER.ID
INNER JOIN OWNER_ADDRESS ON OWNER.ADDRESS_ID = OWNER_ADDRESS.ID
WHERE LOAN.NUMBER_TX = '9100824' AND LOAN.LENDER_ID = 1000


--Work Item Search by Process			
SELECT * 
FROM WORK_ITEM 
WHERE RELATE_ID = 23400728

--Cross JOIN on Users, Users Security Group Relate, and User Login to get username, email, user ID, Security Group User ID, Security Group ID
SELECT USER_NAME_TX [Username], EMAIL_TX [Email], USER_ID, USER_SECURITY_GROUP_RELATE.ID [Security Group User ID], SEC_GRP_ID [Security Group ID], KEY_CD, SERIALIZED_OBJ
FROM USERS 
CROSS JOIN dbo.USER_SECURITY_GROUP_RELATE
CROSS JOIN User_Login 
WHERE USER_ID = '2059'	AND USER_NAME_TX = 'jrussell' AND USER_SYS_ID = '2059' 
ORDER BY SEC_GRP_ID ASC


SELECT *
FROM USER_LOGIN
WHERE USER_SYS_ID = '2059'

--CROSS JOIN on Lender and Address so that you can get the Name of the Lender, Code, Type CD, Status, Address
SELECT NAME_TX [Lender Name], CODE_TX, TYPE_CD, STATUS_CD, LINE_1_TX, CITY_TX, STATE_PROV_TX, POSTAL_CODE_TX
FROM LENDER 
CROSS JOIN dbo.ADDRESS 
WHERE CODE_tX = '5600' AND CITY_TX ='Anderson' AND STATE_PROV_TX = 'IN'AND LINE_1_TX = '5411 Dr. Mlk Jr. Blvd'



--CROSS JOIN on Lender and Address 
SELECT NAME_TX [Lender Name], ADDRESS.ID [Address ID], LENDER.ID [Lender ID], CODE_TX, TYPE_CD, STATUS_CD, LINE_1_TX, CITY_TX, STATE_PROV_TX, POSTAL_CODE_TX, PHONE_TX, PHONE_EXT_TX, SECONDARY_PHONE_TX, SECONDARY_PHONE_EXT_TX, FAX_TX
FROM LENDER 
CROSS JOIN dbo.ADDRESS 
WHERE ADDRESS.ID IN (12070,12071) AND LENDER.ID = '904'



--Notices by Cycle Process
SELECT DM.SERVER_SHARE_TX+'\'+RELATIVE_PATH_TX+'\'+CAST(DC.ID as varchar(20))+'.pdf',*
from PROCESS_LOG pl
inner join process_log_item pli on pli.PROCESS_LOG_ID = pl.id and pli.relate_type_cd = 'allied.unitrac.notice'
inner join NOTICE N on N.id = pli.relate_id 
left outer join document_container dc on dc.relate_id = N.id and dc.relate_class_name_tx = 'allied.unitrac.notice'
INNER JOIN DOCUMENT_MANAGEMENT DM ON DC.DOCUMENT_MANAGEMENT_ID = DM.ID
INNER JOIN PROCESS_DEFINITION PD ON pl.PROCESS_DEFINITION_ID = PD.ID
INNER JOIN LENDER L ON SETTINGS_XML_IM.value('(/ProcessDefinitionSettings/LenderList/LenderID)[1]' , 'varchar(20)') = L.ID
WHERE PROCESS_TYPE_CD = 'CYCLEPRC' AND PD.ACTIVE_IN = 'Y' AND L.CODE_TX = '5600' AND PL.START_DT >= '2015-06-10'




SELECT DISTINCT execution_freq_cd 
FROM UniTrac..PROCESS_DEFINITION

SELECT * 
FROM UniTrac..PROCESS_DEFINITION
WHERE STATUS_CD = 'Error'


SELECT DISTINCT STATUS_CD
FROM UniTrac..PROCESS_DEFINITION


SELECT * 
FROM UniTrac..PROCESS_DEFINITION
WHERE ID = 904


SELECT DISTINCT UPDATE_USER_TX
FROM UniTrac..PROCESS_DEFINITION


SELECT *
FROM LENDER 
WHERE CODE_tX = '5600'


SELECT DISTINCT STATUS_CD
FROM dbo.LENDER
