USE UniTrac


SELECT DISTINCT TP.EXTERNAL_ID_TX  [Lender Code] ,
       tp.NAME_TX [Lender Name] ,
	   LO.NAME_TX [Division],
        PD.TYPE_CD [Pre-Processing Details],
        CU.TO_VALUE_TX [Enable First Line Of Insurance],
		 C.CREATE_DT [Enable First Line Of Insurance Added],
		RD.VALUE_TX [Import Configurations]
		FROM    dbo.PREPROCESSING_DETAIL PD
        INNER JOIN dbo.PPDATTRIBUTE PPD ON PPD.PREPROCESSING_DETAIL_ID = PD.ID 
        INNER JOIN dbo.DELIVERY_INFO_GROUP D ON D.ID = PD.DELIVERY_INFO_GROUP_ID AND PD.TYPE_CD = 'Informatica'
        INNER JOIN dbo.DELIVERY_INFO DD ON DD.ID = D.DELIVERY_INFO_ID
        INNER JOIN dbo.TRADING_PARTNER TP ON TP.ID = DD.TRADING_PARTNER_ID
        INNER JOIN dbo.DELIVERY_INFO_DELIVER_TO_TP_RELATE DT ON DT.DELIVERY_INFO_ID = DD.ID
		INNER JOIN dbo.DELIVERY_INFO_EXTRACT_CONFIG_RELATE DIE ON DIE.DELIVERY_INFO_ID = DD.ID
		INNER JOIN dbo.CHANGE C ON C.ENTITY_ID = DD.ID 
		INNER JOIN dbo.CHANGE_UPDATE CU ON C.ID = CU.CHANGE_ID AND Cu.QUALIFIER_TX like '%Enable 1st Line of Insurance Processing%'
		INNER JOIN dbo.LENDER LL ON LL.CODE_TX = TP.EXTERNAL_ID_TX
		INNER JOIN dbo.LENDER_ORGANIZATION LO ON LO.LENDER_ID = LL.ID
		INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID 
		WHERE   CU.TO_VALUE_TX   IN ('Y') AND RD.VALUE_TX = 'IMPORT'  AND LO.TYPE_CD = 'DIV'
	
		


--SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
--FROM LENDER L
--INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
--INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID AND LO.TYPE_CD = 'DIV'
--WHERE L.CODE_TX = '1588' 

