USE UniTrac


SELECT  DISTINCT 
LL.CODE_TX [Lender Code] ,
LL.NAME_TX [Lender Name] ,
  LO.NAME_TX [Division],
      PD.TYPE_CD [Pre-Processing Details],
        CU.TO_VALUE_TX [Enable First Line Of Insurance], C.CREATE_DT [Enable First Line Of Insurance Added],
		RD.VALUE_TX [Import Configurations]
			FROM    dbo.PREPROCESSING_DETAIL PD
        INNER JOIN dbo.PPDATTRIBUTE PPD ON PPD.PREPROCESSING_DETAIL_ID = PD.ID --AND PPD.VALUE_TX = 'INFORMATICA'
        INNER JOIN dbo.DELIVERY_INFO_GROUP D ON D.ID = PD.DELIVERY_INFO_GROUP_ID --AND PD.TYPE_CD = 'Informatica'
        INNER JOIN dbo.DELIVERY_INFO DI ON DI.ID = D.DELIVERY_INFO_ID
        INNER JOIN dbo.TRADING_PARTNER TP ON TP.ID = Di.TRADING_PARTNER_ID
        INNER JOIN dbo.DELIVERY_INFO_DELIVER_TO_TP_RELATE DT ON DT.DELIVERY_INFO_ID = DI.ID
		INNER JOIN dbo.DELIVERY_INFO_EXTRACT_CONFIG_RELATE DIE ON DIE.DELIVERY_INFO_ID = DI.ID
		INNER JOIN dbo.CHANGE C ON C.ENTITY_ID = DI.ID --AND C.ENTITY_NAME_TX = 'LDHLib.DeliveryInfo'
		INNER JOIN dbo.CHANGE_UPDATE CU ON C.ID = CU.CHANGE_ID AND Cu.QUALIFIER_TX like '%Enable 1st Line of Insurance Processing%'AND CU.QUALIFIER_TX NOT LIKE '%Escrow%'
		INNER JOIN dbo.LENDER LL ON LL.CODE_TX = TP.EXTERNAL_ID_TX
		INNER JOIN dbo.LENDER_ORGANIZATION LO ON LO.LENDER_ID = LL.ID AND LO.TYPE_CD = 'DIV' 
		LEFT JOIN RELATED_DATA RD ON DI.ID = RD.RELATE_ID AND RD.DEF_ID = '96'
		WHERE   lo.PURGE_DT IS NULL AND CU.TO_VALUE_TX = 'Y' AND PD.PURGE_DT IS NULL --AND  LL.CODE_TX  IN  ( '7350') 
		ORDER BY PD.TYPE_CD DESC

		





