
IF EXISTS (SELECT ServerLocation FROM DBA.info.Instance WHERE ServerLocation = 'ON-PREM')
BEGIN 
PRINT 'DO SOMETHING: THIS IS A ON-PREM INSTANCE AND USE DDBOOST'

END 
ELSE IF EXISTS (SELECT ServerLocation FROM DBA.info.Instance WHERE ServerLocation = 'AWS-RDS')

BEGIN 
PRINT 'DO NOTHING: THIS IS A AWS-RDS INSTANCE'
END 

ELSE IF EXISTS (SELECT ServerLocation FROM DBA.info.Instance WHERE ServerLocation = 'MS-AZURE')

BEGIN 

PRINT 'DO NOTHING: THIS IS A MS-AZURE INSTANCE' 
END 

ELSE IF EXISTS (SELECT ServerLocation FROM DBA.info.Instance WHERE ServerLocation = 'AWS-EC2')

BEGIN 
PRINT 'DO SOMETHING: THIS IS A AWS-EC2 INSTANCE'
END 

ELSE

BEGIN

PRINT 'ERROR: CHECK THE DBA.INFO.INSTANCE TABLE'

END