Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRBSS |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREDIIDR  |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRDEF |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTUSD |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTPENF |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVRADHOC |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTINFO  |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTHUNT |Restart-Service
Get-Service	 -ComputerName	 Unitrac-WH08	 -Name	MSGSRVREXTGATE |Restart-Service