
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 10000
show WAREHOUSES like 'BOND_DEV_INFA_WH'
show WAREHOUSES
show terse DATABASES limit 10000
USE SECONDARY ROLES NONE
show WAREHOUSES like 'BOND_DEV_INFA_WH'
SELECT SYSTEM$DISABLE_DATABASE_REPLICATION('BOND_DEV');
show WAREHOUSES
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 10000
show terse DATABASES limit 10000
show WAREHOUSES like 'BOND_DEV_INFA_WH'
show TASKS like 'BOND_DEV_REFRESH_TASK' in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse VIEWS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse TASKS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse TABLES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse SEQUENCES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse STREAMS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse USER PROCEDURES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse PIPES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse USER FUNCTIONS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse STAGES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse FILE FORMATS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show SCHEMAS like 'PUBLIC' in DATABASE IDENTIFIER('"BOND_DEV"')
show SCHEMAS like 'INFORMATION_SCHEMA' in DATABASE IDENTIFIER('"BOND_DEV"')
show SCHEMAS like 'LND' in DATABASE IDENTIFIER('"BOND_DEV"')
show DATABASES like 'BOND_PROD'
show SCHEMAS like 'BOND' in DATABASE IDENTIFIER('"BOND_DEV"')
show DATABASES like 'BOND_DEV'
show WAREHOUSES like 'BOND_DEV_INFA_WH'
CREATE TASK BOND_DEV_Refresh_Task   WAREHOUSE = BOND_DEV_INFA_WH   SCHEDULE = '1440 MINUTE'   USER_TASK_TIMEOUT_MS = 14400000 AS   ALTER DATABASE BOND_DEV REFRESH;
show WAREHOUSES like 'BOND_DEV_INFA_WH'
show WAREHOUSES
show grants on WAREHOUSE IDENTIFIER('"BOND_DEV_INFA_WH"')
USE WAREHOUSE IDENTIFIER('"BOND_DEV_INFA_WH"')
show WAREHOUSES
USE SCHEMA IDENTIFIER('"PUBLIC"')