QUERY_TEXT
show WAREHOUSES like 'COMPUTE_WH'
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 10000
show WAREHOUSES
show terse DATABASES limit 1001
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 1001
show terse STREAMS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse USER PROCEDURES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse VIEWS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show WAREHOUSES
show terse TASKS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse PIPES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse SEQUENCES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse USER FUNCTIONS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse STAGES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse FILE FORMATS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse DATABASES limit 10000
show terse TABLES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 1001
show terse VIEWS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse STREAMS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse PIPES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse USER PROCEDURES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse DATABASES limit 1001
show terse TABLES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse STAGES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse USER FUNCTIONS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse SEQUENCES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse TASKS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse FILE FORMATS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
ALTER DATABASE BOND_DEV REFRESH;
show SCHEMAS like 'BOND' in DATABASE IDENTIFIER('"BOND_DEV"')
show DATABASES like 'EDW_DEV'
show terse TABLES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse STAGES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse SEQUENCES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse VIEWS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse USER FUNCTIONS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse TASKS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse FILE FORMATS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse USER PROCEDURES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show terse STREAMS in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 1001
show terse PIPES in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"')
show SCHEMAS like 'INFORMATION_SCHEMA' in DATABASE IDENTIFIER('"BOND_DEV"')
show SCHEMAS like 'STG' in DATABASE IDENTIFIER('"BOND_DEV"')
show SCHEMAS like 'PUBLIC' in DATABASE IDENTIFIER('"BOND_DEV"')
show SCHEMAS like 'LND' in DATABASE IDENTIFIER('"BOND_DEV"')
show DATABASES like 'BOND_DEV'
show WAREHOUSES like 'COMPUTE_WH'
show WAREHOUSES like 'COMPUTE_WH'
select * from table(information_schema.database_refresh_progress('BOND_DEV'));
USE SCHEMA IDENTIFIER('"PUBLIC"')
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 10000
show WAREHOUSES
show DATABASES like 'POWERBIACTIVITY_DEV'
show DATABASES like 'SNOWFLAKE'
show DATABASES like 'BOND_DEV'
alter DATABASE IDENTIFIER('"BOND_DEV"') refresh
DROP DATABASE BOND_DEV;
USE SCHEMA IDENTIFIER('"PUBLIC"')
USE DATABASE IDENTIFIER('"BOND_DEV"')
USE SCHEMA IDENTIFIER('"PUBLIC"')
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 10000
USE DATABASE IDENTIFIER('"EDW_DEV"')
show WAREHOUSES like 'COMPUTE_WH'
create DATABASE IDENTIFIER('"BOND_DEV"') AS REPLICA OF IDENTIFIER('"ALLIED"."SS53963"."BOND_DEV"')
show terse ROLES
ALTER DATABASE BOND_DEV REFRESH;
SELECT SYSTEM$DISABLE_DATABASE_REPLICATION('BOND_DEV');
show WAREHOUSES like 'COMPUTE_WH'
show WAREHOUSES like 'COMPUTE_WH'
show WAREHOUSES
show terse DATABASES limit 10000
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 10000
CREATE TASK BOND_DEV_Refresh_Task   WAREHOUSE = COMPUTE_WH   SCHEDULE = '1 day'   USER_TASK_TIMEOUT_MS = 14400000 AS   ALTER DATABASE BOND_DEV REFRESH;
show grants on WAREHOUSE IDENTIFIER('"COMPUTE_WH"')
show WAREHOUSES
show WAREHOUSES like 'COMPUTE_WH'
ALTER DATABASE BOND_DEV REFRESH;
select * from table(information_schema.database_refresh_progress('BOND_DEV'));
show OBJECTS like 'TABLE%' in SCHEMA IDENTIFIER('"BOND_DEV"."PUBLIC"') limit 2
USE SCHEMA IDENTIFIER('"PUBLIC"')
USE DATABASE IDENTIFIER('"BOND_DEV"')
show terse SCHEMAS in DATABASE IDENTIFIER('"BOND_DEV"') limit 10000
show WAREHOUSES
show WAREHOUSES like 'COMPUTE_WH'
show terse DATABASES limit 1001
show WAREHOUSES like 'COMPUTE_WH'
show DATABASES like 'BOND_DEV'
create DATABASE IDENTIFIER('"BOND_DEV"') AS REPLICA OF IDENTIFIER('"ALLIED"."SS53963"."BOND_DEV"')
show terse DATABASES limit 1001
show DATABASES like 'EDW_DEV'
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 10000
select * from table(information_schema.database_refresh_progress('EDW_DEV'));
select * from table(information_schema.database_refresh_progress('EDW_DEV'));
show WAREHOUSES like 'COMPUTE_WH'
select * from table(information_schema.database_refresh_progress('EDW_DEV'));
show WAREHOUSES like 'COMPUTE_WH'
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 10000
show terse DATABASES limit 10000
show WAREHOUSES like 'COMPUTE_WH'
show WAREHOUSES
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 1001
show terse ROLES
ALTER DATABASE EDW_DEV REFRESH;
show WAREHOUSES
show terse DATABASES limit 10000
show SCHEMAS like 'CLAIMS' in DATABASE IDENTIFIER('"EDW_DEV"')
show SCHEMAS like 'CRM' in DATABASE IDENTIFIER('"EDW_DEV"')
show SCHEMAS like 'CRM_STG' in DATABASE IDENTIFIER('"EDW_DEV"')
show SCHEMAS like 'CDW' in DATABASE IDENTIFIER('"EDW_DEV"')
show DATABASES like 'EDW_DEV'
show WAREHOUSES like 'COMPUTE_WH'
select * from table(information_schema.database_refresh_progress('EDW_DEV'));
select * from table(information_schema.database_refresh_progress('EDW_DEV'));
USE SCHEMA IDENTIFIER('"PUBLIC"')
show WAREHOUSES
show terse SCHEMAS in DATABASE IDENTIFIER('"EDW_DEV"') limit 1001
show grants on ACCOUNT
alter DATABASE IDENTIFIER('"EDW_DEV"') refresh