
 USE ROLE OWNER_BOND_STAGE; 

DECLARE DB_NAME varchar default (select  COUNT(*) from snowflake.account_usage.databases  where DATABASE_NAME = 'BOND_STAGE'AND DELETED IS NULL) ;
BEGIN 
IF (DB_NAME = 0)
THEN 
BEGIN
CREATE DATABASE BOND_STAGE;
RETURN 'SUCCESS: Database created';
END ;
ELSEIF (DB_NAME <> 0)
THEN 
BEGIN 
RETURN 'WARNING: Database exists';
END;
END IF;
END;



GRANT USAGE ON DATABASE BOND_STAGE TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON DATABASE BOND_STAGE TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON DATABASE BOND_STAGE TO ROLE READ_BOND_STAGE;


GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON ALL SCHEMA BOND_STAGE TO ROLE READ_BOND_STAGE;
