USE ROLE SYSADMIN; 


DECLARE WAREHOUSE_NAME varchar default (select count(*) FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES GU WHERE name = 'BOND_STAGE_INFA_WH' and granted_on = 'WAREHOUSE'and deleted_on is null) ;
BEGIN 
IF (WAREHOUSE_NAME = 0)
THEN 
BEGIN
CREATE WAREHOUSE BOND_STAGE_INFA_WH WAREHOUSE_SIZE=X-SMALL INITIALLY_SUSPENDED=TRUE;
RETURN 'SUCCESS: Warehouse created';
END ;
ELSEIF (WAREHOUSE_NAME <> 0)
THEN 
BEGIN 
RETURN 'WARNING: Warehouse exists';
END;
END IF;
END;



GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE OWNER_BOND_STAGE;
GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE READWRITE_BOND_STAGE;
GRANT USAGE ON WAREHOUSE BOND_STAGE_INFA_WH  TO ROLE READ_BOND_STAGE;