select * from UniTrac..DOCUMENT_MANAGEMENT

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTIMAGE','\UTIMAGE','\UT_TEST_IMAGE') WHERE STORAGE_TYPE_CD = 'IMAGE'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTCERT','\UTCERT','\UT_TEST_CERT') WHERE STORAGE_TYPE_CD = 'CERT'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTNOTICE','\UTNOTICE','\UT_TEST_NOTICE') WHERE STORAGE_TYPE_CD = 'NTC'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\UTREPORT','\UTREPORT','\UT_TEST_REPORT') WHERE STORAGE_TYPE_CD = 'RPT'

UPDATE UniTrac..DOCUMENT_MANAGEMENT
SET SERVER_SHARE_TX = REPLACE('\\unitrac\EDI_IMAGE','\EDI_IMAGE','\UT_TEST_PDF') WHERE STORAGE_TYPE_CD = 'EDITXN'


--------- STOP PROCESS DEFINITIONS!!!!!!!
UPDATE UniTrac..PROCESS_DEFINITION
SET ACTIVE_IN = 'N' WHERE ACTIVE_IN = 'Y'

--------- Don't Forget HOV Mapping!!!!!!
UPDATE OUTPUT_DEVICE
SET UNC_PATH_TX = 'c:\outputbatchfiles\UniTracHOVQA'
WHERE NAME_TX LIKE 'HOV%' 

--------- Whatever this does, update it!!!!!!! (LFP Stuff!)
UPDATE PPDATTRIBUTE
SET VALUE_TX = 'UTQA-SQL2012'
WHERE CODE_CD = 'DBServer'

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'qa2012user'
WHERE CODE_CD = 'DBUserId'

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'qa2012user'
WHERE CODE_CD = 'DBPassword'

UPDATE PPDATTRIBUTE
SET VALUE_TX = 'VUT' WHERE CODE_CD IN ('DBInstance', 'PPDHelperTypeCode')

SELECT * FROM UniTrac..PPDATTRIBUTE
WHERE CODE_CD IN ('DBServer','DBUserID','DBPassword','DBUserID')

UPDATE PREPROCESSING_DETAIL
SET TYPE_CD = 'TrackingCH' WHERE TYPE_CD = 'Tracking'
