declare @lenderCode nvarchar(10), @centerCode nvarchar(20), @rddID bigint
set @lenderCode = '1729'
SET @centerCode = 'Plano'
set @rddID = (select id from RELATED_DATA_DEF where RELATE_CLASS_NM = 'LenderOrganization' and NAME_TX = 'AssociatedServiceCenter')

INSERT into SERVICE_CENTER_FUNCTION_LENDER_RELATE (LENDER_ID, SERVICE_CENTER_FUNCTION_ID, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
values ((select ID from LENDER where CODE_TX = @lenderCode), (select f.ID from SERVICE_CENTER_FUNCTION f inner join SERVICE_CENTER sc on sc.id = f.SERVICE_CENTER_ID 
where CODE_TX = @centerCode), getdate(), GETDATE(), 'script', 1)

INSERT into RELATED_DATA (DEF_ID, RELATE_ID, VALUE_TX, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
select @rddID DEF_ID, div.id, @centerCode, GETDATE(), GETDATE(), 'script', 1
from LENDER_ORGANIZATION div
   inner join LENDER l on l.ID = div.LENDER_ID 
where l.CODE_TX = @lenderCode
   and div.TYPE_CD = 'DIV' and div.PURGE_DT is null   

go


/*
SELECT C.CODE_TX, C.NAME_TX,*
FROM LENDER L
INNER JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFLR ON L.ID = SCFLR.LENDER_ID AND SCFLR.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER_FUNCTION SCF ON SCFLR.SERVICE_CENTER_FUNCTION_ID = SCF.ID AND SCF.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER C ON SCF.SERVICE_CENTER_ID = C.ID  AND C.PURGE_DT IS NULL
WHERE L.CODE_TX = '1729'


SELECT RD.VALUE_TX,LO.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '1729'
*/

