use unitrac


************************************************************************
2) Carrier TP Nat Gen 28%
*************************************************************************



/*
--Tables to be inserted into
TRADING_PARTNER
DELIVERY_INFO
DELIVERY_INFO_GROUP
DELIVERY_DETAIL
PREPROCESSING_DETAIL
PPDATTRIBUTE
DELIVERY_INFO_DELIVER_TO_TP_RELATE

--Tables to insert file specific info
RELATED_DATA


--***NOTE***
I would say one or the other has to be updated. Either what’s in the database, or the filename. 
It looks like the file name is derived by the Trading Partner Name. It’s then concatenated with USD and some date values to match the period. 
 
Thanks,
Raelee
-----------

*/


SELECT *
FROM CARRIER
WHERE CODE_TX IN ('NG-29%','SEC-32%')
ORDER BY CODE_TX


--1) Insert into Trading Partner Table (use info from CARRIER table)

INSERT INTO TRADING_PARTNER 
(EXTERNAL_ID_TX,NAME_TX,TYPE_CD,STATUS_CD,RECEIVE_FROM_TP_ID,DELIVER_TO_TP_ID,UPDATE_DT,UPDATE_USER_TX,PURGE_DT,LOCK_ID,ACTIVE_IN,TRANSACTION_XSLT,DELIVER_TO_TP_IN,CREATE_DT) 
VALUES 
('',N'',N'CARRIER_TP',N'ACTIVE',0,2046,GETDATE(),N'MsgSrvr',NULL,1,'Y','','N',GETDATE()); 


SELECT *
FROM TRADING_PARTNER
WHERE EXTERNAL_ID_TX IN ('NG-29%','SEC-32%')

--2) Insert into Delivery_Info table

--Query to get DI ID insert
select *
from DELIVERY_INFO
WHERE TRADING_PARTNER_ID IN (3479,3480)


INSERT INTO DELIVERY_INFO (TRADING_PARTNER_ID,DOCUMENT_TYPE_CD,DELIVERY_TYPE_CD,FILESIZE_VARIANCE_NO,DELIVERY_FREQ_CD,PREPROCESS_TYPE_CD,OVERDUE_DELIVERY_THRESHOLD_NO,FILE_FORMAT_TYPE_CD,BRANCH_ID,UPDATE_DT,UPDATE_USER_TX,PURGE_DT,LOCK_ID,ACTIVE_IN)
SELECT '',DOCUMENT_TYPE_CD,DELIVERY_TYPE_CD,FILESIZE_VARIANCE_NO,DELIVERY_FREQ_CD,PREPROCESS_TYPE_CD,OVERDUE_DELIVERY_THRESHOLD_NO,FILE_FORMAT_TYPE_CD,BRANCH_ID,getdate(),UPDATE_USER_TX,PURGE_DT,LOCK_ID,ACTIVE_IN
FROM DELIVERY_INFO
WHERE ID IN (14326)


--3) Insert into Delivery_Info_Group table

--Query to get DIG ID
SELECT *
FROM DELIVERY_INFO_GROUP
WHERE DELIVERY_INFO_ID IN (14560,14561)

--Query to get DIG Name (always suffix with .*.dat )

SELECT *
FROM CARRIER
WHERE CODE_TX IN ('NG-29%','SEC-32%')
ORDER BY CODE_TX


INSERT INTO DELIVERY_INFO_GROUP (DELIVERY_INFO_ID,NAME_TX,ORDER_NO,UPDATE_DT,UPDATE_USER_TX,PURGE_DT,LOCK_ID)
SELECT '','',ORDER_NO,GETDATE(),UPDATE_USER_TX,PURGE_DT,LOCK_ID
FROM DELIVERY_INFO_GROUP
WHERE ID = 16733

--4) Insert into Delivery_Detail

--Query to review existing DD info
SELECT *
FROM DELIVERY_DETAIL
WHERE DELIVERY_INFO_GROUP_ID IN (17021,
17022)

INSERT INTO DELIVERY_DETAIL(DELIVERY_INFO_GROUP_ID,DELIVERY_CODE_TX,VALUE_TX,UPDATE_DT,UPDATE_USER_TX,PURGE_DT,LOCK_ID)
SELECT '',DELIVERY_CODE_TX,VALUE_TX,GETDATE(),UPDATE_USER_TX,PURGE_DT,LOCK_ID
FROM DELIVERY_DETAIL
WHERE DELIVERY_INFO_GROUP_ID = 16733

--Update file names from DIG.NAME_TX column

UPDATE DELIVERY_DETAIL SET VALUE_TX = ''
WHERE DELIVERY_CODE_TX = 'InputFileName' AND DELIVERY_INFO_GROUP_ID = 17022

UPDATE DELIVERY_DETAIL SET VALUE_TX = ''
WHERE DELIVERY_CODE_TX = 'OutputFileName' AND DELIVERY_INFO_GROUP_ID = 17022


--5) DELIVERY_INFO_DELIVER_TO_TP_RELATE Insert
SELECT *
FROM DELIVERY_INFO_DELIVER_TO_TP_RELATE
WHERE DELIVERY_INFO_ID IN (14560,14561)

INSERT INTO DELIVERY_INFO_DELIVER_TO_TP_RELATE (DELIVERY_INFO_ID, DELIVER_TO_TP_ID, CREATE_dT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
SELECT '', DELIVER_TO_TP_ID, CREATE_dT, GETDATE(), 'MsgSrvr', LOCK_ID
FROM DELIVERY_INFO_DELIVER_TO_TP_RELATE
WHERE DELIVERY_INFO_ID IN (14326)

--6) Insert to RELATED_DATA table for EOM file
SELECT *
FROM RELATED_DATA_DEF
WHERE ID = 96

SELECT *
FROM RELATED_DATA
WHERE DEF_ID IN (96) AND VALUE_TX = 'EOM'
and relate_id IN (14561,14560)


INSERT INTO RELATED_DATA (DEF_ID, RELATE_ID, VALUE_TX, COMMENT_TX, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
VALUES (96,'','EOM','UniTracDeliveryType',GETDATE(),GETDATE(),'MsgSrvr',1)

--7) Insert into PreProcessing_Detail
SELECT *
FROM PREPROCESSING_DETAIL
WHERE DELIVERY_INFO_GROUP_ID IN (17022,17021)

INSERT INTO PREPROCESSING_DETAIL (DELIVERY_INFO_GROUP_ID, ORDER_NO, TYPE_CD, VALUE_TX, CODE_CD, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
SELECT '', ORDER_NO, TYPE_CD, VALUE_TX, CODE_CD, GETDATE(), UPDATE_USER_TX, LOCK_ID
FROM PREPROCESSING_DETAIL
WHERE DELIVERY_INFO_GROUP_ID IN (16733)

--8) Insert into PPDATTRIBUTE

SELECT *
FROM PPDATTRIBUTE
WHERE PREPROCESSING_DETAIL_ID IN (20223,20224)

INSERT INTO PPDATTRIBUTE (PREPROCESSING_DETAIL_ID,VALUE_TX, CODE_CD, CREATE_DT,UPDATE_DT, UPDATE_USER_TX, LOCK_ID, VALUE_XML, COMMON_STYLESHEET_ID)
SELECT '',VALUE_TX, CODE_CD, GETDATE(),GETDATE(), UPDATE_USER_TX, LOCK_ID, VALUE_XML, COMMON_STYLESHEET_ID
FROM PPDATTRIBUTE
WHERE PREPROCESSING_DETAIL_ID IN (19399)


--Verification Query
SELECT DIG.ID,*
FROM TRADING_PARTNER TP
INNER JOIN DELIVERY_INFO DI ON TP.ID = DI.TRADING_PARTNER_ID
INNER JOIN DELIVERY_INFO_GROUP DIG ON DI.ID = DIG.DELIVERY_INFO_ID
INNER JOIN DELIVERY_DETAIL DD ON DIG.ID = DD.DELIVERY_INFO_GROUP_ID
INNER JOIN RELATED_DATA RD on RD.RELATE_ID = DI.ID and RD.DEF_ID = 96
INNER JOIN PREPROCESSING_DETAIL PD on PD.DELIVERY_INFO_GROUP_ID = DIG.ID
INNER JOIN PPDATTRIBUTE PPD on PPD.PREPROCESSING_DETAIL_ID = PD.ID
WHERE TP.TYPE_CD = 'CARRIER_TP' AND EXTERNAL_ID_TX IN ('')
