
---Search by process id
SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss],  PD.NAME_TX,  PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE CAST(PL.UPDATE_DT AS DATE) >= CAST(GETDATE()-7 AS DATE)
and  CONVERT(TIME,END_DT- START_DT) > '00:05:00.000'
ORDER BY PL.UPDATE_DT DESC 



SELECT  COUNT(PL.ID)
FROM Unitrac.dbo.PROCESS_LOG PL
WHERE PL.CREATE_DT >= DateAdd(MINUTE, -2, getdate()) AND PL.PROCESS_DEFINITION_ID IN (51)
AND PL.END_DT IS NOT NULL
AND PL.STATUS_CD = 'InProcess'
AND  CONVERT(TIME,GETDATE()-END_DT) > '0:30:00'

SELECT *
FROM Unitrac.dbo.PROCESS_LOG PL
WHERE PL.CREATE_DT >= DateAdd(HOUR, -24, getdate()) AND PL.PROCESS_DEFINITION_ID IN (51)
AND PL.END_DT IS NOT NULL
AND PL.STATUS_CD = 'InProcess'
AND  CONVERT(TIME,GETDATE()-END_DT) >'0:30:00'

--Search by type
SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], PD.NAME_TX,  PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE CAST(PL.UPDATE_DT AS DATE) >= CAST(GETDATE() AS DATE) AND PD.PROCESS_TYPE_CD IN ( '')
ORDER BY PL.UPDATE_DT DESC 

--Search by server
SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], PD.NAME_TX,  PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE CAST(PL.UPDATE_DT AS DATE) >= CAST(GETDATE() AS DATE)  AND SERVER_TX IS NOT NULL AND 
CONVERT(TIME,END_DT- START_DT) > '01:00:00.0000000' AND PD.NAME_TX  LIKE '%Billing%'
ORDER BY PL.UPDATE_DT DESC 


SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], PD.NAME_TX,  PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE PL.UPDATE_DT >= Dateadd(HOUR, -4, Getdate())  AND SERVER_TX ='UTPROD-ASR7'
ORDER BY PL.end_dt DESC 




SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], * from Unitrac.dbo.PROCESS_LOG
where PROCESS_DEFINITION_ID = 1979354
and CONVERT(TIME,END_DT- START_DT) is not null
ORDER BY CREATE_DT DESC  

SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], * from Unitrac.dbo.PROCESS_LOG
where PROCESS_DEFINITION_ID = 1992126
and CONVERT(TIME,END_DT- START_DT) is not null
ORDER BY CREATE_DT DESC  




--Search by Service
SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], PD.NAME_TX,  PL.SERVICE_NAME_TX , SERVER_TX, PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE CAST(PL.UPDATE_DT AS DATE) >= CAST(GETDATE() AS DATE)  AND SERVICE_NAME_TX IN  ('')
ORDER BY PL.UPDATE_DT DESC 

SELECT CONVERT(TIME,END_DT- START_DT)[hh:mm:ss], PD.NAME_TX,  PL.*
FROM Unitrac.dbo.PROCESS_LOG PL
JOIN Unitrac.dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
where CAST(PL.UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE) and SERVICE_NAME_TX IN  ('')
ORDER BY CONVERT(TIME,END_DT- START_DT) DESC 




/*	

select * from Unitrac.dbo.process_log_item
where process_log_id = 123022384

SELECT active_in, onhold_in, *
FROM Unitrac.dbo.PROCESS_DEFINITION PD
WHERE ID  IN (1992767)




SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ID = 30
PROCESS_TYPE_CD IN ( 'UTLIBREPRC')


exec UT_MessageTypeBreakDown

*/



