USE [UniTrac]
GO
----------- CONNECTION DESCRIPTORS OY!!! -------------------------------
select * from UniTrac..CONNECTION_DESCRIPTOR



Update CONNECTION_DESCRIPTOR Set NAME_TX = 'UniTracDW',SERVER_TX = 'UTQA-SQL-14', 
USERNAME_TX = 'nClZlXE2ktrN5UdonQgfWMV9leEPNo96CTTKyO0zp8c=', 
PASSWORD_TX = 'flNVdN5QdgKa6ZTJkXPz2Qcpaqlgap1OMgJnN4nTvxwXXly+OogMLQ==' where ID = 1

Update CONNECTION_DESCRIPTOR Set NAME_TX = 'VUT_Agency',SERVER_TX = 'VUTQA01', 
USERNAME_TX = 'ykGX/FdKYchEg5OZ0B7PIA==', 
PASSWORD_TX = 'ykGX/FdKYchEg5OZ0B7PIA==' where ID = 3

DELETE 
--SELECT *
FROM CONNECTION_DESCRIPTOR
WHERE ID not IN (1,3,29,35,36,37)

Update CONNECTION_DESCRIPTOR Set NAME_TX = 'Scan',SERVER_TX = 'UTQA-SQL-14',USERNAME_TX = 'nClZlXE2ktrN5UdonQgfWMV9leEPNo96CTTKyO0zp8c=',PASSWORD_TX = 'flNVdN5QdgKa6ZTJkXPz2Qcpaqlgap1OMgJnN4nTvxwXXly+OogMLQ==' where ID = 29
Update CONNECTION_DESCRIPTOR Set NAME_TX = 'PERFLOG',SERVER_TX = 'UTQA-SQL-14',DATABASE_NM = 'Unitrac',USERNAME_TX = 'nClZlXE2ktrN5UdonQgfWMV9leEPNo96CTTKyO0zp8c=',PASSWORD_TX = 'flNVdN5QdgKa6ZTJkXPz2Qcpaqlgap1OMgJnN4nTvxwXXly+OogMLQ==' where ID = 35
Update CONNECTION_DESCRIPTOR Set NAME_TX = 'ProdRO',SERVER_TX = 'UNITRAC-DB01',DATABASE_NM = 'Unitrac', USERNAME_TX = '6AQRyQ1OIN9iZ11ys1Tcfh3Yef2QEMcJp1IAcWJjorM=',PASSWORD_TX = 'eTup3wL/SuV0ly4K/X2Fe+3PvDDPSShu' where ID = 36
Update CONNECTION_DESCRIPTOR Set NAME_TX = 'UnitracArchive',SERVER_TX = 'UTQA-SQL-14',USERNAME_TX = 'nClZlXE2ktrN5UdonQgfWMV9leEPNo96CTTKyO0zp8c=',PASSWORD_TX = 'flNVdN5QdgKa6ZTJkXPz2Qcpaqlgap1OMgJnN4nTvxwXXly+OogMLQ==' where ID = 37


