
-- 38496 Clean up

DELETE from report where NAME_TX='StatusNotProgressing'
delete from REF_DOMAIN where DOMAIN_CD = 'Report_StatNoProgress'
delete from REF_CODE where DOMAIN_CD = 'Report_StatNoProgress'
delete from REPORT_CONFIG where report_DOMAIN_CD = 'Report_StatNoProgress'
delete from REF_CODE_ATTRIBUTE where DOMAIN_CD = 'Report_StatNoProgress'
delete FROM REF_CODE_ATTRIBUTE WHERE  VALUE_TX = 'Report_StatNoProgress'


-- 38496 Read ref codes and report



IF NOT EXISTS (SELECT * FROM REPORT WHERE NAME_TX = 'StatusNotProgressing')
INSERT INTO REPORT (NAME_TX, DISPLAY_NAME_TX, DESCRIPTION_TX, DASHBOARD_IN, SERVER_PATH_TX, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID, CATEGORY_CD,ACTIVE_IN)
VALUES ('StatusNotProgressing', 'Status Not Progressing Report', 'Status Not Progressing Report', 'Y', 'UniTracReports', GETDATE(), GETDATE(), 'admin', 1, 'LENDER', 'Y')

Go




DECLARE @reportID bigint
SELECT @reportID = ID FROM Report WHERE NAME_TX='StatusNotProgressing'


--DOMAIN FOR Report_StatNoProgress
IF NOT EXISTS (SELECT * FROM REF_DOMAIN WHERE DOMAIN_CD = 'Report_StatNoProgress')
Insert into REF_DOMAIN (DOMAIN_CD,DESCRIPTION_TX,REF_CODE_MAX_LENGTH_NO,CREATE_DT,UPDATE_DT,PURGE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_BASED_IN)
Values ('Report_StatNoProgress','Status Not Progressing Report',30,GETDATE(),GETDATE(),NULL,'admin',1,'N')

--DEFAULT
IF NOT EXISTS (SELECT * FROM REF_CODE WHERE CODE_CD = 'DEFAULT' and DOMAIN_CD ='Report_StatNoProgress')
Insert into REF_CODE (CODE_CD,DOMAIN_CD,MEANING_TX,DESCRIPTION_TX,ACTIVE_IN,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID)
Values ('DEFAULT','Report_StatNoProgress','DEFAULT','DEFAULT','Y',GETDATE(),GETDATE(),'admin',1,0)

--StatNoProg_PreBind
IF NOT EXISTS (SELECT * FROM REF_CODE WHERE CODE_CD = 'StatNoProg_PreBind' and DOMAIN_CD ='Report_StatNoProgress')
Insert into REF_CODE (CODE_CD,DOMAIN_CD,MEANING_TX,DESCRIPTION_TX,ACTIVE_IN,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID)
Values ('StatNoProg_PreBind','Report_StatNoProgress','Uninsured Not Progressing','Uninsured Loans Not Progressing Report','Y',GETDATE(),GETDATE(),'admin',1,0)

--REPORT_CONFIG

--StatNoProg_PreBind
IF NOT EXISTS (SELECT * FROM REPORT_CONFIG WHERE CODE_TX = 'StatNoProg_PreBind' and REPORT_DOMAIN_CD ='Report_StatNoProgress')
Insert into REPORT_CONFIG (CODE_TX,MEANING_TX,NAME_TX,REPORT_ID,REPORT_DOMAIN_CD,REPORT_CD,GROUP_TX,SORT_TX,FILTER_TX,HEADER_TX,FOOTER_TX, DISPLAY_IN, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID)
Values ('StatNoProg_PreBind','Uninsured Not Progressing','Uninsured Loans Not Progressing Report', @reportID,'Report_StatNoProgress','StatNoProg_PreBind','[LOAN_BRANCHCODE_TX] + '' / '' + [REQUIREDCOVERAGE_TYPE_TX]','[OWNER_LASTNAME_TX] + '' / '' + isnull([OWNER_FIRSTNAME_TX],'''')',
'','','', 'Y', GETDATE(), GETDATE(), 'admin', 1)



--Common
--In Report Column Order
--Currently there is only one way to run the report. Default column settings.

--Lender Code: LOAN_LENDERCODE_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LN_LenderCode' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LN_LenderCode','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Lender Name: LENDER_NAME_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LN_Name' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LN_Name','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)


--Branch: LOAN_BRANCHCODE_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LN_BranchCode' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LN_BranchCode','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)


--Lender Admin:LA_Name
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LA_Name' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LA_Name','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Loan Number: LOAN_NUMBER_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LN_Number' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LN_Number','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Last Name & First Name: OWNER_LASTNAME_TX & OWNER_FIRSTNAME_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'OWN_Name' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('OWN_Name','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Product Type: PRODUCT_TYPE
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'Product_Type' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('Product_Type','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Escrow: ESCROW_IN
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'Escrow' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('Escrow','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Property Description: PROPERTY_DESCRIPTION
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'PROPERTY_DESCRIPTION' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('PROPERTY_DESCRIPTION','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--VIN: COLLATERAL_VIN_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'PRY_VIN' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('PRY_VIN','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Loan Balance: LOAN_BALANCE_NO
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LOAN_BALANCE' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LOAN_BALANCE','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Required Cov. Amount: REQUIREDCOVERAGE_AMOUNT_NO
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'REQUIREDCOVERAGE_AMOUNT' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('REQUIREDCOVERAGE_AMOUNT','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Loan Eff Date: LOAN_EFFECTIVE_DT
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LN_Effective' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LN_Effective','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Borrower Ins Exp/Cxl Date: BORRINSCOMPANY_EXPCXL_DT
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'BORRINS_ExpCxl' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('BORRINS_ExpCxl','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Coverage Exposure: Exposure
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'CV_Exposure' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('CV_Exposure','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Cancel Reason: CancelRea
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'INS_CancelReason' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('INS_CancelReason','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Predictive Decile: PREDICTIVE_DECILE_NO
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'Predictive_Decile' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('Predictive_Decile','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Status: CoverageStatus
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'CV_Status' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('CV_Status','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Coverage: REQUIREDCOVERAGE_TYPE_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'CV_TypeCode' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('CV_TypeCode','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Last Notice Action: LastNotice_Action
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'LastNotice_Action' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('LastNotice_Action','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--PreBinder Reason: PreBinder_Reason
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'PreBinder_Reason' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('PreBinder_Reason','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)

--Rejection Reason: REJECT_REASON_TX
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'REJECT_REASON_TX' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('REJECT_REASON_TX','DEFAULT','Report_StatNoProgress','T',GETDATE(),GETDATE(),'admin',1,0)


-- Optional
IF NOT EXISTS (Select * From REF_CODE_ATTRIBUTE Where ATTRIBUTE_CD = 'BlankField' AND REF_CD = 'DEFAULT' AND DOMAIN_CD = 'Report_StatNoProgress') 
INSERT INTO REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID) 
Values ('BlankField','DEFAULT','Report_StatNoProgress','F',GETDATE(),GETDATE(),'admin',1,0)

--GroupBy and SortBy
IF NOT EXISTS (SELECT * FROM REF_CODE_ATTRIBUTE WHERE REF_CD = 'L/B/C' and VALUE_TX = 'Report_StatNoProgress')
Insert into REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID)
Values ('GB_StatNoProgress','L/B/C','Report_GroupBy','Report_StatNoProgress',GETDATE(),GETDATE(),'admin',1,0)

IF NOT EXISTS (SELECT * FROM REF_CODE_ATTRIBUTE WHERE REF_CD = 'BorrowerName' and VALUE_TX = 'Report_StatNoProgress')
Insert into REF_CODE_ATTRIBUTE (ATTRIBUTE_CD,REF_CD,DOMAIN_CD,VALUE_TX,CREATE_DT,UPDATE_DT,UPDATE_USER_TX,LOCK_ID,AGENCY_ID)
Values ('SB_StatNoProgress','BorrowerName','Report_SortBy','Report_StatNoProgress',GETDATE(),GETDATE(),'admin',1,0)



GO




