USE UniTrac


SELECT *
FROM dbo.OUTPUT_BATCH OB 
WHERE ob.UPDATE_DT > '2018-01-25 07:00'
AND  ob.STATUS_CD = 'PEND' AND OB.EXTERNAL_ID NOT LIKE 'RPT%'

SELECT * FROM dbo.OUTPUT_BATCH OB 
WHERE ob.UPDATE_DT > '2018-02-01 16:00'
AND  ob.STATUS_CD = 'COMP' --AND OB.EXTERNAL_ID NOT LIKE 'RPT%'
AND ob.OUTPUT_CONFIGURATION_ID IN (SELECT * FROM #tmp) 
ORDER BY OB.UPDATE_DT DESC 


SELECT * FROM dbo.OUTPUT_CONFIGURATION
WHERE ID IN (SELECT DISTINCT OB.OUTPUT_CONFIGURATION_ID 
--INTO UniTracHDStorage..[BatchesNotCompleting]
FROM dbo.OUTPUT_BATCH OB 
WHERE ob.UPDATE_DT > '2018-01-25 07:00'
AND  ob.STATUS_CD = 'PEND')
--1345



SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (SELECT * FROM #tmpPL)
AND STATUS_CD = 'ERR'
AND RELATE_TYPE_CD LIKE '%Batch'

SELECT * FROM dbo.OUTPUT_BATCH
WHERE ID IN (
1783571,
1786220,
1785136,
1785136,
1786220,
1790951,
1783966)

	
SELECT * FROM dbo.PROCESS_LOG
WHERE SERVICE_NAME_TX= 'UnitracBusinessServiceFax' AND UPDATE_DT >= '2018-02-05 06:00'
ORDER BY UPDATE_DT DESC

SELECT * FROM dbo.PROCESS_DEFINITION
WHERE PROCESS_TYPE_CD = 'FULFILLPRC'


SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ID = 83


SELECT 
LEFT(EXTERNAL_ID, 3) [Type]
INTO #tmpP
FROM dbo.OUTPUT_BATCH ob
WHERE ob.UPDATE_DT > '2018-01-25 07:00'
AND  ob.STATUS_CD = 'PEND'

SELECT COUNT(*)[Count],[Type] FROM #tmpP
GROUP BY [Type]

DROP TABLE #tmpP

/*
5719	RPT
712	NTC
185	FPC

*/







SELECT DISTINCT

OB.ID INTO #tmp

FROM dbo.OUTPUT_BATCH OB

JOIN PROCESS_LOG_ITEM(NOLOCK) pli ON pli.PROCESS_LOG_ID = OB.PROCESS_LOG_ID AND pli.PURGE_DT IS NULL

JOIN PROCESS_LOG pl ON pl.ID = pli.PROCESS_LOG_ID

JOIN PROCESS_DEFINITION pd ON pd.ID = pl.PROCESS_DEFINITION_ID

WHERE OB.UPDATE_DT > '2018-01-25 07:00'

AND OB.STATUS_CD = 'PEND'

AND pd.PROCESS_TYPE_CD = 'CYCLEPRC'

AND OB.PURGE_DT IS NULL

AND pl.PURGE_DT IS NULL

AND pd.PURGE_DT IS NULL

　

SELECT

dbo.fn_IsOutputBatchReadyToPrint(ob.ID),

COUNT(*)

FROM #tmp ob

GROUP BY dbo.fn_IsOutputBatchReadyToPrint(ob.ID)

DROP TABLE #tmp
