IF OBJECT_ID(N'tempdb..#TMPWI',N'U') IS NOT NULL
       DROP TABLE #TMPWI 
       
SELECT WI.ID AS WI_ID , WI.RELATE_ID , WI.STATUS_CD , WI.CREATE_DT ,
WI.CURRENT_QUEUE_ID , WI.CURRENT_OWNER_ID 
INTO #TMPWI 
 FROM WORK_ITEM WI
JOIN LOAN ON LOAN.ID = WI.RELATE_ID
WHERE LOAN.PURGE_DT IS NULL
AND WI.WORKFLOW_DEFINITION_ID = 8
AND WI.PURGE_DT IS NULL
AND WI.RELATE_TYPE_CD = 'Allied.UniTrac.Loan'
--AND WI.STATUS_CD NOT IN ('Complete', 'Withdrawn')
AND WI.ID IN (SELECT ID FROM UniTracHDStorage..WI_INC0222261)
----124459

--- GET THE RC'S WITH LP SET AS 'ORDERUP' , 'VSI' AND THE OTHER COVERAGE IS NOT SUPPORTED FOR VD ALSO
IF OBJECT_ID(N'tempdb..#TMPWI_01',N'U') IS NOT NULL
       DROP TABLE #TMPWI_01 

SELECT DISTINCT LENDER.AGENCY_ID ,  LENDER.CODE_TX , LENDER.NAME_TX AS LENDER_NAME_TX , 
LENDER.CANCEL_DT , LENDER.TEST_IN , 
WI.* , LP.ID AS LENDER_PRODUCT_ID , LP.NAME_TX , LP.DESCRIPTION_TX , 
LP.BASIC_TYPE_CD , LP.BASIC_SUB_TYPE_CD , 
LOAN.NUMBER_TX , LOAN.RECORD_TYPE_CD , 
RC.PROPERTY_ID
INTO #TMPWI_01
 FROM #TMPWI WI
JOIN LOAN ON LOAN.ID = WI.RELATE_ID
JOIN LENDER ON LENDER.ID = LOAN.LENDER_ID
JOIN COLLATERAL COLL ON COLL.LOAN_ID = LOAN.ID
AND COLL.PURGE_DT IS NULL AND COLL.PRIMARY_LOAN_IN = 'Y'
JOIN PROPERTY PR ON PR.ID = COLL.PROPERTY_ID
AND PR.PURGE_DT IS NULL
JOIN REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = PR.ID
AND RC.PURGE_DT IS NULL
JOIN LENDER_PRODUCT LP ON LP.ID = RC.LENDER_PRODUCT_ID
AND LP.PURGE_DT IS NULL
OUTER APPLY
(
SELECT RC1.ID , RC1.LENDER_PRODUCT_ID 
 FROM REQUIRED_COVERAGE RC1 
 JOIN LENDER_PRODUCT LP1 ON LP1.ID = RC1.LENDER_PRODUCT_ID
 AND LP1.PURGE_DT IS NULL
 WHERE RC1.PROPERTY_ID = RC.PROPERTY_ID
 AND RC1.PURGE_DT IS NULL
 AND RC1.ID <> RC.ID
 AND ( LP1.BASIC_TYPE_CD NOT IN ( 'ORDERUP' , 'VSI' , 'TRKONLY' )
   OR
   (LP1.BASIC_TYPE_CD = 'TRKONLY' AND LP1.BASIC_SUB_TYPE_CD = 'WNTC')
  )
) AS RC3
WHERE LP.BASIC_TYPE_CD IN ( 'ORDERUP' , 'VSI' )
AND RC3.ID IS NULL
ORDER BY LENDER.AGENCY_ID , LENDER.CODE_TX , LP.NAME_TX , BASIC_TYPE_CD
----23

--- GET THE RC'S WITH LP SET AS TRKONLY/WONTC AND THE OTHER COVERAGE IS NOT SUPPORTED FOR VD ALSO
INSERT INTO #TMPWI_01
SELECT DISTINCT LENDER.AGENCY_ID ,  LENDER.CODE_TX , LENDER.NAME_TX AS LENDER_NAME_TX , 
LENDER.CANCEL_DT , LENDER.TEST_IN , 
WI.* , LP.ID AS LENDER_PRODUCT_ID , LP.NAME_TX , LP.DESCRIPTION_TX , 
LP.BASIC_TYPE_CD , LP.BASIC_SUB_TYPE_CD , 
LOAN.NUMBER_TX , LOAN.RECORD_TYPE_CD , 
RC.PROPERTY_ID
 FROM #TMPWI WI
JOIN LOAN ON LOAN.ID = WI.RELATE_ID
JOIN LENDER ON LENDER.ID = LOAN.LENDER_ID
JOIN COLLATERAL COLL ON COLL.LOAN_ID = LOAN.ID
AND COLL.PURGE_DT IS NULL AND COLL.PRIMARY_LOAN_IN = 'Y'
JOIN PROPERTY PR ON PR.ID = COLL.PROPERTY_ID
AND PR.PURGE_DT IS NULL
JOIN REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = PR.ID
AND RC.PURGE_DT IS NULL
JOIN LENDER_PRODUCT LP ON LP.ID = RC.LENDER_PRODUCT_ID
AND LP.PURGE_DT IS NULL
OUTER APPLY
(
SELECT RC1.ID , RC1.LENDER_PRODUCT_ID 
 FROM REQUIRED_COVERAGE RC1 
 JOIN LENDER_PRODUCT LP1 ON LP1.ID = RC1.LENDER_PRODUCT_ID
 AND LP1.PURGE_DT IS NULL
 WHERE RC1.PROPERTY_ID = RC.PROPERTY_ID
 AND RC1.PURGE_DT IS NULL
 AND RC1.ID <> RC.ID
 AND ( LP1.BASIC_TYPE_CD NOT IN ( 'ORDERUP' , 'VSI' , 'TRKONLY' )
   OR
   (LP1.BASIC_TYPE_CD = 'TRKONLY' AND LP1.BASIC_SUB_TYPE_CD = 'WNTC')
  )
) AS RC3
WHERE LP.BASIC_TYPE_CD = 'TRKONLY'
AND LP.BASIC_SUB_TYPE_CD = 'WONTC'
AND RC3.ID IS NULL
ORDER BY LENDER.AGENCY_ID , LENDER.CODE_TX , LP.NAME_TX , BASIC_TYPE_CD
----5


UPDATE WI SET STATUS_CD = 'Withdrawn' , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'BUG30969' , 
LOCK_ID = WI.LOCK_ID % 255 + 1
---- SELECT COUNT(*)
FROM WORK_ITEM WI JOIN #TMPWI_01 TMP ON 
TMP.WI_ID = WI.ID
AND WI.PURGE_DT IS NULL
---- 28

INSERT INTO WORK_ITEM_ACTION (WORK_ITEM_ID, ACTION_CD, FROM_STATUS_CD, TO_STATUS_CD, CURRENT_QUEUE_ID, 
CURRENT_OWNER_ID, ACTION_NOTE_TX, ACTIVE_IN, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID, ACTION_USER_ID)
SELECT DISTINCT WI_ID , 'Withdraw' , STATUS_CD , 'Withdrawn' , CURRENT_QUEUE_ID , 
CURRENT_OWNER_ID , 'Bug30969' , 'Y' , GETDATE() , GETDATE() , 'BUG30969' , 1 , 1
FROM #TMPWI_01
ORDER BY STATUS_CD
---- 26


UPDATE LN SET SPECIAL_HANDLING_XML = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX  = 'BUG30969' , 
LOCK_ID = LN.LOCK_ID % 255 + 1
--- SELECT LN.NUMBER_TX
FROM LOAN LN JOIN #TMPWI_01 ON #TMPWI_01.RELATE_ID = LN.ID
--- 28