--SELECT * FROM WORK_ITEM WHERE ID = 18279764 

IF OBJECT_ID(N'tempdb..#TMPPLI',N'U') IS NOT NULL
       DROP TABLE #TMPPLI    
       
--- DROP TABLE #TMPPLI
SELECT pli.* 
INTO #TMPPLI
FROM PROCESS_LOG_ITEM pli
inner join NOTICE n on n.ID = RELATE_ID
		and n.TYPE_CD = 'IL'
WHERE pli.PROCESS_LOG_ID = 17106637 
AND pli.RELATE_TYPE_CD = 'Allied.UniTrac.Notice'
AND pli.STATUS_CD = 'COMP'
---- 567


IF OBJECT_ID(N'tempdb..#TMPNTC',N'U') IS NOT NULL
       DROP TABLE #TMPNTC  
       
----- DROP TABLE #TMPNTC
SELECT  LOAN.NUMBER_TX ,  NTC.TYPE_CD , NTC.SEQUENCE_NO , NTC.ISSUE_DT , NTC.LOAN_ID , NTC.NAME_TX , 
NTC.CPI_QUOTE_ID , NTC.ID AS NTC_ID , REL.REQUIRED_COVERAGE_ID , QT.BASIS_NO , pli.INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]', 'varchar(100)') AS USER_ACTION , 
PLI.* , 
PLI.INFO_XML AS NEW_XML ,
0 as EXCLUDE
INTO #TMPNTC
FROM #TMPPLI PLI
JOIN NOTICE NTC ON NTC.ID = PLI.RELATE_ID
AND NTC.PURGE_DT IS NULL
JOIN NOTICE_REQUIRED_COVERAGE_RELATE REL ON REL.NOTICE_ID = NTC.ID
AND REL.PURGE_DT IS NULL
--AND NTC.TYPE_CD  = 'I'
JOIN LOAN ON LOAN.ID = NTC.LOAN_ID
LEFT JOIN CPI_QUOTE QT ON QT.ID = NTC.CPI_QUOTE_ID
JOIN REQUIRED_COVERAGE RC ON RC.ID = REL.REQUIRED_COVERAGE_ID
WHERE SEQUENCE_NO = 1
----- 567

--SELECT * FROM #TMPNTC WHERE SEQUENCE_NO = 2
---- 0


UPDATE #TMPNTC SET 
NEW_XML.modify('insert <USER_ACTION>TEST</USER_ACTION> as last into /INFO_LOG[1]')
WHERE INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]', 'varchar(30)') IS NULL
AND EXCLUDE = 0 
---- 0


UPDATE #TMPNTC SET 
NEW_XML.modify('replace value of 
   (/INFO_LOG/USER_ACTION/text())[1] with "Reject"')
   WHERE EXCLUDE = 0 
 --WHERE (INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]', 'varchar(30)') IS NULL
 --OR INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]', 'varchar(30)') = 'Approve' )
--- 567


UPDATE PLI SET  INFO_XML = TMP.NEW_XML , PURGE_DT = GETDATE() ,
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN PLI.LOCK_ID >= 255 THEN 1 ELSE PLI.LOCK_ID + 1 END
 ---- SELECT TMP.NEW_XML , PLI.INFO_XML.value('(/INFO_LOG/USER_ACTION)[1]', 'varchar(30)')
 FROM PROCESS_LOG_ITEM PLI JOIN #TMPNTC TMP ON TMP.ID = PLI.ID 
 WHERE EXCLUDE = 0
 ----- 567
 
 
 UPDATE NTC SET PURGE_DT = GETDATE() , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN NTC.LOCK_ID >= 255 THEN 1 ELSE NTC.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM NOTICE NTC JOIN #TMPNTC ON #TMPNTC.NTC_ID = NTC.ID 
  WHERE EXCLUDE = 0
 ---- 567
  
 
 UPDATE REL SET PURGE_DT = GETDATE() , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN REL.LOCK_ID >= 255 THEN 1 ELSE REL.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM NOTICE_REQUIRED_COVERAGE_RELATE REL JOIN #TMPNTC ON #TMPNTC.NTC_ID = REL.NOTICE_ID 
  WHERE EXCLUDE = 0
 ---- 567
  
 
 UPDATE QT SET PURGE_DT = GETDATE() , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN QT.LOCK_ID >= 255 THEN 1 ELSE QT.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM CPI_QUOTE QT JOIN #TMPNTC ON #TMPNTC.CPI_QUOTE_ID = QT.ID 
  WHERE EXCLUDE = 0
 ---- 0
 
 
 UPDATE IH SET PURGE_DT = GETDATE() , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN IH.LOCK_ID >= 255 THEN 1 ELSE IH.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM INTERACTION_HISTORY IH JOIN #TMPNTC ON #TMPNTC.CPI_QUOTE_ID = IH.RELATE_ID
 WHERE IH.RELATE_CLASS_TX = 'ALLIED.UNITRAC.CPIQUOTE'
 AND IH.TYPE_CD = 'CPI'
  AND EXCLUDE = 0
 ----- 0
 
 
 UPDATE IH SET PURGE_DT = GETDATE() , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN IH.LOCK_ID >= 255 THEN 1 ELSE IH.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM INTERACTION_HISTORY IH JOIN #TMPNTC ON #TMPNTC.NTC_ID = IH.RELATE_ID
 WHERE EXCLUDE = 0 AND IH.RELATE_CLASS_TX = 'ALLIED.UNITRAC.NOTICE'
 AND IH.TYPE_CD = 'NOTICE'
  AND EXCLUDE = 0
 ---- 567
 
 
 UPDATE DC SET PURGE_DT = GETDATE() , PRINT_STATUS_CD = 'EXCLUDE' , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN DC.LOCK_ID >= 255 THEN 1 ELSE DC.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM DOCUMENT_CONTAINER DC JOIN #TMPNTC ON #TMPNTC.NTC_ID = DC.RELATE_ID
 WHERE EXCLUDE = 0 AND DC.RELATE_CLASS_NAME_TX = 'ALLIED.UNITRAC.NOTICE'
  AND EXCLUDE = 0
 ---- 868
 
 
 UPDATE RC SET GOOD_THRU_DT = NULL , 
 CPI_QUOTE_ID = NULL , NOTICE_DT = NULL , NOTICE_SEQ_NO = NULL , 
 NOTICE_TYPE_CD = NULL , LAST_EVENT_DT = NULL , LAST_EVENT_SEQ_ID = NULL , 
 LAST_SEQ_CONTAINER_ID = NULL , 
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN RC.LOCK_ID >= 255 THEN 1 ELSE RC.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM REQUIRED_COVERAGE RC JOIN #TMPNTC ON #TMPNTC.REQUIRED_COVERAGE_ID = RC.ID
 WHERE EXCLUDE = 0
 ----- 567
 

 UPDATE EE SET STATUS_CD = 'CLR' ,
 UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'BUG32222' ,
 LOCK_ID = CASE WHEN EE.LOCK_ID >= 255 THEN 1 ELSE EE.LOCK_ID + 1 END
 ---- SELECT COUNT(*)
 FROM EVALUATION_EVENT EE JOIN #TMPNTC ON #TMPNTC.REQUIRED_COVERAGE_ID = EE.REQUIRED_COVERAGE_ID
 WHERE EXCLUDE = 0 AND EE.STATUS_CD = 'PEND'
 AND EE.EVENT_SEQUENCE_ID > 0
 ---- 0
 