--Select loan from WI 18279764 (PLID 17106637)  that have a Leinholder Impaired Notice
select distinct n.LOAN_ID as LoanId 
into #Temp1
from PROCESS_LOG_ITEM pli 
	inner join NOTICE n on n.ID = pli.RELATE_ID
		and n.TYPE_CD = 'IL'
where 
pli.PROCESS_LOG_ID = 17106637
and pli.RELATE_TYPE_CD = 'Allied.UniTrac.Notice'

---- DROP TABLE #TMP_NTC
SELECT DISTINCT LOAN.BRANCH_CODE_TX , LOAN.DIVISION_CODE_TX , LOAN.NUMBER_TX , 
LOAN.ID AS LOAN_ID , COLL.ID AS COLL_ID , COLL.PROPERTY_ID  , 
RC.ID AS RC_ID , RC.TYPE_CD , RC.STATUS_CD , RC.SUMMARY_STATUS_CD , RC.SUMMARY_SUB_STATUS_CD ,
RC.CPI_QUOTE_ID , RC.NOTICE_SEQ_NO
INTO #TMP_NTC
FROM LOAN (NOLOCK) 
JOIN COLLATERAL COLL  (NOLOCK) ON COLL.LOAN_ID = LOAN.ID 
JOIN PROPERTY PROP  (NOLOCK) ON COLL.PROPERTY_ID = PROP.ID
JOIN REQUIRED_COVERAGE RC   (NOLOCK) ON RC.PROPERTY_ID = PROP.ID
WHERE  LOAN.ID in (select t1.LoanId from #Temp1 t1)
ORDER BY LOAN.NUMBER_TX


----- GET THE LIST OF RC'S IN #TMPRC
---- DROP TABLE #TMPRC
SELECT  *
INTO #TMPRC
FROM #TMP_NTC
WHERE CPI_QUOTE_ID > 0

---- DROP TABLE #tmpIH
SELECT IH.ID AS IH_ID
INTO #tmpIH
FROM #TMPRC tmp
		JOIN INTERACTION_HISTORY IH ON IH.RELATE_ID = tmp.CPI_QUOTE_ID
WHERE
		IH.TYPE_CD = 'CPI'
		AND IH.RELATE_CLASS_TX = 'ALLIED.UNITRAC.CPIQUOTE'
		AND tmp.RC_ID = ISNULL(IH.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]', 'BIGINT'),0 )
		and tmp.PROPERTY_ID = IH.property_id     
		AND ISNULL(IH.SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar(20)'),'') = 'Open'
		AND IH.PURGE_DT IS NULL
	
INSERT INTO
	PROPERTY_CHANGE (
		ENTITY_NAME_TX,
		ENTITY_ID,
		USER_TX,
		ATTACHMENT_IN,
		CREATE_DT,
		AGENCY_ID,
		DESCRIPTION_TX,
		DETAILS_IN,
		FORMATTED_IN,
		LOCK_ID,
		PARENT_NAME_TX,
		PARENT_ID,
		TRANS_STATUS_CD,
		UTL_IN)
SELECT DISTINCT
	'Allied.UniTrac.RequiredCoverage',
	tf.RC_ID,
	'BUG32222',
	'N',
	GETDATE(),
	1,
	'Notice Cycle Cleared',
	'N',
	'Y',
	1,
	'Allied.UniTrac.RequiredCoverage',
	TF.RC_ID,
	'PEND',
	'N'
FROM
	 #TMP_NTC tf
WHERE
	NOTICE_SEQ_NO > 0
			
--select * from #TMP_NTC tf					
			
UPDATE QT
	SET	QT.CLOSE_REASON_CD = 'NCC',
		QT.CLOSE_DT = GETDATE(),
		QT.UPDATE_DT = GETDATE(),
		QT.UPDATE_USER_TX = 'BUG32222',
		QT.LOCK_ID = (QT.LOCK_ID % 255) + 1
	--SELECT COUNT(*)
	FROM CPI_QUOTE QT
	JOIN #TMPRC RC
		ON RC.CPI_QUOTE_ID = QT.ID
			
			
UPDATE IH
SET	SPECIAL_HANDLING_XML.modify('replace value of (/SH/Status/text())[1] with "Closed" '),
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'BUG32222',
	LOCK_ID = (LOCK_ID % 255) + 1
--SELECT COUNT(*)
FROM INTERACTION_HISTORY IH
JOIN #tmpIH
	ON #tmpIH.IH_ID = IH.ID


-- Update RequiredCoverage Status from Track to Active
UPDATE RC SET 
GOOD_THRU_DT = NULL , 
CPI_QUOTE_ID = NULL , NOTICE_DT = NULL , NOTICE_TYPE_CD = NULL , 
NOTICE_SEQ_NO = NULL , LAST_EVENT_SEQ_ID = NULL , LAST_EVENT_DT = NULL ,
LAST_SEQ_CONTAINER_ID = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'BUG32222' , 
LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END 
---- SELECT COUNT(*)
FROM REQUIRED_COVERAGE RC JOIN #TMP_NTC TMP 
ON TMP.RC_ID = RC.ID 


UPDATE EVALUATION_EVENT
SET STATUS_CD = 'CLR',
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'BUG32222',
	LOCK_ID = (LOCK_ID % 255) + 1
--SELECT ee.*
FROM
	EVALUATION_EVENT ee
	JOIN #TMP_NTC te ON ee.REQUIRED_COVERAGE_ID = te.RC_ID
	WHERE ee.STATUS_CD = 'PEND'
	AND ee.EVENT_SEQUENCE_ID > 0

GO