USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE

--drop table #tmpIH
SELECT C.PROPERTY_ID INTO #tmpIH FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX = '2845' AND RC.CPI_QUOTE_ID IS NOT NULL


--drop table #tmpCPI
SELECT RELATE_ID INTO #tmpCPI FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT * FROM #tmpIH)
AND TYPE_CD= 'CPI'
AND SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar (50)') = 'Open'


SELECT cpi.* 
INTO UniTracHDStorage..Bug44998_CPIQuote
FROM dbo.CPI_ACTIVITY CPI
JOIN dbo.REQUIRED_COVERAGE RC ON RC.CPI_QUOTE_ID = CPI.CPI_QUOTE_ID
WHERE cpi.CPI_QUOTE_ID IN (SELECT * FROM #tmpCPI)

SELECT * 
--INTO UniTracHDStorage..Bug44998_InteractionHistory
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT * FROM #tmpIH)
AND TYPE_CD= 'CPI'
AND SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar (50)') = 'Closed'
AND ID NOT IN (380951817)


UPDATE cpi 
SET CPI.PURGE_DT = GETDATE()
--SELECT * 
FROM dbo.CPI_ACTIVITY CPI
JOIN dbo.REQUIRED_COVERAGE RC ON RC.CPI_QUOTE_ID = CPI.CPI_QUOTE_ID
WHERE cpi.CPI_QUOTE_ID IN (SELECT * FROM #tmpCPI)
--2018-11-01 00:00:00.0000000


SELECT *
INTO UniTracHDStorage..Bug44998_RequiredCoverage
FROM dbo.REQUIRED_COVERAGE
WHERE CPI_QUOTE_ID IN (SELECT * FROM #tmpCPI)



UPDATE RC
SET RC.CPI_QUOTE_ID = NULL, RC.UPDATE_DT = GETDATE(), RC.UPDATE_USER_TX = '', RC.LOCK_ID = RC.LOCK_ID+1
--SELECT CPI_QUOTE_ID, * 
FROM dbo.REQUIRED_COVERAGE RC
WHERE ID IN (SELECT ID FROM UniTracHDStorage..Bug44998_RequiredCoverage)

UPDATE IH
SET purge_dt = NULL, IH.SPECIAL_HANDLING_XML= '<SH>
  <Status>Closed</Status>
  <RC>186095467</RC>
  <StatusDate>1/30/2018</StatusDate>
  <Reason>Notice Cycle Cleared</Reason>
  <EffDate>11/1/2017</EffDate>
  <ExDate>11/1/2018</ExDate>
  <Premium>2658</Premium>
</SH>', IH.NOTE_TX = NULL
--SELECT * 
FROM dbo.INTERACTION_HISTORY  IH
WHERE ID IN (SELECT id FROM UniTracHDStorage..Bug44998_InteractionHistory)




UPDATE IH
SET 
    IH.NOTE_TX = --'Notice Cycle Cleared' 
	NULL
--SELECT * 
FROM dbo.INTERACTION_HISTORY IH
WHERE ID IN ( 380954815 )



UPDATE IH SET IH.NOTE_TX = 'Notice Cycle Cleared', IH.PURGE_DT = GETDATE()
	--SELECT * 
FROM dbo.INTERACTION_HISTORY  IH
WHERE IH.ID = 407272627





SELECT * 
--INTO UniTracHDStorage..Bug44998_InteractionHistory
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT * FROM #tmpIH)
AND TYPE_CD= 'CPI'
AND SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar (50)') = 'Closed'
AND ID NOT IN (380951817)



SELECT CPI_QUOTE_ID,* FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (124205723)


--40376161