use unitrac 


SELECT ldr.ID AS ldr_id, lp.ID AS lp_id
INTO #tmp
FROM BUSINESS_OPTION_GROUP bog
JOIN LENDER_PRODUCT lp ON lp.ID = bog.RELATE_ID
JOIN LENDER ldr ON ldr.ID = lp.LENDER_ID
JOIN BUSINESS_OPTION bo on bo.BUSINESS_OPTION_GROUP_ID = bog.id
WHERE bog.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
AND bog.PURGE_DT is NULL
AND lp.PURGE_DT is NULL
AND ldr.PURGE_DT is null
AND bo.PURGE_DT is NULL
AND ldr.TEST_IN = 'N'
AND bo.NAME_TX = 'EventOptionReaudit'
AND ISNULL(bo.DEFAULT_VALUE_TX, '') = ''
SELECT ldr.ID AS ldr_id, lp.ID AS lp_id
INTO #tmp2
FROM BUSINESS_OPTION_GROUP bog
JOIN LENDER_PRODUCT lp ON lp.ID = bog.RELATE_ID
JOIN LENDER ldr ON ldr.ID = lp.LENDER_ID
JOIN BUSINESS_OPTION bo on bo.BUSINESS_OPTION_GROUP_ID = bog.id
WHERE bog.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
AND bo.NAME_TX = 'LFPEventOptionReaudit'
AND bog.PURGE_DT is NULL
AND lp.PURGE_DT is NULL
AND ldr.PURGE_DT is null
AND bo.PURGE_DT is NULL
AND ldr.TEST_IN = 'N'
AND ISNULL(bo.DEFAULT_VALUE_TX, '') = ''


UPDATE bo
SET bo.DEFAULT_VALUE_TX = '999', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'Bug46604'
FROM BUSINESS_OPTION_GROUP bog
JOIN LENDER_PRODUCT lp ON lp.ID = bog.RELATE_ID
JOIN LENDER ldr ON ldr.ID = lp.LENDER_ID
JOIN BUSINESS_OPTION bo on bo.BUSINESS_OPTION_GROUP_ID = bog.id
WHERE bog.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
AND bog.PURGE_DT is NULL
AND lp.PURGE_DT is NULL
AND ldr.PURGE_DT is null
AND bo.PURGE_DT is NULL
AND ldr.TEST_IN = 'N'
AND bo.NAME_TX = 'EventOptionReaudit'
AND ISNULL(bo.DEFAULT_VALUE_TX, '') = ''


UPDATE bo
SET bo.DEFAULT_VALUE_TX = '99999', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'Bug46604'
FROM BUSINESS_OPTION_GROUP bog
JOIN LENDER_PRODUCT lp ON lp.ID = bog.RELATE_ID
JOIN LENDER ldr ON ldr.ID = lp.LENDER_ID
JOIN BUSINESS_OPTION bo on bo.BUSINESS_OPTION_GROUP_ID = bog.id
WHERE bog.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
AND bo.NAME_TX = 'LFPEventOptionReaudit'
AND bog.PURGE_DT is NULL
AND lp.PURGE_DT is NULL
AND ldr.PURGE_DT is null
AND bo.PURGE_DT is NULL
AND ldr.TEST_IN = 'N'
AND ISNULL(bo.DEFAULT_VALUE_TX, '') = ''



UPDATE lpc
SET LAST_CHANGE_DT = GETDATE()
FROM LENDER_PRODUCT_CHANGE lpc
JOIN #tmp2 t ON t.lp_id = lpc.ID
JOIN #tmp t1 ON t1.ldr_id = t.ldr_id

​