USE UniTrac

DECLARE @BATCH_CREATE_START_DT DATETIME=NULL
DECLARE @BATCH_CREATE_END_DT DATETIME=NULL

SET @BATCH_CREATE_START_DT = '2016-10-01 00:00:01'
SET @BATCH_CREATE_END_DT = '2016-10-30 23:59:59'

SELECT DISTINCT
			OB.EXTERNAL_ID AS [EXTERNAL_BATCH_ID],
			L.CODE_TX [LENDER_CODE],
			L.NAME_TX AS [LENDER_NAME],
			PD.NAME_TX AS [PROCESS NAME],
			OB.CREATE_DT AS [BATCH_DATE],
			 DC.PRINT_STATUS_ASSIGNED_DT  AS [LAST_SUBMITTED_DATE],
			 CASE OC.OUTPUT_TYPE_CD WHEN 'IH' THEN DC.PRINTED_DT ELSE OBL.CREATE_DT END AS [COMPLETED_DATE],
			 CONTENT_XML.value('(/Content/LenderAdmin/Name)[1]', 'varchar (50)') [Lender Admin]

	FROM
			OUTPUT_BATCH OB
			INNER JOIN OUTPUT_CONFIGURATION OC ON OB.OUTPUT_CONFIGURATION_ID=OC.ID
			INNER JOIN LENDER L ON OC.RELATE_ID=L.ID AND OC.RELATE_CLASS_TX='Allied.UniTrac.Lender'
			INNER JOIN PROCESS_LOG PL ON OB.PROCESS_LOG_ID=PL.ID
			INNER JOIN PROCESS_DEFINITION PD ON PL.PROCESS_DEFINITION_ID=PD.ID
			INNER JOIN dbo.WORK_ITEM WI ON WI.RELATE_ID = PL.ID AND WI.RELATE_TYPE_CD = 'Osprey.ProcessMgr.ProcessLog' 
			INNER JOIN PROCESS_LOG_ITEM PLI ON PL.ID=PLI.PROCESS_LOG_ID
			INNER JOIN FORCE_PLACED_CERTIFICATE FPC ON PLI.RELATE_ID=FPC.ID AND PLI.RELATE_TYPE_CD='Allied.UniTrac.ForcePlacedCertificate'
			INNER JOIN DOCUMENT_CONTAINER DC ON FPC.ID=DC.RELATE_ID AND DC.RELATE_CLASS_NAME_TX='Allied.UniTrac.ForcePlacedCertificate'
			LEFT OUTER JOIN OUTPUT_BATCH_LOG OBL ON OBL.OUTPUT_BATCH_ID = OB.ID AND OBL.LOG_TXN_TYPE_CD='Consolidate'		
WHERE OC.TYPE_CD='FPC'
AND NOT(OC.OUTPUT_TYPE_CD = 'IH' AND DC.PRINTED_DT IS NULL)
AND NOT(OC.OUTPUT_TYPE_CD <> 'IH' AND OBL.CREATE_DT IS NULL)
AND ((OC.OUTPUT_TYPE_CD = 'IH' AND DC.PRINTED_DT >= @BATCH_CREATE_START_DT) OR (OC.OUTPUT_TYPE_CD <> 'IH' AND OBL.CREATE_DT >= @BATCH_CREATE_START_DT))
AND ((OC.OUTPUT_TYPE_CD = 'IH' AND DC.PRINTED_DT <= @BATCH_CREATE_END_DT) OR (OC.OUTPUT_TYPE_CD <> 'IH' AND OBL.CREATE_DT <= @BATCH_CREATE_END_DT))
ORDER BY L.CODE_TX, OB.EXTERNAL_ID

