SELECT  PDA.VALUE_TX,* --INTO UniTrac_Old..DBChange
 FROM dbo.PREPROCESSING_DETAIL PD
INNER JOIN dbo.DELIVERY_INFO_GROUP DIG ON DIG.ID = PD.DELIVERY_INFO_GROUP_ID
INNER JOIN dbo.PPDATTRIBUTE PDA ON PDA.PREPROCESSING_DETAIL_ID = PD.ID
WHERE PDA.CODE_CD = 'DBServer' AND PDA.VALUE_TX = 'UTSTAGE01' 
