USE UniTrac


SELECT * FROM dbo.REPORT_HISTORY
WHERE STATUS_CD = 'PEND'




SELECT COUNT(*)[Number of Reports Done by UBSRPT], MAX(RECORD_COUNT_NO) [Last Report Done by UBSRPT]
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'COMP' AND REPORT_ID = '27'
		AND UPDATE_USER_TX = 'UBSRPT'
		 


SELECT DISTINCT REPORT_DATA_XML.value( '(/ReportData/Report/Title/@value)[1]', 'varchar(500)' ) as TITLE
 FROM dbo.REPORT_HISTORY
WHERE STATUS_CD != 'COMP' AND RECORD_COUNT_NO >= '322444'
AND UPDATE_USER_TX = 'UBSRPT' AND REPORT_ID = '27'