USE [UniTrac]
GO

/****** Object:  StoredProcedure [dbo].[GetForcePlacedCertificates]    Script Date: 11/9/2016 11:37:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--Changes to Force_Placed_Certificate columns also have to be made to GetForcePlacedCertificatesForBilling
CREATE PROCEDURE [dbo].[GetForcePlacedCertificates] (
	@id BIGINT = NULL
	,@lenderCode NVARCHAR(10) = NULL
	,@startDate DATETIME2 = NULL
	,@endDate DATETIME2 = NULL
	,@fpcNumber NVARCHAR(18) = NULL
	,@requiredCoverageId BIGINT = NULL
	,@loanId BIGINT = NULL
	,@lenderFinTxnId BIGINT = NULL
	,@billingGroupId BIGINT = NULL
	,@lCGCTId BIGINT = NULL
	,@onlyBLIT INT = 0
	,@lenderId BIGINT = NULL
	,@openFunding CHAR(1) = NULL
	,@agencyId BIGINT = NULL
	,@loanIdviaRC BIGINT = NULL
	,@masterPolicyId BIGINT = NULL
	,@isServiceFeeInvoiceCall VARCHAR(1) = NULL
	,@isLenderUnitracTxnProcessCall VARCHAR(1) = NULL
	)
AS
BEGIN
	SET NOCOUNT ON

	IF @id = 0
		SET @id = NULL

	IF @lCGCTId = 0
		SET @lCGCTId = NULL

	IF @billingGroupId = 0
		SET @billingGroupId = NULL

	IF @lenderFinTxnId = 0
		SET @lenderFinTxnId = NULL

	IF @agencyId = 0
		SET @agencyId = NULL

	IF @masterPolicyId = 0
		SET @masterPolicyId = NULL

	IF (@openFunding = 'Y')
	BEGIN
		IF (@billingGroupId IS NOT NULL)
		BEGIN
			SELECT TOP 1000 0 AS ID
				,@lenderFinTxnId AS LFT_ID
				,OFU.FPC_ID
				,NULL AS TXN_TYPE_CD
				,0 AS AMOUNT_NO
				,OFU.AMOUNT_NO AS AP_AR_AMOUNT_NO
				,@billingGroupId AS BILLING_GROUP_ID
				,0 AS LOCK_ID
				,dbo.GetFPCOutstandingAmount(ofu.FPC_ID)
				,dbo.GetFPCTotalFundAmount(ofu.FPC_ID)
				,dbo.GetFPCTotalRefundAmount(ofu.FPC_ID)
				,dbo.GetFPCIssueAmount(ofu.FPC_ID)
				,dbo.GetFPCIsBilled(ofu.FPC_ID)
				,F.ID
				,F.LOAN_ID
				,F.CPI_QUOTE_ID
				,F.NUMBER_TX
				,F.PRODUCER_NUMBER_TX
				,F.LOAN_NUMBER_TX
				,F.ACTIVE_IN
				,F.MONTHLY_BILLING_IN
				,F.HOLD_IN
				,F.CLAIM_PENDING_IN
				,F.CURRENT_PAYMENT_AMOUNT_NO
				,F.PREVIOUS_PAYMENT_AMOUNT_NO
				,F.CREATED_BY_TX
				,F.STATUS_CD
				,F.LOCK_ID
				,F.CAPTURED_DATA_XML
				,F.GENERATION_SOURCE_CD
				,F.EXPECTED_ISSUE_DT
				,F.ISSUE_DT
				,F.EFFECTIVE_DT
				,F.EXPIRATION_DT
				,F.CANCELLATION_DT
				,F.TEMPLATE_ID
				,F.COVER_LETTER_TEMPLATE_ID
				,F.PDF_GENERATE_CD
				,F.MSG_LOG_TX
				,---added by AD-01/25/12 - Bug11392
				F.CARRIER_ID
				,F.MASTER_POLICY_ID
				,F.MASTER_POLICY_ASSIGNMENT_ID
				,F.AUTH_REQ_DT
				,F.QUICK_ISSUE_IN
				,F.BILL_CD
				,F.BILLING_STATUS_CD
				,F.EARNED_PAYMENT_NO
				,F.AUTHORIZED_BY_TX
				,F.LENDER_INTENT
				,F.PAYMENT_REPORT_CD
				,F.PAYMENT_REPORT_DT
				,F.PIR_DT
				,F.CREATE_DT
			FROM FORCE_PLACED_CERTIFICATE F
			INNER JOIN (
				SELECT ft.FPC_ID
					,SUM(ft.AMOUNT_NO) AS 'AMOUNT_NO'
				FROM FINANCIAL_TXN_APPLY A
				INNER JOIN FINANCIAL_TXN FT ON a.FINANCIAL_TXN_ID = FT.ID
					AND FT.PURGE_DT IS NULL
				WHERE A.BILLING_GROUP_ID = @billingGroupId
					AND A.PURGE_DT IS NULL
				GROUP BY ft.FPC_ID
				) OFU ON F.ID = OFU.FPC_ID
			OUTER APPLY (
				SELECT SUM(AMOUNT_NO) AS FT_AMOUNT_NO
				FROM FINANCIAL_TXN FT
				WHERE FT.PURGE_DT IS NULL
					AND FT.FPC_ID = F.ID
				) AS FT
			WHERE F.PURGE_DT IS NULL
				AND (
					(FT.FT_AMOUNT_NO <> 0)
					OR (
						(dbo.GetFPCOutstandingAmount(ofu.FPC_ID) = 0)
						AND (isnull(dbo.GetFPCTotalFundAmount(ofu.FPC_ID), 0) = isnull(dbo.GetFPCTotalRefundAmount(ofu.FPC_ID), 0))
						)
					)
			ORDER BY FT.FT_AMOUNT_NO
		END
		ELSE IF (@id IS NOT NULL)
		BEGIN
			SELECT 0 AS ID
				,@lenderFinTxnId AS LFT_ID
				,@id AS FPC_ID
				,NULL AS TXN_TYPE_CD
				,0 AS AMOUNT_NO
				,(
					SELECT sum(ft.AMOUNT_NO)
					FROM FINANCIAL_TXN ft
					WHERE ft.FPC_ID = @id
						AND ft.PURGE_DT IS NULL
					) AS AP_AR_AMOUNT_NO
				,NULL AS BILLING_GROUP_ID
				,0 AS LOCK_ID
				,dbo.GetFPCOutstandingAmount(@id)
				,dbo.GetFPCTotalFundAmount(@id)
				,dbo.GetFPCTotalRefundAmount(@id)
				,dbo.GetFPCIssueAmount(@id)
				,dbo.GetFPCIsBilled(@id)
		END
		ELSE IF (@lenderFinTxnId IS NOT NULL)
		BEGIN
			SELECT OPF.ID
				,OPF.LFT_ID
				,OPF.FPC_ID
				,OPF.TXN_TYPE_CD
				,OPF.AMOUNT_NO
				,CASE 
					WHEN 0 = OPF.BILLING_GROUP_ID
						THEN (
								SELECT sum(ft.AMOUNT_NO)
								FROM FINANCIAL_TXN ft
								WHERE ft.FPC_ID = OPF.FPC_ID
									AND ft.PURGE_DT IS NULL
								)
					ELSE (
							SELECT sum(ft.AMOUNT_NO)
							FROM FINANCIAL_TXN ft
							INNER JOIN FINANCIAL_TXN_APPLY fta ON ft.ID = fta.FINANCIAL_TXN_ID
								AND fta.BILLING_GROUP_ID = OPF.BILLING_GROUP_ID
							WHERE ft.FPC_ID = OPF.FPC_ID
								AND ft.PURGE_DT IS NULL
							)
					END AS AP_AR_AMOUNT_NO
				,OPF.BILLING_GROUP_ID
				,OPF.LOCK_ID
				,dbo.GetFPCOutstandingAmount(OPF.FPC_ID)
				,dbo.GetFPCTotalFundAmount(OPF.FPC_ID)
				,dbo.GetFPCTotalRefundAmount(OPF.FPC_ID)
				,dbo.GetFPCIssueAmount(OPF.FPC_ID)
				,dbo.GetFPCIsBilled(OPF.FPC_ID)
				,FPC.ID
				,FPC.LOAN_ID
				,FPC.CPI_QUOTE_ID
				,FPC.NUMBER_TX
				,FPC.PRODUCER_NUMBER_TX
				,FPC.LOAN_NUMBER_TX
				,FPC.ACTIVE_IN
				,MONTHLY_BILLING_IN
				,FPC.HOLD_IN
				,FPC.CLAIM_PENDING_IN
				,FPC.CURRENT_PAYMENT_AMOUNT_NO
				,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
				,FPC.CREATED_BY_TX
				,FPC.STATUS_CD
				,FPC.LOCK_ID
				,FPC.CAPTURED_DATA_XML
				,FPC.GENERATION_SOURCE_CD
				,FPC.EXPECTED_ISSUE_DT
				,FPC.ISSUE_DT
				,FPC.EFFECTIVE_DT
				,FPC.EXPIRATION_DT
				,FPC.CANCELLATION_DT
				,FPC.TEMPLATE_ID
				,FPC.COVER_LETTER_TEMPLATE_ID
				,FPC.PDF_GENERATE_CD
				,FPC.MSG_LOG_TX
				,FPC.CARRIER_ID
				,FPC.MASTER_POLICY_ID
				,FPC.MASTER_POLICY_ASSIGNMENT_ID
				,FPC.AUTH_REQ_DT
				,FPC.QUICK_ISSUE_IN
				,FPC.BILL_CD
				,FPC.BILLING_STATUS_CD
				,FPC.EARNED_PAYMENT_NO
				,FPC.AUTHORIZED_BY_TX
				,FPC.LENDER_INTENT
				,FPC.PAYMENT_REPORT_CD
				,FPC.PAYMENT_REPORT_DT
				,FPC.PIR_DT
				,FPC.CREATE_DT
			FROM FORCE_PLACED_CERTIFICATE FPC
			INNER JOIN OPEN_FUNDING OPF ON FPC.ID = OPF.FPC_ID
				AND OPF.LFT_ID = @lenderFinTxnId
				AND OPF.PURGE_DT IS NULL
				AND OPF.BILLING_GROUP_ID IS NOT NULL
			WHERE FPC.PURGE_DT IS NULL
		END
	END
	ELSE IF @id > 0
	BEGIN
		IF (
				(ISNULL(@lCGCTId, 0) > 0)
				AND (@onlyBLIT = 0)
				)
		BEGIN
			SELECT FPC.ID
				,FPC.LOAN_ID
				,FPC.CPI_QUOTE_ID
				,FPC.NUMBER_TX
				,FPC.PRODUCER_NUMBER_TX
				,FPC.LOAN_NUMBER_TX
				,FPC.ACTIVE_IN
				,MONTHLY_BILLING_IN
				,FPC.HOLD_IN
				,FPC.CLAIM_PENDING_IN
				,FPC.CURRENT_PAYMENT_AMOUNT_NO
				,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
				,FPC.CREATED_BY_TX
				,FPC.STATUS_CD
				,FPC.LOCK_ID
				,FPC.CAPTURED_DATA_XML
				,FPC.GENERATION_SOURCE_CD
				,FPC.EXPECTED_ISSUE_DT
				,FPC.ISSUE_DT
				,FPC.EFFECTIVE_DT
				,FPC.EXPIRATION_DT
				,FPC.CANCELLATION_DT
				,FPC.TEMPLATE_ID
				,FPC.COVER_LETTER_TEMPLATE_ID
				,FPC.PDF_GENERATE_CD
				,FPC.MSG_LOG_TX
				,FPC.CARRIER_ID
				,FPC.MASTER_POLICY_ID
				,FPC.MASTER_POLICY_ASSIGNMENT_ID
				,FPC.AUTH_REQ_DT
				,FPC.QUICK_ISSUE_IN
				,FPC.BILL_CD
				,FPC.BILLING_STATUS_CD
				,FPC.EARNED_PAYMENT_NO
				,FPC.AUTHORIZED_BY_TX
				,FPC.LENDER_INTENT
				,FPC.PAYMENT_REPORT_CD
				,FPC.PAYMENT_REPORT_DT
				,FPC.PIR_DT
				,FPC.CREATE_DT
			FROM FORCE_PLACED_CERTIFICATE FPC
			INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPR ON FPR.FPC_ID = FPC.ID
			INNER JOIN REQUIRED_COVERAGE RC ON RC.ID = FPR.REQUIRED_COVERAGE_ID
			WHERE (
					(RC.LCGCT_ID = @lCGCTId)
					AND (FPC.ID = @id)
					AND (FPC.STATUS_CD ! = 'UH')
					AND (FPC.HOLD_IN != 'Y')
					AND (FPC.PURGE_DT IS NULL)
					)
				AND FPR.PURGE_DT IS NULL
		END
		ELSE IF (
				(ISNULL(@lCGCTId, 0) > 0)
				AND (@onlyBLIT != 0)
				)
		BEGIN
			SELECT FPC.ID
				,FPC.LOAN_ID
				,FPC.CPI_QUOTE_ID
				,FPC.NUMBER_TX
				,FPC.PRODUCER_NUMBER_TX
				,FPC.LOAN_NUMBER_TX
				,FPC.ACTIVE_IN
				,MONTHLY_BILLING_IN
				,FPC.HOLD_IN
				,FPC.CLAIM_PENDING_IN
				,FPC.CURRENT_PAYMENT_AMOUNT_NO
				,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
				,FPC.CREATED_BY_TX
				,FPC.STATUS_CD
				,FPC.LOCK_ID
				,FPC.CAPTURED_DATA_XML
				,FPC.GENERATION_SOURCE_CD
				,FPC.EXPECTED_ISSUE_DT
				,FPC.ISSUE_DT
				,FPC.EFFECTIVE_DT
				,FPC.EXPIRATION_DT
				,FPC.CANCELLATION_DT
				,FPC.TEMPLATE_ID
				,FPC.COVER_LETTER_TEMPLATE_ID
				,FPC.PDF_GENERATE_CD
				,FPC.MSG_LOG_TX
				,FPC.CARRIER_ID
				,FPC.MASTER_POLICY_ID
				,FPC.MASTER_POLICY_ASSIGNMENT_ID
				,FPC.AUTH_REQ_DT
				,FPC.QUICK_ISSUE_IN
				,FPC.BILL_CD
				,FPC.BILLING_STATUS_CD
				,FPC.EARNED_PAYMENT_NO
				,FPC.AUTHORIZED_BY_TX
				,FPC.LENDER_INTENT
				,FPC.PAYMENT_REPORT_CD
				,FPC.PAYMENT_REPORT_DT
				,FPC.PIR_DT
				,FPC.CREATE_DT
			FROM FORCE_PLACED_CERTIFICATE FPC
			INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPR ON FPR.FPC_ID = FPC.ID
			INNER JOIN REQUIRED_COVERAGE RC ON RC.ID = FPR.REQUIRED_COVERAGE_ID
			WHERE (
					(RC.LCGCT_ID = @lCGCTId)
					AND (FPC.ID = @id)
					AND (FPC.BILLING_STATUS_CD = 'BLIT')
					AND (FPC.STATUS_CD ! = 'UH')
					AND (FPC.HOLD_IN != 'Y')
					AND (FPC.PURGE_DT IS NULL)
					)
				AND FPR.PURGE_DT IS NULL
		END
		ELSE
		BEGIN
			SELECT ID
				,LOAN_ID
				,CPI_QUOTE_ID
				,NUMBER_TX
				,PRODUCER_NUMBER_TX
				,LOAN_NUMBER_TX
				,ACTIVE_IN
				,MONTHLY_BILLING_IN
				,HOLD_IN
				,CLAIM_PENDING_IN
				,CURRENT_PAYMENT_AMOUNT_NO
				,PREVIOUS_PAYMENT_AMOUNT_NO
				,CREATED_BY_TX
				,STATUS_CD
				,LOCK_ID
				,CAPTURED_DATA_XML
				,GENERATION_SOURCE_CD
				,EXPECTED_ISSUE_DT
				,ISSUE_DT
				,EFFECTIVE_DT
				,EXPIRATION_DT
				,CANCELLATION_DT
				,TEMPLATE_ID
				,COVER_LETTER_TEMPLATE_ID
				,PDF_GENERATE_CD
				,MSG_LOG_TX
				,---added by AD-01/25/12 - Bug11392
				CARRIER_ID
				,MASTER_POLICY_ID
				,MASTER_POLICY_ASSIGNMENT_ID
				,AUTH_REQ_DT
				,QUICK_ISSUE_IN
				,BILL_CD
				,BILLING_STATUS_CD
				,EARNED_PAYMENT_NO
				,AUTHORIZED_BY_TX
				,LENDER_INTENT
				,PAYMENT_REPORT_CD
				,PAYMENT_REPORT_DT
				,PIR_DT
				,CREATE_DT
			FROM FORCE_PLACED_CERTIFICATE F
			WHERE ID = @id
		END
	END
			-- merging ...ForBilling sproc
	ELSE IF (
			(ISNULL(@lCGCTId, 0) > 0)
			AND (@onlyBLIT = 0)
			)
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,FPC.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPR ON FPR.FPC_ID = FPC.ID
		INNER JOIN REQUIRED_COVERAGE RC ON RC.ID = FPR.REQUIRED_COVERAGE_ID
		WHERE (
				(RC.LCGCT_ID = @lCGCTId)
				AND (FPC.STATUS_CD ! = 'UH')
				AND (FPC.HOLD_IN != 'Y')
				AND (FPC.PURGE_DT IS NULL)
				)
			AND FPR.PURGE_DT IS NULL
	END
	ELSE IF (
			(ISNULL(@lCGCTId, 0) > 0)
			AND (@onlyBLIT != 0)
			)
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,FPC.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPR ON FPR.FPC_ID = FPC.ID
		INNER JOIN REQUIRED_COVERAGE RC ON RC.ID = FPR.REQUIRED_COVERAGE_ID
		WHERE (
				(RC.LCGCT_ID = @lCGCTId)
				AND (FPC.BILLING_STATUS_CD = 'BLIT')
				AND (FPC.STATUS_CD ! = 'UH')
				AND (FPC.HOLD_IN != 'Y')
				AND (FPC.PURGE_DT IS NULL)
				)
			AND FPR.PURGE_DT IS NULL
	END
	ELSE IF ISNULL(@billingGroupId, 0) > 0
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		WHERE FPC.ID IN (
				SELECT DISTINCT FT.FPC_ID
				FROM FINANCIAL_TXN FT
				INNER JOIN FINANCIAL_TXN_APPLY FTA ON FTA.FINANCIAL_TXN_ID = FT.ID
				WHERE FTA.BILLING_GROUP_ID = @billingGroupId
				)
			AND FPC.PURGE_DT IS NULL
	END
	ELSE IF (
			ISNULL(@lenderCode, '') <> ''
			AND @startDate IS NOT NULL
			AND @endDate IS NOT NULL
			)
	BEGIN
		SELECT ID
			,LOAN_ID
			,CPI_QUOTE_ID
			,NUMBER_TX
			,PRODUCER_NUMBER_TX
			,LOAN_NUMBER_TX
			,ACTIVE_IN
			,MONTHLY_BILLING_IN
			,HOLD_IN
			,CLAIM_PENDING_IN
			,CURRENT_PAYMENT_AMOUNT_NO
			,PREVIOUS_PAYMENT_AMOUNT_NO
			,CREATED_BY_TX
			,STATUS_CD
			,LOCK_ID
			,CAPTURED_DATA_XML
			,GENERATION_SOURCE_CD
			,EXPECTED_ISSUE_DT
			,ISSUE_DT
			,EFFECTIVE_DT
			,EXPIRATION_DT
			,CANCELLATION_DT
			,TEMPLATE_ID
			,COVER_LETTER_TEMPLATE_ID
			,PDF_GENERATE_CD
			,MSG_LOG_TX
			,---added by AD-01/25/12 - Bug11392
			CARRIER_ID
			,MASTER_POLICY_ID
			,MASTER_POLICY_ASSIGNMENT_ID
			,AUTH_REQ_DT
			,QUICK_ISSUE_IN
			,BILL_CD
			,BILLING_STATUS_CD
			,EARNED_PAYMENT_NO
			,AUTHORIZED_BY_TX
			,LENDER_INTENT
			,PAYMENT_REPORT_CD
			,PAYMENT_REPORT_DT
			,PIR_DT
			,CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE F
		WHERE convert(DATE, CREATE_DT, 101) >= convert(DATE, @startDate, 101)
			AND convert(DATE, CREATE_DT, 101) <= convert(DATE, @endDate, 101)
			AND CAPTURED_DATA_XML.value('(//CapturedData/Lender/@number)[1]', 'varchar(10)') = @lenderCode
			AND (
				@fpcNumber IS NULL
				OR F.NUMBER_TX LIKE '%' + @fpcNumber + '%'
				)
			AND F.PURGE_DT IS NULL
	END
			--- Added by AD - 04/13/12
	ELSE IF ISNULL(@requiredCoverageId, 0) > 0
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,FPC.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPR ON FPR.FPC_ID = FPC.ID
		WHERE FPR.REQUIRED_COVERAGE_ID = @requiredCoverageId
			AND FPC.PURGE_DT IS NULL
			AND FPR.PURGE_DT IS NULL
	END
			---- end added - 04/13/12
	ELSE IF ISNULL(@loanId, 0) > 0
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		WHERE FPC.LOAN_ID = @loanId
			AND FPC.PURGE_DT IS NULL
	END
			-- added by OA - 10/29/12
	ELSE IF (
			@fpcNumber IS NOT NULL
			AND @lenderId IS NOT NULL
			)
	BEGIN
		SELECT F.ID
			,F.LOAN_ID
			,F.CPI_QUOTE_ID
			,F.NUMBER_TX
			,F.PRODUCER_NUMBER_TX
			,F.LOAN_NUMBER_TX
			,F.ACTIVE_IN
			,F.MONTHLY_BILLING_IN
			,F.HOLD_IN
			,F.CLAIM_PENDING_IN
			,F.CURRENT_PAYMENT_AMOUNT_NO
			,F.PREVIOUS_PAYMENT_AMOUNT_NO
			,F.CREATED_BY_TX
			,F.STATUS_CD
			,F.LOCK_ID
			,F.CAPTURED_DATA_XML
			,F.GENERATION_SOURCE_CD
			,F.EXPECTED_ISSUE_DT
			,F.ISSUE_DT
			,F.EFFECTIVE_DT
			,F.EXPIRATION_DT
			,F.CANCELLATION_DT
			,F.TEMPLATE_ID
			,F.COVER_LETTER_TEMPLATE_ID
			,F.PDF_GENERATE_CD
			,F.MSG_LOG_TX
			,---added by AD-01/25/12 - Bug11392
			F.CARRIER_ID
			,F.MASTER_POLICY_ID
			,F.MASTER_POLICY_ASSIGNMENT_ID
			,F.AUTH_REQ_DT
			,F.QUICK_ISSUE_IN
			,F.BILL_CD
			,F.BILLING_STATUS_CD
			,F.EARNED_PAYMENT_NO
			,F.AUTHORIZED_BY_TX
			,F.LENDER_INTENT
			,F.PAYMENT_REPORT_CD
			,F.PAYMENT_REPORT_DT
			,F.PIR_DT
			,F.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE F
		INNER JOIN LOAN ON LOAN.ID = F.LOAN_ID
			AND LOAN.LENDER_ID = @lenderId
		WHERE F.NUMBER_TX LIKE @fpcNumber + '%'
			AND F.PURGE_DT IS NULL
	END
			-- end added -10/29/12
	ELSE IF (
			@fpcNumber IS NOT NULL
			AND @lenderId IS NULL
			AND @agencyId IS NOT NULL
			)
	BEGIN
		SELECT F.ID
			,F.LOAN_ID
			,F.CPI_QUOTE_ID
			,F.NUMBER_TX
			,F.PRODUCER_NUMBER_TX
			,F.LOAN_NUMBER_TX
			,F.ACTIVE_IN
			,F.MONTHLY_BILLING_IN
			,F.HOLD_IN
			,F.CLAIM_PENDING_IN
			,F.CURRENT_PAYMENT_AMOUNT_NO
			,F.PREVIOUS_PAYMENT_AMOUNT_NO
			,F.CREATED_BY_TX
			,F.STATUS_CD
			,F.LOCK_ID
			,F.CAPTURED_DATA_XML
			,F.GENERATION_SOURCE_CD
			,F.EXPECTED_ISSUE_DT
			,F.ISSUE_DT
			,F.EFFECTIVE_DT
			,F.EXPIRATION_DT
			,F.CANCELLATION_DT
			,F.TEMPLATE_ID
			,F.COVER_LETTER_TEMPLATE_ID
			,F.PDF_GENERATE_CD
			,F.MSG_LOG_TX
			,---added by AD-01/25/12 - Bug11392
			F.CARRIER_ID
			,F.MASTER_POLICY_ID
			,F.MASTER_POLICY_ASSIGNMENT_ID
			,F.AUTH_REQ_DT
			,F.QUICK_ISSUE_IN
			,F.BILL_CD
			,F.BILLING_STATUS_CD
			,F.EARNED_PAYMENT_NO
			,F.AUTHORIZED_BY_TX
			,F.LENDER_INTENT
			,F.PAYMENT_REPORT_CD
			,F.PAYMENT_REPORT_DT
			,F.PIR_DT
			,F.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE F
		INNER JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE fpcrcr ON fpcrcr.FPC_ID = F.id
			AND fpcrcr.PURGE_DT IS NULL
		INNER JOIN REQUIRED_COVERAGE rc ON rc.id = fpcrcr.required_coverage_id
			AND rc.PURGE_DT IS NULL
		INNER JOIN PROPERTY p ON p.id = rc.property_id
			AND p.Agency_id = @agencyId
			AND p.PURGE_DT IS NULL
		WHERE F.NUMBER_TX LIKE @fpcNumber + '%'
			AND F.PURGE_DT IS NULL
	END
	ELSE IF (
			@lenderId IS NOT NULL
			AND @isLenderUnitracTxnProcessCall IS NULL
			)
	BEGIN
		SELECT F.ID
			,F.LOAN_ID
			,F.CPI_QUOTE_ID
			,F.NUMBER_TX
			,F.PRODUCER_NUMBER_TX
			,F.LOAN_NUMBER_TX
			,F.ACTIVE_IN
			,F.MONTHLY_BILLING_IN
			,F.HOLD_IN
			,F.CLAIM_PENDING_IN
			,F.CURRENT_PAYMENT_AMOUNT_NO
			,F.PREVIOUS_PAYMENT_AMOUNT_NO
			,F.CREATED_BY_TX
			,F.STATUS_CD
			,F.LOCK_ID
			,F.CAPTURED_DATA_XML
			,F.GENERATION_SOURCE_CD
			,F.EXPECTED_ISSUE_DT
			,F.ISSUE_DT
			,F.EFFECTIVE_DT
			,F.EXPIRATION_DT
			,F.CANCELLATION_DT
			,F.TEMPLATE_ID
			,F.COVER_LETTER_TEMPLATE_ID
			,F.PDF_GENERATE_CD
			,F.MSG_LOG_TX
			,---added by AD-01/25/12 - Bug11392
			F.CARRIER_ID
			,F.MASTER_POLICY_ID
			,F.MASTER_POLICY_ASSIGNMENT_ID
			,F.AUTH_REQ_DT
			,F.QUICK_ISSUE_IN
			,F.BILL_CD
			,F.BILLING_STATUS_CD
			,F.EARNED_PAYMENT_NO
			,F.AUTHORIZED_BY_TX
			,F.LENDER_INTENT
			,F.PAYMENT_REPORT_CD
			,F.PAYMENT_REPORT_DT
			,F.PIR_DT
			,F.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE F
		INNER JOIN LOAN ON LOAN.ID = F.LOAN_ID
			AND LOAN.LENDER_ID = @lenderId
		WHERE F.PURGE_DT IS NULL
	END
	ELSE IF (@loanIdviaRC IS NOT NULL)
	BEGIN
		SELECT F.ID
			,F.LOAN_ID
			,F.CPI_QUOTE_ID
			,F.NUMBER_TX
			,F.PRODUCER_NUMBER_TX
			,F.LOAN_NUMBER_TX
			,F.ACTIVE_IN
			,F.MONTHLY_BILLING_IN
			,F.HOLD_IN
			,F.CLAIM_PENDING_IN
			,F.CURRENT_PAYMENT_AMOUNT_NO
			,F.PREVIOUS_PAYMENT_AMOUNT_NO
			,F.CREATED_BY_TX
			,F.STATUS_CD
			,F.LOCK_ID
			,F.CAPTURED_DATA_XML
			,F.GENERATION_SOURCE_CD
			,F.EXPECTED_ISSUE_DT
			,F.ISSUE_DT
			,F.EFFECTIVE_DT
			,F.EXPIRATION_DT
			,F.CANCELLATION_DT
			,F.TEMPLATE_ID
			,F.COVER_LETTER_TEMPLATE_ID
			,F.PDF_GENERATE_CD
			,F.MSG_LOG_TX
			,F.CARRIER_ID
			,F.MASTER_POLICY_ID
			,F.MASTER_POLICY_ASSIGNMENT_ID
			,F.AUTH_REQ_DT
			,F.QUICK_ISSUE_IN
			,F.BILL_CD
			,F.BILLING_STATUS_CD
			,F.EARNED_PAYMENT_NO
			,F.AUTHORIZED_BY_TX
			,F.LENDER_INTENT
			,F.PAYMENT_REPORT_CD
			,F.PAYMENT_REPORT_DT
			,F.PIR_DT
			,F.CREATE_DT
		FROM LOAN
		JOIN COLLATERAL COLL ON COLL.LOAN_ID = LOAN.ID
			AND LOAN.PURGE_DT IS NULL
			AND COLL.PURGE_DT IS NULL
		JOIN PROPERTY PR ON PR.ID = COLL.PROPERTY_ID
			AND PR.PURGE_DT IS NULL
		JOIN REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = PR.ID
			AND RC.PURGE_DT IS NULL
		JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE REL ON REL.REQUIRED_COVERAGE_ID = RC.ID
			AND REL.PURGE_DT IS NULL
		JOIN FORCE_PLACED_CERTIFICATE F ON F.ID = REL.FPC_ID
			AND F.PURGE_DT IS NULL
		WHERE LOAN.ID = @loanIdviaRC
	END
	ELSE IF (@masterPolicyId IS NOT NULL)
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,FPC.CREATE_DT
		FROM FORCE_PLACED_CERTIFICATE FPC
		WHERE FPC.MASTER_POLICY_ID = @masterPolicyId
			AND FPC.PURGE_DT IS NULL
	END
			-- For Service Fee Invoice Calls
	ELSE IF @isServiceFeeInvoiceCall IS NOT NULL
	BEGIN
		SELECT FPC.ID
			,FPC.LOAN_ID
			,FPC.CPI_QUOTE_ID
			,FPC.NUMBER_TX
			,FPC.PRODUCER_NUMBER_TX
			,FPC.LOAN_NUMBER_TX
			,FPC.ACTIVE_IN
			,FPC.MONTHLY_BILLING_IN
			,FPC.HOLD_IN
			,FPC.CLAIM_PENDING_IN
			,FPC.CURRENT_PAYMENT_AMOUNT_NO
			,FPC.PREVIOUS_PAYMENT_AMOUNT_NO
			,FPC.CREATED_BY_TX
			,FPC.STATUS_CD
			,FPC.LOCK_ID
			,FPC.CAPTURED_DATA_XML
			,FPC.GENERATION_SOURCE_CD
			,FPC.EXPECTED_ISSUE_DT
			,FPC.ISSUE_DT
			,FPC.EFFECTIVE_DT
			,FPC.EXPIRATION_DT
			,FPC.CANCELLATION_DT
			,FPC.TEMPLATE_ID
			,FPC.COVER_LETTER_TEMPLATE_ID
			,FPC.PDF_GENERATE_CD
			,FPC.MSG_LOG_TX
			,FPC.CARRIER_ID
			,FPC.MASTER_POLICY_ID
			,FPC.MASTER_POLICY_ASSIGNMENT_ID
			,FPC.AUTH_REQ_DT
			,FPC.QUICK_ISSUE_IN
			,FPC.BILL_CD
			,FPC.BILLING_STATUS_CD
			,FPC.EARNED_PAYMENT_NO
			,FPC.AUTHORIZED_BY_TX
			,FPC.LENDER_INTENT
			,FPC.PAYMENT_REPORT_CD
			,FPC.PAYMENT_REPORT_DT
			,FPC.PIR_DT
			,FPC.CREATE_DT
		FROM dbo.FORCE_PLACED_CERTIFICATE fpc
		INNER JOIN LOAN loan WITH (NOLOCK) ON fpc.LOAN_ID = loan.ID
			AND loan.purge_dt IS NULL
		INNER JOIN DOCUMENT_CONTAINER dc WITH (NOLOCK) ON fpc.ID = dc.RELATE_ID
			AND dc.RELATE_CLASS_NAME_TX = 'Allied.UniTrac.ForcePlacedCertificate'
		WHERE LENDER_ID = @lenderId
			AND dc.PRINT_STATUS_CD = 'PRINTED'
			AND fpc.PURGE_DT IS NULL
			AND dc.PURGE_DT IS NULL
			AND dc.PRINTED_DT BETWEEN @startDate
				AND @endDate
	END
	ELSE IF @isLenderUnitracTxnProcessCall IS NOT NULL
	BEGIN
		SELECT F.ID
			,F.LOAN_ID
			,F.CPI_QUOTE_ID
			,F.NUMBER_TX
			,F.PRODUCER_NUMBER_TX
			,F.LOAN_NUMBER_TX
			,F.ACTIVE_IN
			,F.MONTHLY_BILLING_IN
			,F.HOLD_IN
			,F.CLAIM_PENDING_IN
			,F.CURRENT_PAYMENT_AMOUNT_NO
			,F.PREVIOUS_PAYMENT_AMOUNT_NO
			,F.CREATED_BY_TX
			,F.STATUS_CD
			,F.LOCK_ID
			,F.CAPTURED_DATA_XML
			,F.GENERATION_SOURCE_CD
			,F.EXPECTED_ISSUE_DT
			,F.ISSUE_DT
			,F.EFFECTIVE_DT
			,F.EXPIRATION_DT
			,F.CANCELLATION_DT
			,F.TEMPLATE_ID
			,F.COVER_LETTER_TEMPLATE_ID
			,F.PDF_GENERATE_CD
			,F.MSG_LOG_TX
			,---added by AD-01/25/12 - Bug11392
			F.CARRIER_ID
			,F.MASTER_POLICY_ID
			,F.MASTER_POLICY_ASSIGNMENT_ID
			,F.AUTH_REQ_DT
			,F.QUICK_ISSUE_IN
			,F.BILL_CD
			,F.BILLING_STATUS_CD
			,F.EARNED_PAYMENT_NO
			,F.AUTHORIZED_BY_TX
			,F.LENDER_INTENT
			,F.PAYMENT_REPORT_CD
			,F.PAYMENT_REPORT_DT
			,F.PIR_DT
			,F.CREATE_DT
		FROM dbo.FORCE_PLACED_CERTIFICATE f
		WHERE Id IN (
				SELECT DISTINCT fpc.Id
				FROM FORCE_PLACED_CERTIFICATE fpc WITH (NOLOCK)
				INNER JOIN LOAN loan WITH (NOLOCK) ON fpc.LOAN_ID = loan.ID
					AND loan.PURGE_DT IS NULL
				INNER JOIN DOCUMENT_CONTAINER dc WITH (NOLOCK) ON fpc.ID = dc.RELATE_ID
					AND dc.RELATE_CLASS_NAME_TX = 'Allied.UniTrac.ForcePlacedCertificate'
				LEFT OUTER JOIN LENDER_UNITRAC_TRANSACTION lut ON lut.TYPE_CD_TX IN (
						'SENDFPC'
						,'SENDNOTICE'
						)
					AND lut.RELATE_CLASS_ID = fpc.ID
					AND lut.RELATE_CLASS_NAME_TX = 'Allied.UniTrac.ForcePlacedCertificate'
				WHERE LENDER_ID = @lenderId
					AND dc.PRINT_STATUS_CD = 'PRINTED'
					AND fpc.PURGE_DT IS NULL
					AND dc.PURGE_DT IS NULL
					AND lut.ID IS NULL
				)
	END
END

GO

