USE UniTrac

SELECT 
 '''' + LND.CODE_TX AS [Lender ID|TextFormat], LND.NAME_TX AS [Lender Name], '''' + LOB.CODE_TX  AS [Branch ID|TextFormat],  
LCGCT.TYPE_CD as Coverage,
BO1.DEFAULT_VALUE_TX AS [Forced Plcy Opt Audit Back Days|WholeNumberFormat],
BO2.DEFAULT_VALUE_TX AS [Forced Plcy Opt Audit Back Date|DateFormat],
BO3.DEFAULT_VALUE_TX AS [Forced Plcy Opt Uninsured Back Date|DateFormat],
BO4.DEFAULT_VALUE_TX AS [Forced Plcy Opt Uninsured Back Days|WholeNumberFormat]

--SELECT DISTINCT  LP.NAME_TX, lnd.NAME_TX
FROM Unitrac.dbo.LENDER LND
JOIN Unitrac.dbo.LENDER_PRODUCT LP on LP.LENDER_ID = LND.ID
JOIN Unitrac.dbo.LENDER_COLLATERAL_GROUP_COVERAGE_TYPE LCGCT on LCGCT.LENDER_PRODUCT_ID = LP.ID
JOIN Unitrac.dbo.LENDER_ORGANIZATION LO on LO.ID = LCGCT.DIVISION_LENDER_ORG_ID
JOIN Unitrac.dbo.LENDER_ORGANIZATION LOB ON LOB.LENDER_ID = LND.ID AND LOB.TYPE_CD = 'BRCH'
LEFT JOIN Unitrac.dbo.BUSINESS_OPTION_GROUP BOG ON BOG.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct' and BOG.RELATE_ID = LP.ID
LEFT JOIN Unitrac.dbo.BUSINESS_OPTION BO1 ON BOG.ID = BO1.BUSINESS_OPTION_GROUP_ID AND BO1.NAME_TX = 'ForcedPlcyOptAuditBackDays'
LEFT JOIN Unitrac.dbo.BUSINESS_OPTION BO2 ON BOG.ID = BO2.BUSINESS_OPTION_GROUP_ID AND BO2.NAME_TX = 'ForcedPlcyOptAuditBackdate'
LEFT JOIN Unitrac.dbo.BUSINESS_OPTION BO3 ON BOG.ID = BO3.BUSINESS_OPTION_GROUP_ID AND BO3.NAME_TX = 'ForcedPlcyOptUninsuredBackdate'
LEFT JOIN Unitrac.dbo.BUSINESS_OPTION BO4 ON BOG.ID = BO4.BUSINESS_OPTION_GROUP_ID AND BO4.NAME_TX = 'ForcedPlcyOptUninsuredBackdays'
WHERE 
(
BO1.DEFAULT_VALUE_TX IS NOT NULL 
OR BO2.DEFAULT_VALUE_TX IS NOT NULL
OR BO3.DEFAULT_VALUE_TX IS NOT NULL
OR BO4.DEFAULT_VALUE_TX IS NOT NULL
)
AND LND.CANCEL_DT IS NULL
AND ISNULL(LND.TEST_IN,'N') <> 'Y'
ORDER BY LND.CODE_TX, LOB.CODE_TX, CASE WHEN LCGCT.TYPE_CD='HAZARD' THEN 1 WHEN LCGCT.TYPE_CD='FLOOD' THEN 2 ELSE 0 END




SELECT  CODE_CD [System] ,
        MEANING_TX [Full length Coverage] ,
        DESCRIPTION_TX [Description]
FROM    dbo.REF_CODE
WHERE   CODE_CD IN ( 'AUTO-LIABILITY', 'BIZ-INTERRUPT', 'BLDR-FLOOD',
                     'BLDR-HAZARD', 'COMM-CONTENT', 'COMM-LIABILITY',
                     'CONTRACTOR-LIABILITY', 'EARTHQUAKE', 'EQUIPMENT',
                     'FLOOD', 'HAZARD', 'HUR', 'LIFE', 'PHYS-DAMAGE',
                     'POLLUTION-LIABILITY', 'PROF-LIABILITY', 'REO-LIABILITY',
                     'WIND', 'WORKER-COMP' )
        AND DOMAIN_CD = 'Coverage'