
UPDATE dbo.USERS
SET PASSWORD_TX = 'K91/Af1stif22ENVJtnKJpUjGs1TXSgQ'
--SELECT * FROM users 
WHERE FAMILY_NAME_TX = 'Miller' AND ID = '107'



UPDATE dbo.USERS
SET PASSWORD_TX = 'QbygESTMUJBuVeI4gcQ5sKxP+HaH6Oiq'
--SELECT * FROM users
WHERE ID = '564'