SELECT *
FROM LENDER
WHERE CODE_TX = '3585'

SELECT *
FROM LOAN
WHERE LENDER_ID = 2271

SELECT *
FROM LENDER_PAYEE_CODE_FILE
WHERE LENDER_ID = 843 AND PAYEE_CODE_TX = '2341'

sp_who3

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
INNER JOIN ADDRESS ON LENDER_PAYEE_CODE_MATCH.REMITTANCE_ADDR_ID = ADDRESS.ID
WHERE LENDER_PAYEE_CODE_FILE_ID = 26753 AND LENDER_PAYEE_CODE_MATCH.PURGE_DT IS NULL

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
WHERE LENDER_PAYEE_CODE_FILE_ID = 26753

UPDATE LENDER_PAYEE_CODE_MATCH
SET PURGE_DT = GETDATE(), UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0251061', LOCK_ID = LOCK_ID + 1
WHERE LENDER_PAYEE_CODE_FILE_ID = 26753 AND ID IN (18287)

SELECT *
FROM BORROWER_INSURANCE_COMPANY
--WHERE NAME = 'HARTFORD'
WHERE ID IN (16278,13920)
