-------------- Check Work Items Before Update (To Verify Work Item Definition and Status)
-------------- Work Item ID Number(s) should be provided on HDT
----REPLACE XXXXXXX WITH THE THE WI ID


SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, *
FROM    UniTrac..WORK_ITEM
WHERE    CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') = '2268' 
--AND STATUS_CD NOT IN ('Complete' ,'Withdrawn' ,'ImportCompleted')
AND WORKFLOW_DEFINITION_ID = '9' AND UPDATE_DT >= '2016-05-09 '
ORDER BY UPDATE_DT DESC

SELECT * FROM dbo.WORK_QUEUE
WHERE --NAME_TX LIKE 'Plano%' AND 
--WORKFLOW_DEFINITION_ID = '9' AND 
id IN( 20, 40, 320, 138)


SELECT * FROM dbo.PROCESS_DEFINITION
WHERE UPDATE_USER_TX = 'WFSrvr' AND ACTIVE_IN = 'Y'
SELECT * FROM dbo.LENDER
WHERE CODE_TX = '2268'



SELECT WQ.ID, WQ.NAME_TX, U.GIVEN_NAME_TX, U.FAMILY_NAME_TX, UWQ.* FROM dbo.WORK_QUEUE WQ
INNER JOIN dbo.USER_WORK_QUEUE_RELATE UWQ ON UWQ.WORK_QUEUE_ID = WQ.ID
INNER JOIN dbo.USERS U ON U.ID = UWQ.USER_ID
WHERE-- U.FAMILY_NAME_TX = 'Nothem' AND 
DESCRIPTION_TX LIKE  '%Cycle'
AND WQ.ACTIVE_IN = 'Y' AND UWQ.PURGE_DT IS NULL 
AND CAN_WORK_OUT_OF_ORDER_IN = 'Y' AND USER_ROLE_CD <> 'LENDER_ADMIN' AND USER_ROLE_CD <> 'MANAGER'
ORDER BY U.FAMILY_NAME_TX
--138

