USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT  RC.* 
into unitrachdstorage..INC0388198_2
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2291') AND L.NUMBER_TX IN ('3003392', '3001481','3003326','3003749','3002118','3003166','3002656',
'3000337','3003483','3003449','3003711','3001960','3002559','3000529','3003391', '531964','543117')




update rc
set CPI_STATUS_CD = 'E', CPI_SUB_STATUS_CD = 'C', SUMMARY_STATUS_CD = 'E', SUMMARY_SUB_STATUS_CD = 'C',GOOD_THRU_DT = NULL,
UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0388198'
--select rc.SUMMARY_STATUS_CD , rc.SUMMARY_SUB_STATUS_CD, i.SUMMARY_STATUS_CD, i.SUMMARY_SUB_STATUS_CD ,rc.CPI_STATUS_CD , rc.CPI_SUB_STATUS_CD, i.CPI_STATUS_CD, i.CPI_SUB_STATUS_CD ,*
from REQUIRED_COVERAGE RC
join unitrachdstorage..INC0388198_2 I on RC.ID = I.ID


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , 'INC0388198' , 'N' , 
 GETDATE() ,  1 , 
'Moved loan to CPI Expired status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
join unitrachdstorage..INC0388198_2 I on RC.ID = I.ID




select * from ref_code
where domain_cd = 'RequiredCoverageInsStatus'


