-------------- Check Work Items Before Update (To Verify Work Item Definition and Status)
-------------- Work Item ID Number(s) should be provided on HDT
----REPLACE XXXXXXX WITH THE THE WI ID


SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, *
FROM    UniTrac..WORK_ITEM
WHERE   ID IN (  1552400 )


SELECT * FROM dbo.WORK_QUEUE
WHERE ID IN (6)

DESCRIPTION_TX LIKE 'Lender%'

SELECT * INTO UniTracHDStorage..INC0215492
FROM dbo.WORK_ITEM WI
WHERE WI.WORKFLOW_DEFINITION_ID = '4' AND 
WI.CREATE_DT <= '2015-07-01' 
AND WI.PURGE_DT IS NULL AND  WI.CURRENT_QUEUE_ID = '6'
AND WI.STATUS_CD <> 'cOMPLETE' AND wi.STATUS_CD <> 'wITHDRAWN'
ORDER BY CREATE_DT DESC
--3119

SELECT * FROM dbo.WORK_ITEM_ACTION
WHERE WORK_ITEM_ID IN ( SELECT ID FROM dbo.WORK_ITEM WI
WHERE WI.WORKFLOW_DEFINITION_ID = '4' AND 
WI.CREATE_DT <= '2015-07-01' 
AND WI.PURGE_DT IS NULL AND  WI.CURRENT_QUEUE_ID = '6'
AND WI.STATUS_CD <> 'cOMPLETE' AND wi.STATUS_CD <> 'wITHDRAWN') 
ORDER BY WORK_ITEM_ID ASC


UPDATE dbo.WORK_ITEM
SET PURGE_DT = GETDATE()
--SELECT COUNT(*) FROM dbo.WORK_ITEM
WHERE ID IN (
SELECT ID FROM UniTracHDStorage..INC0215492)