--1) Main Service Center Query (SERVICE_CENTER_FUNCTION_LENDER_RELATE)
SELECT C.CODE_TX, C.NAME_TX, SCFLR.ID as SCFLR_ID,*
FROM LENDER L
INNER JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFLR ON L.ID = SCFLR.LENDER_ID AND SCFLR.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER_FUNCTION SCF ON SCFLR.SERVICE_CENTER_FUNCTION_ID = SCF.ID AND SCF.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER C ON SCF.SERVICE_CENTER_ID = C.ID  AND C.PURGE_DT IS NULL
WHERE L.CODE_TX = '1630'

--SCFLR ROW
SELECT *
FROM SERVICE_CENTER_FUNCTION_LENDER_RELATE
WHERE ID = 1856



--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE SERVICE_CENTER_FUNCTION_LENDER_RELATE
SET SERVICE_CENTER_FUNCTION_ID = 54
WHERE ID = 1856



--2) Service Center Setup by Division
SELECT RD.DEF_ID,RD.VALUE_TX,LO.NAME_TX,RD.ID as RD_ID,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '1630'

--RELATED_DATA ROW(S)
SELECT *
FROM RELATED_DATA
WHERE ID IN (25555153,
25555154,
25555155,
25555156)

--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE RELATED_DATA
SET VALUE_TX = 'Sioux City'
WHERE ID IN (25555153,
25555154,
25555155,
25555156)
