USE UniTrac

SELECT DISTINCT  L.NUMBER_TX,  C.ID ,
        C.LOAN_ID ,
        C.PROPERTY_ID ,
        C.PRIMARY_LOAN_IN ,
        C.STATUS_CD ,
        C.CPI_SUSPEND_DT ,
        C.LOAN_BALANCE_NO ,
        C.LOAN_PERCENTAGE_NO ,
        C.COLLATERAL_CODE_ID ,
        C.LENDER_COLLATERAL_CODE_TX ,
        C.PURPOSE_CODE_TX ,
        C.EXTRACT_UNMATCH_COUNT_NO ,
        C.RETAIN_IN ,
        C.RELEASE_DT ,
        C.RELEASE_OFFICER_CODE_TX ,
        C.REPO_DT ,
        C.LEGAL_STATUS_CODE_TX ,
        C.LENDER_STATUS_DT ,
        C.LENDER_STATUS_OFFICER_TX ,
        C.CATEGORY_TX ,
        C.DUE_NOT_PAID_AMOUNT_NO ,
        C.COLLATERAL_NUMBER_NO ,
        C.CREATE_DT ,
        C.UPDATE_DT ,
        C.UPDATE_USER_TX ,
        C.PURGE_DT ,
        C.LOCK_ID ,
        C.OTHER_LENDER_LOAN_AMOUNT_NO ,
        C.DO_NOT_TRACK_BY_USER_TX ,
        C.LIEN_POSITION_NO ,
        C.FLOOD_DETERMINATION_COMPANY_CD ,
        C.FLOOD_DETERMINATION_CONTRACT_NUMBER_TX ,
        C.ASSET_NUMBER_TX
--INTO   JCs..INC0304092
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID		
		INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
		WHERE  LL.CODE_TX ='2285' AND L.STATUS_CD = 'A'
		AND C.STATUS_CD = 'A' AND C.PRIMARY_LOAN_IN = 'N'
		AND C.PURGE_DT IS NULL
		AND L.PURGE_DT IS NULL 
		




