USE unitrac

SELECT * FROM work_item
WHERE id = '38101021'

SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID = 14560
AND UPDATE_DT >='2017-04-01'


SELECT * FROM dbo.PROCESS_LOG
WHERE --PROCESS_DEFINITION_ID = 14560 AND 
UPDATE_DT >='2017-02-01' 
AND SERVER_TX IS NOT NULL
 ORDER BY PROCESS_LOG.PROCESS_DEFINITION_ID, UPDATE_DT DESC 


SELECT * FROM dbo.PROCESS_DEFINITION
WHERE NAME_TX LIKE '%3035%' AND PROCESS_TYPE_CD = 'CYCLEPRC'
AND EXECUTION_FREQ_CD <> 'RUNONCE'


SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID IN (14557,
14558,
14559,
14560)
AND UPDATE_DT >='2017-04-01' AND STATUS_CD = 'Complete'

SELECT PL.PROCESS_DEFINITION_ID 
, CAST(PL.UPDATE_DT AS DATE)[Date], 
COUNT(PL.PROCESS_DEFINITION_ID) [Count]
--, COUNT(CAST(PL.UPDATE_DT AS DATE)) [] 
INTO #tmp
  FROM dbo.PROCESS_LOG pl
JOIN dbo.PROCESS_DEFINITION PD ON PD.ID = pl.PROCESS_DEFINITION_ID
WHERE --PROCESS_DEFINITION_ID = '14560' AND 
 PL.UPDATE_DT >= '2017-02-01 ' AND PD.PROCESS_TYPE_CD = 'CYCLEPRC' AND EXECUTION_FREQ_CD <> 'RUNONCE'
 AND PL.STATUS_CD = 'Complete' 
 GROUP BY PL.PROCESS_DEFINITION_ID , CAST(PL.UPDATE_DT AS DATE)
 HAVING COUNT(PL.PROCESS_DEFINITION_ID)  >= '2'
 AND  COUNT(CAST(PL.UPDATE_DT AS DATE)) >= '2'

 SELECT * FROM dbo.PROCESS_LOG
 WHERE PROCESS_DEFINITION_ID  IN (SELECT  PROCESS_DEFINITION_ID FROM #tmp)
 AND UPDATE_DT >= '2017-02-01 ' AND STATUS_CD = 'Complete' AND MSG_TX <> 'Success'
 ORDER BY PROCESS_LOG.PROCESS_DEFINITION_ID, UPDATE_DT DESC 


 SELECT * FROM dbo.PROCESS_DEFINITION
 WHERE ID IN (SELECT  PROCESS_DEFINITION_ID FROM #tmp)