USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT RC.ESCROW_IN,  RC1.DESCRIPTION_TX [Coverage Status] ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] ,
        L.EFFECTIVE_DT ,
        L.NUMBER_TX, RC.ID [RC_ID]
		INTO #tmpRC
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
		INNER JOIN dbo.REQUIRED_ESCROW RE ON RE.REQUIRED_COVERAGE_ID = RC.ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.REF_CODE RC1 ON RC1.CODE_CD = RC.STATUS_CD
                                       AND RC1.DOMAIN_CD = 'RequiredCoverageStatus'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
WHERE   LL.CODE_TX = '7100'
        AND RC.ESCROW_In = 'Y'






SELECT * 
FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT RC_ID FROM #tmpRC)
AND PROPERTY_ID = '36454973'


SELECT * FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
WHERE P.ID = '36454973'


USE UniTrac
UPDATE dbo.REQUIRED_COVERAGE
SET ESCROW_IN = 'N', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0251600',
LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0251600_RC)


SELECT ESCROW_IN, * FROM UniTracHDStorage..INC0251600_RC




SELECT ESCROW_IN,* FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0251600_RC)




 

UPDATE  LOAN
SET     Escrow_IN = 'N' ,
        UPDATE_DT = GETDATE() ,
        UPDATE_USER_TX = 'INC0251600' ,
        LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1
                       ELSE LOCK_ID + 1
                  END
WHERE   LENDER_ID = 200
        AND PURGE_DT IS NULL
        AND ESCROW_IN = 'y'

 
