USE UniTrac

SELECT DISTINCT L.NUMBER_TX,LL.NAME_TX, A.CITY_TX, A.STATE_PROV_TX 
INTO jcs..INC0331749
FROM dbo.LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN MASTER_POLICY MP ON LL.ID = MP.LENDER_ID
INNER JOIN dbo.CARRIER C ON C.ID = MP.CARRIER_ID
INNER JOIN dbo.ADDRESS A ON LL.PHYSICAL_ADDRESS_ID = A.ID
WHERE C.NAME_TX LIKE '%National General%' AND MP.END_DT >= '2016-06-07 '
AND A.STATE_PROV_TX = 'OR' AND LL.STATUS_CD <> 'CANCEL'
