USE unitrac


SELECT * FROM dbo.PROPERTY_CHANGE pc
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON pc.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '152095674' AND PC.ENTITY_NAME_TX = 'Allied.UniTrac.RequiredCoverage'


SELECT * FROM dbo.IMPAIRMENT
WHERE ID = 4859407



SELECT * INTO UniTracHDStorage..INC0296889
 FROM dbo.WAIVE_TRACK
WHERE id = 7361374


UPDATE WT
SET PURGE_DT = GETDATE(), UPDATE_USER_TX = 'INC0296889', LOCK_ID = LOCK_ID+1, UPDATE_DT= GETDATE()
--SELECT * 
FROM dbo.WAIVE_TRACK WT
WHERE id = 7361374


