USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.RECORD_TYPE_CD, P.RECORD_TYPE_CD, RC.RECORD_TYPE_CD,
O.LAST_NAME_TX, O.FIRST_NAME_TX,

* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.RECORD_TYPE_CD = 'E' and
--L.NUMBER_TX IN ('112127328') AND 
O.FIRST_NAME_TX = 'Shaun' AND O.LAST_NAME_TX = 'Wadsworth'
--AND LL.CODE_TX = '8448'
ORDER BY O.LAST_NAME_TX DESC


SELECT * FROM dbo.LOAN
WHERE ID IN (2016535941)


SELECT L. * 
INTO UniTracHDStorage..INC0234697L
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE 
L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'


SELECT C. * 
INTO UniTracHDStorage..INC0234697C
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'




SELECT P. *
INTO UniTracHDStorage..INC0234697P
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'


SELECT RC. *
INTO UniTracHDStorage..INC0234697RC
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'

SELECT O. *
INTO UniTracHDStorage..INC0234697O
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'


SELECT OA. *
INTO UniTracHDStorage..INC0234697OA
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'

SELECT OL. *
INTO UniTracHDStorage..INC0234697OL
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE  L.NUMBER_TX IN ('112127328') AND O.FIRST_NAME_TX = 'Shaun' AND LL.CODE_TX = '8448'



UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0234697', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'G'
--SELECT PURGE_DT, * 
FROM Loan L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697L)




UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0234697', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'G'
--SELECT  * 
FROM dbo.PROPERTY L
INNER JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = L.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = L.ID
INNER JOIN dbo.LOAN LL ON LL.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697P)


UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0234697', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'G'
--SELECT  * 
FROM dbo.PROPERTY P
INNER JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.REQUIRED_COVERAGE L ON L.PROPERTY_ID = P.ID
INNER JOIN dbo.LOAN LL ON LL.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697RC )







SELECT RECORD_TYPE_CD, * FROM  UniTracHDStorage..INC0234697L



SELECT RECORD_TYPE_CD, * FROM UniTracHDStorage..INC0234697P

SELECT RECORD_TYPE_CD, * FROM UniTracHDStorage..INC0234697RC




SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RecordType'




 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0234697' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loan to Active Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697L)




 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Property' , L.ID , 'INC0234697' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loan to Active Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Property' , L.ID , 'PEND' , 'N'
FROM dbo.PROPERTY L
INNER JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = L.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = L.ID
INNER JOIN dbo.LOAN LL ON LL.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697P)




 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , 'INC0234697' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loan to Active Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM dbo.PROPERTY L
INNER JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = L.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = L.ID
INNER JOIN dbo.LOAN LL ON LL.ID = C.LOAN_ID
WHERE RC.ID IN (SELECT ID FROM  UniTracHDStorage..INC0234697RC)





--1085


SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE ENTITY_ID = '2016535941' AND ENTITY_NAME_TX = 'Allied.UniTrac.Loan'