USE UniTrac

SELECT A.POSTAL_CODE_TX, A.ID INTO #tmpA FROM dbo.LENDER_PAYEE_CODE_FILE LFP
JOIN dbo.LENDER LL ON LL.ID = LFP.LENDER_ID
JOIN dbo.ADDRESS A ON A.ID = LFP.PAYEE_ADDRESS_ID
WHERE LL.CODE_TX = '3057'
AND  CAST(LFP.CREATE_DT AS DATE) >= CAST(GETDATE() AS DATE)
AND LEN(A.POSTAL_CODE_TX) = '6'

SELECT * FROM #tmpA

UPDATE dbo.ADDRESS
SET POSTAL_CODE_TX = REPLACE(POSTAL_CODE_TX, '103', '03')
--SELECT * FROM dbo.ADDRESS
WHERE POSTAL_CODE_TX IN ( SELECT POSTAL_CODE_TX FROM #tmpA WHERE POSTAL_CODE_TX LIKE '103%' )



UPDATE dbo.ADDRESS
SET POSTAL_CODE_TX = REPLACE(POSTAL_CODE_TX, '102', '02')
--SELECT * FROM dbo.ADDRESS
WHERE POSTAL_CODE_TX IN ( SELECT POSTAL_CODE_TX FROM #tmpA WHERE POSTAL_CODE_TX LIKE '102%' )




SELECT * FROM dbo.ADDRESS
WHERE id IN ( SELECT id FROM #tmpA  )