USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT  DISTINCT L.NUMBER_TX ,
        L.BRANCH_CODE_TX ,
        L.DIVISION_CODE_TX ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type], L.ID [LoanID], LENDER_ID
--		INTO #tmp
FROM    LOAN L
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
WHERE   L.BRANCH_CODE_TX = 'COMM' AND L.LENDER_ID = '2239'


SELECT *
INTO UniTracHDStorage..INC0232068
 FROM dbo.LOAN
WHERE ID IN (SELECT LoanID FROM #tmp)



SELECT * FROM dbo.LENDER
WHERE CODE_TX = '2981'


UPDATE dbo.LOAN
SET UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0232068', LOCK_ID = LOCK_ID+1,
DIVISION_CODE_TX = '10'
--SELECT * FROM LOAN
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0232068)

 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0232068' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loans from Branch Code "COMM" moved to Division 10', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0232068)



SELECT DIVISION_CODE_TX, RC.TYPE_CD,  * FROM UniTracHDStorage..INC0232068
INNER JOIN dbo.COLLATERAL C ON C.ID = INC0232068.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = C.PROPERTY_ID
WHERE LENDER_ID <> '681'



SELECT L.DIVISION_CODE_TX [Current Database],  I.DIVISION_CODE_TX [Backup before JC screwup]  FROM UniTracHDStorage..INC0232068 I
INNER JOIN dbo.LOAN L ON L.ID = I.ID 
WHERE L.LENDER_ID <> '681'



UPDATE L 
SET  L.DIVISION_CODE_TX =  I.DIVISION_CODE_TX, Update_dt = GETDATE()
--SELECT L.DIVISION_CODE_TX, *
FROM dbo.LOAN L 
INNER JOIN UniTracHDStorage..INC0232068 I ON I.ID = L.ID
WHERE L.LENDER_ID <> '2239'


 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0232068' , 'N' , 
 GETDATE() ,  1 , 
 'Fixed loans that were updated by mistake', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0232068)
AND L.LENDER_ID <> '2239'