USE unitrac


SELECT L.NUMBER_TX, E.*
--INTO #tmp
 FROM dbo.ESCROW E
JOIN dbo.LOAN L ON L.ID = E.LOAN_ID
JOIN dbo.ESCROW_REQUIRED_COVERAGE_RELATE ERC ON ERC.ESCROW_ID = E.ID
WHERE E.ID IN (403467)


SELECT * 
FROM dbo.ESCROW E
JOIN dbo.INTERACTION_HISTORY ih ON e.PROPERTY_ID = ih.PROPERTY_ID
JOIN dbo.OWNER_POLICY op ON e.POLICY_NUMBER_TX = op.POLICY_NUMBER_TX
WHERE op.POLICY_NUMBER_TX = 'TXL16304' AND op.PURGE_DT IS NULL
AND E.ID = '403467'


UPDATE dbo.ESCROW
SET PURGE_DT = GETDATE()
WHERE ID = '403467'


UPDATE dbo.INTERACTION_HISTORY
SET PURGE_DT = GETDATE()
FROM dbo.INTERACTION_HISTORY IH
WHERE ID = '242105602'


UPDATE dbo.OWNER_POLICY
set PURGE_DT = GETDATE()
WHERE  ID IN (140973581)

