USE [UniTrac]
GO 

SELECT * FROM dbo.LENDER
WHERE CODE_TX	= '6155'


SELECT * FROM UniTracHDStorage..INC0222294_RC_ONLYNew

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE


SELECT * FROM UniTracHDStorage..INC0222294_RC_ONLYNew
--2) Update GOOD_THRU_DT field to NULL in REQUIRED_COVERAGE table
UPDATE RC SET RC.GOOD_THRU_DT = NULL ,RC.UPDATE_DT = GETDATE() , RC.UPDATE_USER_TX = 'INC0222294' ,    RC.INSURANCE_STATUS_CD = 'A',
        RC.SUMMARY_STATUS_CD = 'A',
RC.LOCK_ID = CASE WHEN RC.LOCK_ID >= 255 THEN 1 ELSE RC.LOCK_ID + 1 END
---- SELECT DISTINCT RC.ID
--- select *
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (93327122)



UPDATE RC SET GOOD_THRU_DT = NULL , 
INSURANCE_STATUS_CD = 'A' , 
SUMMARY_STATUS_CD = 'A' , 
NOTICE_DT = NULL , 
NOTICE_SEQ_NO = NULL , 
NOTICE_TYPE_CD = NULL , 
LAST_EVENT_DT = NULL , 
LAST_EVENT_SEQ_ID = NULL , 
LAST_SEQ_CONTAINER_ID = NULL ,
UPDATE_DT = GETDATE() , 
UPDATE_USER_TX = 'INC0222294' , 
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT DISTINCT RC.ID
--- select *
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (93327122)

--(SELECT L_ID FROM UniTracHDStorage..INC0222294_RC_ONLYNew)


UPDATE P 
SET P.UPDATE_USER_TX = 'INC0222294' ,  P.UPDATE_DT = GETDATE()
FROM dbo.PROPERTY P
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (93327122)

--3) Insert History into PROPERTY_CHANGE table
--Update description field based on new and old branch name. If it varies on loan by loan basis, need to link in our temp table form the beginning

 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , 'INC0222294' , 'N' , 
 GETDATE() ,  1 , 
 'Moved RC to Audit', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT L_ID FROM UniTracHDStorage..INC0222294_RC_ONLYNew)



SELECT RC.SUMMARY_STATUS_CD, RC.UPDATE_USER_TX, RC.INSURANCE_STATUS_CD,NUMBER_TX, RC.GOOD_THRU_DT, * FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (93327122)

--6155

