--1) Update BRANCH_CODE_TX field in LOAN table
UPDATE dbo.LOAN 
SET ESCROW_IN = 'Y',
LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
WHERE ID IN (52879913)
--1085


--2) Update GOOD_THRU_DT field to NULL in REQUIRED_COVERAGE table
UPDATE RC SET RC.ESCROW_IN = 'Y', LOCK_ID = CASE WHEN RC.LOCK_ID >= 255 THEN 1 ELSE RC.LOCK_ID + 1 END
--SELECT DISTINCT RC.ID
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (52879913)
--1094

--RC.GOOD_THRU_DT = NULL ,RC.UPDATE_DT = GETDATE() , --RC.UPDATE_USER_TX = 'INC0205932' ,
--RC.LOCK_ID = CASE WHEN RC.LOCK_ID >= 255 THEN 1 ELSE RC.LOCK_ID + 1 END, rc.REQUIRED_AMOUNT_NO = '75000.00',
--RC.LAST_GOOD_INSURANCE_DT = '2013-09-22 00:00:00.0000000', 
--3) Insert History into PROPERTY_CHANGE table
 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'UNITRAC' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loan to Indirect Branch', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM UnitracHDStorage.dbo.INC0205932)
--1085

  SELECT
		  ID,
		  UTL_LOAN_ID,
		  UTL_PROPERTY_ID,
		  AGENCY_ID,
		  PROPERTY_ID,
		  LOAN_ID,
		  UTL_OWNER_POLICY_ID,
		  TXN_ID,
		  SCORE_NO,
		  SCORE_PERCENT_NO,
		  SCORE_DETAIL_XML,
		  MATCH_RESULT_CD,
		  USER_MATCH_RESULT_CD,
		  USER_MATCH_TX,
		  MSG_LOG_TX,
		  LOG_TX,
		  APPLY_STATUS_CD,
		  CRITERIA_XML,
		  ESCROW_IN,
		  LOCK_ID
	   FROM UTL_MATCH_RESULT
	   WHERE
		  UTL_LOAN_ID IN (138308715 )

SELECT C.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
--SELECT * FROM dbo.LOAN L
WHERE LL.CODE_TX = '1007' AND L.RECORD_TYPE_CD = 'U' AND L.SOURCE_CD = 'UI' AND l.NUMBER_Tx = '7198L30'


SELECT * FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '2' AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-20 AS DATE)

RELATE_ID = '60995862'


SELECT * FROM dbo.UTL_MATCH_RESULT
WHERE ID IN (59404878)
SELECT * FROM dbo.LENDER
WHERE CODE_TX= '1007'

SELECT  *
FROM    WORK_ITEM
WHERE  -- RELATE_TYPE_CD = 'Allied.UniTrac.UTLMatchResult'
        --AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
	 RELATE_ID IN (
sELECT  UTL_MATCH_RESULT.ID
        FROM    LOAN
                INNER JOIN COLLATERAL ON LOAN.ID = COLLATERAL.LOAN_ID-- AND COLLATERAL.PURGE_DT IS NULL
                INNER JOIN PROPERTY ON COLLATERAL.PROPERTY_ID = PROPERTY.ID
                INNER JOIN dbo.UTL_MATCH_RESULT ON PROPERTY.ID = UTL_MATCH_RESULT.PROPERTY_ID
                INNER JOIN LENDER ON LOAN.LENDER_ID = LENDER.ID 
				WHERE NUMBER_TX = '7198L30')
				
				UPDATE dbo.LOAN
				SET SPECIAL_HANDLING_XML = '<SH>
  <Misc>
    <VerifyDataWorkItemId>28398547</VerifyDataWorkItemId>
  </Misc>
</SH>'
				--SELECT * FROM dbo.LOAN
				WHERE NUMBER_TX ='7198L30'


--28398546

				SELECT * FROM dbo.WORK_ITEM
				WHERE RELATE_ID = '0' AND WORKFLOW_DEFINITION_ID = '8'


 SELECT *  FROM UTLMATCH_REQ_COV_RELATE
	  WHERE UTL_MATCH_RESULT_ID IN (
									SELECT ID
									FROM UTL_MATCH_RESULT
									WHERE UTL_LOAN_ID = 138308715)
		