
update lrc set GENERATION_TYPE_CD = 'INACTIVE', LRC.UPDATE_DT = GETDATE(), LRC.UPDATE_USER_TX = 'INC0449567'
--SELECT lrc.id as LenderReportConfigID,LE.CODE_TX AS LENDER_CODE,LE.NAME_TX AS LENDER_NAME,lrc.GENERATION_TYPE_CD AS GENERATION_SOURCE,LRC.DESCRIPTION_TX lENDER_REPORT_NAME,RC.NAME_TX AS REPORT_NAME,RC.CODE_TX AS REPORT_CODE,isnull(lrc.coverage_type_cd,'') AS COVERAGE_TYPE,isnull(lrc.cyclemode_cd,'') AS CYCLE_MODE,ISNULL(LO.CODE_TX,'') AS BRANCH_CODE,ISNULL(LO2.CODE_tX,'') AS DIVISION_CODE,lrc.purge_dt as LenderReportConfigPurgeDate
FROM LENDER_REPORT_CONFIG LRC
INNER JOIN REPORT_CONFIG RC ON RC.ID = LRC.REPORT_CONFIG_ID
INNER JOIN LENDER LE ON LE.ID = LRC.LENDER_ID
LEFT JOIN LENDER_ORGANIZATION LO ON LO.ID = LRC.BRANCH_LENDER_ORG_ID AND LO.TYPE_CD = 'BRCH'
LEFT JOIN LENDER_ORGANIZATION LO2 ON LO2.ID = LRC.DIVISION_LENDER_ORG_ID AND LO2.TYPE_CD = 'DIV'
WHERE RC.id = '685'
AND LE.CANCEL_DT IS NULL
AND LE.STATUS_CD = 'ACTIVE'
AND RC.PURGE_DT IS NULL
AND LRC.PURGE_DT IS NULL
AND LE.TEST_IN = 'N'
AND LRC.PURGE_DT IS NULL
AND LRC.GENERATION_TYPE_CD <> 'INACTIVE'
