--1) Main Service Center Query (SERVICE_CENTER_FUNCTION_LENDER_RELATE)
SELECT C.CODE_TX, C.NAME_TX, SCFLR.ID as SCFLR_ID,*
FROM LENDER L
INNER JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFLR ON L.ID = SCFLR.LENDER_ID AND SCFLR.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER_FUNCTION SCF ON SCFLR.SERVICE_CENTER_FUNCTION_ID = SCF.ID AND SCF.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER C ON SCF.SERVICE_CENTER_ID = C.ID  AND C.PURGE_DT IS NULL
WHERE L.CODE_TX = '3000'

--previously 72	Laguna Hills


--SCFLR ROW
SELECT *
FROM SERVICE_CENTER_FUNCTION_LENDER_RELATE
WHERE ID = 2000

--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE SERVICE_CENTER_FUNCTION_LENDER_RELATE
SET SERVICE_CENTER_FUNCTION_ID = 108, UPDATE_USER_TX = 'INC0212998'
WHERE ID = 2000



--2) Service Center Setup by Division
SELECT RD.VALUE_TX,LO.NAME_TX,RD.ID as RD_ID,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '3000'

--RELATED_DATA ROW(S)
SELECT *
FROM RELATED_DATA
WHERE ID IN (25555409)
--Previously Laguna Hills


--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE RELATED_DATA
SET VALUE_TX = 'Calif Mortgage', UPDATE_USER_TX = 'INC0212998'
WHERE ID IN (25555409)



SELECT  CONTENT_XML.value('(/Content/Coverage/Type)[1]', 'varchar (50)') ,
        CURRENT_QUEUE_ID , STATUS_CD
        RELATE_TYPE_CD ,
        CREATE_DT ,
        UPDATE_DT ,
        CONTENT_XML
FROM    UniTrac..WORK_ITEM
WHERE   CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') = '3000' 
AND STATUS_CD NOT LIKE 'Complete' AND STATUS_CD NOT LIKE 'Withdrawn' AND STATUS_CD NOT LIKE 'ImportCompleted'
AND CONTENT_XML.value('(/Content/Coverage/Type)[1]', 'varchar (50)') <> 'Physical Damage'
AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE()  AS DATE)
ORDER BY CURRENT_QUEUE_ID


SELECT * FROM dbo.WORK_QUEUE
WHERE ID IN (16, 144, 231, 287)