USE UniTrac


SELECT GOOD_THRU_DT, rc.SUMMARY_STATUS_CD, SUMMARY_SUB_STATUS_CD, END_DT FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
JOIN dbo.PROPERTY_OWNER_POLICY_RELATE pop ON pop.PROPERTY_ID = P.ID
JOIN dbo.OWNER_POLICY OP ON OP.ID = pop.OWNER_POLICY_ID
JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
JOIN dbo.INTERACTION_HISTORY ih ON ih.PROPERTY_ID = p.id
WHERE rc.ID IN (SELECT RC.id FROM Jcs..JDByrider_expired3)



SELECT * FROM dbo.BUSINESS_OPTION BO
JOIN dbo.BUSINESS_OPTION_GROUP BG ON BO.BUSINESS_OPTION_GROUP_ID = BG.ID
LEFT JOIN dbo.BUSINESS_RULE_BASE BR ON BR.ID = BO.BUSINESS_RULE_ID
LEFT JOIN dbo.LENDER_PRODUCT LP ON LP.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
LEFT JOIN dbo.LENDER L ON L.ID =LP.LENDER_ID
LEFT JOIN dbo.AGENCY A ON A.ID = L.AGENCY_ID
LEFT JOIN dbo.WORK_QUEUE WQ ON A.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'UnitracWorkQueue'
LEFT JOIN dbo.COMMISSION_RATE CR ON CR.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM =  'Allied.UniTrac.CommissionRate'
WHERE L.CODE_TX = '3303' AND BO.NAME_TX = 'EventOptionAudit'


SELECT  * FROM dbo.EVENT_SEQ_CONTAINER E
JOIN dbo.ESC_ERD_RELATE EE ON EE.ESC_ID = E.ID
JOIN dbo.EVENT_REACTION_DEFINITION ERD ON ERD.ID = EE.ERD_ID
JOIN dbo.EVENT_STATUS ES ON ES.EVENT_REACTION_DEFINITION_ID = ERD.ID
JOIN dbo.LENDER_PRODUCT lp ON lp.id = LENDER_PRODUCT_ID
JOIN dbo.IMPAIRMENT_DEFINITION ID ON ID.LENDER_PRODUCT_ID = lp.ID
JOIN dbo.LENDER L ON L.ID = E.LENDER_ID
WHERE l.CODE_TX = '3303' AND e.DESCRIPTION_TX LIKE 'audit%' AND e.PURGE_DT IS NULL 

SELECT RC.CREATE_DT, L.CREATE_DT,  L.EFFECTIVE_DT, RC.TYPE_CD,  GOOD_THRU_DT, LAST_GOOD_INSURANCE_DT, EXPOSURE_DT, 
SUMMARY_STATUS_CD , SUMMARY_SUB_STATUS_CD, INSURANCE_STATUS_CD, INSURANCE_SUB_STATUS_CD,
RC.* 
--SELECT rc.STATUS_CD, l.STATUS_CD,c.STATUS_CD,rc.SUMMARY_STATUS_CD
--SELECT IH.*
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID
--INNER JOIN dbo.CPI_QUOTE CQ ON CQ.ID = IH.RELATE_ID AND IH.TYPE_CD = 'CPI'
WHERE LL.CODE_TX IN ('3303') AND L.NUMBER_TX IN ('7010018922')
--CoverageStatus = A
--CollateralStatus = A
--LoanStatus = A
--CoverageSummaryStatus = A
SELECT  L.EFFECTIVE_DT, GOOD_THRU_DT, LAST_GOOD_INSURANCE_DT, EXPOSURE_DT, L.STATUS_DT, L.BALANCE_LAST_UPDATE_DT,
SUMMARY_STATUS_CD , SUMMARY_SUB_STATUS_CD, INSURANCE_STATUS_CD, INSURANCE_SUB_STATUS_CD, RC.TYPE_CD, EventOptionAudit, EventOptionReaudit, ForcedPlcyOptUninsuredBackdate, ForcedPlcyOptUninsuredBackDays,
L.* 
--SELECT IH.*
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
WHERE SUMMARY_STATUS_CD = 'A' AND RC.INSURANCE_STATUS_CD = 'A' AND RC.STATUS_CD = 'A' AND 
L.UPDATE_DT >= '2016-10-01 '
ORDER BY L.UPDATE_DT DESC


UPDATE L
SET EFFECTIVE_DT =NULL, UPDATE_DT = GETDATE(), LOCK_ID= LOCK_ID+1
--SELECT CREATE_DT, EFFECTIVE_DT,  * 
FROM dbo.LOAN L
WHERE  ID = '161761731'

UPDATE RC
SET CREATE_DT = L.CREATE_DT, STATUS_CD = 'A', GOOD_THRU_DT = NULL, SUMMARY_STATUS_CD = 'A', SUMMARY_SUB_STATUS_CD = '', INSURANCE_STATUS_CD = 'A', 
LAST_GOOD_INSURANCE_DT = NULL
--SELECT RC.CREATE_DT, RC.* 
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
WHERE RC.PROPERTY_ID = '134482461' AND RC.TYPE_CD = 'HAZARD'



SELECT * FROM dbo.PROCESS_DEFINITION
WHERE NAME_TX LIKE '%good%' AND ACTIVE_IN = 'Y'
AND ONHOLD_IN = 'N' AND PROCESS_TYPE_CD = 'GOODTHRUDT'

