USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT
        LO.NAME_TX [Division], L.BRANCH_CODE_TX, 
        L.NUMBER_TX [Loan Number] ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] ,
		RC5.DESCRIPTION_TX [Title],
        O.LAST_NAME_TX ,
        O.FIRST_NAME_TX ,
        OA.CITY_TX ,
        OA.STATE_PROV_TX ,
        OA.COUNTRY_TX ,
        OA.POSTAL_CODE_TX ,
        P.DESCRIPTION_TX ,
        P.VIN_TX ,
        C.COLLATERAL_NUMBER_NO ,
		L.EFFECTIVE_DT,
        C.LOAN_BALANCE_NO ,
        BIC_NAME_TX ,
        POLICY_NUMBER_TX ,
        OP.EFFECTIVE_DT ,
        OP.EXPIRATION_DT ,
        RC.TYPE_CD
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
        INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = C.PROPERTY_ID
        INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD AND RC4.DOMAIN_CD = 'LoanType'
		INNER JOIN dbo.REF_CODE RC5 ON RC5.CODE_CD = P.TITLE_CD AND RC5.DOMAIN_CD = 'TitleType'
        INNER JOIN LENDER_ORGANIZATION LO ON Lo.CODE_TX = L.DIVISION_CODE_TX
                                             AND LO.LENDER_ID = '1824'
                                             AND Lo.TYPE_CD = 'DIV'
WHERE   L.EFFECTIVE_DT >= '2015-04-01'
        AND TITLE_CD = 'Y' AND L.LENDER_ID = '1824' 
ORDER BY L.BRANCH_CODE_TX 




