USE [UniTrac]
GO 




 --drop table  #tmpCPI
 --drop table #tmpC
SELECT fpc.id [FPC_ID], CPI.* INTO #tmpCPI
 FROM dbo.CPI_QUOTE CPI
JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CPI.ID
JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.CPI_QUOTE_ID = CPI.ID
JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
WHERE  CA.REASON_CD = 'LOSS' AND 
 LENDER_ID = '2305'

 SELECT C.FPC_ID, CA.* INTO #tmpC
 FROM #tmpCPI C
 JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = C.ID

SELECT L.NUMBER_TX [Loan Number], (SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') [Lapse Days], C.TOTAL_PREMIUM_NO, REFUND_AMOUNT_NO,
C.PROCESS_DT [Refund Date], C.START_DT, C.END_DT
FROM 
 dbo.CERTIFICATE_DETAIL CD
 JOIN #tmpC C ON C.ID = CD.CPI_ACTIVITY_ID
 JOIN dbo.FINANCIAL_REPORT_TXN F ON F.FPC_ID = C.FPC_ID
 JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.ID = F.FPC_ID
 JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
 WHERE C.REASON_CD = 'LOSS' AND f.PURGE_DT IS NULL
  AND (SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') IS NOT NULL
 UNION
SELECT L.NUMBER_TX [Loan Number], (SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') [Lapse Days], C.TOTAL_PREMIUM_NO, REFUND_AMOUNT_NO,
C.PROCESS_DT [Refund Date], C.START_DT, C.END_DT
FROM 
 dbo.CERTIFICATE_DETAIL CD
 JOIN #tmpC C ON C.ID = CD.CPI_ACTIVITY_ID
  JOIN dbo.FINANCIAL_REPORT_TXN F ON F.FPC_ID = C.FPC_ID
   JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.ID = F.FPC_ID
 JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
 WHERE C.REASON_CD = 'A' AND f.PURGE_DT IS NULL
 AND (SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') IS NOT NULL



--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT IH.SPECIAL_HANDLING_XML.value('(/SH/PartialCancelFPCId)[1]', 'varchar (50)') [FPC_id] , IH.* 
--INTO #tmpFPC
--*
FROM LOAN L
LEFT JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
WHERE LL.CODE_TX IN ('2715') AND
 L.NUMBER_TX IN ('55652410-81')
AND IH.SPECIAL_HANDLING_XML.value('(/SH/PartialCancelFPCId)[1]', 'varchar (50)') IS NOT NULL

SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID = '145312893'


--SELECT * FROM UNITRACARCHIVE..INTERACTION_HISTORY IH
--INNER JOIN PROPERTY P ON IH.PROPERTY_ID = P.ID


SELECT PDF_GENERATE_CD, CPI_QUOTE_ID, LOAN_NUMBER_TX, * --INTO #tmpCPI 
FROM dbo.FORCE_PLACED_CERTIFICATE
WHERE ID = '5958257'
--IN (SELECT * FROM #tmpFPC)


SELECT * FROM dbo.DOCUMENT_CONTAINER
WHERE RELATE_ID = '5958517'

SELECT (SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') [Lapse Days],
* 
--INTO jcs..INC0284069
FROM dbo.CPI_QUOTE CPI
JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CPI.ID
JOIN dbo.CERTIFICATE_DETAIL CD ON CD.CPI_ACTIVITY_ID = CA.ID
WHERE CPI.ID = '37200876'


SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'LOSS'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'CPIActivityCancelReason'


SELECT * FROM dbo.REF_CODE
WHERE CODE_CD IN ('A') AND DOMAIN_CD = 'CPIActivityType'



SELECT TOP 10  L.NUMBER_TX,
(SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') [Lapse Days],
 CA.TOTAL_PREMIUM_NO [Refund], START_DT, END_DT, PROCESS_DT,  
 (SELECT TOTAL_PREMIUM_NO WHERE CA.REASON_CD = 'A') ,
  * 
--INTO jcs..INC0284069
FROM dbo.CPI_QUOTE CPI
JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CPI.ID
JOIN dbo.CERTIFICATE_DETAIL CD ON CD.CPI_ACTIVITY_ID = CA.ID
JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.CPI_QUOTE_ID = CPI.ID
JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
WHERE  CA.REASON_CD = 'LOSS' AND 
 LENDER_ID = '2305'

 UNION

 SELECT TOP 10  L.NUMBER_TX,
(SELECT DATEDIFF(DAY,START_DT,END_DT  )-365 WHERE REASON_CD = 'LOSS') [Lapse Days],
 CA.TOTAL_PREMIUM_NO [Refund], START_DT, END_DT, PROCESS_DT,  
 (SELECT TOTAL_PREMIUM_NO WHERE CA.REASON_CD = 'A') ,
  * 
--INTO jcs..INC0284069
FROM dbo.CPI_QUOTE CPI
JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CPI.ID
JOIN dbo.CERTIFICATE_DETAIL CD ON CD.CPI_ACTIVITY_ID = CA.ID
JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.CPI_QUOTE_ID = CPI.ID
JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
WHERE  CA.REASON_CD = 'A' AND 
 LENDER_ID = '2305'