
SELECT * FROM dbo.LENDER
WHERE ID = '2063'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'LoanStatus'


SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX LIKE 'New'



SELECT * FROM dbo.LENDER
WHERE CODE_TX = '3180'


SELECT DISTINCT L.ID FROM dbo.LOAN L
INNER JOIN dbo.PROPERTY P ON P.LENDER_ID = L.LENDER_ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
WHERE L.EFFECTIVE_DT < '8/1/15' AND L.LENDER_ID = '2063' AND RC.INSURANCE_STATUS_CD = 'N'

SELECT TOP 1 * FROM dbo.REQUIRED_COVERAGE



SELECT TOP 1 * FROM dbo.CPI_ACTIVITY

SELECT TOP 1 * FROM dbo.CPI_QUOTE

SELECT  COUNT(*) FROM dbo.LOAN L
WHERE L.EFFECTIVE_DT < '8/1/15' AND L.LENDER_ID = '2063'


SELECT TOP 1 * FROM	dbo.LOAN

SELECT TOP 1 * FROM dbo.REQUIRED_COVERAGE

SELECT TOP 1 * FROM dbo.PROPERTY

SELECT TOP 1 * FROM dbo.NOTICE

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RequiredCoverageInsStatus'


SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'LoanStatus'

SELECT  RC.* INTO UniTracHDStorage..INC0207741
 from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE  L.LENDER_ID = '2063' AND RC.INSURANCE_STATUS_CD = 'N' AND L.EFFECTIVE_DT < '8/1/15' AND L.STATUS_CD <> 'U'


----1) Update BRANCH_CODE_TX field in LOAN table
--UPDATE dbo.LOAN 
--SET BRANCH_CODE_TX = 'Indirect',UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0205932' ,
--LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--WHERE ID IN (SELECT DISTINCT ID FROM UnitracHDStorage.dbo.LOAN_INC0205932)
----1085

