USE UniTrac 

SELECT  DISTINCT
        L.NAME_TX [Lender Name],
        CODE_TX [Lender Code], concat(BO.NAME_TX ,'- ', BO.DESCRIPTION_TX ) as  [Required Coverage Amount Rule],
        DEFAULT_VALUE_TX [Value] ,
        BG.NAME_TX [Product] 
		INTO jcs..INC0274953_FloodOnly
         FROM dbo.BUSINESS_OPTION BO
JOIN dbo.BUSINESS_OPTION_GROUP BG ON BO.BUSINESS_OPTION_GROUP_ID = BG.ID
LEFT JOIN dbo.BUSINESS_RULE_BASE BR ON BR.ID = BO.BUSINESS_RULE_ID
LEFT JOIN dbo.LENDER_PRODUCT LP ON LP.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
LEFT JOIN dbo.LENDER L ON L.ID =LP.LENDER_ID
WHERE BO.NAME_TX = 'RequiredCoverageAmountRule' AND DEFAULT_VALUE_TX <> 'FEMAFLOOD'
AND L.STATUS_CD = 'Active' AND L.TEST_IN = 'N' AND BO.PURGE_DT IS NULL AND BG.PURGE_DT IS NULL
AND LP.PURGE_DT IS NULL AND L.PURGE_DT IS NULL AND lp.DESCRIPTION_TX LIKE '%flood%'
ORDER BY L.CODE_TX ASC 




SELECT   * 
FROM dbo.EVENT_SEQ_CONTAINER E
JOIN dbo.ESC_ERD_RELATE EE ON EE.ESC_ID = E.ID
JOIN dbo.EVENT_REACTION_DEFINITION ERD ON ERD.ID = EE.ERD_ID
JOIN dbo.EVENT_STATUS ES ON ES.EVENT_REACTION_DEFINITION_ID = ERD.ID
JOIN dbo.LENDER_PRODUCT lp ON lp.id = LENDER_PRODUCT_ID
JOIN dbo.IMPAIRMENT_DEFINITION ID ON ID.LENDER_PRODUCT_ID = lp.ID
JOIN dbo.LENDER L ON L.ID = E.LENDER_ID
WHERE l.CODE_TX = '4804' AND e.PURGE_DT IS NULL 
AND e.DESCRIPTION_TX LIKE '' 