--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT
       DISTINCT L.NUMBER_TX ,
        BIC_NAME_TX ,
        RC1.DESCRIPTION_TX [Coverage Status] ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] ,
        IH.TYPE_CD, IH.EFFECTIVE_DT, op.id
	--	SELECT COUNT(*)
INTO JCs..INC0246925_OUTBND
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
        INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
        LEFT JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID
                                                AND IH.TYPE_CD = 'OUTBNDCALL'
        INNER JOIN REQUIRED_COVERAGE RC ON IH.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]',
                                                              'varchar (50)') = RC.ID
        INNER JOIN dbo.REF_CODE RC1 ON RC1.CODE_CD = RC.INSURANCE_STATUS_CD
                                       AND RC1.DOMAIN_CD = 'RequiredCoverageInsStatus'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
WHERE   OP.BIC_NAME_TX LIKE '%GEICO%'
        AND RC.INSURANCE_STATUS_CD <> 'F' AND op.EFFECTIVE_DT >= '2016-03-28 '
	


		SELECT TOP 50 * FROM dbo.OWNER_POLICY
		WHERE id = '123911465'

		SELECT op.*
		FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
        INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
		WHERE  L.NUMBER_TX = '08Q9628' AND 
		op.EFFECTIVE_DT >= '2016-03-28 '