SELECT * --INTO UniTracHDStorage..INC0206112 
FROM dbo.SERVICE_CENTER
WHERE ID = '108'

SELECT * FROM UniTracHDStorage..INC0206112



UPDATE dbo.SERVICE_CENTER
SET FAX_TX = '707-603-2816'
WHERE ID = '108'



SELECT LENDER_ID, L.NAME_TX, * FROM dbo.SERVICE_CENTER SC
INNER JOIN dbo.SERVICE_CENTER_FUNCTION SCF ON SCF.SERVICE_CENTER_ID = SC.ID
INNER JOIN dbo.SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFR ON SCFR.SERVICE_CENTER_FUNCTION_ID = SCF.ID
INNER JOIN dbo.LENDER L ON L.ID = SCFR.LENDER_ID
WHERE SC.ID = '108'


SELECT * FROM dbo.ADDRESS
WHERE ID = '176009'



SELECT * FROM dbo.SERVICE_CENTER_FUNCTION_LENDER_RELATE


SELECT * FROM dbo.SERVICE_CENTER_FUNCTION