USE UniTrac 

SELECT DISTINCT L.NAME_TX [Lender Name], L.CODE_TX [Lender Code], BO.NAME_TX [Lender Option],
Lp.NAME_TX [Lender Product],  Bo.DESCRIPTION_TX [Lender Description], 'Yes' [Lender Value]
--SELECT *
FROM dbo.BUSINESS_OPTION BO
JOIN dbo.BUSINESS_OPTION_GROUP BG ON BO.BUSINESS_OPTION_GROUP_ID = BG.ID
LEFT JOIN dbo.BUSINESS_RULE_BASE BR ON BR.ID = BO.BUSINESS_RULE_ID
LEFT JOIN dbo.LENDER_PRODUCT LP ON LP.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'Allied.UniTrac.LenderProduct'
LEFT JOIN dbo.LENDER L ON L.ID =LP.LENDER_ID
LEFT JOIN dbo.AGENCY A ON A.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'Allied.UniTrac.Agency'
LEFT JOIN dbo.WORK_QUEUE WQ ON A.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM = 'UnitracWorkQueue'
LEFT JOIN dbo.COMMISSION_RATE CR ON CR.ID = BG.RELATE_ID AND BG.RELATE_CLASS_NM =  'Allied.UniTrac.CommissionRate'
WHERE BO.NAME_TX LIKE '%ForcedPlcyOptUseCertAuth%' AND LP.NAME_TX LIKE '%Mortgage%'
AND DEFAULT_VALUE_TX = '1'AND L.STATUS_CD = 'ACTIVE' AND L.TEST_IN = 'N' --AND L.code_tx = '3275'
AND BG.PURGE_DT IS  NULL 


SELECT   * 
FROM dbo.EVENT_SEQ_CONTAINER E
JOIN dbo.ESC_ERD_RELATE EE ON EE.ESC_ID = E.ID
JOIN dbo.EVENT_REACTION_DEFINITION ERD ON ERD.ID = EE.ERD_ID
JOIN dbo.EVENT_STATUS ES ON ES.EVENT_REACTION_DEFINITION_ID = ERD.ID
JOIN dbo.LENDER_PRODUCT lp ON lp.id = LENDER_PRODUCT_ID
JOIN dbo.IMPAIRMENT_DEFINITION ID ON ID.LENDER_PRODUCT_ID = lp.ID
JOIN dbo.LENDER L ON L.ID = E.LENDER_ID
WHERE l.CODE_TX = '4804' AND e.PURGE_DT IS NULL 
AND e.DESCRIPTION_TX LIKE '' 



