USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.IMPAIRMENT I	 ON I.REQUIRED_COVERAGE_ID = RC.ID
WHERE LL.CODE_TX IN ('2715') AND L.NUMBER_TX = '55214100-84'

SELECT * FROM dbo.PROPERTY_CHANGE Pc
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_NAME_TX  = 'Allied.UniTrac.RequiredCoverage'
AND PC.ENTITY_ID = '139199741'





---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'


SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX LIKE '%storage%'
---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = 'XXXX'


SELECT RC.*
INTO UniTracHDStorage..INC0248107_RC
	FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2715') 	AND NOTICE_TYPE_CD = 'IS'


SELECT I.* 
--INTO UniTracHDStorage..INC0248107_I
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.IMPAIRMENT I	 ON I.REQUIRED_COVERAGE_ID = RC.ID
WHERE LL.CODE_TX IN ('2715') 	AND NOTICE_TYPE_CD = 'IS'


SELECT  OP.* 
INTO UniTracHDStorage..INC0248107_OP
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE LL.CODE_TX IN ('2715') 	AND NOTICE_TYPE_CD = 'IS'



UPDATE i
SET I.end_dt = GETDATE(), I.LOCK_ID = I.LOCK_ID+1, I.UPDATE_DT = GETDATE(), I.UPDATE_USER_TX = 'INC0248107'
--SELECT *
FROM dbo.IMPAIRMENT I
WHERE I.ID  IN (SELECT ID FROM UniTracHDStorage..INC0248107_I)
--1595


UPDATE dbo.REQUIRED_COVERAGE
SET INSURANCE_SUB_STATUS_CD = 'R', INSURANCE_STATUS_CD = 'E',
 SUMMARY_SUB_STATUS_CD = 'R',  SUMMARY_STATUS_CD = 'E', SUB_STATUS_CD = '',
 LOCK_ID = LOCK_ID+1, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0248107'
--SELECT INSURANCE_SUB_STATUS_CD, SUMMARY_SUB_STATUS_CD, * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0248107_RC)

--798

UPDATE OP
SET OP.EXPIRATION_DT = RC.EXPOSURE_DT , OP.SUB_STATUS_CD = 'R', OP.STATUS_CD = 'E',
  OP.LOCK_ID = OP.LOCK_ID+1, OP.UPDATE_DT = GETDATE(), OP.UPDATE_USER_TX = 'INC0248107'
--SELECT OP.EXPIRATION_DT , RC.EXPOSURE_DT, *
FROM dbo.OWNER_POLICY OP 
JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.OWNER_POLICY_ID = OP.ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = POP.PROPERTY_ID
WHERE op.ID IN (SELECT ID FROM UniTracHDStorage..INC0248107_OP)
--863


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , ' INC0248107' , 'N' , 
 GETDATE() ,  1 , 
 'Move Insurance to Re-Audit Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
WHERE RC.ID IN (SELECT ID FROM UniTracHDStorage..INC0248107_RC)
--798


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.OwnerPolicy' , RC.ID , ' INC0248107' , 'N' , 
 GETDATE() ,  1 , 
 'Move Insurance to Re-Audit Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.OwnerPolicy' , RC.ID , 'PEND' , 'N'
FROM dbo.OWNER_POLICY RC 
WHERE RC.ID IN (SELECT ID FROM UniTracHDStorage..INC0248107_OP)
--863



SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX = 'Expired'