USE UniTrac


SELECT DISTINCT L.NUMBER_TX [Loan Number], O.FIRST_NAME_TX [First Name], O.LAST_NAME_TX [Last Name],
FPC.NUMBER_TX [Certificate Number], CC.NAME_TX [Carrier Name], FPC.EFFECTIVE_DT [Effective Date], FPC.EXPIRATION_DT [Expiration Date], LOAN_BALANCE_NO [Loan Balance]
INTO JCs..INC0250960
 FROM dbo.INTERACTION_HISTORY IH
JOIN dbo.PROPERTY P ON P.ID = IH.PROPERTY_ID
JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
JOIN dbo.OWNER_LOAN_RELATE OLR ON OLR.LOAN_ID = L.ID
JOIN dbo.OWNER O ON O.ID = OLR.OWNER_ID
JOIN dbo.OWNER_ADDRESS OA ON OA.ID = P.ADDRESS_ID
JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.LOAN_ID = L.ID
JOIN dbo.CARRIER CC ON CC.ID = FPC.CARRIER_ID
WHERE IH.TYPE_CD = 'CPI' AND L.LENDER_ID = '674' AND FPC.EFFECTIVE_DT >= '2011-01-01 '
ORDER BY FPC.EFFECTIVE_DT ASC 


