USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT C.* 
--INTO UniTracHDStorage..INC0246129_C
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2771') AND L.ID = '66157698'


---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'

UPDATE dbo.COLLATERAL
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0246129',LOCK_ID=LOCK_ID+1, PRIMARY_LOAN_IN = 'N'
--SELECT * FROM COLLATERAL
WHERE ID IN (132209808)

UPDATE dbo.COLLATERAL
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0246129',LOCK_ID=LOCK_ID+1, PRIMARY_LOAN_IN = 'Y'
--SELECT * FROM COLLATERAL
WHERE ID IN (40557806)



INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , P.ID , ' INC0246129' , 'N' , 
 GETDATE() ,  1 , 
 'Moved property 40021632 to Non Primary Loan',
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , P.ID , 'PEND' , 'N'
FROM dbo.COLLATERAL P
WHERE P.ID IN (132209808)


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , P.ID , ' INC0246129' , 'N' , 
 GETDATE() ,  1 , 
 'Moved property 40021632 to  Primary Loan',
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , P.ID , 'PEND' , 'N'
FROM dbo.COLLATERAL P
WHERE P.ID IN (40557806)



SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN  dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '132209808' AND PC.ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'


SELECT * FROM dbo.COLLATERAL
WHERE ID = '132209808'

SELECT * FROM dbo.COLLATERAL
WHERE LOAN_ID IN ('67089526','66157698')
AND PROPERTY_ID = '40021632'


