USE UniTrac	

SELECT * FROM dbo.LENDER
WHERE CODE_TX = '6497'

--January 2016

SELECT COUNT(*) FROM dbo.LOAN
WHERE LENDER_ID = '41'
AND CREATE_DT >= '2016-01-01 ' AND  CREATE_DT <= '2016-02-01 '
AND RECORD_TYPE_CD = 'G'
--3016

SELECT N.NAME_TX [Notice], N.SEQUENCE_NO [Sequence], COUNT(N.NAME_TX) [Count] 
FROM dbo.NOTICE N
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID
WHERE L.LENDER_ID = '41' AND N.SEQUENCE_NO in ('1')
AND N.CREATE_DT >= '2016-01-01 ' AND  N.CREATE_DT <= '2016-02-01 ' AND N.PURGE_DT IS NULL
GROUP BY N.NAME_TX, N.SEQUENCE_NO
ORDER BY N.NAME_TX ASC 


--January 2017
SELECT COUNT(*) FROM dbo.LOAN
WHERE LENDER_ID = '41'
AND CREATE_DT >= '2017-01-01 ' AND  CREATE_DT <= '2017-02-01 '
AND RECORD_TYPE_CD = 'G'
--3363

SELECT N.NAME_TX [Notice], N.SEQUENCE_NO [Sequence], COUNT(N.NAME_TX) [Count] FROM dbo.NOTICE N
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID
WHERE L.LENDER_ID = '41' AND N.SEQUENCE_NO in ('1')
AND N.CREATE_DT >= '2017-01-01 ' AND  N.CREATE_DT <= '2017-02-01 '
GROUP BY N.NAME_TX, N.SEQUENCE_NO
ORDER BY N.NAME_TX ASC 



---Verification on the duplicate loans to ensure that there are two different notices that were sent 
SELECT N.LOAN_ID [Notice], N.SEQUENCE_NO [Sequence], COUNT(N.LOAN_ID) [Count] INTO #tmp
FROM dbo.NOTICE N
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID
WHERE L.LENDER_ID = '41' AND N.SEQUENCE_NO in ('1')
AND N.CREATE_DT >= '2016-01-01 ' AND  N.CREATE_DT <= '2016-02-01 ' AND N.PURGE_DT IS NULL
GROUP BY N.LOAN_ID, N.SEQUENCE_NO
HAVING COUNT(N.LOAN_ID) >= '2'
ORDER BY N.LOAN_ID ASC 


SELECT DISTINCT L.NUMBER_TX--, N.* 
FROM dbo.NOTICE N
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID
WHERE L.ID IN (SELECT Notice FROM #tmp) AND 

L.LENDER_ID = '41' AND N.SEQUENCE_NO in ('1')
AND N.CREATE_DT >= '2016-01-01 ' AND  N.CREATE_DT <= '2016-02-01 ' AND N.PURGE_DT IS NULL
ORDER BY LOAN_ID ASC 