USE UniTrac
GO

declare @wi as varchar(MAX)
DECLARE @pl AS VARCHAR(max)
DECLARE @TranType AS varchar(max)

set @wi = 33262878

SET @TranType ='UNITRAC'


SELECT
      @pl = RELATE_ID 
FROM
      dbo.WORK_ITEM WI
WHERE
      WI.id = @wi
 
SELECT
RELATE_ID INTO #tmp
--*
FROM
      dbo.PROCESS_LOG_ITEM
	  WHERE PROCESS_LOG_ID = @pl
	  AND RELATE_TYPE_CD = 'Allied.UniTrac.Notice'


	  SELECT * FROM dbo.NOTICE
	  WHERE ID IN (SELECT * FROM #tmp) AND PDF_GENERATE_CD <> 'COMP'



	  UPDATE dbo.NOTICE
	  SET PDF_GENERATE_CD = 'PEND', MSG_LOG_TX = NULL,
	  UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0244768'
	  --SELECT PDF_GENERATE_CD, * FROM dbo.NOTICE
	  WHERE ID IN (18728056,18728060,18728076,18728093,18728102,18728108)


	  SELECT TOP 11 * FROM dbo.PROCESS_LOG
	  WHERE PROCESS_DEFINITION_ID = '6'
	  ORDER BY UPDATE_DT DESC 