USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.*
INTO UniTracHDStorage..INC0297775_Division
 FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2088')


UPDATE dbo.LOAN
SET DIVISION_CODE_TX = '99', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0297775'
--SELECT DIVISION_CODE_TX, * FROM   LOAN L
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0297775_Division)



INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0297775' , 'N' , 
 GETDATE() ,  1 , 
'Moved to Division 99', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0297775_Division)