USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX, RC.id, I.*
--INTO UniTracHDStorage..INC0244507_RC
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN REQUIRED_COVERAGE RC ON C.PROPERTY_ID = RC.PROPERTY_ID
INNER JOIN dbo.IMPAIRMENT I ON I.REQUIRED_COVERAGE_ID = RC.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3039') AND L.NUMBER_TX = 'SF355420004'


SELECT IH.* 
INTO UniTracHDStorage..INC0244507_IH
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID
LEFT JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3039') AND IH.TYPE_CD = 'IMPAIRMENT'



SELECT *
INTO UniTracHDStorage..INC0244507_Impairment
 FROM dbo.IMPAIRMENT
WHERE REQUIRED_COVERAGE_ID IN (SELECT ID FROM UniTracHDStorage..INC0244507_RC)


UPDATE dbo.IMPAIRMENT
SET PURGE_DT = GETDATE(), UPDATE_DT = GETDATE(), 
LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0244507'
--SELECT * FROM dbo.IMPAIRMENT
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0244507_Impairment)



UPDATE dbo.INTERACTION_HISTORY
SET PURGE_DT = GETDATE(), UPDATE_DT = GETDATE(), 
LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0244507'
--SELECT * FROM dbo.INTERACTION_HISTORY
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0244507_IH)


UPDATE REQUIRED_COVERAGE 
 SET GOOD_THRU_DT = NULL , 
INSURANCE_STATUS_CD = 'F' , 
INSURANCE_SUB_STATUS_CD = 'D' , 
SUMMARY_STATUS_CD = 'F' , 
SUMMARY_SUB_STATUS_CD = 'D' , 
NOTICE_DT = NULL , 
NOTICE_SEQ_NO = NULL , 
NOTICE_TYPE_CD = NULL , 
LAST_EVENT_DT = NULL , 
LAST_EVENT_SEQ_ID = NULL , 
LAST_SEQ_CONTAINER_ID = NULL ,
UPDATE_DT = GETDATE() , 
UPDATE_USER_TX =  'INC0244507' , 
LOCK_ID = LOCK_ID % 255 + 1
---- SELECT * FROM REQUIRED_COVERAGE 
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0244507_RC)



INSERT  INTO PROPERTY_CHANGE
        ( ENTITY_NAME_TX ,
          ENTITY_ID ,
          USER_TX ,
          ATTACHMENT_IN ,
          CREATE_DT ,
          AGENCY_ID ,
          DESCRIPTION_TX ,
          DETAILS_IN ,
          FORMATTED_IN ,
          LOCK_ID ,
          PARENT_NAME_TX ,
          PARENT_ID ,
          TRANS_STATUS_CD ,
          UTL_IN
        )
        SELECT DISTINCT
                'Allied.UniTrac.RequiredCoverage' ,
                ID ,
                ' INC0XXXXXX' ,
                'N' ,
                GETDATE() ,
                1 ,
                'Changed Summary status to Borrowers Insurance after removing Impairment' ,
                'N' ,
                'Y' ,
                1 ,
                'Allied.UniTrac.RequiredCoverage' ,
                ID ,
                'PEND' ,
                'N'
        FROM    dbo.REQUIRED_COVERAGE
        WHERE   ID IN ( SELECT  ID
                        FROM    UniTracHDStorage..INC0244507_RC )
