---------- Validate Work Item before making update
----REPLACE XXXXXXX WITH THE WI ID
----REPLACE INCXXXXXXX WITH TICKET NUMBER
SELECT * 
INTO UniTracHDStorage..INC0252267
FROM UniTrac..WORK_ITEM
WHERE ID IN (34216012,34312860,34401562)


--------- Insert New Row in Work Item Action (for History Tracking)
----REPLACE XXXXXXX WITH THE THE WI ID

INSERT INTO dbo.WORK_ITEM_ACTION (WORK_ITEM_ID ,ACTION_CD ,FROM_STATUS_CD , TO_STATUS_CD ,CURRENT_QUEUE_ID ,CURRENT_OWNER_ID ,ACTION_NOTE_TX , ACTIVE_IN ,CREATE_DT ,PURGE_DT ,UPDATE_DT ,UPDATE_USER_TX ,LOCK_ID,ACTION_USER_ID) VALUES  ( 34216012 , N'Complete' , N'Initial' , N'Complete' ,5 , 738 ,N'Manual Close Request HDT' , 'Y' , GETDATE() , NULL ,GETDATE() , N'INC0252267' , 1 , 1 )
INSERT INTO dbo.WORK_ITEM_ACTION (WORK_ITEM_ID ,ACTION_CD ,FROM_STATUS_CD , TO_STATUS_CD ,CURRENT_QUEUE_ID ,CURRENT_OWNER_ID ,ACTION_NOTE_TX , ACTIVE_IN ,CREATE_DT ,PURGE_DT ,UPDATE_DT ,UPDATE_USER_TX ,LOCK_ID,ACTION_USER_ID) VALUES  ( 34312860 , N'Complete' , N'Initial' , N'Complete' ,5 , 738 ,N'Manual Close Request HDT' , 'Y' , GETDATE() , NULL ,GETDATE() , N'INC0252267' , 1 , 1 )
INSERT INTO dbo.WORK_ITEM_ACTION (WORK_ITEM_ID ,ACTION_CD ,FROM_STATUS_CD , TO_STATUS_CD ,CURRENT_QUEUE_ID ,CURRENT_OWNER_ID ,ACTION_NOTE_TX , ACTIVE_IN ,CREATE_DT ,PURGE_DT ,UPDATE_DT ,UPDATE_USER_TX ,LOCK_ID,ACTION_USER_ID) VALUES  ( 34401562 , N'Complete' , N'Initial' , N'Complete' ,5 , 738 ,N'Manual Close Request HDT' , 'Y' , GETDATE() , NULL ,GETDATE() , N'INC0252267' , 1 , 1 )




SELECT * FROM dbo.WORK_ITEM_ACTION
WHERE WORK_ITEM_ID = 'XXXXXXX'


--(34216012,34312860,34401562)
----Use Last WIA ID that was created for LAST_WORK_ITEM_ACTION_ID column 
UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete', 
LAST_WORK_ITEM_ACTION_ID = (SELECT MAX(ID) FROM dbo.WORK_ITEM_ACTION WHERE   WORK_ITEM_ID IN ( 34401562 )),
UPDATE_DT = GETDATE(),LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0252267'
WHERE   ID IN ( 34401562 )
        AND WORKFLOW_DEFINITION_ID = 7
        AND ACTIVE_IN = 'Y'



----Use Last WIA ID that was created for LAST_WORK_ITEM_ACTION_ID column 
UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete', 
LAST_WORK_ITEM_ACTION_ID = (SELECT MAX(ID) FROM dbo.WORK_ITEM_ACTION WHERE   WORK_ITEM_ID IN ( 34312860 )),
UPDATE_DT = GETDATE(),LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0252267'
WHERE   ID IN ( 34312860 )
        AND WORKFLOW_DEFINITION_ID = 7
        AND ACTIVE_IN = 'Y'



----Use Last WIA ID that was created for LAST_WORK_ITEM_ACTION_ID column 
UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete', 
LAST_WORK_ITEM_ACTION_ID = (SELECT MAX(ID) FROM dbo.WORK_ITEM_ACTION WHERE   WORK_ITEM_ID IN ( 34216012 )),
UPDATE_DT = GETDATE(),LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0252267'
WHERE   ID IN ( 34216012 )
        AND WORKFLOW_DEFINITION_ID = 7
        AND ACTIVE_IN = 'Y'
