USE UniTrac


SELECT * FROM dbo.PROCESS_DEFINITION
WHERE UPDATE_USER_TX = 'LDHUSD'


SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID IN (39,
27515) AND UPDATE_DT >= '2016-10-26 '


SELECT CC.CODE_TX, L.NUMBER_TX FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
WHERE LL.CODE_TX = '4150' --AND L.RECORD_TYPE_CD = 'G'
AND COLLATERAL_CODE_ID IN (228)


select  ID [WorkItem], current_owner_id FROM dbo.WORK_ITEM
where id IN ('34801529','34699668')



---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 


UPDATE CCR
SET CCR.PURGE_DT = NULL
--SELECT *
FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '4150' AND CC.ID IN (228, 39, 40)


UPDATE L
SET PURGE_DT = NULL
--SELECT *
FROM dbo.LOAN L 
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
WHERE C.COLLATERAL_CODE_ID IN (228, 39, 40)
AND LENDER_ID = '694'


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '4150'