USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT LL.NAME_TX [Lender Name], LL.CODE_TX [Lender Code], L.NUMBER_TX, L.ORIGINAL_BALANCE_AMOUNT_NO [Original Loan Balance], CC.DESCRIPTION_TX [Collateral],
IH.SPECIAL_HANDLING_XML.value('(/SH/Reason)[1]', 'varchar (50)')[CPI Reason], 
IH.SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar (50)') [CPI Status], A.NAME_TX[Agency Affiliation]
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = C.PROPERTY_ID AND IH.TYPE_CD = 'CPI' AND IH.RELATE_CLASS_TX = 'Allied.UniTrac.CPIQuote'
INNER JOIN dbo.COLLATERAL_CODE CC ON C.COLLATERAL_CODE_ID = CC.ID AND C.COLLATERAL_CODE_ID = '8'
INNER JOIN dbo.AGENCY A ON A.ID = LL.AGENCY_ID
WHERE L.ORIGINAL_BALANCE_AMOUNT_NO >= '100000' AND LL.STATUS_CD <> 'CANCEL'
ORDER BY L.NUMBER_TX DESC 

