USE unitrac



SELECT L.*
INTO UniTracHDStorage..INC0291268
 FROM dbo.LOAN L
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX = '4422' AND DIVISION_CODE_TX <> '99'


SELECT * FROM UniTracHDStorage..INC0291268


UPDATE dbo.LOAN
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0291268', 
LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END, DIVISION_CODE_TX = '99'
--SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0291268)
	

	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0291268' , 'N' , 
 GETDATE() ,  1 , 
'Moved Loans to Division 99', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0291268)
