USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT
        L.NUMBER_TX [Loan Number] ,
        L.ORIGINAL_PAYMENT_AMOUNT_NO ,
        CQ.PAYMENT_INCREASE_METHOD_VALUE_NO ,
        FPC.CURRENT_PAYMENT_AMOUNT_NO ,
        CR.Description_tx [Status]
FROM    LOAN L
        LEFT JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.LOAN_ID = L.ID
        LEFT JOIN dbo.FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCR ON FPCR.FPC_ID = FPC.ID
        LEFT JOIN dbo.REQUIRED_COVERAGE RC ON RC.ID = FPCR.REQUIRED_COVERAGE_ID
        LEFT JOIN dbo.CPI_QUOTE CQ ON CQ.ID = FPC.CPI_QUOTE_ID
        LEFT JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CQ.ID
        LEFT JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        LEFT JOIN dbo.REF_CODE CR ON CR.CODE_CD = FPC.STATUS_CD
                                     AND DOMAIN_CD = 'ForcePlacedCertificateStatus'
WHERE   LL.CODE_TX IN ( '3170' )
        AND FPC.STATUS_CD NOT IN ( 'F', 'B' )
UNION
SELECT DISTINCT
        L.NUMBER_TX [Loan Number] ,
        L.ORIGINAL_PAYMENT_AMOUNT_NO ,
        CQ.PAYMENT_INCREASE_METHOD_VALUE_NO ,
        FPC.CURRENT_PAYMENT_AMOUNT_NO ,
        CR.Description_tx [Status]
FROM    LOAN L
        LEFT JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.LOAN_ID = L.ID
        LEFT JOIN dbo.FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCR ON FPCR.FPC_ID = FPC.ID
        LEFT JOIN dbo.REQUIRED_COVERAGE RC ON RC.ID = FPCR.REQUIRED_COVERAGE_ID
        LEFT JOIN dbo.CPI_QUOTE CQ ON CQ.ID = FPC.CPI_QUOTE_ID
        LEFT JOIN dbo.CPI_ACTIVITY CA ON CA.CPI_QUOTE_ID = CQ.ID
        LEFT JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        LEFT JOIN dbo.REF_CODE CR ON CR.CODE_CD = FPC.STATUS_CD
                                     AND DOMAIN_CD = 'ForcePlacedCertificateStatus'
WHERE   LL.CODE_TX IN ( '3170' )
        AND FPC.STATUS_CD IN ( 'F', 'B' )
		ORDER BY CR.Description_tx DESC 
