USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.* INTO #tmpRC
--INTO UniTracHDStorage..INC0279132_RC
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE --LL.CODE_TX IN ('3067') AND L.DIVISION_CODE_TX IN ('4')
--AND RC.STATUS_CD = 'M'-- AND RC.ID NOT IN (SELECT ID FROM UniTracHDStorage..INC0279132)


---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'



---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = 'XXXX'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD LIKE 'requiredcoveragestatus'

UPDATE dbo.REQUIRED_COVERAGE
SET STATUS_CD = 'A', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0279132', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0279132)


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , L.ID , 'INC0279132' , 'N' , 
 GETDATE() ,  1 , 
'Set status Active', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , L.ID , 'PEND' , 'N'
FROM dbo.REQUIRED_COVERAGE L WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0279132_rc)



SELECT ID FROM UniTracHDStorage..INC0279132
WHERE ID IN (37512791,
42257446,
42421694,
61269817,
61303810)

SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0279132)



SELECT * FROM dbo.PROPERTY_CHANGE pc
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE pcu ON PC.ID = PCU.CHANGE_ID 
WHERE PC.ENTITY_NAME_TX = 'Allied.UniTrac.RequiredCoverage' AND PC.ENTITY_ID IN (SELECT ID FROM UniTracHDStorage..INC0279132)




UPDATE dbo.REQUIRED_COVERAGE
SET STATUS_CD = 'I', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0279132', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (49589564,
54117473,
97741880,
97742539,
97744735,
97744800,
97744855,
107427946,
120263271,
126618201)


UPDATE dbo.REQUIRED_COVERAGE
SET STATUS_CD = 'W', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0279132', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (65754206,66071037,68661616,69771247,100438251,102262837)
