USE Unitrac


SELECT L.* 
INTO UniTracHDStorage..INC0308558
FROM dbo.LOAN L
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX = '2261'


UPDATE L
SET DIVISION_CODE_TX = '99', UPDATE_DT = GETDATE(), LOCK_ID = LOCK_ID+1, UPDATE_USER_TX = 'INC0308558'
--SELECT DIVISION_CODE_TX, * 
FROM dbo.LOAN L
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0308558)



INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0308558' , 'N' , 
 GETDATE() ,  1 , 
'DIVISION_CODE_TX moved to 99', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0308558)

