USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT  ESCROW_PAID_THRU_DT, RC.ESCROW_IN, RC.*
--INTO #tmp
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('1729') AND L.NUMBER_TX = '1110438801'



UPDATE dbo.REQUIRED_COVERAGE
SET ESCROW_IN = 'N', UPDATE_DT = GETDATE()-2, UPDATE_USER_TX = 'INC0234786', LOCK_ID = LOCK_ID+1, ESCROW_STATUS_CD = NULL
--SELECT ESCROW_IN, LOCK_ID [RC], * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (12177272)



SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%%'
        AND AGENCY_ID = '1'
        AND ID IN (  )



SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'




SELECT * FROM dbo.REQUIRED_ESCROW
WHERE REQUIRED_COVERAGE_ID = '12177272'


SELECT * 
INTO UniTracHDStorage..INC0234786_RE
FROM dbo.REQUIRED_ESCROW
WHERE REQUIRED_COVERAGE_ID = '12177272'



UPDATE dbo.REQUIRED_ESCROW
SET PURGE_DT = GETDATE()-2, UPDATE_DT = GETDATE()-2, UPDATE_USER_TX = 'INC0234786', LOCK_ID = LOCK_ID+1
--SELECT * FROM dbo.REQUIRED_ESCROW
WHERE ID IN (SELECT ID FROM  UniTracHDStorage..INC0234786_RE) AND SUB_STATUS_CD = 'POD'