USE UniTrac


SELECT L.CODE_TX, L.NAME_TX, MP.*
INTO UniTracHDStorage..INC0241114
FROM dbo.MASTER_POLICY MP
INNER JOIN dbo.LENDER L ON MP.LENDER_ID = L.ID AND L.STATUS_CD = 'ACTIVE'
INNER JOIN dbo.CARRIER C ON C.ID = MP.CARRIER_ID
WHERE C.Id = '64'

SELECT * FROM dbo.CARRIER
WHERE NAME_TX LIKE 'American National%'


SELECT * FROM dbo.LENDER 
WHERE STATUS_CD = 'ACTIVE'