USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX, OP.*
INTO jcs..INC0318278
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
INNER JOIN dbo.OWNER_POLICY op ON op.id = ih.RELATE_ID AND ih.RELATE_CLASS_TX ='Allied.UniTrac.OwnerPolicy'
WHERE LL.CODE_TX IN ('2375') AND L.DIVISION_CODE_TX = '4'
AND IH.EFFECTIVE_DT >= '2017-07-25 ' AND IH.TYPE_CD = 'OWNERPOLICY' 
--AND  L.NUMBER_TX IN ( '1030883701')



SELECT L.NUMBER_TX, OP.* INTO jcs..INC0318278_B  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
INNER JOIN dbo.OWNER_POLICY op ON op.id = ih.RELATE_ID AND ih.RELATE_CLASS_TX ='Allied.UniTrac.OwnerPolicy'
WHERE LL.CODE_TX IN ('2375') AND L.DIVISION_CODE_TX = '4'
AND IH.EFFECTIVE_DT >= '2017-07-17 ' AND IH.TYPE_CD = 'OWNERPOLICY' 

SELECT * FROM  dbo.LENDER_ORGANIZATION LO 
JOIN dbo.LENDER L ON L.ID = LO.LENDER_ID
WHERE L.CODE_TX = '2375'





SELECT * FROM  dbo.PROPERTY
WHERE ID = 

SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = ''


SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX LIKE '%%'