USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.ID, P.ID, C.ID FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2202') AND L.NUMBER_TX = '2274670L4'

SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE pcU ON pCU.CHANGE_ID = pc.id
WHERE (pc.ENTITY_ID = '169739687' AND pc.ENTITY_NAME_TX = 'Allied.UniTrac.Loan'
OR pc.ENTITY_ID IN ('103740281','142451274') AND pc.ENTITY_NAME_TX = 'Allied.UniTrac.Property'
OR pc.ENTITY_ID IN  ('144322289','143923467') AND pc.ENTITY_NAME_TX = 'Allied.UniTrac.Collateral')
ORDER BY pc.ENTITY_NAME_TX ASC 

SELECT * FROM dbo.COLLATERAL
WHERE ID = '144322289'

SELECT * FROM dbo.PROPERTY
WHERE ID = '103740281'

SELECT * FROM dbo.LOAN
WHERE ID = '169739687'



SELECT * FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
WHERE P.ID IN ('103740281','142451274')



SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX LIKE '%multi%'

