USE UniTrac


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '1836'


SELECT SPECIAL_HANDLING_XML.value('(/SH/Misc/VerifyDataWorkItemId)[1]', 'varchar (50)') [Work Item], *
--INTO UniTracHDStorage..INC0239034_Loan
 FROM dbo.LOAN
WHERE LENDER_ID = '435'
AND SPECIAL_HANDLING_XML IS NOT NULL
AND SPECIAL_HANDLING_XML.value('(/SH/Misc/VerifyDataWorkItemId)[1]', 'varchar (50)') <> '0'
--AND NUMBER_TX = '11345063-30'



SELECT * 
INTO UniTracHDStorage..INC0239034WI
FROM dbo.WORK_ITEM
WHERE WORKFLOW_DEFINITION_ID = '8' AND 
RELATE_ID IN (SELECT ID FROM UniTracHDStorage..INC0239034_Loan)




SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, * --INTO UniTracHDStorage..WI_INC0222261
INTO    #TMPWI
FROM    UniTrac..WORK_ITEM
WHERE   ID IN ( SELECT ID FROM UniTracHDStorage..INC0239034WI  )



UPDATE WI SET STATUS_CD = 'Withdrawn' , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0239034' , 
LOCK_ID = WI.LOCK_ID % 255 + 1
---- SELECT COUNT(*)
FROM WORK_ITEM WI JOIN #TMPWI TMP ON 
TMP.ID = WI.ID
AND WI.PURGE_DT IS NULL 
---- 

INSERT INTO WORK_ITEM_ACTION (WORK_ITEM_ID, ACTION_CD, FROM_STATUS_CD, TO_STATUS_CD, CURRENT_QUEUE_ID, 
CURRENT_OWNER_ID, ACTION_NOTE_TX, ACTIVE_IN, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID, ACTION_USER_ID)
SELECT DISTINCT ID , 'Withdraw' , STATUS_CD , 'Withdrawn' , CURRENT_QUEUE_ID , 
CURRENT_OWNER_ID , 'INC0239034' , 'Y' , GETDATE() , GETDATE() , 'INC0239034' , 1 , 1
FROM #TMPWI
ORDER BY STATUS_CD
---- 


UPDATE LN SET SPECIAL_HANDLING_XML = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX  = 'INC0239034' , 
LOCK_ID = LN.LOCK_ID % 255 + 1
--- SELECT LN.NUMBER_TX
FROM LOAN LN JOIN #TMPWI ON #TMPWI.RELATE_ID = LN.ID
--- 


SELECT * FROM UniTracHDStorage..INC0239034_Loan

SELECT * FROM UniTracHDStorage..INC0239034WI 