USE [UniTrac]
GO 

SELECT * FROM dbo.LENDER
WHERE CODE_TX = '1831'

SELECT * FROM dbo.WORK_ITEM
WHERE ID IN ( '30508884 ', '30508891')


SELECT * FROM UniTracHDStorage..INC0237108_L

SELECT * FROM UniTracHDStorage..INC0237108_P

SELECT * FROM UniTracHDStorage..INC0237108_RC

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT *
--INTO UniTracHDStorage..INC0237108_RC
 FROM LOAN L
INNER JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
INNER JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
WHERE L.LENDER_ID = '372' AND L.ID IN( '140713813 ', '141035384')




UPDATE RC
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = ' INC0237108',LOCK_ID=LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT RECORD_TYPE_CD, * 
FROM dbo.REQUIRED_COVERAGE RC
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0237108_RC)

UPDATE L 
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0237108',LOCK_ID=LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT RECORD_TYPE_CD, * 
FROM dbo.LOAN L
WHERE ID IN (SELECT ID FROM  UniTracHDStorage..INC0237108_L)


UPDATE P
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0237108',LOCK_ID=LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT RECORD_TYPE_CD, * 
FROM dbo.PROPERTY P
WHERE ID IN (SELECT ID FROM  UniTracHDStorage..INC0237108_P)




INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , ' INC0237108' , 'N' , 
 GETDATE() ,  1 , 
 'Make Loan Archive', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
WHERE RC.ID IN (SELECT ID FROM UniTracHDStorage..INC0237108_RC)

INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , ' INC0237108' , 'N' , 
 GETDATE() ,  1 , 
'Make Loan Archive', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0237108_L)



INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Property' , P.ID , ' INC0237108' , 'N' , 
 GETDATE() ,  1 , 
 'Make Loan Archive',
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Property' , P.ID , 'PEND' , 'N'
FROM PROPERTY P
WHERE P.ID IN (SELECT ID FROM UniTracHDStorage..INC0237108_P)



SELECT * FROM dbo.PROPERTY_CHANGE
WHERE CREATE_DT >= '2016-06-15 ' AND USER_TX = 'INC0237108'