--Payment Increase Notice History and Config Info
USE UniTrac

SELECT *
FROM LENDER
WHERE CODE_TX = '2047'

SELECT * FROM dbo.PROCESS_DEFINITION
WHERE NAME_TX LIKE '%2047%'


SELECT ID INTO #tmpPL FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID IN ( 13882)AND UPDATE_DT >= '2016-11-08 '
AND STATUS_CD = 'Complete'

SELECT * FROM dbo.WORK_ITEM
WHERE RELATE_ID IN (40224290,
40224312)


--DROP TABLE #tmpRH
SELECT RELATE_ID INTO #tmpRH FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (40224290,
40224312) AND RELATE_TYPE_CD = 'Allied.UniTrac.ReportHistory'



SELECT rh.REPORT_DATA_XML.value( '(/ReportData/Report/WorkItemId/@value)[1]', 'varchar(500)' ) as [WI.ID],
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/ProcessDefinitionID/@value)[1]', 'varchar(500)' ) as [PD.ID],
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/ProcessLogID/@value)[1]', 'varchar(500)' ) as [ProcessLog.ID],
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/Title/@value)[1]', 'varchar(500)' ) as TITLE, R.NAME_TX,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/ReportType/@value)[1]', 'varchar(500)' ) AS ReportType,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/Branches/Branch)[1]', 'varchar(500)' ) AS Branch,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/Division/@value)[1]', 'varchar(500)' ) AS Division,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/Coverage/@value)[1]', 'varchar(500)' ) AS Coverage,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/GroupByTx/@value)[1]', 'varchar(500)' ) AS GroupByTx,
	rh.REPORT_DATA_XML.value( '(/ReportData/Report/ReportConfig/@value)[1]', 'varchar(500)' ) AS ReportConfig,
		rh.REPORT_DATA_XML.value( '(/ReportData/Report/SortByTx/@value)[1]', 'varchar(500)' ) AS SortByCode,
		rh.REPORT_DATA_XML.value( '(/ReportData/Report/StartDate/@value)[1]', 'varchar(500)' ) AS StartDate,
		rh.REPORT_DATA_XML.value( '(/ReportData/Report/EndDate/@value)[1]', 'varchar(500)' ) AS EndDate,
rh.*
FROM    REPORT_HISTORY rh
	JOIN REPORT R ON R.id = RH.REPORT_ID
WHERE REPORT_ID = '58' --AND rh.id IN (SELECT * FROM #tmpRH)
AND rh.REPORT_DATA_XML.value( '(/ReportData/Report/ProcessLogID/@value)[1]', 'varchar(500)' ) IN (SELECT * FROM #tmpPL)
ORDER BY rh.UPDATE_DT DESC



SELECT *
FROM LENDER_REPORT_CONFIG LRC
JOIN dbo.LENDER L ON L.ID = LRC.LENDER_ID
WHERE L.CODE_TX = '2047' AND DESCRIPTION_TX like 'Payment Increase %'

SELECT *
FROM REPORT_CONFIG
WHERE CODE_TX = 'PI1LP-IN01-BLNK'


SELECT *
FROM DOCUMENT_CONTAINER
WHERE ID = '????????' 
----------------------------------

--Payment Increase Notice SP

--EXEC Report_PaymentIncreaseNotices @LenderCode=N'1919',@Branch=N'',@Division=N'3',@Coverage=N'',@ReportType=N'PI1LP-IN01-BLNK',@GroupByCode=N'',@SortByCode=N'PolicyNumber',@FilterByCode=N'PI1LP-IN01-BLNK',@ReportConfig=N'PI1LP-IN01-BLNK',@Report_History_ID=N'1'

--DROP TABLE #tmpFPC
SELECT RELATE_ID INTO #tmpFPC FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '40224290' AND RELATE_TYPE_CD = 'Allied.UniTrac.ForcePlacedCertificate'
-----------------------------------

--***********************************************************************************************
---If Missing, there are Two Reasons
--1) FPC.ISSUE_DT does not fall within last 30 day window
--2) FTX.NET_AMOUNT = 0
--***********************************************************************************************


---FPC Updates to ensure ISSUE_DT falls within 30 day window. 
--Date logic is in this query:
--		DATEADD(DAY, CASE WHEN FPC.QUICK_ISSUE_IN = 'Y' THEN 0 
--			ELSE ISNULL(RC.PmtOptIncrDelayedBilling,0) 
--			END, FPC.ISSUE_DT),RC.PmtOptIncrDelayedBilling

select ID,ISSUE_DT,*
from FORCE_PLACED_CERTIFICATE
WHERE ID IN (SELECT * FROM #tmpFPC)
ORDER BY FORCE_PLACED_CERTIFICATE.ID

select * --INTO UniTracHDStorage..INC0276920_FPC
from FORCE_PLACED_CERTIFICATE
WHERE ID IN (SELECT * FROM #tmpFPC)
ORDER BY FORCE_PLACED_CERTIFICATE.ID

--5576000	2016-03-25 02:27:26.8730000
--5595373	2016-04-08 02:20:09.5430000
--5595375	2016-04-08 02:20:15.1930000
--5595380	2016-04-08 02:20:29.8400000
--5595382	2016-04-08 02:20:30.5600000

--Update ISSUE_DT to comply
UPDATE FORCE_PLACED_CERTIFICATE
SET ISSUE_DT = '2016-11-22 03:00 '
--SELECT ISSUE_DT,* FROM FORCE_PLACED_CERTIFICATE
WHERE ID IN (SELECT * FROM #tmpFPC)


-------------------


UPDATE  [UniTrac].[dbo].[REPORT_HISTORY]
SET     STATUS_CD = 'PEND' ,
        RETRY_COUNT_NO = 0 ,
        MSG_LOG_TX = NULL ,
        RECORD_COUNT_NO = 0 ,
        ELAPSED_RUNTIME_NO = 0,
REPORT_DATA_XML.modify('replace value of (/ReportData/Report/StartDate/@value)[1] with "2016-11-25T02:02:28"') ,
		UPDATE_DT = GETDATE(), DOCUMENT_CONTAINER_ID = NULL 
--	, REPORT_DATA_XML = ''
--		,REPORT_ID = '27'
--SELECT * FROM dbo.REPORT_HISTORY
WHERE   ID IN (SELECT * FROM #tmpRH) AND REPORT_ID = '58'



UPDATE fpc
SET fpc.ISSUE_DT = fpc2.ISSUE_DT
--SELECT fpc.ISSUE_DT [Live] , fpc2.ISSUE_DT[Backup] ,*
FROM dbo.FORCE_PLACED_CERTIFICATE fpc
JOIN  UniTracHDStorage..INC0276920_FPC fpc2 ON fpc.id=fpc2.id



--Calls out all specific certs by Number in #tmpSpecialFPCs
		SELECT FPC.ID, FPC.QUICK_ISSUE_IN, FPC.ISSUE_DT,
		DATEADD(DAY, CASE WHEN FPC.QUICK_ISSUE_IN = 'Y' THEN 0 
			ELSE ISNULL(RC.PmtOptIncrDelayedBilling,0) 
			END, FPC.ISSUE_DT),RC.PmtOptIncrDelayedBilling
		FROM FORCE_PLACED_CERTIFICATE FPC
		JOIN LOAN L ON FPC.LOAN_ID = L.ID AND L.PURGE_DT IS NULL
		JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCRCR ON FPCRCR.FPC_ID = FPC.ID AND FPCRCR.PURGE_DT IS NULL
		JOIN REQUIRED_COVERAGE RC ON FPCRCR.REQUIRED_COVERAGE_ID = RC.ID AND RC.PURGE_DT IS NULL	
		WHERE 1=1
		AND FPC.PURGE_DT IS NULL AND FPC.ID IN  (SELECT * FROM #tmpFPC)
			  --ORDER BY FPC.ID
		AND 
      ((FPC.QUICK_ISSUE_IN = 'N' AND DATEADD(DAY,ISNULL(RC.PmtOptIncrDelayedBilling,0), FPC.ISSUE_DT)  BETWEEN '2016-11-07 ' and '2016-12-16') OR --only pulls the FPC IDs that fall between the Start/End date and have the special logic  (based on current date)
       (FPC.QUICK_ISSUE_IN = 'Y' AND FPC.ISSUE_DT BETWEEN '2016-11-07 ' and '2016-12-16')  ---use end date of prev & current cycle for QI  (based on current date)
      )
---------------------------


---Actual Inserts for Main Query

CREATE TABLE #tmpSpecialFPCs ( 
	ID bigint,
	QUICK_ISSUE_IN varchar(1) NULL,
	ISSUE_DT DATETIME2(7) NULL,
	NEW_ISSUE_DT DATETIME2(7) NULL
) ON [PRIMARY]

CREATE TABLE #tmpFPCIDs ( 
	ID bigint PRIMARY KEY
) ON [PRIMARY]

	INSERT INTO #tmpSpecialFPCs (ID, QUICK_ISSUE_IN, ISSUE_DT, NEW_ISSUE_DT)
		SELECT FPC.ID, FPC.QUICK_ISSUE_IN, FPC.ISSUE_DT,
		DATEADD(DAY, CASE WHEN FPC.QUICK_ISSUE_IN = 'Y' THEN 0 
			ELSE ISNULL(RC.PmtOptIncrDelayedBilling,0) 
			END, FPC.ISSUE_DT)
		FROM FORCE_PLACED_CERTIFICATE FPC
		JOIN LOAN L ON FPC.LOAN_ID = L.ID AND L.PURGE_DT IS NULL
		JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCRCR ON FPCRCR.FPC_ID = FPC.ID AND FPCRCR.PURGE_DT IS NULL
		JOIN REQUIRED_COVERAGE RC ON FPCRCR.REQUIRED_COVERAGE_ID = RC.ID AND RC.PURGE_DT IS NULL	
		WHERE 1=1
		AND FPC.PURGE_DT IS NULL
		AND L.LENDER_ID = 67
		AND FPC.ISSUE_DT between  '2016-12-06 ' and '2016-12-16' --widens the start and end date by 100 days to only pull a subset of FPCs (based on current date)

	INSERT INTO #tmpFPCIDs (ID)	
		SELECT SFPC.ID 
		FROM #tmpSpecialFPCs SFPC
		WHERE 
      (
       (SFPC.QUICK_ISSUE_IN = 'N' AND SFPC.NEW_ISSUE_DT BETWEEN '2016-12-06 ' and '2016-12-16') OR --only pulls the FPC IDs that fall between the Start/End date and have the special logic (based on current date)
       (SFPC.QUICK_ISSUE_IN = 'Y' AND SFPC.NEW_ISSUE_DT BETWEEN '2016-12-06 ' and '2016-12-16')  ---use end date of prev & current cycle for QI (based on current date)
      )
		GROUP BY SFPC.ID


--Final FPCs for Query
SELECT *
FROM #tmpFPCIDs
-----

---Actual Query Results being pulled into Report
DECLARE	@Branch as nvarchar(max)
DECLARE	@Division as nvarchar(10)
DECLARE @Coverage as nvarchar(100)
DECLARE @FIL_DATERANGE AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_PIR AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_SPECIAL AS varchar(1) = 'T'
DECLARE @FIL_FUNDDT_RANGE AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_FILE AS varchar(1) = 'F'


SET @Division = '3'

DECLARE @BranchTable AS TABLE(ID int, STRVALUE nvarchar(30))
			INSERT INTO @BranchTable SELECT * FROM SplitFunction(@Branch, ',')  

SELECT *
FROM #tmpFPCIDs tmp
JOIN FORCE_PLACED_CERTIFICATE FPC on tmp.ID = FPC.ID
JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCRCR ON FPCRCR.FPC_ID = FPC.ID AND FPCRCR.PURGE_DT IS NULL
JOIN CARRIER CR ON FPC.CARRIER_ID = CR.ID AND CR.PURGE_DT IS NULL	
JOIN REQUIRED_COVERAGE RC ON FPCRCR.REQUIRED_COVERAGE_ID = RC.ID AND RC.PURGE_DT IS NULL					 
JOIN LOAN L ON L.ID = FPC.LOAN_ID AND L.PURGE_DT IS NULL 
JOIN LENDER LND ON LND.ID = L.LENDER_ID AND LND.PURGE_DT IS NULL
JOIN OWNER_LOAN_RELATE OLR ON OLR.LOAN_ID = L.ID AND OLR.PRIMARY_IN = 'Y' AND OLR.PURGE_DT IS NULL
JOIN [OWNER] O ON O.ID = OLR.OWNER_ID AND O.PURGE_DT IS NULL
JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID AND P.PURGE_DT IS NULL											
JOIN COLLATERAL C ON C.LOAN_ID = L.ID AND C.PROPERTY_ID = P.ID AND C.PURGE_DT IS NULL
LEFT JOIN LENDER_ORGANIZATION LO ON L.BRANCH_CODE_TX = LO.CODE_TX AND L.LENDER_ID = LO.LENDER_ID AND LO.TYPE_CD = 'BRCH' AND LO.PURGE_DT IS NULL
LEFT JOIN [ADDRESS] LOPADDR ON LO.PHYSICAL_ADDRESS_ID = LOPADDR.ID AND LOPADDR.PURGE_DT IS NULL
LEFT JOIN [ADDRESS] LOMADDR ON LO.MAILING_ADDRESS_ID = LOMADDR.ID AND LOMADDR.PURGE_DT IS NULL
LEFT JOIN OWNER_ADDRESS AP ON AP.ID = P.ADDRESS_ID AND AP.PURGE_DT IS NULL
LEFT JOIN [OWNER_ADDRESS] AO ON AO.ID = O.ADDRESS_ID AND AO.PURGE_DT IS NULL
LEFT JOIN REF_CODE RC_COVERAGETYPE ON RC_COVERAGETYPE.DOMAIN_CD = 'Coverage' and RC_COVERAGETYPE.CODE_CD = RC.TYPE_CD 
LEFT JOIN REF_CODE RC_DIVISION on RC_DIVISION.DOMAIN_CD = 'ContractType' and RC_DIVISION.CODE_CD = L.DIVISION_CODE_TX 
LEFT JOIN COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID AND CC.PURGE_DT IS NULL
left Join REF_CODE RC_SC on RC_SC.DOMAIN_CD = 'SecondaryClassification' AND CC.SECONDARY_CLASS_CD = RC_SC.CODE_CD
left Join REF_CODE_ATTRIBUTE RCA_PROP on RC_SC.DOMAIN_CD = RCA_PROP.DOMAIN_CD and RC_SC.CODE_CD = RCA_PROP.REF_CD and RCA_PROP.ATTRIBUTE_CD = 'PropertyType'
LEFT JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCR ON SCR.LENDER_ID = LND.ID
LEFT JOIN SERVICE_CENTER_FUNCTION SCF ON SCF.ID = SCR.SERVICE_CENTER_FUNCTION_ID
LEFT JOIN SERVICE_CENTER SC ON SC.ID = SCF.SERVICE_CENTER_ID
LEFT JOIN CPI_QUOTE CPQ ON  CPQ.ID = FPC.CPI_QUOTE_ID AND CPQ.PURGE_DT IS NULL
LEFT JOIN CPI_ACTIVITY CPA_I on CPA_I.CPI_QUOTE_ID = CPQ.ID AND CPA_I.TYPE_CD = 'I'	AND CPA_I.PURGE_DT IS NULL AND CPA_I.CREATE_DT <= '2016-09-11'
OUTER APPLY 
(SELECT SUM(TOTAL_PREMIUM_NO) AS TOTAL_PREMIUM_NO, MAX(REASON_CD) AS REASON_CD, MAX(REPORTING_CANCEL_DT) AS REPORTING_CANCEL_DT 
FROM CPI_ACTIVITY C  
WHERE C.CPI_QUOTE_ID = CPQ.ID AND C.TYPE_CD IN ('C', 'R', 'MT') AND C.PURGE_DT IS NULL AND C.CREATE_DT <= '2016-09-11'
) CPA_C
CROSS APPLY
(
SELECT 
-- Note that some of the SUMs use EARNED_PAYMENT_AMOUNT_NO and others use NEW_PAYMENT_AMOUNT_NO or TOTAL_PREMIUM_NO
-- 04292013 Anu Only use row for EARNED_PAYMENT_AMOUNT (EarnedPremium) for the max ProcessDate
SUM(CASE WHEN CPI.TYPE_CD  IN('C','MT') AND CPI.PROCESS_DT = CPI_MX.PROCESS_DT THEN CPI.EARNED_PAYMENT_AMOUNT_NO ELSE 0 END) AS EarnedPremium,
-- (CalcPmtDecrease) C & MT
SUM(CASE WHEN CPI.TYPE_CD  IN('C','MT')  AND CPI.PROCESS_DT = CPI_MX.PROCESS_DT THEN CPI.PAYMENT_CHANGE_AMOUNT_NO ELSE 0 END) AS CalcPmtIncr,
--For Payment decrease � we can get the sum of NewPaymentAmount from CPIActivity � for Types � C, MT, R
SUM(CASE WHEN CPI.TYPE_CD  IN('C','MT','R') THEN CPI.PAYMENT_CHANGE_AMOUNT_NO ELSE 0 END) AS PmtDecrAmount,
SUM(CASE WHEN CPI.TYPE_CD  IN('I') THEN CPI.TOTAL_PREMIUM_NO ELSE 0 END) AS CalcIssTtlCharges,
SUM(CASE WHEN CPI.TYPE_CD  IN('C','MT','R') THEN CPI.TOTAL_PREMIUM_NO ELSE 0 END) AS CalcCanTtlCharges
FROM CPI_ACTIVITY CPI
CROSS APPLY 
 (
	SELECT MAX(CPI1.PROCESS_DT) AS PROCESS_DT FROM CPI_ACTIVITY CPI1 
	WHERE CPI1.CPI_QUOTE_ID = CPQ.ID AND CPI1.TYPE_CD  IN('C','MT') AND CPI1.PURGE_DT IS NULL AND CPI1.CREATE_DT <= '2016-09-11'
 ) CPI_MX
 WHERE CPI.CPI_QUOTE_ID = CPQ.ID AND CPI.PURGE_DT IS NULL AND CPI.CREATE_DT <= '2016-09-11'
) CPI_ALL
--ADDED Anu 04/23/2013 to get IPRM_AMOUNT_NO for Increased By Calculation
OUTER APPLY (
SELECT  
SUM(CASE WHEN CD_SQ.TYPE_CD = 'PRM' AND CPA_SQ.TYPE_CD = 'I' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS IPRM_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'FEE' AND CPA_SQ.TYPE_CD = 'I' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS IFEE_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'OTH' AND CPA_SQ.TYPE_CD = 'I' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS IOTH_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'TAX1' AND CPA_SQ.TYPE_CD = 'I' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS ITAX1_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'TAX2' AND CPA_SQ.TYPE_CD = 'I' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS ITAX2_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'PRM' AND CPA_SQ.TYPE_CD = 'C' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS CPRM_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'FEE' AND CPA_SQ.TYPE_CD = 'C' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS CFEE_AMOUNT_NO,
SUM(CASE WHEN CD_SQ.TYPE_CD = 'OTH' AND CPA_SQ.TYPE_CD = 'C' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS COTH_AMOUNT_NO, 
SUM(CASE WHEN CD_SQ.TYPE_CD = 'TAX1' AND CPA_SQ.TYPE_CD = 'C' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS CTAX1_AMOUNT_NO, 
SUM(CASE WHEN CD_SQ.TYPE_CD = 'TAX2' AND CPA_SQ.TYPE_CD = 'C' THEN CD_SQ.AMOUNT_NO ELSE 0 END) AS CTAX2_AMOUNT_NO
FROM CPI_ACTIVITY CPA_SQ 
JOIN CERTIFICATE_DETAIL CD_SQ ON CD_SQ.CPI_ACTIVITY_ID = CPA_SQ.ID AND CPA_SQ.CPI_QUOTE_ID = CPQ.ID AND CD_SQ.PURGE_DT IS NULL
WHERE CPA_SQ.CPI_QUOTE_ID = CPQ.ID AND CPA_SQ.PURGE_DT IS NULL AND CPA_SQ.CREATE_DT <= '2016-09-11'
) CPISQ

OUTER APPLY(SELECT SUM(AMOUNT_NO) as NET_AMOUNT FROM FINANCIAL_TXN FTX 
WHERE FTX.FPC_ID = FPC.ID AND FTX.PURGE_DT IS NULL
and TXN_DT <= '2016-09-11' and TXN_TYPE_CD != 'P'
) FTX
CROSS APPLY dbo.fn_FilterCollateralByDivisionCd(C.ID, @Division) fn_FCBD

WHERE 1=1
AND L.RECORD_TYPE_CD = 'G' AND RC.RECORD_TYPE_CD = 'G' AND P.RECORD_TYPE_CD = 'G'
--AND L.EXTRACT_UNMATCH_COUNT_NO = 0 and C.EXTRACT_UNMATCH_COUNT_NO = 0
AND FPC.PURGE_DT IS NULL
AND (LND.ID = 67)
AND (L.BRANCH_CODE_TX IN (SELECT STRVALUE FROM @BranchTable) or @Branch = '1' or @Branch = '' or @Branch is NULL)
AND fn_FCBD.loanType IS NOT NULL
AND (RC.TYPE_CD = @Coverage or @Coverage = '1' or @Coverage is NULL)
AND (@FIL_DATERANGE_FILE = 'F' OR (@FIL_DATERANGE_FILE = 'T' AND (FPC.ID IN (SELECT ID FROM #tmpFPCIDs))))
AND (@FIL_DATERANGE = 'F' OR (@FIL_DATERANGE = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_FUNDDT_RANGE = 'F' OR (@FIL_FUNDDT_RANGE = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_DATERANGE_PIR = 'F' OR (@FIL_DATERANGE_PIR = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_DATERANGE_SPECIAL = 'F' OR (@FIL_DATERANGE_SPECIAL = 'T' AND FPC.ID in (select ID from #tmpFPCIDs) 
	AND ISNULL(FPC.HOLD_IN,'N') = 'N' AND FPC.MONTHLY_BILLING_IN = 'N' 
	AND ((FTX.NET_AMOUNT IS NOT NULL AND FTX.NET_AMOUNT > 0) OR (FTX.NET_AMOUNT IS NULL AND ISNULL(CPA_I.TOTAL_PREMIUM_NO,0) - ABS(ISNULL(CPA_C.TOTAL_PREMIUM_NO,0)) > 0))
	))
AND [HOLD_IN] <> 'Y' AND [MONTHLY_BILLING_IN] <> 'Y' 
AND (FTX.NET_AMOUNT > 0 OR (CPA_I.TOTAL_PREMIUM_NO - CPA_C.TOTAL_PREMIUM_NO) > 0)
--AND [CPI_NETPREMIUM_AMOUNT_NO] > 0

------------------------------------------------------------




----If Certs are being Filtered out still, it is because the Net Premium is now Zero.
--To confirm : Pay special attention to FTX.NET_AMOUNT in Where clause

DECLARE	@Division as nvarchar(10)
set @Division = '1'
DECLARE @FIL_DATERANGE AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_PIR AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_SPECIAL AS varchar(1) = 'T'
DECLARE @FIL_FUNDDT_RANGE AS varchar(1) = 'F'
DECLARE @FIL_DATERANGE_FILE AS varchar(1) = 'F'

select FPC.ID,FPC.ISSUE_DT,FTX.NET_AMOUNT,CPA_I.TOTAL_PREMIUM_NO,CPA_C.TOTAL_PREMIUM_NO,FPC.*
from FORCE_PLACED_CERTIFICATE FPC
JOIN LOAN L ON L.ID = FPC.LOAN_ID AND L.PURGE_DT IS NULL 
JOIN LENDER LND ON LND.ID = L.LENDER_ID AND LND.PURGE_DT IS NULL
JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCRCR ON FPCRCR.FPC_ID = FPC.ID AND FPCRCR.PURGE_DT IS NULL
JOIN CARRIER CR ON FPC.CARRIER_ID = CR.ID AND CR.PURGE_DT IS NULL	
JOIN REQUIRED_COVERAGE RC ON FPCRCR.REQUIRED_COVERAGE_ID = RC.ID AND RC.PURGE_DT IS NULL	
JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID AND P.PURGE_DT IS NULL	
JOIN COLLATERAL C ON C.LOAN_ID = L.ID AND C.PROPERTY_ID = P.ID AND C.PURGE_DT IS NULL
LEFT JOIN CPI_QUOTE CPQ ON  CPQ.ID = FPC.CPI_QUOTE_ID AND CPQ.PURGE_DT IS NULL	
LEFT JOIN CPI_ACTIVITY CPA_I on CPA_I.CPI_QUOTE_ID = CPQ.ID AND CPA_I.TYPE_CD = 'I'	AND CPA_I.PURGE_DT IS NULL  AND CPA_I.CREATE_DT <= '2016-09-11'
OUTER APPLY 
(SELECT SUM(TOTAL_PREMIUM_NO) AS TOTAL_PREMIUM_NO, MAX(REASON_CD) AS REASON_CD, MAX(REPORTING_CANCEL_DT) AS REPORTING_CANCEL_DT 
FROM CPI_ACTIVITY C  
WHERE C.CPI_QUOTE_ID = CPQ.ID AND C.TYPE_CD IN ('C', 'R', 'MT') AND C.PURGE_DT IS NULL AND C.CREATE_DT <= '2016-09-11'
) CPA_C
OUTER APPLY(SELECT SUM(AMOUNT_NO) as NET_AMOUNT FROM FINANCIAL_TXN FTX 
WHERE FTX.FPC_ID = FPC.ID AND FTX.PURGE_DT IS NULL
and TXN_DT <= '2016-09-11' and TXN_TYPE_CD != 'P'
) FTX
CROSS APPLY dbo.fn_FilterCollateralByDivisionCd(C.ID, @Division) fn_FCBD
WHERE FPC.NUMBER_TX IN ('SC80480193','SC80480205','SC80473372','SC80480191','SC80480196','SC80480199','SC80480201','SC80480202','SC80473377','SC80480181','SC80480198','SC80480186','SC80480200','SC80480188','SC80480180','SC80473375','SC80480185','SC80480197','SC80480184','SC80480189','SC80480183','SC80480208','SC80480192','SC80473371','SC80467500','SC80480206','SC80480203','SC80480204','SC80480190')
AND L.RECORD_TYPE_CD = 'G' AND RC.RECORD_TYPE_CD = 'G' AND P.RECORD_TYPE_CD = 'G'
AND (LND.ID = 2242)
AND (FTX.NET_AMOUNT > 0 OR (CPA_I.TOTAL_PREMIUM_NO - CPA_C.TOTAL_PREMIUM_NO) > 0)
--AND (L.BRANCH_CODE_TX IN (SELECT STRVALUE FROM @BranchTable) or @Branch = '1' or @Branch = '' or @Branch is NULL)
AND fn_FCBD.loanType IS NOT NULL
AND (@FIL_DATERANGE_FILE = 'F' OR (@FIL_DATERANGE_FILE = 'T' AND (FPC.ID IN (SELECT ID FROM #tmpFPCIDs))))
AND (@FIL_DATERANGE = 'F' OR (@FIL_DATERANGE = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_FUNDDT_RANGE = 'F' OR (@FIL_FUNDDT_RANGE = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_DATERANGE_PIR = 'F' OR (@FIL_DATERANGE_PIR = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)))
AND (@FIL_DATERANGE_SPECIAL = 'F' OR (@FIL_DATERANGE_SPECIAL = 'T' AND FPC.ID in (select ID from #tmpFPCIDs)
	AND ISNULL(FPC.HOLD_IN,'N') = 'N' AND FPC.MONTHLY_BILLING_IN = 'N' 
	--AND ((FTX.NET_AMOUNT IS NOT NULL AND FTX.NET_AMOUNT > 0) OR (FTX.NET_AMOUNT IS NULL AND ISNULL(CPA_I.TOTAL_PREMIUM_NO,0) - ABS(ISNULL(CPA_C.TOTAL_PREMIUM_NO,0)) > 0))
	))
ORDER BY FTX.NET_AMOUNT,FPC.ID
----------------------------------

---FPCs being Excluded
select FPC.NUMBER_TX,FPC.ISSUE_DT,L.NUMBER_TX,P.YEAR_TX,P.MAKE_TX,P.MODEL_TX,P.VIN_TX--,RC.*--FTX.NET_AMOUNT,CPA_I.TOTAL_PREMIUM_NO,CPA_C.TOTAL_PREMIUM_NO,FPC.*
from FORCE_PLACED_CERTIFICATE FPC
JOIN LOAN L ON L.ID = FPC.LOAN_ID AND L.PURGE_DT IS NULL 
JOIN FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCRCR ON FPCRCR.FPC_ID = FPC.ID AND FPCRCR.PURGE_DT IS NULL
JOIN REQUIRED_COVERAGE RC ON FPCRCR.REQUIRED_COVERAGE_ID = RC.ID AND RC.PURGE_DT IS NULL	
JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID AND P.PURGE_DT IS NULL	
WHERE FPC.NUMBER_TX IN ('SC80480193','SC80480205','SC80473372','SC80480191','SC80480196','SC80480199','SC80480201','SC80480202','SC80473377','SC80480181','SC80480198','SC80480186','SC80480200','SC80480188','SC80480180','SC80473375','SC80480185','SC80480197','SC80480184','SC80480189','SC80480183','SC80480208','SC80480192','SC80473371','SC80467500','SC80480206','SC80480203','SC80480204','SC80480190')
AND FPC.ID IN (5576000,5595375,5615477,5615480,5615485,5615486,5615495,5615499,5615503,5615504)
-------------

--Financial Txn Info to Confirm
SELECT *
FROM FINANCIAL_TXN
WHERE FPC_ID IN (5576000,5595375,5615477,5615480,5615485,5615486,5615495,5615499,5615503,5615504)
AND FINANCIAL_TXN.PURGE_DT IS NULL
and TXN_DT <= '2016-09-11' and TXN_TYPE_CD != 'P'
ORDER BY FPC_ID
-------------










