USE Unitrac



SELECT L.RECORD_TYPE_CD, COUNT(*) FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
WHERE C.COLLATERAL_CODE_ID IN (240)
AND (L.PURGE_DT IS NULL
OR C.PURGE_DT IS NULL)
GROUP BY L.RECORD_TYPE_CD

SELECT C.COLLATERAL_CODE_ID, L.* INTO UniTracHDStorage..INC0324297
FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
WHERE C.COLLATERAL_CODE_ID IN (240)
AND (L.PURGE_DT IS NULL
OR C.PURGE_DT IS NULL)


SELECT *
FROM dbo.LOAN L
WHERE L.LENDER_ID = 285
AND L.RECORD_TYPE_CD NOT IN ('E', 'I')

---Finding Collateral Code
SELECT  CC.*
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2900' AND CC.ID = 240



UPDATE LCCG
SET LCCG.PURGE_DT = NULL
--SELECT * 
FROM dbo.LENDER_COLLATERAL_CODE_GROUP LCCG
WHERE ID IN (428)

UPDATE CCR
SET PURGE_DT = NULL
--SELECT * 
FROM dbo.LCCG_COLLATERAL_CODE_RELATE CCR
WHERE ID = 4815




	
	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , L.ID , 'INC0324297' , 'N' , 
 GETDATE() ,  1 , 
'Moved to Default for Merge', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , L.ID , 'PEND' , 'N'
FROM dbo.COLLATERAL L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0324297)


