USE UniTrac


SELECT 
*  INTO jcs..INC0334233
FROM dbo.CPI_ACTIVITY
WHERE TYPE_CD=  'C'
AND REASON_CD ='Re_POSS'

SELECT   
         DAY(I.UPDATE_DT - REPORTING_CANCEL_DT) [Days] ,
         L.NUMBER_TX [Loan Number] ,
         FPC.NUMBER_TX [Cert] ,
         I.TYPE_CD ,
         I.PROCESS_DT ,
         I.TOTAL_PREMIUM_NO ,
         I.START_DT ,
         I.END_DT ,
         I.REASON_CD ,
         I.PAYMENT_EFFECTIVE_DT ,
         I.PAYMENT_CHANGE_AMOUNT_NO ,
         I.PRIOR_PAYMENT_AMOUNT_NO ,
         I.NEW_PAYMENT_AMOUNT_NO ,
         I.REPORTING_CANCEL_DT ,
         I.EXECUTION_STEPS_TX ,
         I.COMMENT_TX ,
         I.EARNED_PAYMENT_AMOUNT_NO ,
         I.SUB_REASON_CD
		 INTO jcs..INC0334233_CPI
FROM     JCs..INC0334233 I
         JOIN dbo.CPI_QUOTE CP ON CP.ID = I.CPI_QUOTE_ID
         JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.CPI_QUOTE_ID = CP.ID
         JOIN dbo.LOAN L ON L.ID = FPC.LOAN_ID
         JOIN dbo.LENDER Le ON Le.ID = L.LENDER_ID
WHERE    DATEPART(DAY, I.UPDATE_DT - REPORTING_CANCEL_DT) <= '10'
         AND Le.CODE_TX = '2257'
         AND I.UPDATE_DT >= '2017-01-01'
         AND I.UPDATE_DT <= '2018-01-01'
ORDER BY DATEPART(DAY, I.UPDATE_DT - REPORTING_CANCEL_DT) ASC


