USE [UniTrac]
GO 

SELECT COUNT(*)
FROM dbo.LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3525')
--151933

SELECT L.* 
--INTO UniTracHDStorage..INC0277872_L
FROM dbo.LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3525') AND L.DIVISION_CODE_TX <> '99'



UPDATE LOAN 
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0277872', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END, 
DIVISION_CODE_TX = '99'
--SELECT DIVISION_CODE_TX, * FROM LOAN
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0277872_L ) AND DIVISION_CODE_TX <> '99'






INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0277872' , 'N' , 
 GETDATE() ,  1 , 
 'Moved loans to Division 99 per ticket INC0277872', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0277872_L ) AND DIVISION_CODE_TX <> '99'