USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT LO.NAME_TX,  L.ID ,
        L.LENDER_ID ,
        L.AGENCY_ID ,
        L.NUMBER_TX ,
        L.TYPE_CD ,
        L.STATUS_CD ,
        L.STATUS_DT ,
        L.BALANCE_AMOUNT_NO ,
        L.BALANCE_LAST_UPDATE_DT ,
        L.RECORD_TYPE_CD ,
        L.SOURCE_CD ,
        L.BALANCE_TYPE_CD ,
        L.DEALER_REPORTED_DT ,
        L.EFFECTIVE_DT ,
        L.MATURITY_DT ,
        L.ORIGINAL_BALANCE_AMOUNT_NO ,
        L.ORIGINAL_PAYMENT_AMOUNT_NO ,
        L.APR_AMOUNT_NO ,
        L.PAYMENT_AMOUNT_NO ,
        L.PAYMENT_FREQUENCY_CD ,
        L.INTEREST_TYPE_CD ,
        L.LAST_PAYMENT_DT ,
        L.NEXT_SCHEDULED_PAYMENT_DT ,
        L.PAYOFF_DT ,
        L.OFFICER_CODE_TX ,
        L.DEALER_CODE_TX ,
        L.BRANCH_CODE_TX ,
        L.DIVISION_CODE_TX ,
        L.DEPARTMENT_CODE_TX ,
        L.SERVICECENTER_CODE_TX ,
        L.CONTRACT_TYPE_CD ,
        L.CREDIT_LINE_AMOUNT_NO ,
        L.FANNIE_MAE_IN ,
        L.EXTRACT_UNMATCH_COUNT_NO ,
        L.NOTE_TX ,
        L.RETAIN_IN ,
        L.RETAIN_UTL_IN ,
        L.ASSOCIATE_IN ,
        L.EXCLUDE_ASSOCIATE_IN ,
        L.CREATE_DT ,
        L.UPDATE_DT ,
        L.UPDATE_USER_TX ,
        L.PURGE_DT ,
        L.LOCK_ID ,
        L.GSE_CD ,
        L.DELINQUENCY_DT ,
        L.DELETED_DT ,
        L.CREDIT_SCORE_CD ,
        L.CURRENT_PAYMENT_INCREASE_AMOUNT_NO ,
        L.STATUS_OFFICER_CODE_TX ,
        L.ESCROW_IN ,
        L.LENDER_BRANCH_CODE_TX ,
        L.EXTRACT_LOAN_UPDATE_ONLY_IN ,
        L.PREDICTIVE_SCORE_NO ,
        L.PREDICTIVE_DECILE_NO FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN LENDER_ORGANIZATION LO ON LL.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID
WHERE LL.CODE_TX IN ('2982') AND L.BRANCH_CODE_TX IN ('01', '01E', '2982', '2982E', '390','390E')
AND CAST(L.UPDATE_DT AS DATE) > CAST(GETDATE()-48 AS DATE)


SELECT * FROM dbo.LENDER
WHERE CODE_TX IN ('4357') 



SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%%'
        AND AGENCY_ID = '1'
        AND ID IN (  )



SELECT DISTINCT LO.TYPE_CD,  Lo.NAME_TX, lo.CODE_TX
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
INNER JOIN dbo.USERS U ON U.UPDATE_USER_TX = LO.UPDATE_USER_TX
WHERE L.CODE_TX = '2982' AND Lo.TYPE_CD = 'BRCH' AND LO.PURGE_DT IS NULL
AND LO.NAME_TX LIKE 'Wintrust%'
ORDER BY LO.CODE_TX ASC


SELECT DISTINCT LO.TYPE_CD, Lo.NAME_TX, lo.CODE_TX, LL.ID LOAN_ID, LL.NUMBER_TX,
LL.CREATE_DT, LL.UPDATE_DT
FROM LENDER L
INNER JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
INNER JOIN dbo.USERS U ON U.UPDATE_USER_TX = LO.UPDATE_USER_TX
WHERE L.CODE_TX = '2982' AND Lo.TYPE_CD = 'BRCH' AND LO.PURGE_DT IS NULL
AND LO.NAME_TX NOT LIKE 'Wintrust%'
AND CAST(L.UPDATE_DT AS DATE) > CAST(GETDATE()-48 AS DATE)
ORDER BY LO.CODE_TX ASC
