USE UniTrac	





SELECT COUNT(*) FROM dbo.WORK_ITEM
WHERE LENDER_ID IN (13,373,227,661,2240,1859)
AND STATUS_CD NOT IN ('Complete', 'Withdrawn')
AND WORKFLOW_DEFINITION_ID = '6'


SELECT * INTO UniTracHDStorage..INC0283333
FROM dbo.WORK_ITEM
WHERE LENDER_ID IN (13,373,227,661,2240,1859)
AND STATUS_CD NOT IN ('Complete', 'Withdrawn')
AND WORKFLOW_DEFINITION_ID = '6' AND PURGE_DT IS NULL




---------- Clear OBC (- rows)
UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete' ,
         LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END,
        UPDATE_DT = GETDATE() ,
        UPDATE_USER_TX = 'INC0283333'
		--SELECT * FROM WORK_ITEM
WHERE   ID IN ( SELECT ID FROM UniTracHDStorage..INC0283333 )
        AND WORKFLOW_DEFINITION_ID = 6
        AND ACTIVE_IN = 'Y'
