USE UniTrac	


SELECT     
concat(SERVER_SHARE_TX,'\',RELATIVE_PATH_TX,'\')  as  [Document]
FROM dbo.DOCUMENT_CONTAINER DC 
JOIN dbo.DOCUMENT_MANAGEMENT DM ON DM.ID = DC.DOCUMENT_MANAGEMENT_ID
WHERE DC.ID = '105962487'



SELECT * FROM dbo.LOAN L 
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX = '3057' AND L.NUMBER_TX = '450093085-69'

SELECT * FROM dbo.ESCROW
WHERE LOAN_ID IN (193996286, 193994768)

SELECT RC.ESCROW_IN, L.ESCROW_IN, l.NUMBER_TX, RC.* FROM dbo.REQUIRED_COVERAGE RC
JOIN dbo.PROPERTY P ON P.ID = RC.PROPERTY_ID
JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
WHERE L.NUMBER_TX IN ('450093085-69','450144317-60')
AND L.LENDER_ID = 1102


UPDATE RC
SET ESCROW_IN = 'N', UPDATE_USER_TX = 'INC0345306', UPDATE_DT = GETDATE(), LOCK_ID =LOCK_ID+1
--SELECT * 
FROM dbo.REQUIRED_COVERAGE RC 
WHERE ID IN (168373776)




INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , L.ID , 'INC0345306' , 'N' , 
 GETDATE() ,  1 , 
'This loan does not have escrow and somehow it was marked as if it caused errors in data', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , L.ID , 'PEND' , 'N'
FROM dbo.REQUIRED_COVERAGE L 
WHERE L.ID IN (168373776)

