USE Unitrac

UPDATE C
SET LEGAL_STATUS_CODE_TX = 'A', C.UPDATE_DT = GETDATE(), C.UPDATE_USER_TX = 'INC0318203' , C.LOCK_ID = CASE WHEN C.LOCK_ID >= 255 THEN 1 ELSE C.LOCK_ID + 1 END
--SELECT C.LEGAL_STATUS_CODE_TX, I.LEGAL_STATUS_CODE_TX, * 
FROM dbo.COLLATERAL C 
JOIN UniTracHDStorage..INC0318203 I ON C.ID = I.ID

	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , L.ID , 'INC0318203' , 'N' , 
 GETDATE() ,  1 , 
'Changed Legal Status to 0', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0318203)



SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = '0'

