USE UniTrac


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '1977'


SELECT dc.RELATE_CLASS_NAME_TX ,  N.SEQUENCE_NO,
dc.DISPLAY_DT ,dc.DISPLAY_DESC_TX , dc.PRINT_STATUS_CD ,
dc.PRINT_STATUS_ASSIGNED_DT , dc.RECIPIENT_TYPE_CD 
FROM dbo.DOCUMENT_CONTAINER dc
JOIN dbo.NOTICE N ON N.id = dc.RELATE_ID AND dc.RELATE_CLASS_NAME_TX = 'Allied.UniTrac.Notice' 
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID AND L.LENDER_ID = '151'
WHERE dc.RECIPIENT_TYPE_CD = 'BORR' AND dc.PRINT_STATUS_CD <> 'VUT' AND dc.PRINT_STATUS_CD = 'PRINTED'
AND Dc.UPDATE_DT >= '2017-01-01'
UNION
SELECT dc.RELATE_CLASS_NAME_TX , NULL ,
dc.DISPLAY_DT ,dc.DISPLAY_DESC_TX , dc.PRINT_STATUS_CD ,
dc.PRINT_STATUS_ASSIGNED_DT , dc.RECIPIENT_TYPE_CD  
FROM dbo.DOCUMENT_CONTAINER dc
JOIN dbo.NOTICE N ON N.id = dc.RELATE_ID AND dc.RELATE_CLASS_NAME_TX ='Allied.UniTrac.ForcePlacedCertificate' AND dc.PRINT_STATUS_CD <> 'VUT'
JOIN dbo.LOAN L ON L.ID = N.LOAN_ID AND L.LENDER_ID = '151'
WHERE dc.RECIPIENT_TYPE_CD = 'BORR' AND dc.PRINT_STATUS_CD <> 'VUT' AND dc.PRINT_STATUS_CD = 'PRINTED'
AND Dc.UPDATE_DT >= '2017-01-01'
ORDER BY dc.DISPLAY_DT ASC 
