USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.*
into untirachdstorage..INC0458558
FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX = '1594' AND L.BRANCH_CODE_TX = 'PROTECTION'
and l.purge_dt is null 

update L set L.BRANCH_CODE_TX = '1594', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0458558' , LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT L.*
FROM LOAN L
join UniTracHDStorage..INC0458558 I on I.ID = L.ID 



INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0458558' , 'N' , 
 GETDATE() ,  1 , 
'Change Loans from Protection Branch to 1594 Branch', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0458558)



---Backout
update L set L.BRANCH_CODE_TX = I.BRANCH_CODE_TX, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0458558' , LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT L.*
FROM LOAN L
join UniTracHDStorage..INC0458558 I on I.ID = L.ID 

