SELECT *
FROM LENDER
WHERE CODE_TX = '2'

SELECT *
FROM LOAN
WHERE LENDER_ID = 2271

SELECT *
FROM LENDER_PAYEE_CODE_FILE
WHERE LENDER_ID = 1833 AND PAYEE_CODE_TX = 101545


sp_who3

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
INNER JOIN ADDRESS ON LENDER_PAYEE_CODE_MATCH.REMITTANCE_ADDR_ID = ADDRESS.ID
WHERE LENDER_PAYEE_CODE_FILE_ID = 11224 --AND LENDER_PAYEE_CODE_MATCH.PURGE_DT IS NULL

--29061

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
INNER JOIN ADDRESS ON LENDER_PAYEE_CODE_MATCH.REMITTANCE_ADDR_ID = ADDRESS.ID
wHERE LENDER_PAYEE_CODE_FILE_ID = 29061 AND LENDER_PAYEE_CODE_MATCH.ID IN (21865)
--21865

SELECT *
FROM LENDER_PAYEE_CODE_MATCH
WHERE LENDER_PAYEE_CODE_FILE_ID = 11224

UPDATE LENDER_PAYEE_CODE_MATCH
SET PURGE_DT = GETDATE(), UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0251017', LOCK_ID = LOCK_ID + 1
--SELECT * FROM dbo.LENDER_PAYEE_CODE_MATCH
WHERE LENDER_PAYEE_CODE_FILE_ID = 29061 AND ID IN (21865)

SELECT *
FROM BORROWER_INSURANCE_COMPANY
--WHERE NAME = 'HARTFORD'
WHERE ID IN (16278,13920)
