USE [UniTrac]
GO 

--DROP TABLE #tmpLoan
--DROP TABLE #tmpCC
--drop table #tmpColl 

CREATE TABLE #tmpLoan (LoanID NVARCHAR(4000), CollID NVARCHAR(4000), [Collateral Notes] NVARCHAR(4000), [Date information added] DATETIME2)
INSERT INTO #tmpLoan
--SELECT  *
SELECT DISTINCT L.ID, ENTITY_ID, PC.NOTE_TX, PC.CREATE_DT
FROM    dbo.PROPERTY_CHANGE PC
        INNER JOIN  dbo.COLLATERAL C ON PC.ENTITY_ID = C.ID
        INNER JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID AND p.ADDRESS_ID IS NOT NULL
        INNER JOIN  dbo.LOAN L ON L.ID = C.LOAN_ID
		INNER JOIN dbo.LENDER LL ON	LL.ID = L.LENDER_ID
WHERE   PC.ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'
        AND PC.NOTE_TX LIKE '%Crosslink%' AND LL.CODE_TX = '6285' --AND L.NUMBER_TX = '3602000858'


SELECT ID INTO #tmpCC FROM dbo.COLLATERAL_CODE
WHERE DESCRIPTION_TX LIKE '%condo%'
AND AGENCY_ID = '1'

SELECT DISTINCT C.ID [CollID], C.PROPERTY_ID[PropID] INTO #tmpColl 
FROM dbo.COLLATERAL C 
JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
join #tmpLoan T ON T.LoanID = L.ID 
WHERE C.PURGE_DT IS NOT NULL AND C.COLLATERAL_CODE_ID IN (SELECT * FROM #tmpCC)
AND PROPERTY_ID = '83834907'

SELECT DISTINCT L.NUMBER_TX ,
        O.LAST_NAME_TX ,
        O.FIRST_NAME_TX ,
        O.MIDDLE_INITIAL_TX ,
        OA.LINE_1_TX ,
        OA.LINE_2_TX ,
        OA.CITY_TX ,
        OA.STATE_PROV_TX ,
        OA.COUNTRY_TX ,
        OA.POSTAL_CODE_TX ,
		T.[Collateral Notes],
		T.[Date information added]--,
       , --c.LOAN_ID 
        c.PROPERTY_ID 
		--INTO JCs..INC0251430
FROM    dbo.OWNER_LOAN_RELATE OLR
        JOIN dbo.OWNER O ON O.ID = OLR.OWNER_ID
        JOIN dbo.OWNER_ADDRESS OA ON OA.ID = O.ADDRESS_ID
        JOIN dbo.LOAN L ON L.ID = OLR.LOAN_ID
        JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
        JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
		JOIN #tmpLoan T ON T.LoanID = L.ID
WHERE   OLR.PURGE_DT IS NULL
        
        AND c.PURGE_DT IS NULL
        AND p.PURGE_DT IS NULL
        AND l.PURGE_DT IS NULL
ORDER BY [Collateral Notes] ASC


SELECT * FROM JCs..INC0251430


SELECT l.NUMBER_TX,C.*
--SELECT DISTINCT L.ID, PC.NOTE_TX, PC.CREATE_DT
FROM    dbo.PROPERTY_CHANGE PC
        INNER JOIN  dbo.COLLATERAL C ON PC.ENTITY_ID = C.ID
        INNER JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID AND p.ADDRESS_ID IS NOT NULL
        left JOIN  dbo.LOAN L ON L.ID = C.LOAN_ID
		INNER JOIN dbo.LENDER LL ON	LL.ID = L.LENDER_ID
		LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE pcu ON pc.id = pcu.CHANGE_ID
WHERE   PC.ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'
        AND --PC.NOTE_TX LIKE '%Crosslink%' AND 
		LL.CODE_TX = '7130' AND c.LOAN_ID = '110979704'
		AND P.ID = '83834907' --AND C.PURGE_DT IS NOT  NULL
		--AND L.NUMBER_TX IN ( '7250003669')



		SELECT * FROM dbo.LOAN L
		JOIN dbo.LENDER ll ON ll.ID = L.LENDER_ID
		WHERE LL.CODE_TX = '7130' AND L.NUMBER_TX IN ( '8705690', '3610000993', '3615000048')


		--Crosslink replaced Collateral: 80 Austin Drive Unit 41 Burlington, VT 05401 with: 80 Austin Drive #73 Burlington, VT 05401 on Loan: 7250003669