use unitrac


SELECT  RC.* into  unitrachdstorage..INC0451564
FROM REQUIRED_COVERAGE RC
INNER JOIN PROPERTY P ON P.ID = RC.PROPERTY_ID AND P.PURGE_DT IS NULL
INNER JOIN COLLATERAL C ON C.PROPERTY_ID = P.ID AND C.PURGE_DT IS NULL
INNER JOIN LOAN L ON L.ID = C.LOAN_ID AND L.PURGE_DT IS NULL
INNER JOIN LENDER LE ON LE.ID = L.LENDER_ID 
WHERE LE.CODE_TX = '3400'
AND L.RECORD_TYPE_CD <> 'D'
AND RC.RECORD_TYPE_CD = 'D'
AND P.RECORD_TYPE_CD <> 'D'




UPDATE dbo.REQUIRED_COVERAGE
SET  UPDATE_DT = GETDATE(),UPDATE_USER_TX = 'INC0451564', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END, RECORD_TYPE_CD = 'G', PURGE_DT = NULL
--SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0451564)








INSERT  INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , RC.ID , 'INC0451564' , 'N' , 
 GETDATE() ,  1 , 
 'Make Loan Active', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , RC.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
WHERE RC.ID IN (SELECT ID FROM UniTracHDStorage..INC0451564)
