USE UniTrac

SELECT fpc.* FROM dbo.LOAN L
JOIN dbo.FORCE_PLACED_CERTIFICATE FPC ON FPC.LOAN_ID = L.ID
WHERE --fpc.PRODUCER_NUMBER_TX = 'AGT0150910'
L.NUMBER_TX= '72394-0143'


UPDATE FPC
SET fpc.PDF_GENERATE_CD = 'PEND', fpc.TEMPLATE_ID = '207', fpc.COVER_LETTER_TEMPLATE_ID=  '53'
--SELECT * 
FROM dbo.FORCE_PLACED_CERTIFICATE fpc
WHERE ID IN (1528060)