USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX [Loan Number],CR.DESCRIPTION_TX[RequiredCoverageInsStatus],CRR.DESCRIPTION_TX[RequiredCoverageInsSubStatus],  
CRS.DESCRIPTION_TX[LoanStatus], CRT.DESCRIPTION_TX [RecordType],  IH.SPECIAL_HANDLING_XML.value('(/SH/MailDate)[1]', 'varchar (50)') [Mail Date]
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
INNER JOIN dbo.REF_CODE CR ON CR.CODE_CD = RC.INSURANCE_STATUS_CD AND CR.DOMAIN_CD = 'RequiredCoverageInsStatus'
INNER JOIN dbo.REF_CODE CRR ON CRR.CODE_CD = RC.INSURANCE_SUB_STATUS_CD AND CRR.DOMAIN_CD = 'RequiredCoverageInsSubStatus'
INNER JOIN dbo.REF_CODE CRS ON CRS.CODE_CD = L.STATUS_CD AND CRS.DOMAIN_CD = 'LoanStatus'
INNER JOIN dbo.REF_CODE CRT ON CRT.CODE_CD = L.RECORD_TYPE_CD AND CRT.DOMAIN_CD = 'RecordType'
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID AND IH.TYPE_CD = 'NOTICE' AND IH.SPECIAL_HANDLING_XML.value('(/SH/MailDate)[1]', 'varchar (50)') <> ''
INNER JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
WHERE LL.CODE_TX IN ('1045') AND RC.ID IN (SELECT DISTINCT ID FROM  UniTracHDStorage..INC0218350 )AND CRR.DESCRIPTION_TX <> 'Borrower Insurance' AND CR.DESCRIPTION_TX <> 'In Force'
ORDER BY [Mail Date] DESC

USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT TOP 1  RC.ID [RC ID], L.ID [LoanID],P.ID,-- OP.EFFECTIVE_DT, 
L.NUMBER_TX,CR.DESCRIPTION_TX,CRR.DESCRIPTION_TX,  
--IH.SPECIAL_HANDLING_XML.value('(/SH/MailDate)[1]', 'varchar (50)') [Mail Date],-- CC.DESCRIPTION_TX, 
C.COLLATERAL_NUMBER_NO
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
--INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
--INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
--INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
INNER JOIN dbo.REF_CODE CR ON CR.CODE_CD = RC.INSURANCE_STATUS_CD AND CR.DOMAIN_CD = 'RequiredCoverageInsStatus'
INNER JOIN dbo.REF_CODE CRR ON CRR.CODE_CD = RC.INSURANCE_SUB_STATUS_CD AND CRR.DOMAIN_CD = 'RequiredCoverageInsSubStatus'
--INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID AND IH.TYPE_CD = 'NOTICE' AND IH.SPECIAL_HANDLING_XML.value('(/SH/MailDate)[1]', 'varchar (50)') <> ''
--INNER JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
WHERE LL.CODE_TX IN ('1045') AND L.NUMBER_TX = '1631935012'
ORDER BY [Mail Date] DESC

SELECT * FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID = '53072788'

SELECT * FROM dbo.LOAN L
INNER JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = C.PROPERTY_ID
WHERE RC.ID IN (SELECT * FROM #tmp)

INSERT INTO
	PROPERTY_CHANGE (
		ENTITY_NAME_TX,
		ENTITY_ID,
		USER_TX,
		ATTACHMENT_IN,
		CREATE_DT,
		AGENCY_ID,
		DESCRIPTION_TX,
		DETAILS_IN,
		FORMATTED_IN,
		LOCK_ID,
		PARENT_NAME_TX,
		PARENT_ID,
		TRANS_STATUS_CD,
		UTL_IN)
SELECT DISTINCT
	'Allied.UniTrac.RequiredCoverage',
	tf.RC_ID,
	'INC0223601',
	'N',
	GETDATE(),
	1,
	'Notice Cycle Cleared',
	'N',
	'Y',
	1,
	'Allied.UniTrac.RequiredCoverage',
	TF.RC_ID,
	'PEND',
	'N'
FROM
	 #TMPLOAN tf
WHERE
	NOTICE_SEQ_NO > 0
	----- 267
			
						
			
UPDATE QT
	SET	QT.CLOSE_REASON_CD = 'NCC',
		QT.CLOSE_DT = GETDATE(),
		QT.UPDATE_DT = GETDATE(),
		QT.UPDATE_USER_TX = 'INC0223601',
		QT.LOCK_ID = (QT.LOCK_ID % 255) + 1
	--SELECT COUNT(*)
	FROM CPI_QUOTE QT
	JOIN #TMPRC RC
		ON RC.CPI_QUOTE_ID = QT.ID
		---- 268
			
			
UPDATE IH
SET	SPECIAL_HANDLING_XML.modify('replace value of (/SH/Status/text())[1] with "Closed" '),
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'INC0223601',
	LOCK_ID = (LOCK_ID % 255) + 1
--SELECT COUNT(*)
FROM INTERACTION_HISTORY IH
JOIN #tmpIH
	ON #tmpIH.IH_ID = IH.ID
	---- 195


-- Update RequiredCoverage Status from Track to Active
UPDATE RC SET RC.SUMMARY_STATUS_CD = 'F',
RC.SUMMARY_SUB_STATUS_CD = 'D', RC.INSURANCE_STATUS_CD = 'F', RC.INSURANCE_SUB_STATUS_CD = 'D', BEGAN_NEW_IN = 'N' , 
GOOD_THRU_DT = NULL , 
CPI_QUOTE_ID = NULL , NOTICE_DT = NULL , NOTICE_TYPE_CD = NULL , 
NOTICE_SEQ_NO = NULL , LAST_EVENT_SEQ_ID = NULL , LAST_EVENT_DT = NULL ,
LAST_SEQ_CONTAINER_ID = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0223601' , 
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT RC.SUMMARY_STATUS_CD , RC.INSURANCE_STATUS_CD , RC.INSURANCE_SUB_STATUS_CD, RC.SUMMARY_SUB_STATUS_CD, RC.BEGAN_NEW_IN , RC.EXPOSURE_DT , RC.TYPE_CD ---,  *
FROM REQUIRED_COVERAGE RC JOIN #TMPLOAN TMP 
ON TMP.RC_ID = RC.ID 
---- 10701

--SELECT DISTINCT LOAN_ID FROM #TMPLOAN

-- Add Property change log
 INSERT INTO PROPERTY_CHANGE
 (
 ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN
 )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , TMP.RC_ID , 'INC0223601' , 'N' ,
 GETDATE(),  1 ,
 'Changed Summary Status from New to Audit' ,
 'N' , 'Y' , 1 ,  'Allied.UniTrac.RequiredCoverage' , TMP.RC_ID , 'PEND' , 'N'
 FROM #TMPLOAN TMP
 ---- 10682


UPDATE EE
SET STATUS_CD = 'CLR',
	UPDATE_DT = GETDATE(),
	UPDATE_USER_TX = 'INC0223601',
	LOCK_ID = (EE.LOCK_ID % 255) + 1
--SELECT ee.*
FROM
	EVALUATION_EVENT EE
	JOIN #TMPLOAN te ON EE.REQUIRED_COVERAGE_ID = te.RC_ID
	WHERE ee.STATUS_CD = 'PEND'
	AND ee.EVENT_SEQUENCE_ID > 0