USE unitrac


SELECT * FROM dbo.LENDER_PAYEE_CODE_FILE LPC
JOIN dbo.LENDER L ON L.ID = LPC.LENDER_ID
WHERE L.CODE_TX = '5115' AND PAYEE_CODE_TX IN (SELECT payeeCode FROM UniTracHDStorage..zipcodes5115)


SELECT * FROM UniTracHDStorage..zipcodes5115

ALTER TABLE UniTracHDStorage..zipcodes5115
ALTER COLUMN payeeCode NVARCHAR(255)




UPDATE A
SET POSTAL_CODE_TX = Z.ZipCode, A.LOCK_ID = A.LOCK_ID+1
--SELECT POSTAL_CODE_TX , Z.ZipCode, * 
FROM dbo.ADDRESS A
JOIN dbo.LENDER_PAYEE_CODE_FILE LPC ON LPC.PAYEE_ADDRESS_ID = A.ID
JOIN UniTracHDStorage..zipcodes5115 Z ON Z.PayeeCode = LPC.PAYEE_CODE_TX
AND LPC.LENDER_ID = '2279'