USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT LCCG_ID, L.*
INTO UniTracHDStorage..INC0279285
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE LCCG ON LCCG.COLLATERAL_CODE_ID = C.COLLATERAL_CODE_ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('1936') AND LCCG_ID IN ('868','867','868')




UPDATE dbo.LOAN
SET DIVISION_CODE_TX = '10', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0279285', LOCK_ID = LOCK_ID +1
--SELECT DIVISION_CODE_TX, * FROM dbo.LOAN
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0279285)


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0279285' , 'N' , 
 GETDATE() ,  1 , 
'Updated to Division 10', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0279285)
