USE [UniTrac]
GO 


SELECT 
WI.CONTENT_XML.value('(/Content/Information/ProcessLogs/ProcessLog/@Id)[1]', 'varchar (50)') ProcessID,
WI.CONTENT_XML.value('(/Content/Information/ProcessLogs/ProcessLog/@Id)[2]', 'varchar (50)') Process_ID,* FROM dbo.WORK_ITEM WI
WHERE WI.ID IN (36590968) 



SELECT RELATE_ID INTO #tmpL FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (41188202,	41188844) AND STATUS_CD = 'COMP'
AND RELATE_TYPE_CD = 'Allied.UniTrac.Loan'

----Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE

SELECT  --C.ID , L.ID,c.UPDATE_DT, c.CREATE_DT,
        --C.COLLATERAL_CODE_ID ,
        P.ID , L.ID [LoanID],
		L.NUMBER_TX [Loan Number] ,
       -- C.UPDATE_DT ,
        RC.STATUS_CD ,
        RC.INSURANCE_STATUS_CD ,
        CC.DESCRIPTION_TX [Collateral Descriptions] ,
        P.LENDER_ID ,
        P.AGENCY_ID ,
        P.DESCRIPTION_TX [Property Descriptions] ,
        P.ACV_NO ,
        P.ACV_DT ,
        P.ACV_VALUATION_REQUIRED_IN ,
        P.ASSET_NUMBER_TX ,
        P.RECORD_TYPE_CD ,
        P.SOURCE_CD ,
        P.YEAR_TX ,
        P.MAKE_TX ,
        P.MODEL_TX ,
        P.BODY_TX ,
        P.VIN_TX ,
        OA.LINE_1_TX ,
        OA.LINE_2_TX ,
        OA.CITY_TX ,
        OA.STATE_PROV_TX ,
        OA.COUNTRY_TX ,
        OA.POSTAL_CODE_TX --INTO UniTracHDStorage..INC0281308_Property_2
--SELECT DISTINCT C.ID, P.ID
--SELECT *
--SELECT  c.UPDATE_DT, L.NUMBER_TX [Loan Number]
--SELECT L.ID INTO #tmpLL

--SELECT TOP 50 RC.UPDATE_USER_TX,RC.Update_DT, RC.TYPE_CD, utl.LOAN_ID,  L.ID, UTL.PROPERTY_ID , P.ID, P.ADDRESS_ID,C.ID[Collateral], *
--SELECT p.ID INTO #tmpP
FROM    LOAN L
        LEFT JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        LEFT JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        LEFT JOIN dbo.UTL_MATCH_RESULT UTL ON UTL.PROPERTY_ID = P.ID
        LEFT JOIN OWNER_ADDRESS OA ON P.ADDRESS_ID = OA.ID
        INNER JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
WHERE   L.ID IN ( SELECT    RELATE_ID    FROM      #tmpL ) AND C.UPDATE_DT >= '2017-01-09 '--AND  L.NUMBER_TX = '4000036189901'
         -- L.NUMBER_TX IN ('4000046799801')--,'4000048904701','4000058947901','4000041407201','4000041296002','120722718','8010080025','120517868','8020341781')
		--AND C.PURGE_DT IS NULL AND P.PURGE_DT IS NULL 
      --  AND UTL.LOAN_ID <> L.ID
	 AND rc.UPDATE_USER_TX = 'UBSGoodThru'
	  AND L.NUMBER_TX IN ('120750269')
	  ORDER BY L.NUMBER_TX ASC 

DROP TABLE UniTracHDStorage..INC0281308_Property_2

SELECT * FROM dbo.LOAN L
LEFT JOIN #tmpL LL ON L.ID = LL.RELATE_ID
LEFT JOIN dbo.UTL_MATCH_RESULT UTL ON UTL.LOAN_ID = L.ID 
WHERE NUMBER_TX IN ('4000046799801','4000048904701','4000058947901','4000041407201','4000041296002','120722718','8010080025','120517868','8020341781')


--Unitrac DB01

USE UniTrac	

UPDATE dbo.PROPERTY
SET  PURGE_DT = NULL  ,UPDATE_USER_TX = 'INC0281308', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END--, RECORD_TYPE_CD = 'G'
--SELECT PURGE_DT, * FROM PROPERTY
WHERE ID IN (
SELECT id from UniTracHDStorage..INC0281308_Property_3)

 (148782713,
148782714)
--WHERE [Loan Number]= '4000036189901')
	
 SELECT * 
 INTO UniTracHDStorage..INC0281308_Property_3
 FROM #tmpP


	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Property' , L.ID , 'INC0281308' , 'N' , 
 GETDATE() ,  1 , 
'Removed Property that doesnt match from UTL', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Property' , L.ID , 'PEND' , 'N'
FROM dbo.PROPERTY L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0281308_Property)



SELECT * FROM UniTracHDStorage..INC0281308_Property
WHERE [Loan Number]= '4000036189901'



UPDATE dbo.PROPERTY
SET  PURGE_DT = NULL,--UPDATE_USER_TX = 'INC0281308', 
LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END--, RECORD_TYPE_CD = 'G'
--SELECT * FROM PROPERTY
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0281308_Property_2)
--WHERE [Loan Number]= '4000036189901')