USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.* 
INTO UniTracHDStorage..INC0272262_2
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('1836') AND CAST(RC.EXPOSURE_DT AS DATE) <= CAST(GETDATE()-90 AS DATE) 
AND RC.TYPE_CD = 'HAZARD'


--4.	Update the Required Coverage table 
UPDATE REQUIRED_COVERAGE 
 SET GOOD_THRU_DT = NULL , 
INSURANCE_STATUS_CD = 'A' , 
INSURANCE_SUB_STATUS_CD = '' , 
SUMMARY_STATUS_CD = 'A' , 
SUMMARY_SUB_STATUS_CD = '' , 
NOTICE_DT = NULL , 
NOTICE_SEQ_NO = NULL , 
NOTICE_TYPE_CD = NULL , 
LAST_EVENT_DT = NULL , 
LAST_EVENT_SEQ_ID = NULL , 
LAST_SEQ_CONTAINER_ID = NULL ,
UPDATE_DT = GETDATE() , 
UPDATE_USER_TX =  'INC0272262' , 
LOCK_ID = LOCK_ID % 255 + 1
---- SELECT EXPOSURE_DT,* FROM REQUIRED_COVERAGE 
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0272262_2)

INSERT  INTO PROPERTY_CHANGE
        ( ENTITY_NAME_TX ,
          ENTITY_ID ,
          USER_TX ,
          ATTACHMENT_IN ,
          CREATE_DT ,
          AGENCY_ID ,
          DESCRIPTION_TX ,
          DETAILS_IN ,
          FORMATTED_IN ,
          LOCK_ID ,
          PARENT_NAME_TX ,
          PARENT_ID ,
          TRANS_STATUS_CD ,
          UTL_IN
        )
        SELECT DISTINCT
                'Allied.UniTrac.RequiredCoverage' ,
                ID ,
                ' INC0272262' ,
                'N' ,
                GETDATE() ,
                1 ,
                'Changed Summary status to audit' ,
                'N' ,
                'Y' ,
                1 ,
                'Allied.UniTrac.RequiredCoverage' ,
                ID ,
                'PEND' ,
                'N'
        FROM    dbo.REQUIRED_COVERAGE
        WHERE   ID IN ( SELECT  ID
                        FROM    UniTracHDStorage..INC0272262_2)



UPDATE RC
SET  RC.GOOD_THRU_DT = I.GOOD_THRU_DT , 
RC.INSURANCE_STATUS_CD = I.INSURANCE_STATUS_CD , 
RC.INSURANCE_SUB_STATUS_CD = I.INSURANCE_SUB_STATUS_CD , 
RC.SUMMARY_STATUS_CD = I.SUMMARY_STATUS_CD , 
RC.SUMMARY_SUB_STATUS_CD = I.SUMMARY_SUB_STATUS_CD, 
RC.NOTICE_DT = I.NOTICE_DT , 
RC.NOTICE_SEQ_NO = I.NOTICE_SEQ_NO , 
RC.NOTICE_TYPE_CD = I.NOTICE_TYPE_CD , 
RC.LAST_EVENT_DT = I.LAST_EVENT_DT , 
RC.LAST_EVENT_SEQ_ID = I.LAST_EVENT_SEQ_ID , 
RC.LAST_SEQ_CONTAINER_ID = I.LAST_SEQ_CONTAINER_ID ,
UPDATE_DT = GETDATE() , 
RC.UPDATE_USER_TX =  I.UPDATE_USER_TX , 
RC.LOCK_ID = I.LOCK_ID
--SELECT *
FROM dbo.REQUIRED_COVERAGE RC
JOIN  UniTracHDStorage..INC0272262 I ON RC.ID = I.ID
