SELECT L.NUMBER_TX INTO #tmp2 FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN jcs..testsubjectA A ON A.LoanNumber_TX = L.NUMBER_TX
WHERE LL.CODE_TX IN ('4171')  AND BRANCH_CODE_TX = '4171'
--35255240


SELECT  BRANCH_CODE_TX, DIVISION_CODE_TX, a.* FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN jcs..testsubjectB A ON A.LoanNumber_TX = L.NUMBER_TX
WHERE LL.CODE_TX IN ('4171')  AND NUMBER_TX LIKE '%-%'

--35255240 




SELECT * FROM #tmp

SELECT * FROM #tmp2


CREATE TABLE #tmpLoanUpdate (Old NVARCHAR(1000), New NVARCHAR(1000))
INSERT INTO #tmpLoanUpdate
SELECT NUMBER_TX, 'Old' FROM #tmp
UNION SELECT NUMBER_TX, 'New' FROM #tmp2 



SELECT * FROM #tmpLoanUpdate
