SELECT * FROM dbo.WORK_ITEM
WHERE ID = '35916577'

SELECT RELATE_ID INTO #tmpN FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '40346515'
AND RELATE_TYPE_CD LIKE '%notice'


SELECT PDF_GENERATE_CD, * FROM dbo.NOTICE
WHERE ID IN (SELECT * FROM  #tmpN) AND PDF_GENERATE_CD <> 'COMP'
AND NAME_TX = 'Agent Notification'


SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'NT'


UPDATE dbo.NOTICE
SET TEMPLATE_ID = '135', PDF_GENERATE_CD = 'PEND', UPDATE_DT = GETDATE(), 
UPDATE_USER_TX = 'INC0276840', LOCK_ID = LOCK_ID+1
--SELECT * FROM dbo.NOTICE
WHERE ID = '20531825'