USE UniTrac

SELECT * FROM dbo.LENDER
WHERE CODE_TX = '1977'

SELECT
SPECIAL_HANDLING_XML.value('(/SH/Source)[1]', 'varchar (50)'),
 * FROM dbo.INTERACTION_HISTORY IH
 JOIN dbo.PROPERTY P ON P.ID = IH.PROPERTY_ID AND P.LENDER_ID = 151
WHERE TYPE_CD ='OWNERPOLICY' AND 
CREATE_DT >= '2017-01-01'
AND CREATE_USER_TX = 'mdewyse' AND SPECIAL_HANDLING_XML.value('(/SH/Source)[1]', 'varchar (50)') = 'QuickPoint'