USE [UniTrac]
GO 

--DROP TABLE JCS..INC0293947
--DROP TABLE #tmp

SELECT DISTINCT CC.ID INTO #tmp        
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID AND CCR.PURGE_DT IS NULL
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID AND LCCG.PURGE_DT IS NULL
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2244'
 AND CC.CODE_TX LIKE '%-A'
        OR CC.CODE_TX LIKE '%-OT'

		SELECT * FROM UniTracHDStorage..Lender2244
--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT L.NUMBER_TX [Loan Number] ,
        CC.CODE_TX 
INTO    UniTracHDStorage..INC0293947_results
FROM    LOAN L
JOIN UniTracHDStorage..Lender2244 S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 250
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                      AND RC2.DOMAIN_CD = 'RecordType'
        LEFT JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                      AND RC3.DOMAIN_CD = 'LoanStatus'
        LEFT JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                      AND RC4.DOMAIN_CD = 'LoanType'
        LEFT JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
WHERE 
        AND C.COLLATERAL_CODE_ID IN (SELECT * FROM #tmp)
/*

SELECT * FROM JCS..INC0293947

---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'

SELECT  DISTINCT CC.ID   
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2725'
 AND CC.CODE_TX LIKE '%-A'
        OR CC.CODE_TX LIKE '%-OT'
		*/


SELECT LENDER_ID, CC.*     
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2244' AND CC.CODE_TX = 'BOAT'
 AND CC.CODE_TX LIKE '%-A'
        OR CC.CODE_TX LIKE '%-OT'




SELECT DISTINCT CC1.ID [Old Collateral_ID], CC2.ID [New Collateral_ID], L.ID [LoanID],  G.* 
INTO #tmpG
FROM UniTracHDStorage..[Grow2244] G
JOIN dbo.COLLATERAL_CODE CC1 ON CC1.CODE_TX = G.[Collateral Code]
JOIN dbo.COLLATERAL_CODE CC2 ON CC2.CODE_TX = G.CHANGE
JOIN dbo.LOAN L ON L.NUMBER_TX = G.[Loan Number] AND L.LENDER_ID = 250

SELECT  DISTINCT
        [New Collateral_ID] ,
        LoanID FROM #tmpG
ORDER BY LoanID ASC 


UPDATE C
SET COLLATERAL_CODE_ID = G.[New Collateral_ID]
--SELECT COLLATERAL_CODE_ID, G.[New Collateral_ID], * 
FROM dbo.COLLATERAL C 
JOIN #tmpG G ON G.LoanID = C.LOAN_ID

SELECT DISTINCT CC.ID, CC.CODE_TX, CC.DESCRIPTION_TX, F.* FROM UniTracHDStorage..[2244Finale] F
JOIN dbo.COLLATERAL_CODE CC ON CC.DESCRIPTION_TX = F.[Change Coll Code]


SELECT * FROM UniTracHDStorage..[2244Finale] F

SELECT * FROM dbo.COLLATERAL_CODE
WHERE CODE_TX IN ('JET SKI','MOTORCYCLE','Vehicle','RV')
AND AGENCY_ID = '1' AND CONTRACT_TYPE_CD = '3'
ORDER BY CODE_TX ASC 

SELECT 'JET SKI', '16'
 'MOTORCYCLE', '7'
'Vehicle', '525' 'RV', '10'


UPDATE F
SET [collateral id] = '10'
--SELECT * 
FROM  UniTracHDStorage..[2244Finale] F
WHERE [Change Coll Code] = 'RV'


SELECT  L.NUMBER_TX [Loan Number] ,
        CC.CODE_TX, C.* 
FROM    LOAN L
JOIN UniTracHDStorage..[2244Finale] S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 250
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
--		LEFT JOIN dbo.COLLATERAL_CODE CCC ON CC.CODE_TX = S.[Change Collateral Code]
		WHERE L.NUMBER_TX = '118039-80'

SELECT * FROM dbo.COLLATERAL_CODE
WHERE id = 542

sp_help collateral_code


UPDATE C
SET C.COLLATERAL_CODE_ID = S.[Collateral ID]
--SELECT C.COLLATERAL_CODE_ID , S.[Collateral ID], * 
FROM    LOAN L
JOIN UniTracHDStorage..[2244Finale] S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 250
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
			WHERE L.NUMBER_TX = '118039-80'


			SELECT DISTINCT C.ID INTO UniTracHDStorage..zzzzzzzzzzzzzzzzzzz
FROM    LOAN L
JOIN UniTracHDStorage..[2244Finale] S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 250
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID


		UPDATE C
		SET C.PURPOSE_CODE_TX =  F.PURPOSE_CODE_TX
		--SELECT C.PURPOSE_CODE_TX ,  F.PURPOSE_CODE_TX, * 
		FROM dbo.COLLATERAL C 
		JOIN UniTracHDStorage..INC0293947_CollateralFix F ON C.ID = F.ID