USE UniTrac


Select 
	   ISNULL(RC_DIVISION.DESCRIPTION_TX,RC_SC.DESCRIPTION_TX) AS LOAN_TYPE_TX,
	   RC.TYPE_CD as REQUIREDCOVERAGE_CODE_TX,
	   RC_COVERAGETYPE.MEANING_TX as REQUIREDCOVERAGE_TYPE_TX,
--LOAN
	   L.NUMBER_TX AS LOAN_NUMBER_TX, 
       L.EFFECTIVE_DT AS LOAN_EFFECTIVE_DT, 
       L.MATURITY_DT AS LOAN_MATURITY_DT, 
       C.LOAN_BALANCE_NO AS LOAN_BALANCE_NO, 
	   (CASE when ISNULL(L.OFFICER_CODE_TX,'') = '' then 'No Loan Officer' else L.OFFICER_CODE_TX END) as [LOAN_OFFICERCODE_TX],
	   L.CREDIT_SCORE_CD as [LOAN_CREDITSCORECODE_TX],
--LENDER
	   LND.CODE_TX AS LENDER_CODE_TX, 
	   LND.NAME_TX AS LENDER_NAME_TX,
--COLLATERAL
	   C.COLLATERAL_NUMBER_NO AS COLLATERAL_NUMBER_NO,
	   CC.CODE_TX as COLLATERAL_CODE_TX,
	   C.LENDER_COLLATERAL_CODE_TX AS LENDER_COLLATERAL_CODE_TX, 
	   C.LEGAL_STATUS_CODE_TX AS LEGAL_STATUS_CODE_TX,		
	   C.PURPOSE_CODE_TX AS PURPOSE_CODE_TX,
--OWNER
       O.LAST_NAME_TX AS OWNER_LASTNAME_TX, 
       O.FIRST_NAME_TX AS OWNER_FIRSTNAME_TX, 
       O.MIDDLE_INITIAL_TX AS OWNER_MIDDLEINITIAL_TX,
       AO.LINE_1_TX as OWNER_LINE1_TX,
       AO.LINE_2_TX as OWNER_LINE2_TX,
       AO.STATE_PROV_TX as OWNER_STATE_TX,
       AO.CITY_TX as OWNER_CITY_TX,
       AO.POSTAL_CODE_TX as OWNER_ZIP_TX,
--PROPERTY
       P.YEAR_TX AS COLLATERAL_YEAR_TX, 
       P.MAKE_TX AS COLLATERAL_MAKE_TX, 
       P.MODEL_TX AS COLLATERAL_MODEL_TX, 
       P.VIN_TX AS COLLATERAL_VIN_TX, 
       P.DESCRIPTION_TX AS COLLATERAL_EQUIP_TX, 
       AM.LINE_1_TX as COLLATERAL_LINE1_TX,
       AM.LINE_2_TX as COLLATERAL_LINE2_TX,
       AM.STATE_PROV_TX as COLLATERAL_STATE_TX,
       AM.CITY_TX as COLLATERAL_CITY_TX,
       AM.POSTAL_CODE_TX as COLLATERAL_ZIP_TX,
	   RCA_PROP.VALUE_TX AS [PROPERTY_TYPE_CD],
--COVERAGE
	   CASE 
		 WHEN RC.NOTICE_DT is not null and RC.NOTICE_SEQ_NO > 0 
				THEN cast(RC.NOTICE_SEQ_NO as char(1)) +  ' ' + NRef.MEANING_TX + ' ' + CONVERT(nvarchar(10), RC.NOTICE_DT, 101) 
	   ELSE CASE 
		WHEN L.STATUS_CD in ('N','O','P') THEN LSRef.MEANING_TX
		WHEN C.STATUS_CD in ('R','S','X') THEN CSRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and C.STATUS_CD = 'Z' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + CSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and C.STATUS_CD = 'Z' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + CSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and C.STATUS_CD = 'Z' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and C.STATUS_CD = 'Z' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and C.STATUS_CD = 'Z' and RC.STATUS_CD not in ('A','D','T')
				THEN LSRef.MEANING_TX + ' ' + CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX
		WHEN C.STATUS_CD = 'Z' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN CSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN C.STATUS_CD = 'Z' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN CSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN C.STATUS_CD = 'Z' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN C.STATUS_CD = 'Z' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN C.STATUS_CD = 'Z' and RC.STATUS_CD not in ('A','D','T')
				THEN CSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX
		WHEN L.STATUS_CD = 'A' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'A' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'A' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN RCSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'A' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN RCSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'A' and RC.STATUS_CD not in ('A','D','T')
				THEN RCSRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and RC.STATUS_CD in ('A','D') and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and RC.STATUS_CD = 'T' and RC.SUMMARY_STATUS_CD not in ('A','N') 
				THEN LSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX + ' ' + RCISSRef.MEANING_TX + ' ' + RCISRef.MEANING_TX
		WHEN L.STATUS_CD = 'B' and RC.STATUS_CD not in ('A','D','T')
				THEN LSRef.MEANING_TX + ' ' + RCSRef.MEANING_TX
	   END
	   END as COVERAGE_STATUS_TX,
--CPI
       CR.NAME_TX as INSCOMPANY_NAME_TX,
       FPC.NUMBER_TX as INSCOMPANY_POLICY_NO,
       FPC.EFFECTIVE_DT as INSCOMPANY_EFF_DT,
       CONVERT(nvarchar(8), FPC.EFFECTIVE_DT, 112) as INSCOMPANY_EFFDTSORT_TX,
       FPC.EXPIRATION_DT as INSCOMPANY_EXP_DT,
       FPC.CANCELLATION_DT as INSCOMPANY_CAN_DT,
       isnull(FPC.CANCELLATION_DT,FPC.EXPIRATION_DT) as INSCOMPANY_EXPCXL_DT,
       FPC.ISSUE_DT as INSCOMPANY_ISSUE_DT,
       CPQ.TERM_NO as CPI_QUOTE_TERM_NO,
--IDs, STATUS
       L.ID as LOAN_ID,
       C.ID as COLLATERAL_ID,
       P.ID as PROPERTY_ID,
       RC.ID as REQUIREDCOVERAGE_ID,
       L.STATUS_CD as LOAN_STATUSCODE,
       LSRef.MEANING_TX as LOAN_STATUSMEANING_TX,
       C.STATUS_CD as COLLATERAL_STATUSCODE,
       CSRef.MEANING_TX as COLLATERAL_STATUSMEANING_TX,
       RC.STATUS_CD as REQUIREDCOVERAGE_STATUSCODE,
       RCSRef.MEANING_TX as REQUIREDCOVERAGE_STATUSMEANING_TX,
       RC.SUB_STATUS_CD as REQUIREDCOVERAGE_SUBSTATUSCODE,
       RC.SUMMARY_STATUS_CD as REQUIREDCOVERAGE_INSSTATUSCODE,
       RCISRef.MEANING_TX as REQUIREDCOVERAGE_INSSTATUSMEANING_TX,
       RC.SUMMARY_SUB_STATUS_CD as REQUIREDCOVERAGE_INSSUBSTATUSCODE,
       RCISSRef.MEANING_TX as REQUIREDCOVERAGE_INSSUBSTATUSMEANING_TX,
	   dbo.fn_GetPropertyDescriptionForReports(C.ID) PROPERTY_DESCRIPTION,
	   IsNull(CPA_I.REASON_CD, '') AS [ISS_REASON_TX],
      CASE WHEN O.FIRST_NAME_TX IS NULL 
		THEN O.LAST_NAME_TX 
		ELSE RTRIM(O.LAST_NAME_TX + ', ' + ISNULL(O.FIRST_NAME_TX,'') + ' ' + ISNULL(O.MIDDLE_INITIAL_TX,'')) END AS [OWNER_NAME],
      LND.NAME_TX AS	[LOAN_LENDERNAME_TX],
	CASE 
		WHEN DATEDIFF(dd,GETDATE(),FPC.EXPIRATION_DT) <= 30 THEN ' 0-30 Days'
		WHEN DATEDIFF(dd,GETDATE(),FPC.EXPIRATION_DT) <= 60 THEN '31-60 Days'
		WHEN DATEDIFF(dd,GETDATE(),FPC.EXPIRATION_DT) <= 90 THEN '61-90 Days'
		WHEN DATEDIFF(dd,GETDATE(),FPC.EXPIRATION_DT) <= 120 THEN '91-120 Days'
		ELSE 'Over 120 Days'
	END AS [INS_EXP_DT_RANGE],
	CASE
		WHEN DATEDIFF(dd,FPC.EFFECTIVE_DT,GETDATE()) <= 30 THEN ' 0-30 Days'
		WHEN DATEDIFF(dd,FPC.EFFECTIVE_DT,GETDATE()) <= 60 THEN '31- 60 Days'
		WHEN DATEDIFF(dd,FPC.EFFECTIVE_DT,GETDATE()) <= 90 THEN '61-90 Days'
		WHEN DATEDIFF(dd,FPC.EFFECTIVE_DT,GETDATE()) <= 120 THEN '91-120 Days'
		ELSE 'Over 120 Days'
	END AS [INS_ISS_DT_RANGE],
	0 AS [PRIOR_CPI_CNT_NO],
	FPC.LOAN_ID AS [FPC_LOAN_ID],
	RC.NOTICE_DT AS [INS_PRINT_DT],
	CASE WHEN SUBSTRING(OL.OWNER_TYPE_CD,1,1) = 'C' THEN 'C' ELSE '' END AS [OWNER_COSIGN_TX],
	FPC.AUTH_REQ_DT	AS [CPI_BILL_DT], 
	0 AS [CPI_PREM_DUE_NO],
	0 AS [CPI_DUE_DAYS_NO],
	RC.START_DT AS [CPI_WNP_DT],
	RC.START_DT AS [WV_START_DT],
	ISNULL(CPQ.BASIS_NO,0) AS [CPI_QUOTE_BASIS_NO],
	CASE WHEN FPC.CANCELLATION_DT IS NULL THEN 'I' ELSE 'C' END as [CPI_POL_CD],
	FPC.HOLD_IN as [CPI_HOLD_IN],
	CASE WHEN (SELECT SUM(AMOUNT_NO) FROM FINANCIAL_TXN WHERE FINANCIAL_TXN.FPC_ID = FPC.ID) = 0 THEN '0' ELSE '1' END AS [CPI_MAX_BILL_DATE_IN],
	ISNULL(CPA_I.TOTAL_PREMIUM_NO,0) - abs(ISNULL(CPA_C.TOTAL_PREMIUM_NO,0)) AS [CPI_NET_CHARGES]
	, L.UPDATE_DT [Loan Update] INTO jcs..INC0323887
FROM PROPERTY P 
Join COLLATERAL C on C.PROPERTY_ID = P.ID AND C.PURGE_DT IS NULL
Join LOAN L on L.ID = C.LOAN_ID and L.LENDER_ID = P.LENDER_ID AND L.PURGE_DT IS NULL
Join LENDER LND on LND.ID = L.LENDER_ID AND LND.PURGE_DT IS NULL
Join OWNER_LOAN_RELATE OL on OL.LOAN_ID = L.ID and OL.PRIMARY_IN = 'Y' AND OL.PURGE_DT IS NULL
Join [OWNER] O on O.ID = OL.OWNER_ID AND O.PURGE_DT IS NULL
left Join [OWNER_ADDRESS] AO on AO.ID = O.ADDRESS_ID AND AO.PURGE_DT IS NULL 
left Join [OWNER_ADDRESS] AM on AM.ID = P.ADDRESS_ID AND AM.PURGE_DT IS NULL
left Join REQUIRED_COVERAGE RC on RC.PROPERTY_ID = P.ID AND RC.PURGE_DT IS NULL
LEFT JOIN COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID AND CC.PURGE_DT IS NULL
left join FORCE_PLACED_CERT_REQUIRED_COVERAGE_RELATE FPCR on FPCR.REQUIRED_COVERAGE_ID = RC.ID AND FPCR.PURGE_DT IS NULL
left Join FORCE_PLACED_CERTIFICATE FPC on FPC.ID = FPCR.FPC_ID and FPC.ACTIVE_IN = 'Y' and (FPC.LOAN_ID = L.ID or FPC.LOAN_ID is null) AND FPC.PURGE_DT IS NULL
left Join CARRIER CR on CR.ID = FPC.CARRIER_ID AND CR.PURGE_DT IS NULL
left Join CPI_QUOTE CPQ ON CPQ.ID = FPC.CPI_QUOTE_ID AND CPQ.PURGE_DT IS NULL
LEFT JOIN CPI_ACTIVITY CPA_I ON CPA_I.CPI_QUOTE_ID = CPQ.ID AND CPA_I.TYPE_CD = 'I'	and CPA_I.PURGE_DT IS NULL
LEFT JOIN CPI_ACTIVITY CPA_C ON CPA_C.CPI_QUOTE_ID = CPQ.ID AND CPA_C.TYPE_CD = 'C'	and CPA_C.PURGE_DT IS NULL
LEFT JOIN PROCESS_LOG_ITEM PLI ON PLI.RELATE_ID = FPC.ID and PLI.RELATE_TYPE_CD like '%ForcePlacedCertificate%' AND PLI.PURGE_DT IS NULL
LEFT JOIN EVALUATION_EVENT EE ON EE.ID = PLI.EVALUATION_EVENT_ID AND EE.PURGE_DT IS NULL
LEFT JOIN DOCUMENT_CONTAINER DC ON DC.RELATE_ID = FPC.ID AND RELATE_CLASS_NAME_TX = 'Allied.UniTrac.ForcePlacedCertificate' and RECIPIENT_TYPE_CD = 'BORR' AND DC.ACTIVE_IN = 'Y' AND DC.PURGE_DT IS NULL
left Join REF_CODE NRef on NRef.DOMAIN_CD = 'NoticeType' and NRef.CODE_CD = RC.NOTICE_TYPE_CD 
left Join REF_CODE LSRef on LSRef.DOMAIN_CD = 'LoanStatus' and LSRef.CODE_CD = L.STATUS_CD 
left Join REF_CODE CSRef on CSRef.DOMAIN_CD = 'CollateralStatus' and CSRef.CODE_CD = C.STATUS_CD 
left Join REF_CODE RCSRef on RCSRef.DOMAIN_CD = 'RequiredCoverageStatus' and RCSRef.CODE_CD = RC.STATUS_CD 
left Join REF_CODE RCISRef on RCISRef.DOMAIN_CD = 'RequiredCoverageInsStatus' and RCISRef.CODE_CD = RC.SUMMARY_STATUS_CD 
left Join REF_CODE RCISSRef on RCISSRef.DOMAIN_CD = 'RequiredCoverageInsSubStatus' and RCISSRef.CODE_CD = RC.SUMMARY_SUB_STATUS_CD 
left Join REF_CODE RC_DIVISION on RC_DIVISION.DOMAIN_CD = 'ContractType' and RC_DIVISION.CODE_CD = L.DIVISION_CODE_TX
left Join REF_CODE RC_COVERAGETYPE on RC_COVERAGETYPE.DOMAIN_CD = 'Coverage' and RC_COVERAGETYPE.CODE_CD = RC.TYPE_CD 
left Join REF_CODE RC_SC on RC_SC.DOMAIN_CD = 'SecondaryClassification' AND CC.SECONDARY_CLASS_CD = RC_SC.CODE_CD
left Join REF_CODE_ATTRIBUTE RCA_PROP on RC_SC.DOMAIN_CD = RCA_PROP.DOMAIN_CD and RC_SC.CODE_CD = RCA_PROP.REF_CD and RCA_PROP.ATTRIBUTE_CD = 'PropertyType'
WHERE 
LND.CODE_TX = '2018'
AND L.UPDATE_DT >= '2014-11-01'
ORDER BY L.UPDATE_DT ASC 