USE UniTrac


---- DROP TABLE #TMPRC
SELECT  TOP 1
 LOAN.NUMBER_TX ,
        LOAN.DIVISION_CODE_TX ,
        LOAN.BRANCH_CODE_TX ,
        RC.REQUIRED_AMOUNT_NO ,
        RC.TYPE_CD ,
        PR.REPLACEMENT_COST_VALUE_NO ,
        LOAN.BALANCE_AMOUNT_NO ,
        LOAN.ID AS LOAN_ID ,
        COLL.ID AS COLL_ID ,
        COLL.PROPERTY_ID AS PR_ID ,
        RC.ID AS RC_ID ,
        PC.BASE_AMOUNT_NO, pc.TYPE_CD [PC_Type], PC.ID [PC_ID]
INTO    #TMPRC
FROM    LOAN
        JOIN COLLATERAL COLL ON COLL.LOAN_ID = LOAN.ID
                                AND COLL.PURGE_DT IS NULL
                                AND LOAN.PURGE_DT IS NULL
        JOIN REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = COLL.PROPERTY_ID
                                     AND RC.PURGE_DT IS NULL and RC.Type_cd = 'HAZARD'
        JOIN PROPERTY PR ON PR.ID = COLL.PROPERTY_ID
                            AND PR.PURGE_DT IS NULL
        INNER JOIN COLLATERAL_CODE ON Coll.COLLATERAL_CODE_ID = COLLATERAL_CODE.ID
        INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = PR.ID
        INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
        INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE   LOAN.LENDER_ID = 2260
        AND ( REPLACEMENT_COST_VALUE_NO IS  NULL
              OR REPLACEMENT_COST_VALUE_NO = 0
            )
        AND COLLATERAL_CODE.SECONDARY_CLASS_CD <> 'COND'
----14110
SELECT * FROM #TMPRC


--DROP TABLE #TMPPLCY
SELECT * 
INTO #TMPPLCY
FROM #TMPRC RC
CROSS APPLY ( SELECT * FROM dbo.GetCurrentCoverage(rc.PR_ID , rc.rc_id , rc.type_cd)
) as Plcy

SELECT * FROM #TMPRC

---- DROP TABLE #TMPPLCY
SELECT  Plcy.ID ,
(select 
	#TMPRC.RC_ID as RC_ID,
	OP.ID as OP_ID,
	#TMPRC.Type_cd as COVERAGE,
	(
		select policy_coverage.ID
		from policy_coverage
		inner join ( select top 1 PC.ID, PC.end_dt from 
                                 FROM   policy_coverage AS pc
								 JOIN dbo.OWNER_POLICY op ON op.ID = pc.OWNER_POLICY_ID
								 JOIN #TMPRC T ON T.PC_ID = PC.ID where pc.owner_policy_id = OP.ID and PC.sub_Type_cd = 'CADW' and PC.Type_cd = #TMPRC.TYPE_CD order by PC.end_dt desc ) as pcmax on pcmax.id = policy_coverage.id
		where
		policy_coverage.owner_policy_id = OP.ID
	) as PC_ID

--INTO    #TMPPLCY
FROM    #TMPRC RC
        CROSS APPLY ( SELECT    *
                      FROM      dbo.GetCurrentCoverage(rc.PR_ID, rc.rc_id,
                                                       rc.type_cd)
                    ) AS Plcy
  INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE   ( REPLACEMENT_COST_VALUE_NO IS  NULL
          OR REPLACEMENT_COST_VALUE_NO = 0
        )
----7437







UPDATE PR SET REPLACEMENT_COST_VALUE_NO = PC.BASE_AMOUNT_NO , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0228273' , 
LOCK_ID = PR.LOCK_ID % 255 + 1
----- SELECT TMP.BALANCE_AMOUNT_NO , PC.BASE_AMOUNT_NO
FROM PROPERTY PR 
JOIN #TMPPLCY TMP ON TMP.PROPERTY_ID = PR.ID 
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = PR.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE NUMBER_TX = '140322133'
---- 2498


 INSERT INTO PROPERTY_CHANGE
 (
 ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN
 )
 SELECT DISTINCT  'Allied.UniTrac.Property' , TMP.PROPERTY_ID , 'INC0228273' , 'N' , 
 GETDATE() ,  1 , 
 'Changed RCV from ' + convert(varchar(20), ISNULL(REPLACEMENT_COST_VALUE_NO,0))  + ' to ' + 
 ISNULL(convert(varchar(20), CAST(BALANCE_AMOUNT_NO AS DECIMAL(18,2))), 'NULL') , 
 'N' , 'Y' , 1 ,  'Allied.UniTrac.Property' , TMP.PROPERTY_ID , 'PEND' , 'N'
 FROM #TMPPLCY TMP 
 WHERE NUMBER_TX = '140322133'
 ---- 2475
 
 --SELECT DISTINCT PROPERTY_ID FROM #TMPPC_01
 ---- 2475
 
 
UPDATE RC SET GOOD_THRU_DT = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0228273' ,
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT COUNT(*)
FROM REQUIRED_COVERAGE RC JOIN #TMPPLCY TMP ON 
TMP.PROPERTY_ID = RC.PROPERTY_ID 
WHERE NUMBER_TX = '140322133'
---- 4996



SELECT RC.INSURANCE_SUB_STATUS_CD,* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.LENDER_PRODUCT LP ON LP.ID = RC.LENDER_PRODUCT_ID
WHERE LL.CODE_TX IN ('7350') AND L.NUMBER_TX IN (SELECT NUMBER_TX FROM #TMPPLCY)
AND L.NUMBER_TX = '140322133'