USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT O.* INTO UnitracHDStorage..INC0329256_CB
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE OWNER_TYPE_CD = 'CB' AND  LL.CODE_TX  = '5659' 

SELECT * FROM dbo.REF_CODE
WHERE --CODE_CD ='CS'
DOMAIN_CD = 'OwnerType'



UPDATE dbo.OWNER
SET PURGE_DT = NULL, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0329256', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
--SELECT * FROM dbo.OWNER
WHERE ID IN (
SELECT  ID FROM UniTracHDStorage..INC0329256_C)




