USE UniTrac


--Finding WI via Number
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, WD.NAME_TX [Definition], 
WQ.NAME_TX [Queue], WI.*
FROM  WORK_ITEM WI
INNER JOIN dbo.WORKFLOW_DEFINITION WD ON WD.ID = WI.WORKFLOW_DEFINITION_ID
INNER JOIN dbo.WORK_QUEUE WQ ON WQ.ID = WI.CURRENT_QUEUE_ID
WHERE WI.ID IN (37523272)



--Finding WI via CODE_TX
----REPLACE #### WITH THE THE Lender ID
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, WD.NAME_TX [Definition], 
WQ.NAME_TX [Queue], WI.*
FROM  WORK_ITEM WI
INNER JOIN dbo.WORKFLOW_DEFINITION WD ON WD.ID = WI.WORKFLOW_DEFINITION_ID
INNER JOIN dbo.WORK_QUEUE WQ ON WQ.ID = WI.CURRENT_QUEUE_ID
INNER JOIN dbo.LENDER L ON L.ID = WI.LENDER_ID
WHERE L.CODE_TX = '7350'AND WI.STATUS_CD = 'Error'  
AND --WI.STATUS_CD NOT IN ('Complete' ,'Withdrawn' ,'ImportCompleted', 'Initial') AND 
WI.UPDATE_DT >= '2016-11-05 '
AND WI.WORKFLOW_DEFINITION_ID = 'X'



--Process Log ID


SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '42160501' AND RELATE_TYPE_CD = 'Allied.UniTrac.ReportHistory'



SELECT * FROM dbo.WORK_QUEUE W
JOIN dbo.WORK_QUEUE_WORK_ITEM_RELATE WW ON WW.WORK_QUEUE_ID = W.ID
WHERE W.WORKFLOW_DEFINITION_ID = '9'

SELECT * FROM dbo.REPORT_HISTORY
WHERE ID IN (11477847,
11477848,
11477849,
11477850,
11477851,
11477852,
11477853,
11477854,
11477855,
11496410) AND STATUS_CD <> 'COMP'


SELECT * FROM dbo.REPORT
WHERE ID IN (33,37)


		            ---------------- Setting Report to Re-Pend/Re-Try -------------------
UPDATE  [UniTrac].[dbo].[REPORT_HISTORY]
SET     STATUS_CD = 'PEND' ,
        RETRY_COUNT_NO = 0 ,
        MSG_LOG_TX = NULL ,
        RECORD_COUNT_NO = 0 ,
        ELAPSED_RUNTIME_NO = 0,
		UPDATE_DT = GETDATE()
--	, REPORT_DATA_XML = ''
--		,REPORT_ID = '27'
--SELECT * FROM dbo.REPORT_HISTORY
WHERE   ID IN (11477851,
11477854)

(11477853,11496410)
