USE UniTrac



SELECT ACTIVE_IN ,
       ONHOLD_IN ,
       PROCESS_TYPE_CD ,
       NAME_TX ,
       EXECUTION_FREQ_CD ,
       LAST_RUN_DT
FROM   dbo.PROCESS_DEFINITION
WHERE PROCESS_TYPE_CD=  'CYCLEPRC'
AND ACTIVE_IN = 'Y' AND ONHOLD_IN = 'N'
UNION
SELECT ACTIVE_IN ,
       ONHOLD_IN ,
       PROCESS_TYPE_CD ,
       NAME_TX ,
       EXECUTION_FREQ_CD ,
       LAST_RUN_DT
FROM   dbo.PROCESS_DEFINITION
WHERE PROCESS_TYPE_CD=  'BILLING'
AND ACTIVE_IN = 'Y' AND ONHOLD_IN = 'N'