USE UniTrac

SELECT *
FROM ref_code
WHERE domain_cd = 'RequiredCoverageInsStatus'


SELECT *
FROM ref_code
WHERE domain_cd = 'RequiredCoverageInsSubStatus'


SELECT * FROM lender
WHERE COde_tx = '3124'


SELECT   DISTINCT L.NUMBER_TX ,
PCU.CREATE_DT [Date of Change],
FC.DESCRIPTION_TX [Status from], CF.DESCRIPTION_TX [Status To],
         OP.POLICY_NUMBER_TX ,
         OP.STATUS_CD ,
         OP.SUB_STATUS_CD ,
         OP.SOURCE_CD ,
         OP.EFFECTIVE_DT ,
         OP.EXPIRATION_DT ,
         OP.CANCELLATION_DT ,
         OP.CANCEL_REASON_CD ,
         OP.MOST_RECENT_MAIL_DT 
		 INTO JCS..INC0323985_Fe2017
FROM     dbo.PROPERTY_CHANGE PC
         JOIN dbo.REQUIRED_COVERAGE RC ON RC.ID = PC.ENTITY_ID
                                          AND PC.ENTITY_NAME_TX IN ( 'Allied.UniTrac.RequiredCoverage' )
         INNER JOIN dbo.PROPERTY P ON P.ID = RC.PROPERTY_ID
         INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
         INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
         JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
         JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
         LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
		 LEFT JOIN dbo.REF_CODE FC ON FC.CODE_CD = PCU.FROM_VALUE_TX AND FC.domain_cd = 'RequiredCoverageInsStatus'
		 LEFT JOIN dbo.REF_CODE CF ON CF.CODE_CD = PCU.TO_VALUE_TX AND CF.domain_cd = 'RequiredCoverageInsStatus'
WHERE    P.LENDER_ID = 2292
         AND PCU.CREATE_DT >= '2017-02-01 '
         AND PCU.CREATE_DT <= '2017-03-01 '
         AND PCU.COLUMN_NM = 'INSURANCE_STATUS_CD'
         AND PCU.FROM_VALUE_TX IN ( 'C', 'CH', 'E', 'EH', 'X', 'XH' )
         AND PCU.TO_VALUE_TX = 'F'
ORDER BY PCU.CREATE_DT DESC


SELECT   DISTINCT L.NUMBER_TX ,
PCU.CREATE_DT [Date of Change],
FC.DESCRIPTION_TX [Status from], CF.DESCRIPTION_TX [Status To],
        OP.POLICY_NUMBER_TX ,
         OP.STATUS_CD ,
         OP.SUB_STATUS_CD ,
         OP.SOURCE_CD ,
         OP.EFFECTIVE_DT ,
         OP.EXPIRATION_DT ,
         OP.CANCELLATION_DT ,
         OP.CANCEL_REASON_CD ,
         OP.MOST_RECENT_MAIL_DT
		 INTO  JCS..INC0323985_Aug2017
FROM     dbo.PROPERTY_CHANGE PC
         JOIN dbo.REQUIRED_COVERAGE RC ON RC.ID = PC.ENTITY_ID
                                          AND PC.ENTITY_NAME_TX IN ( 'Allied.UniTrac.RequiredCoverage' )
         INNER JOIN dbo.PROPERTY P ON P.ID = RC.PROPERTY_ID
         INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
         INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
         JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
         JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
         LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
		 LEFT JOIN dbo.REF_CODE FC ON FC.CODE_CD = PCU.FROM_VALUE_TX AND FC.domain_cd = 'RequiredCoverageInsStatus'
		 LEFT JOIN dbo.REF_CODE CF ON CF.CODE_CD = PCU.TO_VALUE_TX AND CF.domain_cd = 'RequiredCoverageInsStatus'
WHERE P.LENDER_ID = 2292 AND PCU.CREATE_DT >= '2017-08-01 '
AND PCU.CREATE_DT <= '2017-09-01 '
AND PCU.COLUMN_NM = 'INSURANCE_STATUS_CD' AND PCU.FROM_VALUE_TX IN ('C', 'CH', 'E', 'EH','X','XH')
AND PCU.TO_VALUE_TX = 'F'
ORDER BY PCU.CREATE_DT DESC




DROP TABLE
JCS..INC0323985_Aug2017

DROP TABLE JCS..INC0323985_Fe2017
