USE [UniTrac]
GO 


SELECT INFO_XML.value('(/INFO_LOG/RELATE_INFO)[1]', 'varchar (50)') [Loan Number], *
INTO #tmpPLI
FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (52418366,52410916,52410942)
AND RELATE_TYPE_CD = 'Allied.UniTrac.Loan' AND STATUS_CD <> 'ERR'



--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.GOOD_THRU_DT, RC.*
--INTO UniTracHDStorage..INC0335742_RC2
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('7676') AND L.NUMBER_TX IN (SELECT [Loan Number] FROM #tmpPLI)


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX,  PC.*  
INTO UniTracHDStorage..INC0335742_PC2
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE LL.CODE_TX IN ('7676') AND L.NUMBER_TX IN (SELECT [Loan Number] FROM #tmpPLI)



SELECT * 
--INTO UniTracHDStorage..INC0335742_IH
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM UniTracHDStorage..INC0335742_RC)



SELECT * 
INTO UniTracHDStorage..INC0335742_IH2
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM UniTracHDStorage..INC0335742_RC2)
AND TYPE_CD = 'OWNERPOLICY'
AND RELATE_ID IS  NULL 

UPDATE IH
SET purge_dt = GETDATE(), IH.UPDATE_DT  = GETDATE(), IH.LOCK_ID = IH.LOCK_ID+1, IH.UPDATE_USER_TX = 'INC0335742'
--SELECT * 
FROM dbo.INTERACTION_HISTORY IH
WHERE ID IN (358372438) OR (ID IN (SELECT ID FROM UniTracHDStorage..INC0335742_IH2))




UPDATE rc
SET rc.INSURANCE_STATUS_CD = 'F', rc.INSURANCE_SUB_STATUS_CD = 'D',
rc.SUMMARY_STATUS_CD = 'F', rc.SUMMARY_SUB_STATUS_CD = 'D', rc.GOOD_THRU_DT = NULL,
 rc.UPDATE_DT  = GETDATE(), rc.LOCK_ID = rc.LOCK_ID+1, rc.UPDATE_USER_TX = 'INC0335742'
--SELECT CR.SUMMARY_STATUS_CD , * 
FROM	 dbo.REQUIRED_COVERAGE rc
JOIN UniTracHDStorage..INC0335742_RC2 CR ON RC.ID = CR.ID 
WHERE RC.ID IN (SELECT ID FROM UniTracHDStorage..INC0335742_RC2)
AND CR.SUMMARY_STATUS_CD = 'E' AND RC.CREATE_DT >= '2017-11-07 '
AND RC.CREATE_DT <= '2017-11-08 '



UPDATE OP
SET OP.EXPIRATION_DT = NULL, OP.STATUS_CD=  'F', op.SUB_STATUS_CD = 'D', OP.PURGE_DT = NULL , op.UPDATE_DT  = GETDATE(), op.LOCK_ID = op.LOCK_ID+1, op.UPDATE_USER_TX = 'INC0335742'
--SELECT * 
FROM dbo.OWNER_POLICY OP
JOIN UniTracHDStorage..INC0335742_OP2 PO ON PO.ID = OP.ID 
WHERE OP.ID IN (SELECT ID FROM UniTracHDStorage..INC0335742_op2)
AND PO.STATUS_CD = 'E' AND OP.CREATE_DT >= '2017-11-07 '
AND OP.CREATE_DT <= '2017-11-08 '



SELECT * FROM dbo.PROCESS_DEFINITION
WHERE NAME_TX LIKE '%7676%'


UPDATE PD
SET
PD.SETTINGS_XML_IM = '<ProcessDefinitionSettings>
  <LastProcessedDate />
  <TargetServerList>
    <TargetServer />
  </TargetServerList>
  <TargetServiceList>
    <TargetService />
  </TargetServiceList>
  <PredecessorProcessList>
    <PredecessorProcess />
  </PredecessorProcessList>
  <LDAPServer>10.10.18.186</LDAPServer>
  <LDAPPath>ou=groups,ou=internal,dc=as,dc=net</LDAPPath>
  <LenderListThrottle>10</LenderListThrottle>
  <AnticipatedNextScheduledDate>1/10/2018 5:56:39 PM</AnticipatedNextScheduledDate>
  <LenderList>
    <LenderID LastProcessed="1/1/2000 12:02:28 PM">7676</LenderID>
  </LenderList>
  <ServiceCapabilityList>
    <ServiceCapability>RAMSMALL</ServiceCapability>
    <ServiceCapability>CPUSMALL</ServiceCapability>
  </ServiceCapabilityList>
</ProcessDefinitionSettings>'
FROM dbo.PROCESS_DEFINITION PD
WHERE ID = 543831



SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID = 543831
AND UPDATE_DT >= '2017-01-10'
ORDER BY UPDATE_DT DESC 