USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.LENDER_PRODUCT_ID, rc.id, c.COLLATERAL_CODE_ID,RC.CPI_QUOTE_ID, l.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('7100') AND L.NUMBER_TX IN ('64933-54')




SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '39599564'

SELECT * FROM dbo.CPI_ACTIVITY
WHERE CPI_QUOTE_ID IN (39599564)

---It will always be on of the items below
/*
ENTITY_NAME_TX
Allied.UniTrac.Collateral
Allied.UniTrac.DocumentInteraction
Allied.UniTrac.Escrow
Allied.UniTrac.Loan
Allied.UniTrac.Owner
Allied.UniTrac.OwnerPolicy
Allied.UniTrac.OwnerPolicyInteraction
Allied.UniTrac.PolicyCoverage
Allied.UniTrac.ProcessHelper.UniTracProcessDefinit
Allied.UniTrac.Property
Allied.UniTrac.RequiredCoverage
Osprey.ProcessMgr.ProcessDefinition
Quote
Refund

*/


SELECT * FROM dbo.LENDER_PRODUCT
WHERE id IN (4379,
4381)


SELECT ES.ORDER_NO, * FROM dbo.EVALUATION_EVENT  EE 
JOIN dbo.EVENT_SEQUENCE ES ON ES.ID = EE.EVENT_SEQUENCE_ID
WHERE EE.EVENT_SEQUENCE_ID IN (365522,365523,365524,365983,365525) AND EE.REQUIRED_COVERAGE_ID IN (5703803, 43035841)
ORDER BY ES.ORDER_NO, EE.REQUIRED_COVERAGE_ID, EE.UPDATE_DT ASC  


SELECT * FROM dbo.EVENT_SEQUENCE
WHERE EVENT_SEQ_CONTAINER_ID= '112650'
ORDER BY ORDER_NO ASC 

ID IN (251450,251451)



SELECT * FROM dbo.EVENT_SEQ_CONTAINER
WHERE LENDER_PRODUCT_ID IN (4379,
4381) AND COLLATERAL_CODE_ID = 313
