USE UniTrac

SELECT C.id
INTO #tmpC
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE ll.CODE_TX = '2990'








SELECT *
--DISTINCT ENTITY_ID 
FROM    PROPERTY_CHANGE
        INNER JOIN PROPERTY_CHANGE_UPDATE ON PROPERTY_CHANGE.ID = PROPERTY_CHANGE_UPDATE.CHANGE_ID
WHERE   ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'
        AND ENTITY_ID IN ( SELECT   ID
                           FROM     #tmpC )
        AND COLUMN_NM = 'COLLATERAL_CODE_ID'



SELECT DISTINCT ENTITY_ID [C_ID] , FROM_VALUE_TX [Old], TO_VALUE_TX [New]
INTO #tmpCID
FROM    PROPERTY_CHANGE
        INNER JOIN PROPERTY_CHANGE_UPDATE ON PROPERTY_CHANGE.ID = PROPERTY_CHANGE_UPDATE.CHANGE_ID
WHERE   ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'
        AND ENTITY_ID IN ( SELECT   *
                           FROM     #tmpC )  AND COLUMN_NM = 'COLLATERAL_CODE_ID'





SELECT DISTINCT L.NUMBER_TX ,
        RC.TYPE_CD ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] ,
        CID.Old [Old Collateral Code ID] ,
        CID.New [New Collateral Code ID]
--INTO    UniTracHDStorage..ZINC0231846
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.LENDER_PRODUCT LP ON LP.ID = RC.LENDER_PRODUCT_ID
        INNER JOIN dbo.REF_CODE RC1 ON RC1.CODE_CD = RC.STATUS_CD
                                       AND RC1.DOMAIN_CD = 'RequiredCoverageStatus'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
        INNER JOIN #tmpCID CID ON CID.C_ID = C.ID 
WHERE   C.ID IN ( SELECT    C_ID
                  FROM      #tmpCID )
        AND LL.CODE_TX = '2990'