--1) Main Service Center Query (SERVICE_CENTER_FUNCTION_LENDER_RELATE)
SELECT C.CODE_TX, C.NAME_TX, SCFLR.ID as SCFLR_ID,*
FROM LENDER L
INNER JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFLR ON L.ID = SCFLR.LENDER_ID AND SCFLR.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER_FUNCTION SCF ON SCFLR.SERVICE_CENTER_FUNCTION_ID = SCF.ID AND SCF.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER C ON SCF.SERVICE_CENTER_ID = C.ID  AND C.PURGE_DT IS NULL
WHERE L.CODE_TX = '1615'

--SCFLR ROW
SELECT *
FROM SERVICE_CENTER_FUNCTION_LENDER_RELATE
WHERE ID = 1855



--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE SERVICE_CENTER_FUNCTION_LENDER_RELATE
SET SERVICE_CENTER_FUNCTION_ID = 105
WHERE ID = 2465



--2) Service Center Setup by Division
SELECT RD.DEF_ID,RD.VALUE_TX,LO.NAME_TX,RD.ID as RD_ID,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '1615' 

--RELATED_DATA ROW(S)
SELECT * --INTO UniTracHDStorage..INC0205685
FROM RELATED_DATA
WHERE ID IN (
25555152)


SELECT * FROM UniTracHDStorage..INC0205685
--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE RELATED_DATA
SET VALUE_TX = 'Plano'
WHERE ID IN (25555152)



SELECT TOP 10
        CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender_Code ,
        CONTENT_XML.value('(/Content/Coverage/Type)[1]', 'varchar (50)') Coverage_Type ,
        *,  CONTENT_XML.value('(/Content/Lender/Id)[1]', 'varchar (50)') Lender_Id ,
		 CONTENT_XML.value('(/Content/Lender/Name)[1]', 'varchar (50)') Lender_Name
FROM    dbo.WORK_ITEM
WHERE   CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') = '1615'
        AND CONTENT_XML.value('(/Content/Coverage/Type)[1]', 'varchar (50)') = 'Flood'
        AND UPDATE_DT > GETDATE() - 3


SELECT * FROM dbo.WORK_QUEUE
WHERE ID IN (83,156, 925)


 SELECT * FROM dbo.WORK_QUEUE
WHERE DESCRIPTION_TX LIKE '%Plano%'


