

SELECT * FROM dbo.REF_CODE WHERE CODE_CD = 'C'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'CPIActivityIssueReason'


SELECT TOP 5 * FROM dbo.CPI_ACTIVITY
INNER JOIN CPI_QUOTE ON CPI_QUOTE.ID = CPI_ACTIVITY.CPI_QUOTE_ID


SELECT * FROM dbo.REPORT_CONFIG RC
INNER JOIN dbo.REPORT_CONFIG_ATTRIBUTE ON REPORT_CONFIG_ATTRIBUTE.ID = RC.ID
INNER JOIN dbo.REF_CODE_ATTRIBUTE ON ATTRIBUTE_CD = REPORT_REF_ATTRIBUTE_CD
INNER JOIN dbo.REF_CODE FC ON CODE_CD =REF_CD
INNER JOIN dbo.REPORT R ON R.ID = RC.REPORT_ID
WHERE CODE_TX = 'LEND_ITD' AND fc.DOMAIN_CD = 'Report_LenderITD' AND REF_CODE_ATTRIBUTE.DOMAIN_CD = 'Report_LenderITD'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'CPIActivityType' OR DOMAIN_CD = 'CPIActivityIssueReason'

SELECT * FROM dbo.REPORT
WHERE ID = '31'