USE [UniTrac]
GO 


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT  L.ID [Loan_ID], L.NUMBER_TX, L.CREATE_DT, L.UPDATE_DT,C.LENDER_COLLATERAL_CODE_TX,
L.BRANCH_CODE_TX
--INTO UniTracHDStorage..INC0222694
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2239') AND LENDER_COLLATERAL_CODE_TX = 'M' AND BRANCH_CODE_TX = '2239'

SELECT * INTO #tmp
FROM UniTracHDStorage..INC0222694

SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '2239' AND Lo.TYPE_CD = 'BRCH'


---Play ground it's temp area

SELECT L.*
INTO #tmp
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2239') AND LENDER_COLLATERAL_CODE_TX = 'M' AND BRANCH_CODE_TX = '2239'




UPDATE #tmp
SET BRANCH_CODE_TX = 'FIRST MORTGAGE', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0222694', LOCK_ID = LOCK_ID %255 + 1
--SELECT BRANCH_CODE_TX,* FROM #tmp
WHERE ID IN (SELECT Loan_ID FROM UniTracHDStorage..INC0222694)
--276



SELECT COUNT(*) FROM dbo.LOAN
---31,329,346

----Update on data once approved by user

UPDATE dbo.LOAN
SET BRANCH_CODE_TX = 'FIRST MORTGAGE', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0222694', LOCK_ID = LOCK_ID %255 + 1
--SELECT * FROM  dbo.LOAN
WHERE ID IN (SELECT Loan_ID FROM UniTracHDStorage..INC0222694)
--276






