USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT C.*
--INTO UniTracHDStorage..INC0240203_Coll
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
--INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
--INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
--INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
--INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
--INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
--INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.LENDER_ID = '281' AND DIVISION_CODE_TX = '10' AND BRANCH_CODE_TX = 'BUSINESS'
AND C.LENDER_COLLATERAL_CODE_TX IN ('PUD', 'RDUP', 'REN4', 'REST',
'RETA', 'RSBU', 'RTRI', 'SFRR', 'SING', 'WARE', 'OFFC', 'IT4F', '2NDH', 'APT', 'CHRC', 'COND',
'COOP', 'DEAL', 'EQUP', 'FLOR', 'FLRE', 'FRMR', 'HCAR', 'MHPK', 'MOTL', 'MULT', 'NURS','SELS')






---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '2864' AND Lo.TYPE_CD = 'DIV'


SELECT COLLATERAL_CODE_ID, * FROM UniTracHDStorage..INC0240203_Coll


---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2864' AND CC.CODE_TX IN ('COMPROP')



UPDATE dbo.COLLATERAL
SET COLLATERAL_CODE_ID  = '511', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0240203', LOCK_ID = LOCK_ID+1
--SELECT COLLATERAL_CODE_ID, * FROM dbo.COLLATERAL
WHERE ID IN (SELECT ID FROM UniTracHDStorage..INC0240203_Coll)




INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , P.ID , ' INC024020' , 'N' , 
 GETDATE() ,  1 , 
 'Moved to COMPROP Collateral ID',
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , P.ID , 'PEND' , 'N'
FROM PROPERTY P
WHERE P.ID IN (SELECT ID FROM UniTracHDStorage..INC0240203_Coll)


