USE [UniTrac]
GO 


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '5175'

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT *  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'



SELECT L. * 
INTO UniTracHDStorage..INC0232899L
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'



SELECT C. * 
INTO UniTracHDStorage..INC0232899C
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'




SELECT P. *
INTO UniTracHDStorage..INC0232899P
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'


SELECT RC. *
INTO UniTracHDStorage..INC0232899RC
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'

SELECT O. *
INTO UniTracHDStorage..INC0232899O
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'


SELECT OA. *
INTO UniTracHDStorage..INC0232899OA
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'

SELECT OL. *
INTO UniTracHDStorage..INC0232899OL
  FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE L.ID = '79571240' AND L.LENDER_ID = '1872'





UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT PURGE_DT, * 
FROM Loan L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899L)


UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT PURGE_DT, * 
FROM dbo.PROPERTY L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899P)


UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1, RECORD_TYPE_CD = 'A'
--SELECT PURGE_DT, * 
FROM dbo.REQUIRED_COVERAGE L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899RC)

UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1
--SELECT PURGE_DT, * 
FROM dbo.COLLATERAL L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899C)

UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1
--SELECT PURGE_DT, * 
FROM dbo.OWNER L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899O)



UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1
--SELECT PURGE_DT, * 
FROM dbo.OWNER_ADDRESS L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899OA)



UPDATE L
SET L.PURGE_DT = NULL, L.UPDATE_DT = GETDATE(), L.UPDATE_USER_TX = 'INC0232899', L.LOCK_ID=L.LOCK_ID+1
--SELECT PURGE_DT, * 
FROM dbo.OWNER_LOAN_RELATE L
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899OL)





SELECT RECORD_TYPE_CD, * FROM  UniTracHDStorage..INC0232899L

SELECT * FROM  UniTracHDStorage..INC0232899C


SELECT RECORD_TYPE_CD, * FROM UniTracHDStorage..INC0232899P

SELECT RECORD_TYPE_CD, * FROM UniTracHDStorage..INC0232899RC

SELECT * FROM UniTracHDStorage..INC0232899O

SELECT * FROM UniTracHDStorage..INC0232899OA

SELECT * FROM UniTracHDStorage..INC0232899OL


SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RecordType'




 INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0232899' , 'N' , 
 GETDATE() ,  1 , 
 'Moved Loan to Archive Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE RC 
INNER JOIN PROPERTY P ON RC.PROPERTY_ID = P.ID
INNER JOIN COLLATERAL C ON P.ID = C.PROPERTY_ID
INNER JOIN LOAN L ON L.ID = C.LOAN_ID
WHERE L.ID IN (SELECT ID FROM  UniTracHDStorage..INC0232899L)





--1085