USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT P.ID, P.ADDRESS_ID, OAB.LINE_1_TX, OA.LINE_1_TX, P.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON P.ADDRESS_ID = OA.ID
INNER JOIN OWNER_ADDRESS OAB ON O.ADDRESS_ID = OAB.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('7350') AND L.NUMBER_TX IN ('6526721')
AND OAB.LINE_1_TX IS not NULL


SELECT * FROM dbo.OWNER_ADDRESS
WHERE ID = '155732110'


SELECT * FROM dbo.PROPERTY_CHANGE PC 
JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '154195105'
AND pc.ENTITY_NAME_TX = 'Allied.UniTrac.Property'

--154195105 -856 Bald Mountain Rd
--119970962 -14 Lakeview St

SELECT * from dbo.PROPERTY_CHANGE_UPDATE PCU-- ON PC.ID = PCU.CHANGE_ID
WHERE PCu.TABLE_ID = '155732110'
AND pcu.TABLE_NAME_TX = 'OWNER_ADDRESS'

SELECT * from dbo.PROPERTY_CHANGE_UPDATE PCU-- ON PC.ID = PCU.CHANGE_ID
WHERE PCu.TABLE_ID = '119970962' AND CREATE_DT >= '2016-12-19 ' AND CREATE_DT <= '2016-12-25 '
AND pcu.TABLE_NAME_TX = 'OWNER_ADDRESS'

SELECT *FROM dbo.PROPERTY_CHANGE
WHERE ID = '5275556442'

SELECT L.PURGE_DT, L.RECORD_TYPE_CD, P.PURGE_DT, P.RECORD_TYPE_CD, C.PURGE_DT, RC.PURGE_DT, RC.RECORD_TYPE_CD,
L.ID, P.ID, C.ID, RC.ID
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('7350') AND L.NUMBER_TX IN ('6526721') AND OA.ID  = '160800200'
---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'



---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = 'XXXX'

