USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT *
--INTO UniTracHDStorage..INC0280749_Loan
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3400') AND RC.ID IN (SELECT * FROM #tmp)
AND RC.STATUS_CD <> 'W'





SELECT L.NUMBER_TX,RC.UPDATE_USER_TX, RC.* 
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3400') AND rc.id IN (SELECT * FROM #tmp)
AND RC.STATUS_CD != 'W'






SELECT L.NUMBER_TX,RC.UPDATE_USER_TX, RC.* 
--INTO UniTracHDStorage..INC0280749_requiredcoverage
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('3400') AND L.NUMBER_TX IN (SELECT * FROM UniTracHDStorage..INC0280749)
AND L.NUMBER_TX IN --( '20049163467','20049464386','20042751151')
('20044305314')

SELECT * FROM  UniTracHDStorage..INC0280749_requiredcoverage



SELECT ID INTO #tmp FROM UniTracHDStorage..INC0280749_requiredcoverage
WHERE status_cd <> 'W'



---Join multiple tables to do an update
	--UPDATE RC 
	--SET RC.STATUS_CD= 'W',
	--RC.UPDATE_DT = GETDATE(),
	--RC.UPDATE_USER_TX = 'INC0280749', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END
	----SELECT COUNT(*)
	--FROM dbo.REQUIRED_COVERAGE RC
	--WHERE RC.ID IN --(53823329)
	
	(SELECT * FROM #tmp)
	
	


 --- UPDATE SUB_STATUS_CD (#tmpLoan.waiveCD from EXCEL value)
UPDATE RC SET STATUS_CD = 'W' ,
SUB_STATUS_CD = TMP.waiveCD ,
GOOD_THRU_DT = NULL ,
CPI_QUOTE_ID = NULL , NOTICE_DT = NULL , NOTICE_TYPE_CD = NULL ,
NOTICE_SEQ_NO = NULL , LAST_EVENT_SEQ_ID = NULL , LAST_EVENT_DT = NULL ,
LAST_SEQ_CONTAINER_ID = NULL ,
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0280749' ,
LOCK_ID = RC.LOCK_ID % 255 + 1
----- SELECT *
FROM REQUIRED_COVERAGE RC JOIN #tmp TMP
ON TMP.ID = RC.ID 
--WHERE RC.STATUS_CD = 'A' --- NOT NEEDED - WE ARE INCLUDING INACTIVE STATUSES TOO
AND TMP.EXCLUDE = 0

UPDATE ee
SET STATUS_CD = 'CLR',
      UPDATE_DT = GETDATE(),
      UPDATE_USER_TX = 'TASK37723',
      LOCK_ID = (ee.LOCK_ID % 255) + 1
--SELECT ee.*
FROM
      EVALUATION_EVENT ee
      JOIN #tmp te ON ee.REQUIRED_COVERAGE_ID = te.id
      WHERE ee.STATUS_CD = 'PEND'
      AND ee.EVENT_SEQUENCE_ID > 0
GO	
	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , L.ID , 'INC0280749' , 'N' , 
 GETDATE() ,  1 , 
'Moved to Waive Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , L.ID , 'PEND' , 'N'
FROM dbo.REQUIRED_COVERAGE L 
WHERE L.ID IN --(53823329)
(SELECT * FROM #tmp)

