USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE

SELECT C.ID INTO #tmpC
--SELECT COUNT(*) 	
FROM dbo.PROPERTY_CHANGE PC
INNER JOIN dbo.COLLATERAL C ON PC.ENTITY_ID = C.ID AND PC.ENTITY_NAME_TX = 'Allied.UniTrac.Collateral'
INNER JOIN LOAN L  ON L.ID = C.LOAN_ID
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.NOTE_TX LIKE '%Cross%' AND L.LENDER_ID = '731'

 
SELECT DISTINCT L.NUMBER_TX ,
        RCC.DESCRIPTION_TX [Record Type] ,
        RCA.DESCRIPTION_TX [Loan Status] , L.DIVISION_CODE_TX, LO.CODE_TX,
		Lo.NAME_TX [Division]
		--INTO JCs..INC0250561
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN dbo.REF_CODE RCC ON RCC.CODE_CD = L.RECORD_TYPE_CD
                                       AND RCC.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RCA ON RCA.CODE_CD = L.STATUS_CD
                                       AND RCA.DOMAIN_CD = 'LoanStatus'
		INNER JOIN LENDER_ORGANIZATION LO ON L.DIVISION_CODE_TX = LO.CODE_TX AND Lo.TYPE_CD = 'DIV'
--INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE   C.ID IN ( SELECT    *
                  FROM      #tmpC ) AND L.LENDER_ID = '731'


				 
---Finding Branch
SELECT *
FROM  LENDER_ORGANIZATION LO

WHERE LENDER_ID = '731' AND TYPE_CD = 'DIV'





