USE UniTrac


--Finding WI via Number
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, WD.NAME_TX [Definition], 
CONTENT_XML.value('(/Content/Information/ProcessLogs/ProcessLog/@Id)[3]', 'varchar (50)') ProcessID,
WQ.NAME_TX [Queue], WI.*
FROM  WORK_ITEM WI
INNER JOIN dbo.WORKFLOW_DEFINITION WD ON WD.ID = WI.WORKFLOW_DEFINITION_ID
INNER JOIN dbo.WORK_QUEUE WQ ON WQ.ID = WI.CURRENT_QUEUE_ID
WHERE WI.ID IN (39193155, 39193515, 39193517,39193518, 39193688, 39193901 )



--Finding WI via CODE_TX
----REPLACE #### WITH THE THE Lender ID
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, WD.NAME_TX [Definition], 
WQ.NAME_TX [Queue], WI.*
FROM  WORK_ITEM WI
INNER JOIN dbo.WORKFLOW_DEFINITION WD ON WD.ID = WI.WORKFLOW_DEFINITION_ID
INNER JOIN dbo.WORK_QUEUE WQ ON WQ.ID = WI.CURRENT_QUEUE_ID
INNER JOIN dbo.LENDER L ON L.ID = WI.LENDER_ID
WHERE L.CODE_TX = '7350'AND WI.STATUS_CD = 'Error'  
AND --WI.STATUS_CD NOT IN ('Complete' ,'Withdrawn' ,'ImportCompleted', 'Initial') AND 
WI.UPDATE_DT >= '2016-11-05 '
AND WI.WORKFLOW_DEFINITION_ID = 'X'



--Process Log ID


SELECT RELATE_ID INTO #tmpPLI FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (44992582,
44993156,
44993200,
44992965,
44992669,
44993412, 
44992714,
44993378)
AND RELATE_TYPE_CD = 'Allied.UniTrac.ReportHistory'



UPDATE  [UniTrac].[dbo].[REPORT_HISTORY]
SET     STATUS_CD = 'PEND' ,
        RETRY_COUNT_NO = 0 ,
        MSG_LOG_TX = NULL ,
        RECORD_COUNT_NO = 0 ,
        ELAPSED_RUNTIME_NO = 0,
		UPDATE_DT = GETDATE(), DOCUMENT_CONTAINER_ID = NULL
--SELECT * FROM dbo.REPORT_HISTORY
WHERE   ID IN 
(SELECT * FROM #tmpPLI)



SELECT * INTO UniTracHDStorage.. INC0298340 
FROM dbo.REPORT_HISTORY
WHERE   ID IN 
(SELECT * FROM #tmpPLI)