SELECT BRANCH_CODE_TX,RC.TYPE_CD, * FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID = 827 AND RC.TYPE_CD = 'FLOOD'
AND BRANCH_CODE_TX = 'MOBILEHOME'
ORDER BY L.EFFECTIVE_DT DESC


SELECT * FROM dbo.LENDER
where ID IN (827)


SELECT * FROM dbo.WORK_ITEM
WHERE ID IN (27945864)