USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.* 
INTO UnitracHDStorage..INC0302484
FROM PROPERTY P 
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
WHERE P.LENDER_ID = '832' AND rc.TYPE_CD = 'REO-LIABILITY'




UPDATE RC
SET PURGE_DT = GETDATE(), lock_id = locK_id+1, update_dt = GETDATE(), update_user_tx = 'INC0302484'
FROM dbo.REQUIRED_COVERAGE RC  
WHERE ID IN (SELECT ID FROM UnitracHDStorage..INC0302484)

