USE [UniTrac]
GO 

--DROP TABLE JCS..INC0293947
--DROP TABLE #tmp

SELECT * FROM  dbo.LENDER
WHERE code_tx = '4296'

SELECT * FROM UniTracHDStorage..['Lender4296']
SELECT DISTINCT CC.ID INTO #tmp        
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '4296'
 AND CC.CODE_TX LIKE '%-A'
        OR CC.CODE_TX LIKE '%-OT'

SELECT  L.NUMBER_TX [Loan Number] ,
        CC.CODE_TX, C.* 
INTO    UniTracHDStorage..INC0293560_Results
FROM    LOAN L
JOIN UniTracHDStorage..['Lender4296'] S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 324
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        LEFT JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                      AND RC2.DOMAIN_CD = 'RecordType'
        LEFT JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                      AND RC3.DOMAIN_CD = 'LoanStatus'
        LEFT JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                      AND RC4.DOMAIN_CD = 'LoanType'
        LEFT JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID

UPDATE C
SET COLLATERAL_CODE_ID = CC.ID 
--SELECT  COLLATERAL_CODE_ID, CC.ID , L.Lender_ID,  * 
FROM dbo.COLLATERAL C 
JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
JOIN UniTracHDStorage..['Lender4296'] S ON L.NUMBER_TX = S.[Loan Number] AND L.Lender_id = 324
JOIN dbo.COLLATERAL_CODE CC ON CC.CODE_TX = S.[Change to]

