SELECT L.NUMBER_TX, O.FIRST_NAME_TX, O.LAST_NAME_TX, OA.LINE_1_TX, OA.LINE_2_TX, OA.CITY_TX, OA.STATE_PROV_TX, OA.POSTAL_CODE_TX, RE.*
into unitrachdstorage..INC0385792
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
inner join required_escrow RE on RE.REQUIRED_COVERAGE_ID = RC.ID 
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('0108') AND RE.UPDATE_USER_TX = 'LDHPCRA'


update RE
set purge_dt = NULL,UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0385792', RE.LOCK_ID = RE.LOCK_ID+1, ACTIVE_IN = 'Y'
--select RE.*
from REQUIRED_ESCROW RE
join unitrachdstorage..INC0385792 I on I.ID = RE.ID



select IH.RELATE_ID into #tmp
--into unitrachdstorage..INC0385792_IH
from PROPERTY P
join Lender L on L.ID = P.LENDER_ID
join INTERACTION_HISTORY IH on IH.PROPERTY_ID = P.ID 
WHERE L.CODE_TX IN ('0108') AND IH.CREATE_USER_TX = 'LDHPCRA'
and IH.TYPE_CD = 'ESCROW'


select * 
into unitrachdstorage..INC0385792_E
from ESCROW
where id in (select * from #tmp)

update E
set purge_dt = GETDATE(),UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0385792', E.LOCK_ID = E.LOCK_ID+1
--select E.*
from ESCROW E
join unitrachdstorage..INC0385792_E I on I.ID = E.ID


update E
set purge_dt = GETDATE(),UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0385792', E.LOCK_ID = E.LOCK_ID+1
--select E.*
from INTERACTION_HISTORY E
join unitrachdstorage..INC0385792_IH I on I.ID = E.ID



update RC set GOOD_THRU_DT = NULL, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0385792', RC.LOCK_ID = RC.LOCK_ID+1
--select GOOD_THRU_DT, RC.*
 FROM LOAN L
 join unitrachdstorage..INC0385792_E I on I.LOAN_ID = L.ID 
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
