--Work Item query to get process log IDs
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, *
FROM WORK_ITEM
WHERE ID IN (28754605)
--WIA query to obtain Process Definition ID (In the ACTION_NOTE_TX)
SELECT *
FROM WORK_ITEM_ACTION
WHERE WORK_ITEM_ID IN (28754605) and ACTION_CD = 'Release For Billing'
--New Billing Processes
SELECT *
FROM PROCESS_DEFINITION
WHERE ID in (255607)
--New Process Log IDs
SELECT *
FROM PROCESS_LOG
WHERE PROCESS_DEFINITION_ID in (255607)
--PLI Table
SELECT *
FROM PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID IN (29900909)
--Billing Group WIs

SELECT * FROM dbo.WORK_ITEM
WHERE RELATE_ID = '1436900'

SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '28754605'



SELECT * FROM dbo.PROCESS_DEFINITION
WHERE PROCESS_TYPE_CD LIKE '%cyc%' AND NAME_TX LIKE '%7545%'
ORDER BY EXECUTION_FREQ_CD DESC, NAME_TX ASC 

SELECT * FROM dbo.WORKFLOW_DEFINITION



SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, *
FROM WORK_ITEM 
WHERE WORKFLOW_DEFINITION_ID = '9' AND CAST(UPDATE_DT AS DATE) > CAST(GETDATE()-16 AS DATE)
AND CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') = '7545'