USE UniTrac

SELECT DISTINCT L.CODE_TX [Lender Code], L.NAME_TX [Lender Name], C.NAME_TX [Carrier Name], MP.START_DT,MP.END_DT [END_DT]
INTO JCs..testrunINC0246495IN
FROM dbo.MASTER_POLICY MP
JOIN dbo.MASTER_POLICY_ASSIGNMENT MPA ON MPA.MASTER_POLICY_ID = MP.ID
JOIN dbo.CARRIER C ON C.ID = MP.CARRIER_ID
JOIN Lender L ON L.ID = LENDER_ID
JOIN dbo.ADDRESS A ON A.ID = L.PHYSICAL_ADDRESS_ID
WHERE STATE_PROV_TX = 'IN' AND  COVERAGE_TYPE_CD = 'PHYS-DAMAGE'
AND MP.END_DT >= '2016-09-07 '



USE UniTrac

SELECT DISTINCT L.CODE_TX [Lender Code], L.NAME_TX [Lender Name], C.NAME_TX [Carrier Name], MP.START_DT,MP.END_DT [END_DT]
INTO JCs..INC0246495CA
FROM dbo.MASTER_POLICY MP
JOIN dbo.MASTER_POLICY_ASSIGNMENT MPA ON MPA.MASTER_POLICY_ID = MP.ID
JOIN dbo.CARRIER C ON C.ID = MP.CARRIER_ID
JOIN Lender L ON L.ID = LENDER_ID
JOIN dbo.ADDRESS A ON A.ID = L.PHYSICAL_ADDRESS_ID
WHERE STATE_PROV_TX = 'CA' AND  COVERAGE_TYPE_CD = 'PHYS-DAMAGE'
AND MP.END_DT >= '2016-09-07 '



DROP TABLE JCs..testrunINC0246495