USE UniTrac

SELECT  DISTINCT MESSAGE_ID
FROM    dbo.TRADING_PARTNER_LOG
WHERE   PROCESS_CD = 'DW'
        AND CAST(CREATE_DT AS DATE) = CAST(GETDATE() AS DATE)
        AND TRADING_PARTNER_ID = '19'


		SELECT * FROM dbo.TRADING_PARTNER
		WHERE EXTERNAL_ID_TX = '1578'


		SELECT * FROM dbo.WORK_ITEM
		WHERE WORKFLOW_DEFINITION_ID = '1' AND RELATE_ID IN (5961775)

		SELECT * FROM dbo.MESSAGE
		WHERE ID IN (5961775)

		SELECT TOP 10 PD.NAME_TX, PL.* FROM dbo.PROCESS_LOG PL
INNER JOIN dbo.PROCESS_DEFINITION PD ON PD.ID = PL.PROCESS_DEFINITION_ID
WHERE PD.ID IN (11847,11848)
ORDER BY PL. UPDATE_DT DESC 



UPDATE dbo.MESSAGE
SET RECEIVED_STATUS_CD = 'HOLD', UPDATE_DT = GETDATE(), LOCK_ID = LOCK_ID+1, 
PROCESSED_IN = 'Y', UPDATE_USER_TX = 'INC0243587'
--SELECT * FROM dbo.MESSAGE
WHERE ID = '5961775'