-------------- Check Work Items Before Update (To Verify Work Item Definition and Status)
-------------- Work Item ID Number(s) should be provided on HDT
----REPLACE XXXXX WITH THE THE WI ID



--Finding WI via CODE_TX
----REPLACE #### WITH THE THE Lender ID
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, *
--INTO UniTracHDStorage..INC0223358
FROM    UniTrac..WORK_ITEM
WHERE    CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') = '7450' 
AND STATUS_CD NOT IN ('Complete' ,'Withdrawn' ,'ImportCompleted')
AND WORKFLOW_DEFINITION_ID = '8'


-------- Verify Data Work Item Clean Up for Cancelled Lender or update initial Select if only specific WI's being closed out.
----REPLACE XXXXXXX WITH THE THE WI ID
----REPLACE #### WITH THE THE Lender ID

SELECT DISTINCT
        WI.ID AS WI_ID ,
        LOAN.ID AS LOAN_ID
INTO    #TMPWI
FROM    LOAN
        JOIN LENDER ON LENDER.ID = LOAN.LENDER_ID
        JOIN WORK_ITEM WI ON WI.RELATE_ID = LOAN.ID
WHERE   LENDER.CODE_TX = '7450'
        AND WI.WORKFLOW_DEFINITION_ID = 8
        AND WI.STATUS_CD NOT IN ( 'COMPLETE', 'Withdrawn' )
        AND WI.PURGE_DT IS NULL
        --AND WI.CREATE_DT < '2014-01-01 00:00:00.000'
        AND LOAN.PURGE_DT IS NULL
        AND LOAN.RECORD_TYPE_CD IN ('G','A')
		AND WI.ID IN (SELECT ID FROM UniTracHDStorage..INC0223358 )
		
SELECT * FROM #TMPWI

SELECT * INTO UniTracHDStorage..LOAN_INC0223358
FROM dbo.LOAN WHERE ID IN (SELECT LOAN_ID FROM #TMPWI)


UPDATE  LN
SET     SPECIAL_HANDLING_XML = NULL ,
        UPDATE_DT = GETDATE() ,
        UPDATE_USER_TX = 'INC0223358' ,
        LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1
                       ELSE LOCK_ID + 1
                  END
--SELECT COUNT(*)
FROM    LOAN LN
        JOIN #TMPWI ON #TMPWI.LOAN_ID = LN.ID


UPDATE  WI
SET     STATUS_CD = 'Withdrawn' ,
        UPDATE_DT = GETDATE() ,
        UPDATE_USER_TX = 'INC0223358' ,
        LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1
                       ELSE LOCK_ID + 1
                  END
--SELECT COUNT(*)
FROM    WORK_ITEM WI
        JOIN #TMPWI ON #TMPWI.WI_ID = WI.ID



SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]', 'varchar (50)') Lender, * --INTO UniTracHDStorage..WI_INC0222261
INTO    #TMPWII
FROM    UniTrac..WORK_ITEM
WHERE   ID IN ( 25750806 )


UPDATE WI SET STATUS_CD = 'Withdrawn' , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0223358' , 
LOCK_ID = WI.LOCK_ID % 255 + 1
---- SELECT COUNT(*)
FROM WORK_ITEM WI JOIN #TMPWII TMP ON 
TMP.ID = WI.ID
AND WI.PURGE_DT IS NULL
---- 28

INSERT INTO WORK_ITEM_ACTION (WORK_ITEM_ID, ACTION_CD, FROM_STATUS_CD, TO_STATUS_CD, CURRENT_QUEUE_ID, 
CURRENT_OWNER_ID, ACTION_NOTE_TX, ACTIVE_IN, CREATE_DT, UPDATE_DT, UPDATE_USER_TX, LOCK_ID, ACTION_USER_ID)
SELECT DISTINCT ID , 'Withdraw' , STATUS_CD , 'Withdrawn' , CURRENT_QUEUE_ID , 
CURRENT_OWNER_ID , 'INC0223358' , 'Y' , GETDATE() , GETDATE() , 'INC0223358' , 1 , 1
FROM #TMPWII
ORDER BY STATUS_CD
---- 26


UPDATE LN SET SPECIAL_HANDLING_XML = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX  = 'INC0222261' , 
LOCK_ID = LN.LOCK_ID % 255 + 1
--- SELECT LN.NUMBER_TX
FROM LOAN LN JOIN #TMPWII ON #TMPWII.RELATE_ID = LN.ID
--- 28
