USE UniTrac


SELECT * FROM dbo.WORK_ITEM
WHERE ID  =  '39743039'


SELECT EVALUATION_EVENT_ID FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = 47286667



     UPDATE EE SET STATUS_CD = 'PEND' , UPDATE_USER_TX = 'INC0312883' , 
	      UPDATE_DT = GETDATE() , LOCK_ID = (LOCK_ID % 255) + 1	
		  --SELECT * 
		  FROM dbo.EVALUATION_EVENT EE
	      WHERE ID IN (SELECT EVALUATION_EVENT_ID FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = 47286667)


 SELECT WI.ID [WorkItemId], OC.OUTPUT_TYPE_CD, OC.TYPE_CD, OB.* FROM dbo.OUTPUT_BATCH OB
JOIN dbo.OUTPUT_CONFIGURATION OC ON OC.ID = OB.OUTPUT_CONFIGURATION_ID
join WORK_ITEM WI ON WI.RELATE_ID = OB.PROCESS_LOG_ID AND WI.RELATE_TYPE_CD = 'Osprey.ProcessMgr.ProcessLog'
  WHERE WI.ID IN (39743039 )

  UPDATE dbo.OUTPUT_BATCH
  SET STATUS_CD = 'EMPTY', OUTSOURCER_STATUS_CD = 'EMPTY'
  --SELECT * FROM dbo.OUTPUT_BATCH
  WHERE ID IN (1411799,1411800,1411801,1411802,1411803)