USE [UniTrac]
GO

/****** Object:  StoredProcedure [dbo].[FindMulti]    Script Date: 11/26/2018 10:37:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[FindMulti] 

AS 
SET NOCOUNT ON ; 

SELECT
	COUNT(C.ID) AS C_COUNT,
	L.ID AS LOAN_ID
INTO 
	#CTEMP
FROM
	LENDER LDR
	JOIN LOAN L ON L.LENDER_ID = LDR.ID AND L.RECORD_TYPE_CD = 'G' AND L.STATUS_CD = 'A' AND L.PURGE_DT IS NULL
	JOIN COLLATERAL C ON C.LOAN_ID = L.ID AND C.PURGE_DT IS NULL
WHERE
	LDR.CODE_TX = '3551'
GROUP BY 
	L.ID;

SELECT
	l.id [LoanID], 
L.NUMBER_TX, 
CETD.TRANSACTION_ID CETD_TRANSACTION_ID,
CETD.SEQUENCE_ID CETD_SEQUENCE_ID,

pp.Tab.value('.', 'nvarchar(30)') [Organization Code] , 
oa.ID [OA_ID],
oa.line_1_tx,
oa.LINE_2_TX,
oa.CITY_TX,
oa.STATE_PROV_TX,
oa.PO_BOX_TX,
oa.POSTAL_CODE_TX,
cetd.RealEstateLine1_TX
FROM
	LENDER LDR
	JOIN LOAN L ON L.LENDER_ID = LDR.ID AND L.RECORD_TYPE_CD = 'G' AND L.STATUS_CD = 'A' AND L.PURGE_DT IS NULL
	JOIN COLLATERAL C ON C.LOAN_ID = L.ID AND C.PURGE_DT IS NULL
	JOIN PROPERTY P ON P.ID = C.PROPERTY_ID AND P.PURGE_DT IS NULL
	JOIN OWNER_ADDRESS OA ON OA.ID = P.ADDRESS_ID AND OA.PURGE_DT IS NULL -- AND OA.ID = 245662010
	JOIN UNITRAC_TO_LATEST_LENDER_DATA_RELATE UTLLDR ON UTLLDR.UNITRAC_RELATE_CLASS_ID = C.ID AND UTLLDR.UNITRAC_RELATE_CLASS_NAME_TX = 'Allied.UniTrac.Collateral' and UTLLDR.PURGE_DT IS NULL
	JOIN COLLATERAL_EXTRACT_TRANSACTION_DETAIL CETD ON CETD.ID = UTLLDR.LENDER_DATA_RELATE_CLASS_ID AND UTLLDR.LENDER_DATA_RELATE_CLASS_NAME_TX = 'Allied.UniTrac.LenderExtract.CollateralExtractTransactionDetail' AND CETD.PURGE_DT IS NULL
	JOIN BORROWER_INSURANCE_EXTRACT_TRANSACTION_DETAIL BIETD ON BIETD.TRANSACTION_ID = CETD.TRANSACTION_ID AND BIETD.SEQUENCE_ID = CETD.SEQUENCE_ID AND BIETD.PURGE_DT IS NULL
	JOIN #CTEMP ON #CTEMP.LOAN_ID = L.ID
	cross apply BIETD.XML_ORIGINAL_LENDER.nodes('//OriginalLenderData/Field[@Name="ORGANIZATION-CD"]') as pp(Tab)  
WHERE
	LDR.CODE_TX = '3551'
	and pp.Tab.value('.', 'nvarchar(30)') IN ('MULTI', 'MULT')
	and ((oa.LINE_1_TX not like 'PRIMARY%' and oa.LINE_1_TX not like 'SECONDARY%') OR (C_COUNT = 1))

GO
