select TOP 5 DIVISION_CODE_TX,C.STATUS_CD,BRANCH_CODE_TX,RC.TYPE_CD,
* from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID = '2254' AND L.STATUS_CD = 'A' AND NUMBER_TX = '1112746-130'

select COUNT(*)
 from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID = '2254'  AND DIVISION_CODE_TX = '10'


select COUNT(*)
 from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID = '2254' AND DIVISION_CODE_TX = '4'



SELECT DISTINCT NUMBER_TX FROM dbo.LOAN
WHERE LENDER_ID = '2254' AND DIVISION_CODE_TX = '4' AND STATUS_CD = 'A'
--30843


SELECT COUNT(*) FROM dbo.LOAN
WHERE LENDER_ID = '2254' AND DIVISION_CODE_TX = '10'

select COUNT(*)
 from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID = '2254' AND L.STATUS_CD = 'A' AND DIVISION_CODE_TX = '3525'






SELECT * FROM dbo.LENDER
WHERE CODE_TX = '3525'


SELECT LO.*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '3525' AND LO.TYPE_CD = 'DIV' AND LO.NAME_TX <> 'Vehicle Loan'
AND LO.PURGE_DT IS NULL



--1112746-130




