USE [Unitrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT
        L.NUMBER_TX [Loan Number] ,
		Lo.NAME_TX,BRANCH_CODE_TX [Branch],
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type],
        O.LAST_NAME_TX ,
        O.FIRST_NAME_TX
FROM    LOAN L
		INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
		INNER JOIN dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
		INNER JOIN LENDER_ORGANIZATION LO ON LO.CODE_TX = L.DIVISION_CODE_TX
		LEFT JOIN OWNER_ADDRESS OA ON P.ADDRESS_ID = OA.ID
WHERE   L.LENDER_ID IN (962) AND L.RECORD_TYPE_CD = 'G' AND L.DIVISION_CODE_TX = '4'
AND LO.TYPE_CD = 'DIV'  AND OA.ID IS NULL





SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '2252' AND Lo.TYPE_CD = 'DIV'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'LoanType'