USE [UniTrac]
GO 



SELECT L.NAME_TX [Lender Name], L.CODE_TX [Lender Code], COUNT(LL.ID) [Loan Count]

FROM dbo.LENDER L
JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = LL.ID
JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
WHERE LL.DIVISION_CODE_TX = '3' AND L.STATUS_CD = 'ACTIVE' AND TEST_IN = 'N'
GROUP BY L.NAME_TX, L.CODE_TX
HAVING COUNT(LL.ID) >= '10000'
ORDER BY COUNT(LL.ID) DESC 




SELECT L.NAME_TX [Lender Name], L.CODE_TX [Lender Code], LL.* FROM dbo.LENDER L
JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
WHERE LL.DIVISION_CODE_TX = '3' AND L.STATUS_CD = 'ACTIVE' AND TEST_IN = 'N'
AND L.CODE_TX = '2800'





SELECT L.NAME_TX [Lender Name], L.CODE_TX [Lender Code], COUNT(LL.ID) [Loan Count]
FROM dbo.LENDER L
JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = LL.ID
JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
JOIN dbo.LENDER_COLLATERAL_GROUP_COVERAGE_TYPE LCGT ON LCGT.ID = RC.LCGCT_ID AND LCGT.TYPE_CD = 'PHYS-DAMAGE'
JOIN dbo.LENDER_PRODUCT LP ON LP.ID = LCGT.LENDER_PRODUCT_ID AND LP.BASIC_TYPE_CD = 'FLTRK'
WHERE L.STATUS_CD = 'ACTIVE' AND TEST_IN = 'N' 
GROUP BY L.NAME_TX, L.CODE_TX
HAVING COUNT(LL.ID) >= '10000'
ORDER BY COUNT(LL.ID) DESC 




SELECT LL.NUMBER_TX, RC.*
FROM dbo.LENDER L
JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = LL.ID
JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
JOIN dbo.LENDER_COLLATERAL_GROUP_COVERAGE_TYPE LCGT ON LCGT.ID = RC.LCGCT_ID AND LCGT.TYPE_CD = 'PHYS-DAMAGE'
JOIN dbo.LENDER_PRODUCT LP ON LP.ID = LCGT.LENDER_PRODUCT_ID AND LP.BASIC_TYPE_CD = 'FLTRK'
WHERE L.STATUS_CD = 'ACTIVE' AND TEST_IN = 'N' 
AND L.CODE_TX = '1574'








SELECT DISTINCT L.NAME_TX [Lender Name], L.CODE_TX [Lender Code], LP.NAME_TX [Lender Product Description], COUNT(LL.ID) [Loan Count]
FROM dbo.LENDER L
JOIN dbo.LOAN LL ON LL.LENDER_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = LL.ID
JOIN  dbo.PROPERTY P ON P.ID = C.PROPERTY_ID
JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
JOIN dbo.LENDER_COLLATERAL_GROUP_COVERAGE_TYPE LCGT ON LCGT.ID = RC.LCGCT_ID AND LCGT.TYPE_CD = 'PHYS-DAMAGE'
JOIN dbo.LENDER_PRODUCT LP ON LP.ID = LCGT.LENDER_PRODUCT_ID AND LP.BASIC_TYPE_CD = 'FLTRK'
WHERE L.STATUS_CD = 'ACTIVE' AND TEST_IN = 'N' 
GROUP BY L.NAME_TX, L.CODE_TX,  LP.NAME_TX
HAVING COUNT(LL.ID) >= '10000'
ORDER BY L.CODE_TX ASC, COUNT(LL.ID) ASC  
