USE [UniTrac]
GO 


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '4750'


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT * INTO UniTracHDStorage..INC0326741_BranchMoved FROM LOAN L
WHERE L.ID IN (SELECT id FROM UniTracHDStorage..INC0326741)


UPDATE L
SET L.UPDATE_DT = GETDATE(), L.LOCK_ID =L.LOCK_ID+1, L.UPDATE_USER_TX = 'INC0326741', L.BRANCH_CODE_TX = 'NON ESCROW'
FROM dbo.LOAN L
WHERE L.ID IN (SELECT id FROM UniTracHDStorage..INC0326741)


	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Loan' , L.ID , 'INC0326741' , 'N' , 
 GETDATE() ,  1 , 
'Moved to branch NON ESCROW', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Loan' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT id FROM UniTracHDStorage..INC0326741)
