USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT P.ID INTO #tmp FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE LL.CODE_TX IN ('4204') AND L.SOURCE_CD = 'EX' 



SELECT SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') [Policy Id], *
INTO #tmpA
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT * FROM #tmp) AND SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') <>   RELATE_ID



SELECT SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') [Policy Id], *
INTO #tmpB
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT * FROM #tmp) AND SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') =   RELATE_ID



SELECT DISTINCT A.PROPERTY_ID 
INTO #TmpC
FROM #tmpA A
LEFT JOIN #tmpB B ON B.RELATE_ID = A.RELATE_ID
WHERE B.[Policy Id] IS NULL 
--ORDER BY A.PROPERTY_ID DESC
--52681


SELECT PROPERTY_ID
INTO #tmpD
FROM    dbo.INTERACTION_HISTORY
WHERE   PROPERTY_ID IN ( SELECT *
                         FROM   #TmpC )   
              AND INTERACTION_HISTORY.TYPE_CD = 'IMPAIRMENT'
--ORDER BY INTERACTION_HISTORY.PROPERTY_ID DESC
--1917



SELECT IH.PROPERTY_ID, IH.UPDATE_USER_TX
INTO #tmpE
FROM    dbo.INTERACTION_HISTORY IH
JOIN #TmpC C ON C.PROPERTY_ID = IH.PROPERTY_ID
LEFT JOIN #tmpD D ON D.PROPERTY_ID = IH.PROPERTY_ID
WHERE D.PROPERTY_ID IS NULL AND IH.UPDATE_USER_TX = 'LDHPCRA'


SELECT IH.PROPERTY_ID
--IH.SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') [Policy Id] ,       IH.*
INTO #tmpF
FROM    dbo.INTERACTION_HISTORY IH
WHERE PROPERTY_ID IN (SELECT PROPERTY_ID FROM #tmpE) AND IH.UPDATE_USER_TX <> 'LDHPCRA'



SELECT IH.PROPERTY_ID, IH.UPDATE_USER_TX
--IH.SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') [Policy Id] ,       IH.*
INTO #tmpG
 FROM    dbo.INTERACTION_HISTORY IH
JOIN #TmpC C ON C.PROPERTY_ID = IH.PROPERTY_ID
LEFT JOIN #tmpD D ON D.PROPERTY_ID = IH.PROPERTY_ID
WHERE D. PROPERTY_ID IS NULL AND IH.UPDATE_USER_TX = 'LDHPCRA'


SELECT PROPERTY_ID
--IH.SPECIAL_HANDLING_XML.value('(/SH/OwnerPolicy/Id)[1]', 'varchar (50)') [Policy Id] ,       IH.*
INTO #tmpH
FROM  #tmpG
WHERE PROPERTY_ID NOT IN (SELECT * FROM #tmpF) 


SELECT DISTINCT L.NUMBER_TX, P.ID
INTO #tmpI
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE LL.CODE_TX IN ('4204') --AND L.NUMBER_TX IN ('520593')
AND P.ID IN (SELECT * FROM #tmpH)

SELECT PROPERTY_ID
INTO #tmpJ
 FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID IN (SELECT ID FROM #tmpI ) AND SPECIAL_HANDLING_XML.value('(/SH/Desc)[1]', 'varchar (50)') IN ('New Insurance' , 'ReAudit')


SELECT DISTINCT NUMBER_TX
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
        INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
        INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE   LL.CODE_TX IN ( '4204' )
        AND P.ID IN ( SELECT    *
                      FROM      #tmpJ )


--42686  distinct loans




--74283 all loans 



--SELECT TOP 65000 A.* 
----INTO UniTracHDStorage..AAINC0230610
--FROM UniTracHDStorage..INC0230610 A
--ORDER BY A.Last_Name_TX ASC 



--SELECT TOP 35000 A.* 
--INTO UniTracHDStorage..AAAINC0230610
--FROM UniTracHDStorage..INC0230610 A
--LEFT JOIN UniTracHDStorage..AAINC0230610 B ON B.LoanID = A.LoanID
--WHERE B.LoanID IS NULL
--ORDER BY A.Last_Name_TX ASC 


--SELECT A.*
--INTO UniTracHDStorage..AAAAINC0230610
--FROM UniTracHDStorage..INC0230610 A
--LEFT JOIN UniTracHDStorage..AAINC0230610 B ON B.LoanID = A.LoanID
--LEFT JOIN UniTracHDStorage..AAAINC0230610 C ON C.LoanID = A.LoanID
--WHERE B.LoanID IS NULL AND  C.LoanID IS NULL
--ORDER BY A.Last_Name_TX ASC 
