USE UNITRAC

SELECT  LL.CODE_TX [Lender Code], LL.NAME_TX [Lender Name], L.NUMBER_TX [Loan Number] ,
        RC1.DESCRIPTION_TX [Coverage Status] , RC.GOOD_THRU_DT [Good Thru Date],
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] ,
		CONCAT(RC6.DESCRIPTION_TX, ' ', RC5.DESCRIPTION_TX) AS [Insurance Coverage Status],
        RC.*
INTO    UniTracHDStorage..INC0383544
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        INNER JOIN dbo.LENDER_PRODUCT LP ON LP.ID = RC.LENDER_PRODUCT_ID
        INNER JOIN dbo.REF_CODE RC1 ON RC1.CODE_CD = RC.STATUS_CD
                                       AND RC1.DOMAIN_CD = 'RequiredCoverageStatus'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        LEFT JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
        LEFT JOIN dbo.REF_CODE RC5 ON RC5.CODE_CD = RC.INSURANCE_STATUS_CD
                                       AND RC5.DOMAIN_CD = 'RequiredCoverageInsStatus'
        LEFT JOIN dbo.REF_CODE RC6 ON RC6.CODE_CD = RC.INSURANCE_SUB_STATUS_CD
                                       AND RC6.DOMAIN_CD = 'RequiredCoverageInsSubStatus'
        LEFT JOIN dbo.REF_CODE RC7 ON RC7.CODE_CD = RC.SUB_STATUS_CD
                                       AND RC7.DOMAIN_CD = 'RequiredCoverageSubStatus'
		LEFT JOIN dbo.LENDER_ORGANIZATION LO ON LO.LENDER_ID = LL.ID 
									    AND LO.TYPE_CD = 'DIV' AND LO.CODE_TX = L.DIVISION_CODE_TX		
where  LL.CODE_TX = '3551' and C.COLLATERAL_CODE_ID = 524
and RC.TYPE_CD = 'HAZARD' and RC.STATUS_CD <> 'T'


UPDATE RC SET STATUS_CD = 'T', 
GOOD_THRU_DT = NULL , 
UPDATE_DT = GETDATE() , UPDATE_USER_TX = 'INC0383544' , 
LOCK_ID = RC.LOCK_ID % 255 + 1
---- SELECT RC.STATUS_CD, RC.SUMMARY_STATUS_CD , RC.INSURANCE_STATUS_CD , RC.BEGAN_NEW_IN , RC.GOOD_THRU_DT , RC.TYPE_CD ---,  *
FROM REQUIRED_COVERAGE RC JOIN UniTracHDStorage..INC0383544 TMP 
ON TMP.ID = RC.ID 
---- 10701


	
INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.RequiredCoverage' , L.ID , 'INC0383544' , 'N' , 
 GETDATE() ,  1 , 
'Moved Loans to Track Status', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.RequiredCoverage' , L.ID , 'PEND' , 'N'
FROM REQUIRED_COVERAGE L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0383544)