USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX [Loan Number], O.LAST_NAME_TX [Last Name], O.FIRST_NAME_TX [First Name], 
LENDER_COLLATERAL_CODE_TX,CC.DESCRIPTION_TX,
OA.LINE_1_TX , OA.LINE_2_TX , OA.CITY_TX , OA.STATE_PROV_TX , OA.COUNTRY_TX, OA.POSTAL_CODE_TX 
--INTO UniTracHDStorage..INC0244748
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_LOAN_RELATE OL ON OL.LOAN_ID = L.ID
INNER JOIN dbo.OWNER O ON O.ID = OL.OWNER_ID
INNER JOIN OWNER_ADDRESS OA ON P.ADDRESS_ID = OA.ID
LEFT JOIN dbo.COLLATERAL_CODE CC ON C.COLLATERAL_CODE_ID = CC.ID
LEFT JOIN dbo.REF_CODE RC ON RC.CODE_CD = CC.SECONDARY_CLASS_CD AND RC.DOMAIN_CD = 'SecondaryClassification'
WHERE L.LENDER_ID = '354' AND L.DIVISION_CODE_TX = '4'

DROP TABLE UniTracHDStorage..INC0244748
---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '2175' AND Lo.TYPE_CD = 'DIV'

SELECT * FROM dbo.LENDER_COLLATERAL_CODE_GROUP L
JOIN dbo.LCCG_COLLATERAL_CODE_RELATE LCC ON LCC.LCCG_ID = L.ID
JOIN dbo.COLLATERAL_CODE CC ON CC.ID = LCC.COLLATERAL_CODE_ID
WHERE L.LENDER_ID = '354'



