USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT RC.TYPE_Cd, RC.ID [RC], L.NUMBER_TX, LL.CODE_TX,
ih.SPECIAL_HANDLING_XML.value('(/SH/InsuranceDocument/@DocumentType)[1]', 'varchar (50)'),
ih.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]', 'varchar (50)'),
 IH.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
WHERE LL.CODE_TX IN ('2814')  AND P.ID IN (134669345)  AND DOCUMENT_ID IS NULL
--63673870

SELECT  * FROM dbo.DOCUMENT_CONTAINER DC
WHERE ID IN (64141855,64140593 )

SELECT IH.
SPECIAL_HANDLING_XML.value('(/SH/InsuranceDocument/@DocumentType)[1]', 'varchar (50)'), IH.* FROM dbo.PROPERTY P
JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = P.ID
JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID
WHERE L.NUMBER_TX = '60000005701-00001'


SELECT DISTINCT TYPE_CD FROM dbo.INTERACTION_HISTORY

SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%%'
        AND AGENCY_ID = '1'
        AND ID IN (  )





SELECT DISTINCT RELATE_CLASS_NAME_TX FROM dbo.DOCUMENT_CONTAINER


SELECT ID INTO #tmpDC FROM dbo.DOCUMENT_CONTAINER
WHERE DISPLAY_DESC_TX = 'CM56169100316/\\unitrac\VUT_IMAGES\2016\06\20\UT-ALLIED\CM56169100316\IMAGESUT-ALLIED20160620_CM5616'


SELECT * FROM dbo.DOCUMENT_CONTAINER
WHERE UPDATE_USER_TX = 'UBSMatchOut'
AND UPDATE_DT >='2016-07-28 08:00:00 '
AND UPDATE_DT <= '2016-07-28 15:00:00 '

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'DocumentQualifier'

SELECT *
INTO #tmpOP
 FROM dbo.OWNER_POLICY
WHERE POLICY_NUMBER_TX IN ('EGGCD000063314', 'CPR13E013204', 'CPR13E013203')


CPR13E013203


SELECT * FROM #tmpOP

SELECT * FROM dbo.POLICY_COVERAGE pc
JOIN #tmpOP t ON t.ID = pc.OWNER_POLICY_ID


SELECT * FROM #tmpOP t
LEFT JOIN dbo.POLICY_COVERAGE pc ON pc.OWNER_POLICY_ID = t.ID



SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'SourceType'


SELECT * FROM dbo.DOCUMENT_CONTAINER
WHERE ID IN (63673870,64140593,64141855,65414191)



--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT TOP 1000 RC.TYPE_Cd, RC.ID [RC], L.NUMBER_TX, LL.CODE_TX,
ih.SPECIAL_HANDLING_XML.value('(/SH/InsuranceDocument/@DocumentType)[1]', 'varchar (50)'),
ih.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]', 'varchar (50)'),
 IH.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
WHERE ih.SPECIAL_HANDLING_XML.value('(/SH/RC)[1]', 'varchar (50)') IS NULL
AND DOCUMENT_ID IS NULL AND IH.NOTE_TX like 'No required coverage matches the specified insurance coverage %'










 LL.CODE_TX IN ('2814')  AND P.ID IN (134669345)  AND DOCUMENT_ID IS NULL