USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT LL.CODE_TX, IH.SPECIAL_HANDLING_XML.value('(/SH/Status)[1]', 'varchar (50)'),
 IH.SPECIAL_HANDLING_XML.value('(/SH/Reason)[1]', 'varchar (50)'), IH.SPECIAL_HANDLING_XML.value('(/SH/Event)[1]', 'varchar (50)'),
 IH.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.INTERACTION_HISTORY IH ON IH.PROPERTY_ID = P.ID 
WHERE L.NUMBER_TX = '8632286-50' AND IH.TYPE_CD = 'CPI'




SELECT RC.SUMMARY_STATUS_CD, SUMMARY_SUB_STATUS_CD, RC.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
WHERE L.NUMBER_TX = '8632286-50'


SELECT OP.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
WHERE L.NUMBER_TX = '8632286-50'



SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'C'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RequiredCoverageInsStatus'

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RequiredCoverageInsSubStatus'

SELECT * FROM dbo.FORCE_PLACED_CERTIFICATE
WHERE LOAN_NUMBER_TX = '8632286-50'

--SC80545372
--

ID = '5821758'

SELECT * FROM dbo.CPI_QUOTE C
JOIN dbo.CPI_ACTIVITY a ON a.CPI_QUOTE_ID = C.ID
WHERE C.ID = 37323554

'37027851'


SELECT * FROM dbo.REF_CODE
WHERE --DOMAIN_CD = 'ForcePlacedCertificateStatus'
DOMAIN_CD = 'CPIActivityType'


UPDATE dbo.FORCE_PLACED_CERTIFICATE
SET PURGE_DT = NULL , LOCK_ID= LOCK_ID+1, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0250765', CLAIM_PENDING_IN = 'Y'
WHERE ID = '5821758'


UPDATE dbo.CPI_QUOTE
SET PURGE_DT = NULL , LOCK_ID= LOCK_ID+1, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0250765'
WHERE ID = '37323554'


UPDATE dbo.INTERACTION_HISTORY
SET PURGE_DT = NULL , LOCK_ID= LOCK_ID+1, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0250765'
WHERE ID IN (248177547)

UPDATE dbo.REQUIRED_COVERAGE
SET SUMMARY_STATUS_CD = 'C', SUMMARY_SUB_STATUS_CD = 'D', LOCK_ID= LOCK_ID+1, UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0250765'
WHERE ID = '124616900'

--37323554



SELECT BEGAN_NEW_IN,  RC.* FROM  LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.REQUIRED_COVERAGE RC ON RC.PROPERTY_ID = P.ID
WHERE L.NUMBER_TX = '8632286-50'

SELECT * INTO UniTracHDStorage..INC0250765IH2
FROM dbo.INTERACTION_HISTORY
WHERE PROPERTY_ID = '123353204'


SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '124616900' AND PC.ENTITY_NAME_TX = 'Allied.UniTrac.RequiredCoverage'

SELECT * FROM dbo.PROPERTY_CHANGE PC
LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ID = PCU.CHANGE_ID
WHERE PC.ENTITY_ID = '123353204' AND PC.ENTITY_NAME_TX = 'Allied.UniTrac.Property'

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT P.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
INNER JOIN dbo.POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE LL.CODE_TX IN ('5150') AND L.NUMBER_TX = '8632286-50'


SELECT * FROM dbo.PRIOR_CARRIER_POLICY
WHERE REQUIRED_COVERAGE_ID = '124616900'


SELECT * FROM dbo.CARRIER C
JOIN dbo.CARRIER_PRODUCT CP ON CP.CARRIER_ID = C.ID
WHERE c.ID = '21'

SELECT * FROM dbo.MASTER_POLICY MP
JOIN dbo.MASTER_POLICY_ASSIGNMENT MPA ON MPA.MASTER_POLICY_ID = MP.ID
JOIN dbo.CANCEL_PROCEDURE CP ON CP.ID = MPA.CANCEL_PROCEDURE_ID
JOIN dbo.ISSUE_PROCEDURE IP ON IP.ID = MPA.ISSUE_PROCEDURE_ID
JOIN dbo.LENDER_ORGANIZATION ON LENDER_ORGANIZATION.ID = MPA.DIV_LENDER_ORG_ID
WHERE mp.ID ='7605'

--SELECT* FROM dbo.MASTER_POLICY_ASSIGNMENT MPA
--JOIN dbo.CANCEL_PROCEDURE CP ON CP.ID = MPA.CANCEL_PROCEDURE_ID
--JOIN dbo.ISSUE_PROCEDURE IP ON IP.ID = MPA.ISSUE_PROCEDURE_ID
--JOIN dbo.LENDER_ORGANIZATION ON LENDER_ORGANIZATION.ID = MPA.DIV_LENDER_ORG_ID
--WHERE MPA.ID = '27959'

SELECT * FROM dbo.FORCE_PLACED_CERTIFICATE
WHERE LOAN_NUMBER_TX = '8632286-50'


SELECT * FROM dbo.TEMPLATE
WHERE ID = '11'


SELECT TOP 10* FROM dbo.NOTICE
WHERE CPI_QUOTE_ID = '37027851'


