USE [UniTrac]
GO 


IF OBJECT_ID(N'UniTracHDStorage..INC0279119',N'U') IS NOT NULL
       DROP TABLE UniTracHDStorage..INC0279119 


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT CR.DESCRIPTION_TX, L.* 
INTO UniTracHDStorage..INC0279119
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
LEFT JOIN dbo.REF_CODE CR ON RC.INSURANCE_STATUS_CD = CR.CODE_CD AND CR.DOMAIN_CD = 'RequiredCoverageInsStatus'
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2244') AND L.PREDICTIVE_DECILE_NO >= '3'
AND rc.INSURANCE_STATUS_CD = 'N'




-----Finding Branch
--SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
--FROM LENDER L
--INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
--INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
--WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'



-----Finding Collateral Code
--SELECT  CC.ID ,
--        CC.CODE_TX ,
--        CC.DESCRIPTION_TX 
--         FROM dbo.COLLATERAL_CODE CC
--INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
--INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
--INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
--WHERE L.CODE_TX = 'XXXX'

