USE UniTrac




SELECT COUNT(*) 
--INTO UniTracHDStorage..INC0329423
FROM collateral 
WHERE id IN (SELECT ID FROM INC0329423_Final)


UPDATE C
SET C.COLLATERAL_CODE_ID = I.CollateralCodeID, C.UPDATE_DT = GETDATE(), C.UPDATE_USER_TX = 'INC0329423', C.LOCK_ID = CASE WHEN C.LOCK_ID >= 255 THEN 1 ELSE C.LOCK_ID + 1 END
--SELECT C.COLLATERAL_CODE_ID , I.CollateralCodeID, * 
FROM dbo.COLLATERAL C
JOIN INC0329423_Final I ON I.ID = C.ID
--90638


INSERT INTO PROPERTY_CHANGE
 ( ENTITY_NAME_TX , ENTITY_ID , USER_TX , ATTACHMENT_IN , 
 CREATE_DT , AGENCY_ID , DESCRIPTION_TX ,  DETAILS_IN , FORMATTED_IN ,
 LOCK_ID , PARENT_NAME_TX , PARENT_ID , TRANS_STATUS_CD , UTL_IN )
 SELECT DISTINCT 'Allied.UniTrac.Collateral' , L.ID , 'INC0329423' , 'N' , 
 GETDATE() ,  1 , 
'Change the Collateral Code ID per INC0329423', 
 'Y' , 'N' , 1 ,  'Allied.UniTrac.Collateral' , L.ID , 'PEND' , 'N'
FROM LOAN L 
WHERE L.ID IN (SELECT ID FROM UniTracHDStorage..INC0329423)