USE UniTrac


--Finding WI via Number
SELECT CONTENT_XML.value('(/Content/Lender/Code)[1]' ,'varchar (50)') Lender, WD.NAME_TX [Definition] , 
WQ.NAME_TX [Queue], WI.*
FROM  WORK_ITEM WI
INNER JOIN dbo.WORKFLOW_DEFINITION WD ON WD.ID = WI.WORKFLOW_DEFINITION_ID
INNER JOIN dbo.WORK_QUEUE WQ ON WQ.ID = WI.CURRENT_QUEUE_ID
WHERE WI.ID IN (34360454 )



--Finding WI via CODE_TX
----REPLACE #### WITH THE THE Lender ID
SELECT RELATE_ID INTO #tmp FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '38020742' AND RELATE_TYPE_CD  = 'Allied.UniTrac.Workflow.OutboundCallWorkItem'

SELECT EVALUATION_EVENT_ID INTO #tmpEE FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '38020742' AND 
RELATE_TYPE_CD = 'Allied.UniTrac.RequiredCoverage' AND STATUS_CD IN ('ERR')
ORDER BY UPDATE_DT DESC  



SELECT * FROM dbo.REQUIRED_COVERAGE
WHERE ID IN (68243225, 1354748)

SELECT * FROM dbo.EVALUATION_EVENT
WHERE ID IN (SELECT * FROM #tmpEE)

UPDATE dbo.EVALUATION_EVENT
SET STATUS_CD = 'COMP'
WHERE ID IN (SELECT * FROM #tmpEE)

--Process Log ID

SELECT * FROM dbo.WORK_ITEM
WHERE ID IN (SELECT * FROM #tmp) AND STATUS_CD = 'Initial'


UPDATE dbo.WORK_ITEM
SET STATUS_CD = 'Complete' LOCK_ID = LOCK_ID+1 UPDATE_DT = GETDATE()
WHERE ID IN (SELECT * FROM #tmpWI)


SELECT * FROM dbo.WORK_ITEM_ACTION
WHERE WORK_ITEM_ID IN (SELECT RELATE_ID FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '38020742' AND RELATE_TYPE_CD  = 'Allied.UniTrac.Workflow.OutboundCallWorkItem')
AND WORK_ITEM_ID   IN (SELECT WORK_ITEM_ID FROM dbo.WORK_ITEM_ACTION WHERE ACTION_CD = 'Complete') AND WORK_ITEM_ACTION.ACTIVE_IN <> 'Y'
ORDER BY WORK_ITEM_ID ASC

INSERT INTO dbo.WORK_ITEM_ACTION
        ( WORK_ITEM_ID 
          ACTION_CD 
          FROM_STATUS_CD 
          TO_STATUS_CD 
          CURRENT_QUEUE_ID 
          CURRENT_OWNER_ID 
          ACTION_NOTE_TX 
          ACTIVE_IN 
          CREATE_DT 
          PURGE_DT 
          UPDATE_DT 
          UPDATE_USER_TX 
          LOCK_ID 
          ACTION_USER_ID
        )
VALUES  ( 34360497  -- WORK_ITEM_ID - bigint
          N'Complete'  -- ACTION_CD - nvarchar(30)
          N'Initial'  -- FROM_STATUS_CD - nvarchar(20)
          N'Complete'  -- TO_STATUS_CD - nvarchar(20)
          334  -- CURRENT_QUEUE_ID - bigint
          925  -- CURRENT_OWNER_ID - bigint
          N'Completed by Evaluation Process'  -- ACTION_NOTE_TX - nvarchar(1000)
          ''  -- ACTIVE_IN - char(1)
          GETDATE()  -- CREATE_DT - datetime
          NULL  -- PURGE_DT - datetime
          GETDATE()  -- UPDATE_DT - datetime
          N'INC0251636'  -- UPDATE_USER_TX - nvarchar(15)
          1  -- LOCK_ID - tinyint
          1  -- ACTION_USER_ID - bigint
        )


----Use Last WIA ID that was created for LAST_WORK_ITEM_ACTION_ID column 
UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete' 
LAST_WORK_ITEM_ACTION_ID = (SELECT MAX(ID) FROM dbo.WORK_ITEM_ACTION WHERE   WORK_ITEM_ID IN ( 34360497 ))
UPDATE_DT = GETDATE()LOCK_ID = LOCK_ID+1 UPDATE_USER_TX = 'INC0251636'
WHERE   ID IN ( 34360497 )
        AND ACTIVE_IN = 'Y'




SELECT TOP 5 * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '38020742' and
RELATE_TYPE_CD = 'Allied.UniTrac.RequiredCoverage' AND STATUS_CD NOT IN ('SKIP', 'ERR')
AND EVALUATION_EVENT_ID <> '0'
ORDER BY UPDATE_DT DESC  



SELECT * FROM dbo.WORK_ITEM WI
WHERE wi.id = '33006907'

SELECT * FROM dbo.WORKFLOW_DEFINITION


SELECT * FROM dbo.WORK_ITEM_ACTION
WHERE WORK_ITEM_ID = '34360454'

SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ID = '376748'

SELECT * FROM dbo.PROCESS_LOG
WHERE PROCESS_DEFINITION_ID = '376748'

SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '38060673'

SELECT * FROM dbo.WORK_ITEM
WHERE RELATE_ID = '1556464'


UPDATE dbo.WORK_ITEM
SET STATUS_CD = 'Withdrawn', UPDATE_DT = GETDATE(), LOCK_ID = LOCK_ID+1
WHERE ID = '34360454'



UPDATE  UniTrac..WORK_ITEM
SET     STATUS_CD = 'Complete' ,
        LOCK_ID = LOCK_ID + 1 ,
        UPDATE_DT = GETDATE() ,
        UPDATE_USER_TX = 'INC0251636'
WHERE   ID IN (34360454 )
        AND WORKFLOW_DEFINITION_ID = 9
        AND ACTIVE_IN = 'Y'