USE UniTrac

SELECT * FROM dbo.CHANGE C
LEFT JOIN dbo.CHANGE_UPDATE CU ON C.ID = CU.CHANGE_ID
WHERE DESCRIPTION_TX LIKE '%EventOptionReaudit%'
ORDER BY C.CREATE_DT DESC 



SELECT * FROM dbo.LENDER_PRODUCT
WHERE ID = 8543


SELECT * FROM dbo.BUSINESS_OPTION BO 
JOIN dbo.BUSINESS_OPTION_GROUP BOG ON BO.BUSINESS_OPTION_GROUP_ID = BOG.ID 
JOIN dbo.LENDER_PRODUCT LP ON LP.ID = BOG.RELATE_ID
JOIN dbo.LENDER L ON L.ID = LP.LENDER_ID
WHERE BO.NAME_TX = 'EventOptionReaudit'


SELECT DISTINCT L.CODE_TX [Lender Code], L.NAME_TX [Lender Name], A.NAME_TX [Agency], BO.NAME_TX, Bo.DESCRIPTION_TX, BO.DEFAULT_VALUE_TX  
INTO JCs..INC0249575
FROM dbo.LENDER L 
JOIN dbo.LENDER_PRODUCT LP ON LP.LENDER_ID = L.ID
JOIN dbo.BUSINESS_OPTION_GROUP BOG ON BOG.RELATE_ID = LP.ID
JOIN dbo.BUSINESS_OPTION BO ON BO.BUSINESS_OPTION_GROUP_ID = BOG.ID 
JOIN dbo.AGENCY A ON A.ID = L.AGENCY_ID
WHERE  BO.NAME_TX = 'EventOptionReaudit' AND (DEFAULT_VALUE_TX = '' OR DEFAULT_VALUE_TX IS NULL)
AND L.STATUS_CD = 'ACTIVE' AND L.TEST_IN = 'N'
ORDER BY A.NAME_TX ASC 