USE UniTrac	


SELECT * FROM dbo.WORK_ITEM
WHERE ID = '36303763'


SELECT RELATE_ID INTO #tmpN FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '40783580' AND RELATE_TYPE_CD = 'Allied.UniTrac.Notice'



SELECT RELATE_ID INTO #tmpFPC FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '40783580' AND RELATE_TYPE_CD = 'Allied.UniTrac.ForcePlacedCertificate'


SELECT * FROM dbo.NOTICE
WHERE ID IN (SELECT * FROM #tmpN) AND TYPE_CD = 'AN' --AND PDF_GENERATE_CD <> 'COMP'
ORDER BY UPDATE_DT DESC 



--173995779

SELECT * FROM dbo.FORCE_PLACED_CERTIFICATE
WHERE ID IN (SELECT * FROM #tmpFPC)



UPDATE dbo.NOTICE
SET TEMPLATE_ID = '135', PDF_GENERATE_CD = 'PEND', UPDATE_DT = GETDATE(), 
UPDATE_USER_TX = 'INC0278187', LOCK_ID = LOCK_ID+1
--SELECT * FROM dbo.NOTICE
WHERE ID IN (SELECT * FROM #tmpN) AND TYPE_CD = 'AN' AND PDF_GENERATE_CD <> 'COMP'



SELECT * FROM dbo.TEMPLATE
WHERE ID = 135