USE UniTrac


SELECT * FROM dbo.WORK_ITEM
WHERE ID = 42904373 

SELECT RELATE_ID INTO #tmpPLI FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = 53833234 AND RELATE_TYPE_CD = 'Allied.UniTrac.Loan'


SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = 53833234 AND RELATE_TYPE_CD = 'Allied.UniTrac.Collateral'


SELECT cc.DESCRIPTION_TX, cc.CODE_TX, L.* 
INTO JCS..INC0332799
FROM dbo.LOAN L
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.COLLATERAL_CODE CC ON CC.id = C.COLLATERAL_CODE_ID
WHERE L.ID IN (SELECT * FROM #tmpPLI) AND CC.CODE_TX = 'BOAT'
AND C.CREATE_DT >= '2017-12-05 '  AND C.CREATE_DT <= '2017-12-08 '




SELECT * FROM dbo.REF_CODE
WHERE DESCRIPTION_TX LIKE '%maintenance%'


SELECT * FROM JCS..INC0332799

SELECT * FROM dbo.REF_CODE
WHERE DOMAIN_CD = 'RecordType'


SELECT L.NUMBER_TX, C.COLLATERAL_CODE_ID, RC.* 
--INTO UNitracHDStorage..INC0332799_RC
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
JOIN dbo.COLLATERAL_CODE CC ON CC.id = C.COLLATERAL_CODE_ID
WHERE L.ID IN (SELECT * FROM #tmpPLI) AND CC.CODE_TX = 'BOAT'
AND C.CREATE_DT >= '2017-12-05 '  AND C.CREATE_DT <= '2017-12-08 '


UPDATE RC
SET RC.STATUS_CD = 'M', UPDATE_USER_TX = 'INC0332799', LOCK_ID = CASE WHEN LOCK_ID >= 255 THEN 1 ELSE LOCK_ID + 1 END,RC.UPDATE_DT = GETDATE()
--SELECT * 
FROM dbo.REQUIRED_COVERAGE RC
WHERE ID IN (SELECT ID FROM UNitracHDStorage..INC0332799_RC)