use unitrac


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX, RC.Type_Cd,
RC2.DESCRIPTION_TX [ Record Type] ,
CONCAT(RC6.DESCRIPTION_TX, ' ', RC5.DESCRIPTION_TX) AS [Insurance Coverage Status], 
P.* 
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
LEFT JOIN dbo.REF_CODE RC5 ON RC5.CODE_CD = RC.CPI_STATUS_CD
                                     AND RC5.DOMAIN_CD = 'RequiredCoverageInsStatus'
LEFT JOIN dbo.REF_CODE RC6 ON RC6.CODE_CD = RC.CPI_SUB_STATUS_CD
                                       AND RC6.DOMAIN_CD = 'RequiredCoverageInsSubStatus'
LEFT JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = P.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
WHERE LL.CODE_TX IN ('3124') --AND L.NUMBER_TX IN ('10074754857')
and --RC.CPI_STATUS_CD= 'F' and 
RC.CPI_SUB_STATUS_CD = 'C'
and P.RECORD_TYPE_CD = 'A'





