--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT L.ID, L.NUMBER_TX,  O.LAST_NAME_TX, O.NAME_TX INTO UniTracHDStorage..INC0213041_2
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID IN (962) AND COLLATERAL_CODE_ID IN (313, 435,436,621,622) 
AND OWNER_TYPE_CD = 'DBA'



SELECT L.*, B.LAST_NAME_TX DBA FROM UniTracHDStorage..INC0213041 L
INNER JOIN UniTracHDStorage..INC0213041_2 B ON L.ID = B.ID 




SELECT * from LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
WHERE L.LENDER_ID IN (962) AND COLLATERAL_CODE_ID IN (313, 435,436,621,622) 
AND NUMBER_TX IN ('421808-1')


SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'DBA'

SELECT * FROM dbo.LENDER
WHERE CODE_TX IN ('') 



--Service Center Setup by Division
SELECT  LO.*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA LOC ON LO.ID = LOC.RELATE_ID --AND LOC.DEF_ID = '105'
WHERE L.CODE_TX = ''



SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%%'
        AND AGENCY_ID = '1'
        AND ID IN (  )