USE [UniTrac]
GO 




--DROP TABLE JCS..INC0295277
--DROP TABLE #tmp

SELECT DISTINCT CC.ID INTO #tmp        
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = '2725'
 AND CC.CODE_TX LIKE '%-A'
        OR CC.CODE_TX LIKE '%-OT'


--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT   	L.NUMBER_TX [Loan Number], C.*
INTO    UniTracHDStorage..INC0295277_2
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
		INNER JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
        LEFT JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        LEFT JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        LEFT JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                      AND RC4.DOMAIN_CD = 'LoanType'
WHERE   LL.CODE_TX IN ( '2725' )
        AND C.COLLATERAL_CODE_ID IN (SELECT * FROM #tmp)



SELECT * FROM UniTracHDStorage..INC0295277

UPDATE C
SET COLLATERAL_CODE_ID = G.[New Collateral_ID]
--SELECT COLLATERAL_CODE_ID, G.[New Collateral_ID], * 
FROM dbo.COLLATERAL C 
JOIN #tmpG G ON G.LoanID = C.LOAN_ID