use UniTrac
USE [UniTrac]
GO 

--Loan Screen Information - LOAN/OLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT L.NUMBER_TX [Loan Number], LO.NAME_TX [Type of Property], RC1.MEANING_TX [Type of Borrower], 
concat(O.FIRST_NAME_TX,' ',O.LAST_NAME_TX ) as  [Owner], 
concat(OA.LINE_1_TX,' ',OA.LINE_2_TX,' ',CITY_TX,' ,',STATE_PROV_TX,' ', LEFT(POSTAL_CODE_TX,5)) [Address],
case when receive_notices_in = 'Y' then 'Yes' else 'No' end as [Receive Notices]
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN REF_CODE RC1 on RC1.CODE_CD = OL.OWNER_TYPE_CD and RC1.DOMAIN_CD = 'OwnerType'
INNER JOIN LENDER_ORGANIZATION LO ON L.DIVISION_CODE_TX = LO.CODE_TX  AND Lo.TYPE_CD = 'DIV' and LO.LENDER_ID = 2447
WHERE LL.CODE_TX IN ('4407') and OWNER_TYPE_CD = 'CS' and receive_notices_in = 'Y'

UPDATE OL Set RECEIVE_NOTICES_IN = 'N', UPDATE_DT = GETDATE(), UPDATE_USER_TX = 'INC0379449'
--SELECT OL.* --INTO UNITRACHDSTORAGE..INC0379449
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN REF_CODE RC1 on RC1.CODE_CD = OL.OWNER_TYPE_CD and RC1.DOMAIN_CD = 'OwnerType'
INNER JOIN LENDER_ORGANIZATION LO ON L.DIVISION_CODE_TX = LO.CODE_TX  AND Lo.TYPE_CD = 'DIV' and LO.LENDER_ID = 2447
WHERE LL.CODE_TX IN ('4407') and OWNER_TYPE_CD = 'CS' and receive_notices_in = 'Y'
