USE [UniTrac]
GO 

--Waive
SELECT  L.NUMBER_TX ,
        L.EFFECTIVE_DT ,
        O.LAST_NAME_TX ,
        O.FIRST_NAME_TX ,
        O.MIDDLE_INITIAL_TX ,
        OA.ID ,
        OA.LINE_1_TX ,
        OA.LINE_2_TX ,
        OA.CITY_TX ,
        OA.STATE_PROV_TX ,
        OA.COUNTRY_TX ,
        OA.POSTAL_CODE_TX ,
        P.YEAR_TX ,
        P.MAKE_TX ,
        P.MODEL_TX ,
        P.BODY_TX ,
        P.VIN_TX ,
        P.REVERSE_VIN_TX
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
        INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
        INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE   LL.CODE_TX IN ( '1822' )
        --AND L.NUMBER_TX IN ( '43211-5', '86383-3', ' 83511-3' )
        AND RC.STATUS_CD = 'W'
        AND L.EFFECTIVE_DT >= '2014-01-01 '
ORDER BY L.EFFECTIVE_DT ASC





--Storage 
SELECT  L.NUMBER_TX ,
        L.EFFECTIVE_DT ,
        O.LAST_NAME_TX ,
        O.FIRST_NAME_TX ,
        O.MIDDLE_INITIAL_TX ,
        OA.ID ,
        OA.LINE_1_TX ,
        OA.LINE_2_TX ,
        OA.CITY_TX ,
        OA.STATE_PROV_TX ,
        OA.COUNTRY_TX ,
        OA.POSTAL_CODE_TX ,
        P.YEAR_TX ,
        P.MAKE_TX ,
        P.MODEL_TX ,
        P.BODY_TX ,
        P.VIN_TX ,
        P.REVERSE_VIN_TX FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('1822') AND RC.SUMMARY_SUB_STATUS_CD = 'L'
--AND L.NUMBER_TX IN ('85783-4')
AND L.EFFECTIVE_DT >= '2014-01-01 '
ORDER BY L.EFFECTIVE_DT ASC

