USE unitrac

--Process of RunOnce
SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION
WHERE CAST(LAST_RUN_DT AS DATE) = CAST(GETDATE()-1 AS DATE)
AND EXECUTION_FREQ_CD = 'RUNONCE'
--572

SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION
WHERE CAST(LAST_RUN_DT AS DATE) = CAST(GETDATE()-8 AS DATE)
AND EXECUTION_FREQ_CD = 'RUNONCE'
--572

SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION
WHERE CAST(LAST_RUN_DT AS DATE) = CAST(GETDATE()-15 AS DATE)
AND EXECUTION_FREQ_CD = 'RUNONCE'
--458


--Process Logs 
SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION PD
JOIN dbo.PROCESS_LOG PL ON PL.PROCESS_DEFINITION_ID = PD.ID
WHERE PD.PROCESS_TYPE_CD IN ('BILLING', 'CYCLEPRC') AND 
 CAST(PL.START_DT AS DATE) = CAST(GETDATE()-1 AS DATE)
--3354

SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION PD
JOIN dbo.PROCESS_LOG PL ON PL.PROCESS_DEFINITION_ID = PD.ID
WHERE PD.PROCESS_TYPE_CD IN ('BILLING', 'CYCLEPRC') AND 
 CAST(PL.START_DT AS DATE) = CAST(GETDATE()-8 AS DATE)
--3107

SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION PD
JOIN dbo.PROCESS_LOG PL ON PL.PROCESS_DEFINITION_ID = PD.ID
WHERE PD.PROCESS_TYPE_CD IN ('BILLING', 'CYCLEPRC') AND 
 CAST(PL.START_DT AS DATE) = CAST(GETDATE()-15 AS DATE)
--1747

SELECT COUNT(*) FROM dbo.PROCESS_DEFINITION PD
JOIN dbo.PROCESS_LOG PL ON PL.PROCESS_DEFINITION_ID = PD.ID
WHERE PD.PROCESS_TYPE_CD IN ('BILLING', 'CYCLEPRC') AND 
 CAST(PL.START_DT AS DATE) = CAST(GETDATE()-22 AS DATE)
--1824



---Reports
SELECT COUNT(*) FROM dbo.REPORT_HISTORY
WHERE STATUS_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-1 AS DATE)
 --12933

 
SELECT COUNT(*) FROM dbo.REPORT_HISTORY
WHERE STATUS_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-15 AS DATE)
 --10493
 
SELECT COUNT(*) FROM dbo.REPORT_HISTORY
WHERE STATUS_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-22 AS DATE)
 --10322




 
 SELECT COUNT(*) FROM dbo.FORCE_PLACED_CERTIFICATE
 WHERE PDF_GENERATE_CD = 'COMP'
 AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-1 AS DATE)
 --21341

SELECT COUNT(*) FROM dbo.FORCE_PLACED_CERTIFICATE
 WHERE PDF_GENERATE_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-15 AS DATE)
 --10493
 
SELECT COUNT(*) FROM dbo.FORCE_PLACED_CERTIFICATE
 WHERE PDF_GENERATE_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-22 AS DATE)
 --4810

SELECT COUNT(*) FROM dbo.NOTICE
 WHERE PDF_GENERATE_CD = 'COMP'
 AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-1 AS DATE)


SELECT COUNT(*) FROM dbo.NOTICE
 WHERE PDF_GENERATE_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-15 AS DATE)

 
SELECT COUNT(*) FROM dbo.NOTICE
 WHERE PDF_GENERATE_CD = 'COMP' AND 
 CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-22 AS DATE)



SELECT COUNT(*) FROM dbo.DOCUMENT_CONTAINER
 WHERE  CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-1 AS DATE)
 --101670

 SELECT COUNT(*) FROM dbo.DOCUMENT_CONTAINER
 WHERE  CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-15 AS DATE)
--93391


 SELECT COUNT(*) FROM dbo.DOCUMENT_CONTAINER
 WHERE  CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-22 AS DATE)
 --101047

