SELECT DISTINCT L.CODE_TX, L.NAME_TX, LP.DESCRIPTION_TX [Lender Product], ESC.DESCRIPTION_TX [Event Sequence], 
TEMPLATE_ID, ESC.UPDATE_USER_TX

FROM dbo.LENDER_PRODUCT LP
JOIN dbo.EVENT_SEQ_CONTAINER ESC ON LP.ID = ESC.LENDER_PRODUCT_ID
JOIN dbo.EVENT_SEQUENCE ES ON ESC.ID = ES.EVENT_SEQ_CONTAINER_ID
JOIN dbo.LENDER L ON L.ID = LP.LENDER_ID
WHERE  NOTICE_TYPE_CD = 'AN'
AND TEMPLATE_ID = '0' AND ESC.PURGE_DT IS NULL AND es.PURGE_DT IS NULL
AND lp.PURGE_DT IS NULL 