USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT L.NUMBER_TX,rc.TYPE_CD, c.PRIMARY_LOAN_IN, rc.STATUS_CD, RC.ID [Collateral], OA.* FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON P.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('1190') AND L.NUMBER_TX IN ('01584485500-00072' ,'01653470100-00001')
AND RC.TYPE_CD = 'FLOOD' AND OA.LINE_1_TX = '205 E Joppa Rd'






SELECT DISTINCT L.NUMBER_TX,
        RC.TYPE_CD ,
        RC1.DESCRIPTION_TX [Coverage Status] ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type] , PCu.FROM_VALUE_TX, PCU.TO_VALUE_TX, PCU.CREATE_DT  
INTO JCs..FloodCoverage_Active_Inactive
FROM    dbo.PROPERTY_CHANGE_UPDATE PCU
        JOIN dbo.REQUIRED_COVERAGE RC ON RC.ID = PCU.TABLE_ID
                                         AND TABLE_NAME_TX = 'REQUIRED_COVERAGE'
        JOIN dbo.COLLATERAL C ON C.PROPERTY_ID = RC.PROPERTY_ID
        JOIN dbo.LOAN L ON L.ID = C.LOAN_ID
        INNER JOIN dbo.REF_CODE RC1 ON RC1.CODE_CD = RC.STATUS_CD
                                       AND RC1.DOMAIN_CD = 'RequiredCoverageStatus'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
WHERE   PCU.FROM_VALUE_TX IN ( 'A', 'I' )
        AND PCU.TO_VALUE_TX IN ( 'A', 'I' )
        AND L.LENDER_ID = '2284'




SELECT DISTINCT L.NUMBER_TX ,
        rc.TYPE_CD ,
        rc.STATUS_CD ,
        RC2.DESCRIPTION_TX [Loan Record Type] ,
        RC3.DESCRIPTION_TX [Loan Status] ,
        RC4.DESCRIPTION_TX [Loan Type]
FROM    LOAN L
        INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
        INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
        INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
        INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
        LEFT JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PCU.TABLE_ID = RC.ID
                                                    AND PCU.COLUMN_NM = 'STATUS_CD'
        INNER JOIN dbo.REF_CODE RC2 ON RC2.CODE_CD = L.RECORD_TYPE_CD
                                       AND RC2.DOMAIN_CD = 'RecordType'
        INNER JOIN dbo.REF_CODE RC3 ON RC3.CODE_CD = L.STATUS_CD
                                       AND RC3.DOMAIN_CD = 'LoanStatus'
        INNER JOIN dbo.REF_CODE RC4 ON RC4.CODE_CD = L.TYPE_CD
                                       AND RC4.DOMAIN_CD = 'LoanType'
WHERE   LL.CODE_TX IN ( '1190' )
      --  AND PCU.TO_VALUE_TX = 'I'
        AND RC.TYPE_CD = 'FLOOD' 
ORDER BY L.NUMBER_TX ASC 

---Finding Branch
SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'



---Finding Collateral Code
SELECT  CC.ID ,
        CC.CODE_TX ,
        CC.DESCRIPTION_TX 
         FROM dbo.COLLATERAL_CODE CC
INNER JOIN dbo.LCCG_COLLATERAL_CODE_RELATE CCR ON CCR.COLLATERAL_CODE_ID = CC.ID
INNER JOIN dbo.LENDER_COLLATERAL_CODE_GROUP LCCG ON LCCG.ID = CCR.LCCG_ID
INNER JOIN dbo.LENDER L ON L.ID = LCCG.LENDER_ID
WHERE L.CODE_TX = 'XXXX'

