--1) Main Service Center Query (SERVICE_CENTER_FUNCTION_LENDER_RELATE)
SELECT C.CODE_TX, C.NAME_TX, SCFLR.ID as SCFLR_ID,*
FROM LENDER L
INNER JOIN SERVICE_CENTER_FUNCTION_LENDER_RELATE SCFLR ON L.ID = SCFLR.LENDER_ID AND SCFLR.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER_FUNCTION SCF ON SCFLR.SERVICE_CENTER_FUNCTION_ID = SCF.ID AND SCF.PURGE_DT IS NULL
INNER JOIN SERVICE_CENTER C ON SCF.SERVICE_CENTER_ID = C.ID  AND C.PURGE_DT IS NULL
WHERE L.CODE_TX = '4204'

--SCFLR ROW
SELECT *
FROM SERVICE_CENTER_FUNCTION_LENDER_RELATE
WHERE ID = 2688

SELECT * FROM dbo.LENDER
--WHERE CODE_TX = '4204'

SELECT * FROM dbo.SERVICE_CENTER_FUNCTION_LENDER_RELATE
WHERE LENDER_ID = '2265'

SELECT * FROM dbo.SERVICE_CENTER_FUNCTION

--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE SERVICE_CENTER_FUNCTION_LENDER_RELATE
SET SERVICE_CENTER_FUNCTION_ID = 105
WHERE ID = 2465



--2) Service Center Setup by Division
SELECT RD.*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '4204'



--RELATED_DATA ROW(S)
SELECT *
FROM RELATED_DATA
WHERE ID IN (55158268,55158269)

--Available Service Centers
SELECT *
FROM SERVICE_CENTER 
WHERE CODE_TX NOT LIKE '%/%'

--Update Query
UPDATE RELATED_DATA
SET VALUE_TX = 'Plano'
WHERE ID IN (55158268,55158269)

INSERT dbo.SERVICE_CENTER_FUNCTION_LENDER_RELATE
        ( SERVICE_CENTER_FUNCTION_ID ,
          LENDER_ID ,
          CREATE_DT ,
          PURGE_DT ,
          UPDATE_DT ,
          UPDATE_USER_TX ,
          LOCK_ID
        )
VALUES  ( 103 , -- SERVICE_CENTER_FUNCTION_ID - bigint
          2265 , -- LENDER_ID - bigint
          GETDATE() , -- CREATE_DT - datetime
          NULL , -- PURGE_DT - datetime
          GETDATE() , -- UPDATE_DT - datetime
          N'script' , -- UPDATE_USER_TX - nvarchar(15)
          1  -- LOCK_ID - tinyint
        )


SELECT * FROM dbo.LENDER
WHERE CODE_TX = '4204'