USE UniTrac


SELECT
COUNT(*) [FPC Counts], PDF_GENERATE_CD [Status]
FROM dbo.FORCE_PLACED_CERTIFICATE
WHERE CAST(CREATE_DT AS DATE) = CAST(GETDATE() AS DATE) 
AND PDF_GENERATE_CD <> 'COMP' AND PURGE_DT IS NULL
GROUP BY	PDF_GENERATE_CD


SELECT
COUNT(*) [Notice Counts], PDF_GENERATE_CD [Status]
FROM dbo.NOTICE
WHERE CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE) 
AND PDF_GENERATE_CD <> 'COMP'
GROUP BY	PDF_GENERATE_CD



SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'ONHO'