USE UniTrac
----BSS Check In
SELECT  TP.EXTERNAL_ID_TX ,
        TP.NAME_TX ,
        TP.TYPE_CD ,
        M.ID ,
        M.CREATE_DT ,
        M.UPDATE_DT ,
        M.UPDATE_USER_TX
FROM    message M
        JOIN TRADING_PARTNER TP ON M.RECEIVED_FROM_TRADING_PARTNER_ID = TP.ID
WHERE   M.PROCESSED_IN = 'N'
        AND M.RECEIVED_STATUS_CD = 'RCVD'
        AND M.MESSAGE_DIRECTION_CD = 'I'
        AND TP.TYPE_CD = 'BSS_TP'
ORDER BY TP.TYPE_CD DESC ,
        M.CREATE_DT ASC 
--6016412


SELECT *
	FROM    dbo.TRADING_PARTNER_LOG
		WHERE MESSAGE_ID = '6456012'


		SELECT * FROM dbo.PROCESS_DEFINITION
		WHERE PROCESS_TYPE_CD = 'MSGSRV'


UPDATE dbo.MESSAGE
SET RECEIVED_STATUS_CD = 'HOLD', PROCESSED_IN = 'Y', LOCK_ID = LOCK_ID+1, UPDATE_DT = GETDATE() 
--SELECT * FROM dbo.MESSAGE
WHERE ID IN (XXXXXXX)
