	SELECT * FROM dbo.WORK_ITEM
									WHERE RELATE_ID IN (4665297, 4631341)
									AND RELATE_TYPE_CD ='LDHLib.Message'


								
								

SELECT * FROM dbo.MESSAGE
WHERE ID IN (4665297)

SELECT * FROM dbo.DOCUMENT
WHERE MESSAGE_ID  IN (4665297)

SELECT * FROM dbo.[TRANSACTION]
WHERE DOCUMENT_ID IN (10641651, 10641666)

SELECT * FROM dbo.TRADING_PARTNER_LOG
WHERE MESSAGE_ID = '4665297'

									


									
			
			
									WHERE PURGE_DT IS NOT NULL

									WHERE RELATED_TRANSACTION_ID = '4665297'



								SELECT * FROM dbo.[TRANSACTION]

									SELECT * FROM dbo.WORK_ITEM_ACTION
									WHERE ID IN (56691424,56724254)

									SELECT * FROM dbo.REF_CODE
									WHERE DOMAIN_CD = 'TPProcess'


SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ID = '19880'



SELECT * FROM dbo.PROCESS_LOG
WHERE UPDATE_USER_TX = 'MsgSrvrEXTHUNT'  AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE()-4  AS DATE)

WHERE ID IN (26998902, 26800551,26938872)


SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '26911677'


 UPDATE_USER_TX = 'LDHHUNT'  AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() - 1 AS DATE)


SELECT * FROM dbo.LENDER
WHERE ID = '1835'

SELECT * FROM dbo.PROCESS_DEFINITION
WHERE ID = '26998902'


SELECT * FROM dbo.MESSAGE
WHERE ID IN (4665297)




SELECT * FROM dbo.MESSAGE
WHERE RECEIVED_STATUS_CD = 'ERR'
  AND   CAST(UPDATE_DT AS DATE) = CAST(GETDATE() - 1 AS DATE)


