USE [Unitrac_Reports]
GO

/****** Object:  StoredProcedure [dbo].[Report_RDLReportType]    Script Date: 1/18/2017 11:44:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[Report_RDLReportType] (@DOMAIN_CD as varchar(50),@REPORT_HISTORY_ID as bigint=NULL)
as
BEGIN

SELECT 
	REF_CODE.CODE_CD,
	CASE 
	  WHEN RC.CODE_TX IS NOT NULL THEN LRC.DESCRIPTION_TX
	  ELSE REF_CODE.DESCRIPTION_TX
	END as DESCRIPTION_TX
FROM REF_CODE 
left Join REPORT_HISTORY RH on RH.ID = @REPORT_HISTORY_ID AND RH.PURGE_DT IS NULL
left Join LENDER_REPORT_CONFIG LRC on LRC.ID = REPORT_DATA_XML.value('(//ReportData/Report/SourceReportConfigID/@value)[1]', 'bigint') AND LRC.PURGE_DT IS NULL
left Join REPORT_CONFIG RC on LRC.REPORT_CONFIG_ID = RC.ID and REF_CODE.CODE_CD = RC.CODE_TX AND RC.PURGE_DT IS NULL
WHERE 
	REF_CODE.DOMAIN_CD = @DOMAIN_CD
	and 
	REF_CODE.CODE_CD <> 'DEFAULT'
ORDER BY REF_CODE.MEANING_TX

END


GO

