

-----Complete
SELECT COUNT(*)[Number of Reports Done by UBSRPT], MAX(UPDATE_DT) [Last Report Done by UBSRPT]
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'COMP'
AND UPDATE_DT >= '2016-03-16 13:15:00'
		AND UPDATE_USER_TX = 'UBSRPT'
        AND GENERATION_SOURCE_CD = 'u'
        AND MSG_LOG_TX IS NOT NULL
		 

-----Complete
SELECT *
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'COMP'
AND UPDATE_DT >= '2016-03-16 00:00:00'
		AND UPDATE_USER_TX = 'UBSRPT'
        AND GENERATION_SOURCE_CD = 'u'
        AND MSG_LOG_TX IS NOT NULL
ORDER BY UPDATE_DT DESC


SELECT *
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'PEND'
ORDER BY UPDATE_DT DESC

SELECT *
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'PEND'
ORDER BY RECORD_COUNT_NO DESC

	
-----Complete
SELECT *
--INTO UniTracHDStorage..ErrorReports_ID_20160315
FROM    REPORT_HISTORY
WHERE   STATUS_CD IN ( 'ERR', 'IGN') AND
UPDATE_DT >= '2016-03-16 00:00:00' --AND ID IN (9059152,9059141)
ORDER BY UPDATE_DT DESC



SELECT TOP 1 *
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'COMP'
ORDER BY UPDATE_DT DESC

SELECT * FROM dbo.USERS
WHERE USER_NAME_TX = 'efrank'

SELECT * FROM dbo.REPORT_HISTORY
WHERE RECORD_COUNT_NO = '606722'



SELECT * FROM dbo.DOCUMENT_CONTAINER
WHERE ID = '55349125'



SELECT * FROM dbo.LENDER
WHERE ID = '2184'

UPDATE  [UniTrac].[dbo].[REPORT_HISTORY]
SET     STATUS_CD = 'HOLD' ,
        RETRY_COUNT_NO = 0 ,
        MSG_LOG_TX = NULL ,
        RECORD_COUNT_NO = 0 ,
        ELAPSED_RUNTIME_NO = 0,
		UPDATE_DT = GETDATE()-1
--SELECT * FROM dbo.REPORT_HISTORY
WHERE   ID IN (9074501)





SELECT
COUNT(*) [Counts], rh.UPDATE_USER_TX [Status], MAX(UPDATE_DT) [Last Report Done]
FROM REPORT_HISTORY rh 
WHERE CAST(RH.UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE) AND  
 STATUS_CD = 'COMP' AND REPORT_ID = '27'
GROUP BY	UPDATE_USER_TX
ORDER BY COUNT(*) DESC



SELECT * FROM dbo.WORK_ITEM
WHERE ID = '30155322'


SELECT * FROM dbo.PROCESS_LOG
WHERE ID = '31963119'

SELECT-- *
RELATE_ID INTO #tmp
 FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '31963119'
AND RELATE_TYPE_CD = 'Allied.UniTrac.ReportHistory'


SELECT * FROM dbo.REPORT_HISTORY
WHERE ID IN (SELECT * FROM #tmp)


--9074501


