USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE


SELECT COUNT(L.NUMBER_TX) [Count], L.NUMBER_TX
FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
where LL.CODE_TX = '5350'
AND L.RECORD_TYPE_CD IN ('G', 'A')
GROUP BY L.NUMBER_TX
HAVING COUNT(L.NUMBER_TX) > 1


--drop table #tmploans 
SELECT COUNT(L.NUMBER_TX) [Count], L.NUMBER_TX, L.LENDER_ID
INTO #TMPLOANS
FROM LOAN L
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
where LL.CODE_TX = '5350'
AND L.RECORD_TYPE_CD IN ('G', 'A')
GROUP BY L.NUMBER_TX, L.LENDER_ID
HAVING COUNT(L.NUMBER_TX) > 1



SELECT DISTINCT L.NUMBER_TX [Loan Number], RC.DESCRIPTION_TX [Loan Type ], P.VIN_TX [VIN], P.YEAR_TX [Year], P.MAKE_TX [Make], P.MODEL_TX [Model], 
L.CREATE_DT [Loan Create Date],CONCAT(RC6.DESCRIPTION_TX, ' ', RC5.DESCRIPTION_TX) AS [Insurance Coverage Status], PC.TYPE_CD,
OP.EFFECTIVE_DT [Insurance Effective Date], OP.MOST_RECENT_EFFECTIVE_DT [Most Recent Effective Date], OP.EXPIRATION_DT [Expiration Date]
INTO UnitracHDS	
--select count(*)
FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
INNER JOIN dbo.PROPERTY_OWNER_POLICY_RELATE POP ON POP.PROPERTY_ID = P.ID
INNER JOIN dbo.OWNER_POLICY OP ON OP.ID = POP.OWNER_POLICY_ID
JOIN dbo.POLICY_COVERAGE pc ON pc.OWNER_POLICY_ID = OP.ID
JOIN dbo.REF_CODE RC ON RC.CODE_CD = L.RECORD_TYPE_CD AND RC.DOMAIN_CD = 'RecordType'
JOIN #TMPLOANS LO ON LO.NUMBER_TX = L.NUMBER_TX AND LO.LENDER_ID = LL.ID
JOIN dbo.REF_CODE RC5 ON RC5.CODE_CD = op.STATUS_CD
                                       AND RC5.DOMAIN_CD = 'RequiredCoverageInsStatus'
JOIN dbo.REF_CODE RC6 ON RC6.CODE_CD = op.SUB_STATUS_CD
                                       AND RC6.DOMAIN_CD = 'RequiredCoverageInsSubStatus'
where LL.CODE_TX = '5350'
AND L.RECORD_TYPE_CD IN ('G', 'A')
--389,635
