USE [UniTrac]
GO

/****** Object:  StoredProcedure [dbo].[SaveEscrow]    Script Date: 5/9/2018 9:02:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SaveEscrow] (
	@ID BIGINT
	,@LOAN_ID BIGINT
	,@PROPERTY_ID BIGINT
	,@TYPE_CD NVARCHAR(3)
	,@STATUS_CD NVARCHAR(4)
	,@SUB_STATUS_CD NVARCHAR(10)
	,@STATUS_DT DATETIME2
	,@RECORD_TYPE_CD CHAR(1)
	,@POLICY_NUMBER_TX NVARCHAR(18)
	,@RECONCILLED_STATUS_CD NVARCHAR(3)
	,@RECONCILLED_STATUS_DT DATETIME2
	,@AMOUNT_TYPE_CD NVARCHAR(10)
	,@TOTAL_AMOUNT_NO DECIMAL(18, 2)
	,@PREMIUM_NO DECIMAL(18, 2)
	,@OTHER_NO DECIMAL(18, 2)
	,@FEE_NO DECIMAL(18, 2)
	,@TOTAL_POLICY_PREMIUM_NO DECIMAL(18, 2) = NULL
	,@DUE_DT DATETIME2
	,@EFFECTIVE_DT DATETIME2
	,@REPORTED_DT DATETIME2 = NULL
	,@TOTAL_PAID_AMOUNT_NO DECIMAL(18, 2)
	,@REMITTANCE_TYPE_CD NVARCHAR(10)
	,@BIC_ID BIGINT
	,@REMITTANCE_ADDR_ID BIGINT
	,@END_DT DATETIME2
	,@CREATE_USER_TX VARCHAR(15)
	,@UPDATE_USER_TX NVARCHAR(15)
	,@lockId TINYINT
	,@purge CHAR(1) = NULL
	,@COMMENTS_TX NVARCHAR(500) = NULL
	,@MAIL_DT DATETIME2
	,@ORIGINAL_TOTAL_AMT_NO DECIMAL(18, 2) = NULL
	,@TOTAL_AMT_CHG_DT DATETIME2 = NULL
	,@SUB_TYPE_CD NVARCHAR(4)
	,@EXCESS_IN CHAR(1) = NULL
	,@QUICK_PAY_IN CHAR(1) = NULL
	,@PAYEE_CODE_TX CHAR(20) = NULL
	,@OVERNIGHT_ADDR_ID BIGINT = NULL
	,@CHECK_NUMBER_TX NVARCHAR(50) = NULL
	,@CHECK_NAME_TX NVARCHAR(100) = NULL
	,@CHECK_DT DATETIME2(7) = NULL
	,@CHECK_AMOUNT_NO DECIMAL(18, 2) = NULL
	,@DOCUMENT_ID_TX NVARCHAR(100) = NULL
	,@TRAN_STATUS_CD NVARCHAR(10) = 'DNS'
	,@LOCKOUT_OVERRIDE_IN CHAR(1) = NULL
	,@LAST_UPDATED_FROM_LENDER_FILE_IN CHAR(1) = 'N' 
	,@LAST_UPDATE_FROM_LENDER_FILE_DT DATETIME2 = NULL
	,@CONTROL_NUMBER_TX NVARCHAR(50) = NULL
	)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @now DATETIME

	SET @now = getdate()

	DECLARE @purgeDate DATETIME

	IF @purge = 'Y'
		SET @purgeDate = @now

	DECLARE @nextLockId INT

	SET @nextLockId = 1

	IF @id = 0
	BEGIN
		INSERT INTO ESCROW (
			LOAN_ID
			,PROPERTY_ID
			,TYPE_CD
			,STATUS_CD
			,SUB_STATUS_CD
			,STATUS_DT
			,RECORD_TYPE_CD
			,POLICY_NUMBER_TX
			,RECONCILLED_STATUS_CD
			,RECONCILLED_STATUS_DT
			,AMOUNT_TYPE_CD
			,TOTAL_AMOUNT_NO
			,PREMIUM_NO
			,OTHER_NO
			,FEE_NO
			,TOTAL_POLICY_PREMIUM_NO
			,DUE_DT
			,EFFECTIVE_DT
			,REPORTED_DT
			,TOTAL_PAID_AMOUNT_NO
			,REMITTANCE_TYPE_CD
			,BIC_ID
			,REMITTANCE_ADDR_ID
			,END_DT
			,CREATE_USER_TX
			,CREATE_DT
			,UPDATE_DT
			,UPDATE_USER_TX
			,LOCK_ID
			,COMMENTS_TX
			,MAIL_DT
			,ORIGINAL_TOTAL_AMT_NO
			,TOTAL_AMT_CHG_DT
			,SUB_TYPE_CD
			,EXCESS_IN
			,QUICK_PAY_IN
			,PAYEE_CODE_TX
			,OVERNIGHT_ADDR_ID
			,CHECK_NUMBER_TX
			,CHECK_NAME_TX
			,CHECK_DT
			,CHECK_AMOUNT_NO
			,DOCUMENT_ID_TX
			,TRAN_STATUS_CD
			,LOCKOUT_OVERRIDE_IN
			,LAST_UPDATED_FROM_LENDER_FILE_IN
			,LAST_UPDATE_FROM_LENDER_FILE_DT
			,CONTROL_NUMBER_TX
			)
		VALUES (
			@LOAN_ID
			,@PROPERTY_ID
			,@TYPE_CD
			,@STATUS_CD
			,@SUB_STATUS_CD
			,@STATUS_DT
			,@RECORD_TYPE_CD
			,@POLICY_NUMBER_TX
			,@RECONCILLED_STATUS_CD
			,@RECONCILLED_STATUS_DT
			,@AMOUNT_TYPE_CD
			,@TOTAL_AMOUNT_NO
			,@PREMIUM_NO
			,@OTHER_NO
			,@FEE_NO
			,@TOTAL_POLICY_PREMIUM_NO
			,@DUE_DT
			,@EFFECTIVE_DT
			,@REPORTED_DT
			,@TOTAL_PAID_AMOUNT_NO
			,@REMITTANCE_TYPE_CD
			,@BIC_ID
			,@REMITTANCE_ADDR_ID
			,@END_DT
			,@CREATE_USER_TX
			,@now
			,@now
			,@UPDATE_USER_TX
			,@nextLockId
			,@COMMENTS_TX
			,@MAIL_DT
			,@ORIGINAL_TOTAL_AMT_NO
			,@TOTAL_AMT_CHG_DT
			,@SUB_TYPE_CD
			,@EXCESS_IN
			,@QUICK_PAY_IN
			,@PAYEE_CODE_TX
			,@OVERNIGHT_ADDR_ID
			,@CHECK_NUMBER_TX
			,@CHECK_NAME_TX
			,@CHECK_DT
			,@CHECK_AMOUNT_NO
			,@DOCUMENT_ID_TX
			,@TRAN_STATUS_CD
			,@LOCKOUT_OVERRIDE_IN
			,@LAST_UPDATED_FROM_LENDER_FILE_IN
			,@LAST_UPDATE_FROM_LENDER_FILE_DT
			,@CONTROL_NUMBER_TX
			)

		SET @id = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		IF @lockId < 255
			SET @nextLockId = @lockId + 1

		UPDATE ESCROW
		SET LOAN_ID = @LOAN_ID
			,PROPERTY_ID = @PROPERTY_ID
			,TYPE_CD = @TYPE_CD
			,STATUS_CD = @STATUS_CD
			,SUB_STATUS_CD = @SUB_STATUS_CD
			,STATUS_DT = @STATUS_DT
			,RECORD_TYPE_CD = @RECORD_TYPE_CD
			,POLICY_NUMBER_TX = @POLICY_NUMBER_TX
			,RECONCILLED_STATUS_CD = @RECONCILLED_STATUS_CD
			,RECONCILLED_STATUS_DT = @RECONCILLED_STATUS_DT
			,AMOUNT_TYPE_CD = @AMOUNT_TYPE_CD
			,TOTAL_AMOUNT_NO = @TOTAL_AMOUNT_NO
			,PREMIUM_NO = @PREMIUM_NO
			,OTHER_NO = @OTHER_NO
			,FEE_NO = @FEE_NO
			,TOTAL_POLICY_PREMIUM_NO = @TOTAL_POLICY_PREMIUM_NO
			,DUE_DT = @DUE_DT
			,EFFECTIVE_DT = @EFFECTIVE_DT
			,REPORTED_DT = @REPORTED_DT
			,TOTAL_PAID_AMOUNT_NO = @TOTAL_PAID_AMOUNT_NO
			,REMITTANCE_TYPE_CD = @REMITTANCE_TYPE_CD
			,BIC_ID = @BIC_ID
			,REMITTANCE_ADDR_ID = @REMITTANCE_ADDR_ID
			,END_DT = @END_DT
			,CREATE_USER_TX = @CREATE_USER_TX
			,UPDATE_DT = @now
			,UPDATE_USER_TX = @UPDATE_USER_TX
			,LOCK_ID = @nextLockId
			,PURGE_DT = @purgeDate
			,COMMENTS_TX = @COMMENTS_TX
			,MAIL_DT = @MAIL_DT
			,ORIGINAL_TOTAL_AMT_NO = @ORIGINAL_TOTAL_AMT_NO
			,TOTAL_AMT_CHG_DT = @TOTAL_AMT_CHG_DT
			,SUB_TYPE_CD = @SUB_TYPE_CD
			,EXCESS_IN = @EXCESS_IN
			,QUICK_PAY_IN = @QUICK_PAY_IN
			,PAYEE_CODE_TX = @PAYEE_CODE_TX
			,OVERNIGHT_ADDR_ID = @OVERNIGHT_ADDR_ID
			,CHECK_NUMBER_TX = @CHECK_NUMBER_TX
			,CHECK_NAME_TX = @CHECK_NAME_TX
			,CHECK_DT = @CHECK_DT
			,CHECK_AMOUNT_NO = @CHECK_AMOUNT_NO
			,DOCUMENT_ID_TX = @DOCUMENT_ID_TX
			,TRAN_STATUS_CD = @TRAN_STATUS_CD
			,LOCKOUT_OVERRIDE_IN = @LOCKOUT_OVERRIDE_IN
			,LAST_UPDATED_FROM_LENDER_FILE_IN = @LAST_UPDATED_FROM_LENDER_FILE_IN
			,LAST_UPDATE_FROM_LENDER_FILE_DT = @LAST_UPDATE_FROM_LENDER_FILE_DT
			,CONTROL_NUMBER_TX = @CONTROL_NUMBER_TX
		WHERE ID = @ID
			AND LOCK_ID = @lockId
	END

	SELECT @id
		,@nextLockId
		,@now
		,@@ROWCOUNT
END

GO

