USE [QCModule]
GO

/****** Object:  StoredProcedure [dbo].[SaveQCBatchDefinition]    Script Date: 7/11/2018 11:13:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SaveQCBatchDefinition]
(
   @PROCESS_DEFINITION_ID bigint,
   @QC_RULE_DEFINITION_ID bigint = null,
   @APPROVAL_TYPE_CD nvarchar(10) = null,
   @THRESHOLD_NO int = null,
   @PARAMETERS_XML xml = null,
   @START_DT datetime = null,
   @AGENCY_ID bigint = null,
   @UPDATE_USER_TX NVARCHAR(15) = null
)
AS
BEGIN

   SET NOCOUNT ON

   IF NOT EXISTS(SELECT 1 FROM QC_BATCH_DEFINITION WHERE PROCESS_DEFINITION_ID = @PROCESS_DEFINITION_ID)
   BEGIN
      INSERT INTO QC_BATCH_DEFINITION
      (
         PROCESS_DEFINITION_ID,
         QC_RULE_DEFINITION_ID,
         APPROVAL_TYPE_CD,
         THRESHOLD_NO,
         PARAMETERS_XML,
		 START_DT,
		 AGENCY_ID
      )
      VALUES
      (
         @PROCESS_DEFINITION_ID,
         @QC_RULE_DEFINITION_ID,
         @APPROVAL_TYPE_CD,
         @THRESHOLD_NO,
         @PARAMETERS_XML,
         @START_DT,
         @AGENCY_ID
      )
   END
   ELSE
   BEGIN
      UPDATE QC_BATCH_DEFINITION 
      SET
         QC_RULE_DEFINITION_ID = @QC_RULE_DEFINITION_ID,
         APPROVAL_TYPE_CD = @APPROVAL_TYPE_CD,
         THRESHOLD_NO = @THRESHOLD_NO,
         PARAMETERS_XML = @PARAMETERS_XML,
         START_DT = @START_DT
      WHERE PROCESS_DEFINITION_ID = @PROCESS_DEFINITION_ID

	  UPDATE PROCESS_DEFINITION
	  SET	
		ANTICIPATED_NEXT_SCHEDULED_DT = @START_DT,
		UPDATE_DT = GETDATE(),
		UPDATE_USER_TX = @UPDATE_USER_TX,
		LOCK_ID = (LOCK_ID % 255) + 1
      WHERE ID = @PROCESS_DEFINITION_ID
   END

   SELECT @PROCESS_DEFINITION_ID
END

GO

