USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT DISTINCT TOP 5 L.NUMBER_TX,LL.Code_TX, LL.Name_TX, CC.ID, CC.DESCRIPTION_TX, N.NAME_TX, N.SEQUENCE_NO
FROM LOAN L
INNER JOIN dbo.NOTICE N ON N.LOAN_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE C.COLLATERAL_CODE_ID IN (13,30) AND N.SEQUENCE_NO IN (1,2)
AND CAST(N.UPDATE_DT AS DATE) >= CAST(GETDATE()-30 AS DATE)
ORDER BY CC.ID ASC 



SELECT DISTINCT TOP 5 L.NUMBER_TX,LL.Code_TX, LL.Name_TX, CC.ID, CC.DESCRIPTION_TX,  N.NAME_TX, N.SEQUENCE_NO
FROM LOAN L
INNER JOIN dbo.NOTICE N ON N.LOAN_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE C.COLLATERAL_CODE_ID IN (36) AND N.SEQUENCE_NO IN (1,2)
AND CAST(N.UPDATE_DT AS DATE) >= CAST(GETDATE()-365 AS DATE)
ORDER BY CC.ID ASC 
--9,60,

SELECT DISTINCT TOP 5 L.NUMBER_TX,LL.Code_TX, LL.Name_TX, CC.ID, CC.DESCRIPTION_TX,  N.NAME_TX, N.SEQUENCE_NO 
FROM LOAN L
INNER JOIN dbo.NOTICE N ON N.LOAN_ID = L.ID
JOIN dbo.COLLATERAL C ON C.LOAN_ID = L.ID
JOIN dbo.COLLATERAL_CODE CC ON CC.ID = C.COLLATERAL_CODE_ID
JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE C.COLLATERAL_CODE_ID IN (23,350,515,583) AND N.SEQUENCE_NO IN (1,2)
--AND CAST(N.UPDATE_DT AS DATE) >= CAST(GETDATE()-365 AS DATE)
ORDER BY CC.ID ASC 
--14,,512,437,411,412,448,517,531,678


SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%Equipment%'


