USE [UniTrac]	
GO 

SELECT
COUNT(*) [Counts], rh.STATUS_CD [Status]
FROM REPORT_HISTORY rh 
WHERE CAST(RH.UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
GROUP BY	rh.STATUS_CD


SELECT COUNT(*)[Number of Reports Done by UBSRPT], MAX(UPDATE_DT) [Last Report Done by UBSRPT], MAX(REPORT_ID) [Last Report ID], MAX(ID) [Last ID processed]
FROM    REPORT_HISTORY
WHERE   STATUS_CD = 'COMP'
AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
		AND UPDATE_USER_TX = 'UBSRPT'




SELECT TOP 2 * FROM UniTrac..PROCESS_LOG
WHERE PROCESS_DEFINITION_ID = '30' AND UPDATE_DT >= '2016-05-24 '
ORDER BY UPDATE_DT DESC

SELECT * FROM dbo.REPORT_HISTORY
WHERE STATUS_CD = 'IGN'
AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)