USE UniTrac

SELECT *
INTO UniTracHDStorage..reportconfig_20160512
 FROM dbo.REPORT_CONFIG

USE UNITRAC
GO

BEGIN TRY
BEGIN TRANSACTION

		  update report_config
		  set report_cd = 'CPIBINDER_14DAYS'
		  where id=944


COMMIT TRANSACTION
END TRY
BEGIN CATCH
   ROLLBACK TRANSACTION
   RAISERROR ('ROLLBACK occured for Report_Config Update. NO RECORDS Updated', 16, 1) WITH LOG
   SELECT
ERROR_NUMBER() AS ErrorNumber
,ERROR_SEVERITY() AS ErrorSeverity
,ERROR_STATE() AS ErrorState
,ERROR_PROCEDURE() AS ErrorProcedure
,ERROR_LINE() AS ErrorLine
,ERROR_MESSAGE() AS ErrorMessage;
END CATCH
GO


	
-- If we have Op.Expiration_Dt use this script 
UPDATE  OP
SET     OP.CANCELLATION_DT = OP.EFFECTIVE_DT ,
        OP.UPDATE_DT = GETDATE() ,
        OP.UPDATE_USER_TX = 'BUG37817'
--SELECT OP.*
FROM    PROPERTY P
        JOIN PROPERTY_OWNER_POLICY_RELATE POP_REL ON POP_REL.PROPERTY_ID = P.ID
                                                     AND POP_REL.PURGE_DT IS NULL
        JOIN OWNER_POLICY OP ON OP.ID = POP_REL.OWNER_POLICY_ID
                                AND OP.PURGE_DT IS NULL
        JOIN POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE   POP_REL.PROPERTY_ID IN ( 32269 )
        AND PC.TYPE_CD = 'PHYS-DAMAGE'
UPDATE  PC
SET     PC.END_DT = PC.START_DT ,
        PC.CANCELLED_IN = 'Y' ,
        PC.UPDATE_DT = GETDATE() ,
        PC.UPDATE_USER_TX = 'BUG37817'
--SELECT P.*
FROM    PROPERTY P
        JOIN PROPERTY_OWNER_POLICY_RELATE POP_REL ON POP_REL.PROPERTY_ID = P.ID
                                                     AND POP_REL.PURGE_DT IS NULL
        JOIN OWNER_POLICY OP ON OP.ID = POP_REL.OWNER_POLICY_ID
                                AND OP.PURGE_DT IS NULL
        JOIN POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
WHERE   POP_REL.PROPERTY_ID IN ( 32269 )
        AND PC.TYPE_CD = 'PHYS-DAMAGE' 






	
UPDATE  OP
SET     OP.CANCELLATION_DT = OP.EFFECTIVE_DT ,
        OP.UPDATE_DT = GETDATE() ,
        OP.UPDATE_USER_TX = 'BUG37816'
--SELECT OP.*
FROM    PROPERTY P
        JOIN PROPERTY_OWNER_POLICY_RELATE POP_REL ON POP_REL.PROPERTY_ID = P.ID
                                                     AND POP_REL.PURGE_DT IS NULL
        JOIN OWNER_POLICY OP ON OP.ID = POP_REL.OWNER_POLICY_ID
                                AND OP.PURGE_DT IS NULL
        JOIN POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
                                   AND ( PC.START_DT > PC.END_DT )
WHERE   POP_REL.PROPERTY_ID IN ( 4630708 )
        AND PC.TYPE_CD = 'HAZARD'
UPDATE  PC
SET     PC.END_DT = PC.START_DT ,
        PC.CANCELLED_IN = 'Y' ,
        PC.UPDATE_DT = GETDATE() ,
        PC.UPDATE_USER_TX = 'BUG37816'
--SELECT P.*
FROM    PROPERTY P
        JOIN PROPERTY_OWNER_POLICY_RELATE POP_REL ON POP_REL.PROPERTY_ID = P.ID
                                                     AND POP_REL.PURGE_DT IS NULL
        JOIN OWNER_POLICY OP ON OP.ID = POP_REL.OWNER_POLICY_ID
                                AND OP.PURGE_DT IS NULL
        JOIN POLICY_COVERAGE PC ON PC.OWNER_POLICY_ID = OP.ID
                                   AND ( PC.START_DT > PC.END_DT )
WHERE   POP_REL.PROPERTY_ID IN ( 4630708 )
        AND PC.TYPE_CD = 'HAZARD'