SELECT* FROM UniTrac..PROCESS_DEFINITION
WHERE ACTIVE_IN = 'y' AND PROCESS_TYPE_CD LIKE 'UT%'



SELECT * FROM dbo.PROCESS_LOG 
WHERE PROCESS_DEFINITION_ID IN (1657)
 AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
 AND MSG_TX <> 'Total WorkItems processed: 0'

SELECT * FROM dbo.LENDER
WHERE CODE_TX ='2120'

 SELECT * FROM dbo.PROCESS_LOG_ITEM
 WHERE PROCESS_LOG_ID = '29170735'
  AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
AND RELATE_ID = '244'
   ORDER BY RELATE_ID ASC


  SELECT * FROM dbo.PROCESS_LOG_ITEM
  WHERE PROCESS_LOG_ID IN (SELECT ID FROM dbo.PROCESS_LOG 
WHERE PROCESS_DEFINITION_ID IN (1657)
 AND CAST(UPDATE_DT AS DATE) = CAST(GETDATE() AS DATE)
 AND MSG_TX <> 'Total WorkItems processed: 0')



   SELECT * FROM dbo.PROCESS_LOG_ITEM
  WHERE PROCESS_LOG_ID IN (29172130,
29172841,
29173337,
29175208,
29175385)



