USE UniTrac


SELECT * FROM dbo.WORK_ITEM
WHERE ID = '32518126'


SELECT * FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '35397484' AND RELATE_TYPE_CD = 'Allied.UniTrac.Workflow.OutboundCallWorkItem'


SELECT * FROM dbo.WORK_ITEM
WHERE RELATE_ID IN (50170800)


SELECT * FROM dbo.EVALUATION_EVENT
WHERE ID IN (SELECT EVALUATION_EVENT_ID FROM dbo.PROCESS_LOG_ITEM
WHERE PROCESS_LOG_ID = '35397484' AND RELATE_TYPE_CD = 'Allied.UniTrac.Workflow.OutboundCallWorkItem')




SELECT DISTINCT STATUS_CD FROM dbo.EVALUATION_EVENT


SELECT * FROM dbo.REF_CODE WHERE CODE_CD = 'NOTU'


