USE [UniTrac]
GO 

--Loan Screen Information - LOAN/COLLATERAL/PROPERTY/OWNER/REQUIRED COVERAGE
SELECT C.ID INTO #tmp
 FROM LOAN L
INNER JOIN COLLATERAL C ON L.ID = C.LOAN_ID
INNER JOIN PROPERTY P ON C.PROPERTY_ID = P.ID
INNER JOIN REQUIRED_COVERAGE RC ON P.ID = RC.PROPERTY_ID
INNER JOIN OWNER_LOAN_RELATE OL ON L.ID = OL.LOAN_ID
INNER JOIN OWNER O ON OL.OWNER_ID = O.ID
INNER JOIN OWNER_ADDRESS OA ON O.ADDRESS_ID = OA.ID
INNER JOIN dbo.LENDER LL ON LL.ID = L.LENDER_ID
WHERE LL.CODE_TX IN ('2032')


SELECT * FROM dbo.LENDER
WHERE CODE_TX IN () 



SELECT  *
FROM    dbo.COLLATERAL_CODE
WHERE   DESCRIPTION_TX LIKE '%%'
        AND AGENCY_ID = '1'
        AND ID IN (  )



SELECT LO.TYPE_CD, LO.CODE_TX , Lo.NAME_TX,*
FROM LENDER L
INNER JOIN LENDER_ORGANIZATION LO ON L.ID = LO.LENDER_ID
INNER JOIN RELATED_DATA RD ON LO.ID = RD.RELATE_ID --AND RD.DEF_ID = '105'
WHERE L.CODE_TX = '' AND Lo.TYPE_CD = 'DIV'




SELECT DISTINCT ENTITY_ID  INTO #tmpA
FROM dbo.PROPERTY_CHANGE PC
INNER JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ENTITY_ID = PCU.TABLE_ID
WHERE PC.ENTITY_ID IN (SELECT * FROM #tmp) AND PC.ENTITY_ID  NOT IN (43229930)
AND COLUMN_NM LIKE 'ADD%' AND PC.CREATE_DT > '2015-02-20' AND ENTITY_NAME_TX = 'Allied.UniTrac.Loan'

SELECT TOP 5 * FROM dbo.PROPERTY_ASSOCIATION


SELECT  * FROM dbo.PROPERTY_CHANGE PC
INNER JOIN dbo.PROPERTY_CHANGE_UPDATE PCU ON PC.ENTITY_ID = PCU.TABLE_ID
WHERE FORMAT_FROM_VALUE_TX LIKE '%REO%'





SELECT * FROM dbo.LOAN
WHERE ID IN (SELECT * FROM #tmpA)



SELECT * FROM dbo.REF_CODE
WHERE CODE_CD = 'REO-LIABILITY'



SELECT * FROM dbo.PROPERTY_CHANGE

