/*
USE [UTL]

IF EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.LOAN') AND name = N'IDX_LOAN_EVALUATION_DT')
BEGIN

CREATE NONCLUSTERED INDEX [IDX_LOAN_EVALUATION_DT] ON [dbo].[LOAN]
(
	[EVALUATION_DT] ASC,
	[PURGE_DT] ASC
)
INCLUDE([LENDER_ID],[CREATE_DT],[ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

END

*/



