--PROD
USE ROLE OWNER_EDW_PROD;
USE WAREHOUSE EDW_PROD_INFA_WH;
USE DATABASE EDW_PROD;
USE SCHEMA STG;

Desc Table EDW_DEV.STG.LND_UT_NOTICE;

ALTER TABLE STG.LND_UT_NOTICE
ALTER COLUMN CAPTURED_DATA_TXT VARCHAR(200000);

Desc Table EDW_DEV.STG.STG_UT_NOTICE;

ALTER TABLE STG.STG_UT_NOTICE
ALTER COLUMN CAPTURED_DATA_TXT VARCHAR(200000);