USE [master]
GO
CREATE LOGIN [ELDREDGE_A\SQL_IVOS_SSAS] FROM WINDOWS WITH DEFAULT_DATABASE=[tempdb], DEFAULT_LANGUAGE=[us_english]
GO
USE [IVOS]
GO
CREATE USER [ELDREDGE_A\SQL_IVOS_SSAS] FOR LOGIN [ELDREDGE_A\SQL_IVOS_SSAS]
GO
USE [IVOS]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\SQL_IVOS_SSAS]
GRANT VIEW DEFINITION TO  [ELDREDGE_A\SQL_IVOS_SSAS]
GO
USE [Jasper]
GO
CREATE USER [ELDREDGE_A\SQL_IVOS_SSAS] FOR LOGIN [ELDREDGE_A\SQL_IVOS_SSAS]
GO
USE [Jasper]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\SQL_IVOS_SSAS]
GRANT VIEW DEFINITION TO  [ELDREDGE_A\SQL_IVOS_SSAS]
GO

USE [JasperServer]
GO
CREATE USER [ELDREDGE_A\SQL_IVOS_SSAS] FOR LOGIN [ELDREDGE_A\SQL_IVOS_SSAS]
GO
USE [JasperServer]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ELDREDGE_A\SQL_IVOS_SSAS]
GRANT VIEW DEFINITION TO  [ELDREDGE_A\SQL_IVOS_SSAS]
GO



